import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const diningOut: IigTopic = {
  slug: "dining-out",
  title: "Dining Out",
  titleVi: "Ăn uống ngoài hàng",
  summary:
    "Từ vựng về nhà hàng, thực đơn, đặt bàn, phục vụ và thanh toán — thường xuất hiện trong các đoạn hội thoại Part 3/4 và đoạn văn Part 6/7 của TOEIC.",
  words: [
    ["appetizer", "n", "/ˈæpɪtaɪzər/", "món khai vị", "We ordered two appetizers before the main course.", "Appetizer (AmE) = Starter (BrE). Appetizer có nghĩa gốc là 'thứ kích thích khẩu vị'."],
    ["banquet", "n", "/ˈbæŋkwɪt/", "tiệc chiêu đãi lớn", "The company held a banquet to celebrate its 50th anniversary.", "Phân biệt: banquet — bữa tiệc chính thức, đông người; dinner party — bữa tối mời khách thân mật hơn."],
    ["beverage", "n", "/ˈbevərɪdʒ/", "đồ uống", "Alcoholic beverages are not permitted in this area.", "Beverage là từ trang trọng, dùng trong menu nhà hàng hoặc văn bản chính thức thay cho 'drink'."],
    ["bill", "n", "/bɪl/", "hóa đơn", "Could I have the bill, please?", "Bill (BrE) = Check (AmE) khi dùng trong nhà hàng. Bill còn có nghĩa là 'tờ tiền' hoặc 'dự luật'."],
    ["buffet", "n", "/ˈbʌfeɪ/", "tiệc buffet, bữa ăn tự chọn", "The hotel offers a breakfast buffet every morning.", "Xuất hiện trong tiếng Pháp từ thế kỷ 18. Buffet: thực khách tự lấy thức ăn từ quầy bày sẵn."],
    ["cafeteria", "n", "/ˌkæfɪˈtɪəriə/", "căng-tin, quán ăn tự phục vụ", "Employees usually have lunch at the company cafeteria.", "Cafeteria: tự lấy thức ăn và thanh toán trước khi ngồi. Khác với restaurant: nhân viên phục vụ tại bàn."],
    ["catering", "n", "/ˈkeɪtərɪŋ/", "dịch vụ ăn uống (cho sự kiện)", "The catering for the conference was handled by a local company.", "Catering service: cung cấp thức ăn, đồ uống cho sự kiện, tiệc cưới, hội nghị, v.v."],
    ["complimentary", "adj", "/ˌkɒmplɪˈmentri/", "miễn phí, tặng kèm", "The restaurant offers complimentary bread before the meal.", "Complimentary: được tặng không mất tiền. Phân biệt với complimentary (ca ngợi) — cùng từ nhưng ngữ cảnh khác."],
    ["cuisine", "n", "/kwɪˈziːn/", "ẩm thực, phong cách nấu ăn", "The restaurant is known for its authentic French cuisine.", "Cuisine (gốc Pháp) chỉ phong cách ẩm thực đặc trưng của một vùng hoặc quốc gia."],
    ["cutlery", "n", "/ˈkʌtləri/", "bộ dao dĩa thìa", "Please ensure that the cutlery is cleaned and polished before service.", "Cutlery (BrE) = Silverware / Flatware (AmE). Bao gồm: knife, fork, spoon."],
    ["delicacy", "n", "/ˈdelɪkəsi/", "món ăn đặc sản, cao lương mỹ vị", "Abalone is considered a delicacy in many Asian countries.", "Delicacy: món ăn hiếm, đắt hoặc đặc biệt của một vùng/văn hóa; không phải chỉ là 'ngon'."],
    ["dessert", "n", "/dɪˈzɜːrt/", "tráng miệng", "Would you like to see the dessert menu?", "Phân biệt: dessert (tráng miệng) vs. desert (sa mạc). Dessert có 2 chữ 's' — nhớ bằng 'Strawberry Shortcake'."],
    ["entrée", "n", "/ˈɒntreɪ/", "món chính", "She chose grilled salmon as her entrée.", "Entrée (AmE): món chính. Nhưng ở Pháp và Anh, entrée là món khai vị. Cần chú ý ngữ cảnh địa lý."],
    ["garnish", "n / v", "/ˈɡɑːrnɪʃ/", "đồ trang trí món ăn; trang trí", "The chef added a sprig of parsley as a garnish.", "Động từ: garnish with something — trang trí món ăn bằng rau thơm, chanh, v.v."],
    ["gratuity", "n", "/ɡrəˈtjuːɪti/", "tiền tip, tiền thưởng thêm", "A 15% gratuity is automatically added to all checks.", "Gratuity = Tip, nhưng gratuity mang tính trang trọng hơn, thường dùng trong menu hoặc hợp đồng."],
    ["ingredient", "n", "/ɪnˈɡriːdiənt/", "nguyên liệu, thành phần", "Fresh ingredients are essential for good cooking.", "Ingredient: thành phần của một món ăn. Số nhiều ingredients dùng khi liệt kê công thức nấu ăn."],
    ["menu", "n", "/ˈmenjuː/", "thực đơn", "Could you bring us the menu, please?", "Menu: danh sách các món ăn của nhà hàng. Set menu: thực đơn cố định theo bộ. À la carte: gọi từng món riêng."],
    ["portion", "n", "/ˈpɔːrʃn/", "phần (ăn)", "The portions at this restaurant are very generous.", "Portion: lượng thức ăn trong một phần phục vụ. Serving cũng có nghĩa tương tự nhưng trung tính hơn."],
    ["recipe", "n", "/ˈresɪpi/", "công thức nấu ăn", "She followed the recipe carefully to make the cake.", "Recipe: hướng dẫn từng bước nấu một món. Không nhầm với receipt (hóa đơn mua hàng)."],
    ["reservation", "n", "/ˌrezərˈveɪʃn/", "đặt chỗ (bàn)", "I'd like to make a reservation for two at 7 p.m.", "Make a reservation = Book a table. Thường dùng trong Part 3 TOEIC khi gọi điện đặt bàn nhà hàng."],
    ["seasoning", "n", "/ˈsiːzənɪŋ/", "gia vị", "Add seasoning to taste before serving.", "Seasoning: gia vị nêm nếm (muối, tiêu, thảo mộc). Season (v): nêm gia vị — Season the chicken with herbs."],
    ["specialty", "n", "/ˈspeʃəlti/", "món đặc biệt, đặc sản", "The chef's specialty is a slow-roasted duck dish.", "Specialty of the house / Chef's specialty: món đặc trưng của nhà hàng hoặc đầu bếp."],
    ["takeout", "n / adj", "/ˈteɪkaʊt/", "đồ ăn mang về", "We decided to order takeout instead of dining in.", "Takeout (AmE) = Takeaway (BrE). Dine in: ăn tại nhà hàng. Drive-through: mua qua cửa sổ xe."],
    ["tip", "n / v", "/tɪp/", "tiền boa; để lại tiền boa", "It is customary to tip your waiter 15–20% in the US.", "Tip = Gratuity. Lưu ý tip cũng có nhiều nghĩa khác: đầu (tip of the iceberg), mẹo (tip for success)."],
    ["venue", "n", "/ˈvenjuː/", "địa điểm (tổ chức sự kiện)", "The restaurant was selected as the venue for the annual dinner.", "Venue: địa điểm diễn ra sự kiện, tiệc, hội nghị. Dùng rộng hơn location vì hàm ý được chọn có chủ đích."],
    ["waiter", "n", "/ˈweɪtər/", "người phục vụ (nam)", "The waiter brought our appetizers promptly.", "Waiter (nam) / Waitress (nữ). Trong tiếng Anh hiện đại, server được dùng trung tính hơn."],
  ],
  quiz: [
    q("The restaurant is famous for its wide selection of -------, from soups to salads.", ["appetizers", "appetizing", "appetize", "appetite"], "A", "Appetizers: các món khai vị (danh từ số nhiều)."),
    q("We held the farewell ------- at a five-star hotel downtown.", ["banquet", "cafeteria", "takeout", "portion"], "A", "Banquet: tiệc chiêu đãi lớn, trang trọng."),
    q("Non-alcoholic ------- are available at the bar.", ["beverages", "beverage", "bevering", "bevered"], "A", "Non-alcoholic beverages: đồ uống không cồn — danh từ số nhiều sau 'are available'."),
    q("Could you bring us the ------- when you have a moment?", ["bill", "recipe", "gratuity", "menu"], "A", "Bring the bill: mang hóa đơn lại (dùng bill trong BrE nhà hàng)."),
    q("The hotel's breakfast ------- includes over 40 dishes.", ["buffet", "entrée", "seasoning", "venue"], "A", "Breakfast buffet: bữa sáng tự chọn."),
    q("All staff are entitled to use the company ------- for lunch.", ["cafeteria", "banquet", "cutlery", "takeout"], "A", "Company cafeteria: căng-tin công ty."),
    q("The ------- for the gala dinner was arranged by an outside firm.", ["catering", "cuisine", "dessert", "specialty"], "A", "Catering: dịch vụ ăn uống phục vụ sự kiện."),
    q("The welcome drink is ------- for all guests.", ["complimentary", "complementary", "completing", "complete"], "A", "Complimentary: miễn phí, tặng kèm. Phân biệt với complementary (bổ sung)."),
    q("The restaurant specializes in Mediterranean -------.", ["cuisine", "cutlery", "cafeteria", "catering"], "A", "Mediterranean cuisine: ẩm thực Địa Trung Hải."),
    q("The ------- was arranged neatly beside each plate.", ["cutlery", "garnish", "dessert", "portion"], "A", "Cutlery: bộ dao dĩa thìa."),
    q("Sharks fin soup is a well-known ------- in Chinese culture.", ["delicacy", "seasoning", "recipe", "ingredient"], "A", "Delicacy: món ăn đặc sản, cao lương mỹ vị."),
    q("She skipped the ------- as she was watching her sugar intake.", ["dessert", "entrée", "appetizer", "beverage"], "A", "Dessert: tráng miệng."),
    q("The grilled steak was the most popular ------- on the menu.", ["entrée", "garnish", "tip", "waiter"], "A", "Entrée (AmE): món chính."),
    q("The plate was beautifully decorated with a lemon ------- on the side.", ["garnish", "seasoning", "ingredient", "cutlery"], "A", "Garnish: đồ trang trí cho món ăn."),
    q("A service charge of 10% is included as a ------- in the final bill.", ["gratuity", "reservation", "specialty", "portion"], "A", "Gratuity: tiền tip hoặc phụ phí dịch vụ."),
    q("The chef insists on using only the freshest ------- in every dish.", ["ingredients", "ingredient", "ingesting", "ingest"], "A", "Fresh ingredients: nguyên liệu tươi — số nhiều vì đề cập chung."),
    q("May I see the ------- for tonight's dinner?", ["menu", "bill", "tip", "venue"], "A", "Menu: thực đơn buổi tối."),
    q("The ------- of the steak was too large for her to finish.", ["portion", "recipe", "gratuity", "garnish"], "A", "Portion: phần ăn."),
    q("He searched online for a ------- to make the perfect risotto.", ["recipe", "reservation", "seasoning", "specialty"], "A", "Recipe: công thức nấu ăn."),
    q("I would like to make a ------- for four people this Saturday evening.", ["reservation", "menu", "bill", "takeout"], "A", "Make a reservation: đặt bàn trước."),
    q("Add salt and pepper ------- to your taste.", ["seasoning", "season", "seasonal", "seasoned"], "A", "Seasoning: gia vị (danh từ)."),
    q("The chef's ------- is a seafood pasta made with locally sourced ingredients.", ["specialty", "cuisine", "delicacy", "catering"], "A", "Chef's specialty: món đặc trưng của đầu bếp."),
    q("Since they were too tired to cook, they ordered -------.", ["takeout", "banquet", "cafeteria", "cutlery"], "A", "Takeout: đồ ăn mang về."),
    q("It is polite to ------- the server if the service was good.", ["tip", "menu", "bill", "venue"], "A", "Tip the server: để lại tiền boa cho người phục vụ."),
    q("The company chose the Grand Ballroom as the ------- for its annual dinner.", ["venue", "cafeteria", "buffet", "catering"], "A", "Venue: địa điểm tổ chức sự kiện."),
    q("The ------- recommended the grilled salmon as the house special.", ["waiter", "garnish", "dessert", "ingredient"], "A", "Waiter: người phục vụ bàn."),
  ],
  written: [],
};
