import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const entertainment: IigTopic = {
  slug: "entertainment",
  title: "Entertainment",
  titleVi: "Giải trí",
  summary:
    "Từ vựng về nghệ thuật, âm nhạc, phim ảnh, sự kiện văn hóa và các hoạt động giải trí — xuất hiện trong Part 4 (thông báo/quảng cáo sự kiện) và Part 7 (bài đọc về hoạt động văn hóa) của TOEIC.",
  words: [
    ["admission", "n", "/ədˈmɪʃn/", "vé vào cổng, phí vào cửa", "Admission to the museum is free on Sundays.", "Admission fee: phí vào cửa. Admission also means 'sự thừa nhận' — admission of guilt."],
    ["applaud", "v", "/əˈplɔːd/", "vỗ tay tán thưởng", "The audience applauded enthusiastically at the end of the performance.", "Applaud → applause (n): tiếng vỗ tay. A round of applause: một tràng pháo tay."],
    ["audience", "n", "/ˈɔːdiəns/", "khán giả", "The audience was captivated by the performance from start to finish.", "Audience: khán giả của một buổi biểu diễn/phim. Viewers: người xem TV. Readers: người đọc."],
    ["broadcast", "n / v", "/ˈbrɔːdkɑːst/", "chương trình phát sóng; phát sóng", "The concert was broadcast live on national television.", "Broadcast (V): phát sóng — quá khứ là broadcast (bất quy tắc, không thêm -ed)."],
    ["caption", "n", "/ˈkæpʃn/", "phụ đề, chú thích hình ảnh", "The documentary is available with English captions.", "Caption: chú thích ảnh hoặc phụ đề (subtitle) của phim/video. Subtitles: phụ đề dịch ngôn ngữ."],
    ["celebrity", "n", "/səˈlebrɪti/", "người nổi tiếng", "Several celebrities attended the charity gala last night.", "Celebrity: danh từ chỉ người nổi tiếng trong showbiz. Plural: celebrities."],
    ["choreography", "n", "/ˌkɒriˈɒɡrəfi/", "biên đạo múa, vũ đạo", "The choreography of the ballet was breathtaking.", "Choreography (n) → choreographer (n): biên đạo viên → choreograph (v): dàn dựng vũ đạo."],
    ["compose", "v", "/kəmˈpəʊz/", "sáng tác (âm nhạc)", "She composed her first symphony at the age of 22.", "Compose → composition (n): tác phẩm âm nhạc → composer (n): nhạc sĩ sáng tác."],
    ["debut", "n / v", "/ˈdeɪbjuː/", "màn ra mắt, lần đầu xuất hiện", "The young singer made her debut at the annual music festival.", "Debut (gốc Pháp, đọc /ˈdeɪbjuː/): lần đầu xuất hiện trước công chúng trong sự nghiệp."],
    ["documentary", "n / adj", "/ˌdɒkjuˈmentri/", "phim tài liệu", "She watched a documentary about climate change last night.", "Documentary film: phim tài liệu. Phân biệt: documentary (thể loại) vs. document (tài liệu)."],
    ["encore", "n / v", "/ˈɒŋkɔːr/", "màn diễn thêm (khi được yêu cầu)", "The crowd cheered loudly, calling for an encore.", "Encore (gốc Pháp, nghĩa là 'once more'): màn biểu diễn thêm sau khi chương trình kết thúc."],
    ["exhibit", "n / v", "/ɪɡˈzɪbɪt/", "vật trưng bày; triển lãm", "The museum will exhibit rare artifacts from ancient Egypt.", "Exhibit (n) = item on display. Exhibition (n): toàn bộ cuộc triển lãm. Exhibit (v): trưng bày."],
    ["festival", "n", "/ˈfestɪvl/", "lễ hội, liên hoan", "Thousands of people attended the international film festival.", "Film festival: liên hoan phim. Music festival: lễ hội âm nhạc. Food festival: lễ hội ẩm thực."],
    ["gallery", "n", "/ˈɡæləri/", "phòng triển lãm, gallery", "She visited an art gallery downtown on her day off.", "Art gallery: nơi trưng bày và thường bán tác phẩm nghệ thuật. Museum: bảo tàng (thường miễn phí xem, lưu giữ lâu dài)."],
    ["interval", "n", "/ˈɪntəvl/", "giờ giải lao (giữa buổi diễn)", "Drinks are served during the interval.", "Interval (BrE) = Intermission (AmE): thời gian nghỉ giải lao giữa các màn của buổi biểu diễn."],
    ["masterpiece", "n", "/ˈmɑːstəpiːs/", "kiệt tác", "The Mona Lisa is widely regarded as Leonardo da Vinci's masterpiece.", "Masterpiece: tác phẩm xuất sắc nhất của một nghệ sĩ hoặc đỉnh cao của một lĩnh vực."],
    ["matinee", "n", "/ˌmætɪˈneɪ/", "suất chiếu/diễn ban ngày", "We decided to catch the matinee to avoid the evening rush.", "Matinee (gốc Pháp 'matin' = buổi sáng): suất diễn chiều hoặc buổi ngày, thường rẻ hơn tối."],
    ["orchestra", "n", "/ˈɔːkɪstrə/", "dàn nhạc giao hưởng", "The orchestra performed a magnificent Beethoven symphony.", "Orchestra: dàn nhạc lớn gồm nhiều nhạc cụ. Orchestra pit: hố nhạc công phía trước sân khấu."],
    ["premiere", "n", "/ˈpremɪeər/", "buổi ra mắt (phim, vở kịch)", "The world premiere of the film will be held in Cannes.", "World premiere: buổi ra mắt quốc tế đầu tiên. Premiere cũng dùng như tính từ: premier (hàng đầu)."],
    ["rehearsal", "n", "/rɪˈhɜːrsl/", "buổi tập diễn, buổi duyệt", "The cast had a final rehearsal before the opening night.", "Rehearsal → rehearse (v): tập dượt, duyệt chương trình. Dress rehearsal: buổi duyệt lần cuối với trang phục đầy đủ."],
    ["repertoire", "n", "/ˈrepətwɑːr/", "danh mục tác phẩm biểu diễn", "The pianist has a wide repertoire of classical music.", "Repertoire: tập hợp các tác phẩm mà một nghệ sĩ hoặc nhóm sẵn sàng biểu diễn."],
    ["screenplay", "n", "/ˈskriːnpleɪ/", "kịch bản phim", "She won an Academy Award for her original screenplay.", "Screenplay = Script: kịch bản phim/chương trình. Screenplay: viết riêng cho phim. Script: dùng rộng hơn."],
    ["sponsor", "n / v", "/ˈspɒnsər/", "nhà tài trợ; tài trợ", "Several major corporations agreed to sponsor the music festival.", "Sponsor (v) → sponsorship (n): sự tài trợ. Corporate sponsorship: tài trợ từ doanh nghiệp."],
    ["subscription", "n", "/səbˈskrɪpʃn/", "đăng ký dịch vụ, thuê bao", "She purchased an annual subscription to the streaming platform.", "Subscription: trả tiền định kỳ để dùng dịch vụ. Subscribe (v) → subscriber (n): người đăng ký."],
    ["venue", "n", "/ˈvenjuː/", "địa điểm biểu diễn, sự kiện", "The concert venue holds up to 20,000 spectators.", "Venue: địa điểm được chọn để tổ chức sự kiện. Concert venue, sports venue, event venue."],
    ["virtuoso", "n / adj", "/ˌvɜːtʃuˈəʊzəʊ/", "nghệ sĩ tài năng xuất chúng", "The young violinist is considered a virtuoso by critics.", "Virtuoso (gốc Ý): người có kỹ năng âm nhạc hoặc nghệ thuật đặc biệt xuất sắc."],
  ],
  quiz: [
    q("------- to the gallery is free for children under 12.", ["Admission", "Admitting", "Admitted", "Admissible"], "A", "Admission: phí vào cửa / quyền vào cửa (danh từ)."),
    q("The audience stood up to ------- when the performance ended.", ["applaud", "applause", "applauded", "applauding"], "A", "Stand up to applaud: đứng dậy vỗ tay — động từ nguyên mẫu sau 'to'."),
    q("A large ------- gathered in the square to watch the outdoor concert.", ["audience", "viewers", "readers", "spectacle"], "A", "Audience: khán giả của buổi biểu diễn trực tiếp."),
    q("The ceremony will be ------- live on Channel 5.", ["broadcast", "broadcasting", "broadcasted", "broadcaster"], "A", "Broadcast live: phát sóng trực tiếp — dạng bị động 'will be broadcast'."),
    q("The video is available with English ------- for hearing-impaired viewers.", ["captions", "caption", "captioning", "captioned"], "A", "Captions: phụ đề (số nhiều, phù hợp sau 'with English')."),
    q("Many ------- attended the charity gala to support the fundraising event.", ["celebrities", "celebrity", "celebrated", "celebration"], "A", "Celebrities: số nhiều — nhiều người nổi tiếng."),
    q("The ------- of the dance performance received high praise from critics.", ["choreography", "choreographer", "choreographed", "choreograph"], "A", "Choreography: vũ đạo (danh từ) — sau tính từ sở hữu 'The'."),
    q("Beethoven ------- nine symphonies during his lifetime.", ["composed", "composition", "composing", "composer"], "A", "Composed: quá khứ đơn của compose (sáng tác)."),
    q("The young actress made her ------- at the International Film Festival.", ["debut", "debuting", "debuted", "debutant"], "A", "Make her debut: ra mắt lần đầu tiên (danh từ)."),
    q("The ------- explores the impact of social media on mental health.", ["documentary", "document", "documentation", "documented"], "A", "Documentary: phim tài liệu (danh từ, chủ ngữ của câu)."),
    q("The crowd cheered so loudly that the band came back for an -------.", ["encore", "interval", "premiere", "rehearsal"], "A", "Encore: màn biểu diễn thêm được khán giả yêu cầu."),
    q("The gallery will ------- paintings by local artists throughout the month.", ["exhibit", "exhibition", "exhibitor", "exhibited"], "A", "Will exhibit: trưng bày (động từ — sau will)."),
    q("The international film ------- attracts thousands of visitors every year.", ["festival", "matinee", "sponsor", "venue"], "A", "Film festival: liên hoan phim quốc tế."),
    q("She spent the afternoon visiting an art ------- near the city center.", ["gallery", "orchestra", "encore", "interval"], "A", "Art gallery: phòng triển lãm nghệ thuật."),
    q("Light refreshments are served during the ------- between Acts 1 and 2.", ["interval", "debut", "caption", "rehearsal"], "A", "Interval: giờ giải lao giữa các màn kịch."),
    q("Many art historians consider this painting to be the artist's -------.", ["masterpiece", "broadcast", "documentary", "screenplay"], "A", "Masterpiece: kiệt tác, tác phẩm xuất sắc nhất."),
    q("They bought tickets for the Sunday ------- to avoid the weekend evening crowds.", ["matinee", "encore", "premiere", "festival"], "A", "Matinee: suất diễn ban ngày (thường chiều Chủ nhật)."),
    q("The city ------- performed Tchaikovsky's Swan Lake at the opera house.", ["orchestra", "audience", "celebrity", "sponsor"], "A", "Orchestra: dàn nhạc giao hưởng."),
    q("The world ------- of the new film will take place in Paris next month.", ["premiere", "debut", "rehearsal", "repertoire"], "A", "World premiere: buổi ra mắt thế giới lần đầu tiên."),
    q("The ballet company held a final dress ------- before the opening night.", ["rehearsal", "interval", "matinee", "encore"], "A", "Dress rehearsal: buổi duyệt cuối cùng với trang phục đầy đủ."),
    q("The pianist has an impressive ------- of over 200 classical pieces.", ["repertoire", "subscription", "screenplay", "exhibit"], "A", "Repertoire: danh mục tác phẩm sẵn sàng biểu diễn."),
    q("The director won an award for the original ------- of the film.", ["screenplay", "broadcast", "caption", "admission"], "A", "Screenplay: kịch bản phim gốc (original screenplay)."),
    q("A local bank agreed to ------- the annual performing arts festival.", ["sponsor", "applaud", "compose", "broadcast"], "A", "Sponsor: tài trợ (động từ)."),
    q("She bought an annual ------- to a classical music streaming service.", ["subscription", "admission", "encore", "caption"], "A", "Annual subscription: đăng ký hàng năm."),
    q("The outdoor concert ------- was transformed into a spectacular stage.", ["venue", "gallery", "festival", "documentary"], "A", "Concert venue: địa điểm biểu diễn."),
    q("The young pianist is regarded as a ------- by music critics worldwide.", ["virtuoso", "celebrity", "choreographer", "composer"], "A", "Virtuoso: nghệ sĩ có tài năng xuất chúng."),
  ],
  written: [],
};
