import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const GENERAL_BUSINESS: IigTopic = {
  slug: "general-business",
  title: "General Business",
  titleVi: "Kinh doanh chung",
  summary: "Hợp đồng, đàm phán, đầu tư, cạnh tranh, thị trường và các khái niệm kinh doanh cơ bản.",
  words: [
    ["abide", "v", "/əˈbaɪd/", "tuân thủ", "Two parties agreed to abide by the judge's decision.", "Abide by: tuân theo (You'll have to abide by the rules of the game). Can't abide sth/sb: không thể chịu được, rất ghét (I can't abide people who look down on others)."],
    ["agreement", "n", "/əˈɡriːmənt/", "sự đồng ý; hợp đồng", "The agreement was signed during a meeting at the conference.", "Agreement with sb: thỏa thuận với ai; agreement between A and B: thỏa thuận giữa hai bên; come to an agreement: đi đến thỏa thuận, ký kết hợp đồng."],
    ["arrangement", "n", "/əˈreɪndʒmənt/", "sự sắp xếp, kế hoạch", "He has some special arrangements with his supplier, which means he's able to sell his goods more cheaply.", "Make an arrangement: sắp xếp (cuộc hẹn); come to an arrangement: đi đến hòa giải, thỏa thuận."],
    ["association", "n", "/əˌsəʊsiˈeɪʃn/", "tổ chức, hiệp hội", "This event was organized in association with a local school."],
    ["assurance", "n", "/əˈʃʊərəns/", "sự đảm bảo", "She gave me her assurance that she would sign the contract immediately.", "Life assurance: bảo hiểm nhân thọ; make assurance double sure: để cho hoàn toàn chắc chắn."],
    ["attend", "v", "/əˈtend/", "tham dự", "The meeting is on the fifth and we're hoping everyone will attend.", "Attend sth: tham dự sự kiện; attend to sb: chăm sóc ai; attend to sth: giải quyết, xử lý việc gì."],
    ["bankrupt", "adj", "/ˈbæŋkrʌpt/", "phá sản", "Hundreds of firms went bankrupt during the recession.", "Go bankrupt: phá sản; be morally bankrupt: không có đạo đức; be bankrupt of one's honour: mất hết danh dự."],
    ["budget", "n", "/ˈbʌdʒɪt/", "ngân sách", "The school budget is going to be cut again this year.", "On a budget / tight budget: ngân sách eo hẹp; over budget: vượt ngân sách; in the budget: trong ngân sách."],
    ["cancel", "v", "/ˈkænsl/", "hủy bỏ", "All flights have been cancelled because of bad weather."],
    ["collaborate", "v", "/kəˈlæbəreɪt/", "hợp tác", "A German company collaborated with an American firm to develop the product."],
    ["compare", "v", "/kəmˈpeə(r)/", "so sánh", "We compared the two reports carefully.", "Compare to: nhấn mạnh sự tương đồng, kể cả khi hai thứ khác nhau hoàn toàn (People compared her to Taylor Swift). Compare with: đặt cạnh nhau để nêu giống/khác (Instant coffee doesn't compare with freshly ground coffee)."],
    ["compete", "v", "/kəmˈpiːt/", "cạnh tranh", "We competed against three other companies to get this contract.", "Compete against/with sb in/for sth: cạnh tranh với ai để giành gì; compete with someone for talent: cạnh tranh nhân tài."],
    ["consequence", "n", "/ˈkɒnsɪkwəns/", "hậu quả, kết quả", "They must be prepared to accept the consequences of their actions.", "Take the consequence of sth: chịu hậu quả; as a consequence (of sth): do hậu quả của việc gì."],
    ["consider", "v", "/kənˈsɪdə(r)/", "cân nhắc, xem xét", "She's being considered for the job.", "Idiom: all things considered — sau khi đã cân nhắc mọi thứ (I think the party was great, all things considered)."],
    ["consume", "v", "/kənˈsjuːm/", "tiêu thụ", "The electricity industry consumes large amounts of fossil fuels."],
    ["contract", "n", "/ˈkɒntrækt/", "hợp đồng", "They could take legal action against you if you break the terms of the contract.", "Contract with sb / for sth; enter into / make / sign a contract: ký hợp đồng; be under contract to sb: đã ký hợp đồng làm việc cho ai."],
    ["convince", "v", "/kənˈvɪns/", "thuyết phục", "I've been trying to convince him to see a doctor.", "Convince: thuyết phục ai tin vào điều gì (He convinced me of his innocence). Persuade: thuyết phục ai làm gì (Can you persuade your sister to join in?)."],
    ["current", "adj", "/ˈkʌrənt/", "hiện tại, đang thịnh hành", "A lot of businesses are being hurt by the current high interest rates."],
    ["customer", "n", "/ˈkʌstəmə(r)/", "khách hàng", "We aim to give all our customers good service.", "Customer: người mua hàng hóa. Client: người nhận và sử dụng dịch vụ chuyên nghiệp, thiết kế riêng cho từng cá nhân."],
    ["determine", "v", "/dɪˈtɜːmɪn/", "xác định, quyết định", "Your health is determined in part by what you eat.", "Determine sb to do sth: thôi thúc ai làm gì; determine on V-ing: quyết tâm làm gì."],
    ["director", "n", "/dəˈrektə(r)/", "giám đốc; đạo diễn", "She has been appointed the director of the new information centre."],
    ["engage", "v", "/ɪnˈɡeɪdʒ/", "thuê, mướn; tham gia", "We have engaged a secretary to deal with all the paperwork.", "Engage sb as sth: thuê ai làm gì (She was engaged as a baby-sitter); engage in: tham gia, làm gì (At college she engaged in various activities)."],
    ["enterprise", "n", "/ˈentəpraɪz/", "doanh nghiệp", "He was responsible for building the pizza company into a billion-dollar enterprise.", "Company: tổ chức kinh doanh tạo lợi nhuận từ sản phẩm/dịch vụ; agency: công ty cung cấp một loại dịch vụ nhất định; enterprise: doanh nghiệp (state-owned enterprise)."],
    ["establish", "v", "/ɪˈstæblɪʃ/", "thành lập", "The committee was established in 1912.", "Establish one's reputation: củng cố thanh danh; establish oneself in sth: ổn định, có chỗ đứng."],
    ["evaluate", "v", "/ɪˈvæljueɪt/", "đánh giá", "It's important to evaluate our competition when making a business plan."],
    ["expire", "v", "/ɪkˈspaɪə(r)/", "hết hạn", "When does your driving licence expire?"],
    ["finance", "n", "/ˈfaɪnæns/", "tài chính", "I'd like to buy a new car, but my finances are in such a bad state that I can't afford to."],
    ["headquarters", "n", "/ˌhedˈkwɔːtəz/", "trụ sở chính", "The company's national headquarters is in Hanoi.", "Headquarter (v): đặt trụ sở chính (thường dùng bị động: BigHit is headquartered in Seoul). Headquarters (n): trụ sở chính."],
    ["implement", "v / n", "/ˈɪmplɪment/", "thi hành, thực hiện; dụng cụ", "The changes to the national health system will be implemented next year.", "Implement còn là danh từ chỉ đồ dùng, dụng cụ: sharp implements."],
    ["income", "n", "/ˈɪnkʌm/", "thu nhập", "More help is needed for people on low incomes.", "Salary: tiền lương cố định hàng tháng/năm. Income: tất cả các khoản tiền kiếm được (cả từ đầu tư, làm thêm)."],
    ["investment", "n", "/ɪnˈvestmənt/", "sự đầu tư", "This country needs investment in education."],
    ["legal", "adj", "/ˈliːɡl/", "hợp pháp, thuộc pháp lý", "We were advised to take legal advice."],
    ["market", "v / n", "/ˈmɑːkɪt/", "tiếp thị; thị trường", "It's a product that will sell if we can find the right way to market it.", "A buyer's market: thị trường người mua; in the market for sth: đang muốn mua gì; on the market: có bán trên thị trường."],
    ["merge", "v", "/mɜːdʒ/", "hợp nhất, sáp nhập", "They decided to merge the two companies into one."],
    ["negotiation", "n", "/nɪˌɡəʊʃiˈeɪʃn/", "cuộc đàm phán", "The agreement was reached after a series of difficult negotiations.", "Under negotiation: đang đàm phán; in negotiation with sb: trong quá trình đàm phán với ai; negotiation with sb: đàm phán với ai."],
    ["participate in", "v", "/pɑːˈtɪsɪpeɪt ɪn/", "tham gia", "She never participates in any of our discussions.", "Participate in: tham gia chủ động vào hoạt động, lễ hội. Attend: có mặt, tham dự (hội nghị, diễn văn), có thể không làm gì."],
    ["productive", "adj", "/prəˈdʌktɪv/", "năng suất, hiệu quả", "My time spent in the library was very productive."],
    ["proposal", "n", "/prəˈpəʊzl/", "lời đề nghị, đề xuất", "The proposal for a new stadium has been rejected.", "Under a proposal: theo đề xuất (Under these proposals, the budget will be significantly strengthened)."],
    ["representative", "n", "/ˌreprɪˈzentətɪv/", "người đại diện", "A representative from the tour company will meet you at the check-in."],
    ["reputation", "n", "/ˌrepjuˈteɪʃn/", "danh tiếng", "The company has a worldwide reputation for quality.", "Have a good/bad reputation; have a reputation as sth: nổi tiếng là…; have a reputation for (doing) sth: nổi tiếng về…"],
    ["require", "v", "/rɪˈkwaɪə(r)/", "yêu cầu, đòi hỏi", "If you require assistance with your bags, we'll be glad to get someone to help you."],
    ["resolve", "v", "/rɪˈzɒlv/", "giải quyết", "We hope to resolve the matter as soon as possible."],
    ["risk", "n", "/rɪsk/", "nguy cơ, rủi ro", "Expanding into a new market is a big risk.", "At risk: gặp nguy hiểm; at your own risk: tự chịu rủi ro; run/take a risk: chấp nhận rủi ro."],
    ["shareholder", "n", "/ˈʃeəhəʊldə(r)/", "cổ đông", "Shareholders will be voting on the proposed merger of the companies next week."],
    ["sponsor", "v / n", "/ˈspɒnsə(r)/", "tài trợ; nhà tài trợ", "We're trying to find companies to sponsor us.", "Danh từ sponsor còn có nghĩa: cha/mẹ đỡ đầu; người bảo lãnh; nhà tài trợ, hãng thuê quảng cáo."],
    ["strategy", "n", "/ˈstrætədʒi/", "chiến lược", "A business plan is a strategy for running a business and avoiding problems."],
    ["substitute", "v", "/ˈsʌbstɪtjuːt/", "thay thế (tạm thời)", "Don't try to substitute intuition for good planning.", "Replace: thay thế lâu dài, vĩnh viễn (Susan replaced him as the director of finance). Substitute: thay thế tạm thời (Bill substituted for Larry, who was off sick)."],
    ["tax", "n", "/tæks/", "thuế", "They're increasing the tax on cigarettes.", "Tax: thuế; taxation: hệ thống thuế."],
    ["vary", "v", "/ˈveəri/", "thay đổi, biến đổi", "The value of stocks will vary from month to month.", "Đừng nhầm với very (rất)."],
    ["workshop", "n", "/ˈwɜːkʃɒp/", "hội thảo (thực hành)", "She was invited to participate in a poetry workshop on campus.", "Development workshop: hội thảo phát triển; hands-on workshop: hội thảo thực hành."],
  ],
  quiz: [
    q("Do you belong to any professional or trade -------?", ["teams", "associations", "groups", "class"], "B", "Trade association: hiệp hội thương mại."),
    q("The wedding was ------- at the last minute.", ["cancelled", "visited", "organized", "watered"], "A", "'Đám cưới bị hủy vào phút chót.'"),
    q("We are ------- to design and build a vehicle that will achieve 200 miles per gallon.", ["collaborating", "collaborative", "collaboration", "collaborate"], "A", "Be + V-ing (hiện tại tiếp diễn): đang hợp tác."),
    q("25 per cent of the world's population ------- 80 per cent of the planet's resources.", ["use", "consumes", "using", "consuming"], "B", "Chủ ngữ population (số ít) → consumes."),
    q("Have you seen the ------- issue (= the most recently published) of Vogue magazine?", ["new", "old", "current", "outdated"], "C", "Current issue: số báo hiện hành."),
    q("She wrote the screenplay and wanted him as -------.", ["director", "manager", "doctor", "assistant"], "A", "Viết kịch bản và muốn anh ấy làm đạo diễn."),
    q("This does not seem like an accurate way of ------- employees' performance.", ["evaluate", "buy", "buying", "evaluating"], "D", "Sau giới từ of là V-ing; evaluate performance: đánh giá hiệu suất."),
    q("The contract between the two companies will ------- at the end of the year.", ["expire", "over", "ended", "started"], "A", "Will + V nguyên mẫu; expire: hết hạn."),
    q("The country's two biggest banks are planning to -------.", ["merged", "separated", "combination", "merge"], "D", "Plan to + V nguyên mẫu; merge: sáp nhập."),
    q("Alex is excited about his ------- sales proceeds.", ["productive", "active", "professional", "energetic"], "A", "Productive: hiệu quả, năng suất cao."),
    q("He visited China in his official capacity as America's trade -------.", ["representative", "represent", "representation", "representational"], "A", "Trade representative: đại diện thương mại."),
    q("True marriage ------- us to show trust and loyalty.", ["need", "requires", "uses", "tries"], "B", "Chủ ngữ số ít; require sb to V: đòi hỏi ai làm gì."),
    q("The couple ------- their differences.", ["tried", "talked", "fought", "resolved"], "D", "Resolve differences: giải quyết bất đồng."),
    q("Poor marketing ------- was blamed for the failure of the service to catch on.", ["ideas", "new", "strategy", "information"], "C", "Marketing strategy: chiến lược tiếp thị."),
  ],
  written: [
    { q: "Chia dạng đúng của từ trong ngoặc: She's got a diploma in banking and ------- . (Finance)", a: "finance" },
    { q: "Chia dạng đúng của từ trong ngoặc: We're always looking for ------- opportunities. (Invest)", a: "investment" },
    { q: "Chia dạng đúng của từ trong ngoặc: The report fails to make a distinction between ------- and ------- immigrants. (Legal)", a: "legal / illegal" },
    { q: "Chia dạng đúng của từ trong ngoặc: Company ------- approved the merger. (Share)", a: "shareholders" },
  ],
};
