import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const TRAVEL: IigTopic = {
  slug: "travel",
  title: "Travel",
  titleVi: "Du lịch",
  summary: "Đặt chỗ, phương tiện, sân bay, khách sạn, điểm đến và trải nghiệm du lịch.",
  words: [
    ["accommodation", "n", "/əˌkɒməˈdeɪʃn/", "nơi ở", "The price of your holiday includes meals, accommodation and transportation."],
    ["adventurous", "adj", "/ədˈventʃərəs/", "phiêu lưu, mạo hiểm", "Adventurous travelers are eager to take risks and have new experiences."],
    ["amenity", "n", "/əˈmiːnəti/", "tiện nghi", "The hotel offers all basic amenities including health clubs, conference facilities, and banqueting rooms.", "Amenity: thứ mang lại sự thoải mái, thích thú, phục vụ giải trí (điều hòa, Wi-Fi, thang máy). Facility: địa điểm/thiết bị đáp ứng nhu cầu cụ thể, không phục vụ giải trí (cơ sở y tế, viễn thông, giáo dục)."],
    ["arrangement", "n", "/əˈreɪndʒmənt/", "sự sắp xếp", "You'll need this information to make travel arrangements on airfare, car rentals, lodging, and more."],
    ["arrival", "n", "/əˈraɪvl/", "sự đến nơi", "Numerous people gathered to await the arrival of a famous singer at the airport.", "Arrival card: thẻ khai nhập cảnh; arrival notice: giấy báo hàng đến; arrival list: danh sách khách đến."],
    ["beverage", "n", "/ˈbevərɪdʒ/", "đồ uống", "The government has imposed a ban on the sale of alcoholic beverages.", "Drink: đồ uống nói chung. Beverage: thường chỉ đồ uống (đặc biệt đồ uống nóng như trà, cà phê) trong ngữ cảnh trang trọng."],
    ["board", "v / n", "/bɔːd/", "lên (tàu, xe, máy bay); cái bảng; hội đồng", "Passengers who are waiting to board, please go to the airport lounge.", "Danh từ board: (1) cái bảng (He wrote his essay on the board); (2) hội đồng quản trị (the board of directors)."],
    ["border", "n", "/ˈbɔːdə(r)/", "biên giới", "She spent two weeks in a town on the border between the U.S. and Mexico.", "Border: đường ranh giới giữa hai quốc gia (thường theo sông, núi). Boundary: ranh giới hành chính (quận, huyện). Frontier: biên giới giữa các nước có hệ thống chính trị khác nhau, được canh phòng nghiêm ngặt."],
    ["budget", "adj / n", "/ˈbʌdʒɪt/", "tiết kiệm, giá rẻ; ngân sách", "Choosing a good and affordable hotel is the key to a memorable budget travel experience.", "Danh từ budget: ngân sách — The company has drawn up a budget for the coming financial year."],
    ["conductor", "n", "/kənˈdʌktə(r)/", "nhân viên trên tàu, xe", "The bus conductor told him to get off because he couldn't pay the fare.", "Anh Anh: người phụ trách lái tàu, xe. Anh Mỹ: người bán vé, soát vé tàu."],
    ["crew", "n / v", "/kruː/", "phi hành đoàn, đoàn thủy thủ", "Luckily, none of the passengers and crew were injured in the accident.", "Động từ crew: điều khiển/chèo thuyền — Normally, this kind of boat is crewed by eight people."],
    ["cruise", "v / n", "/kruːz/", "đi du thuyền; chuyến du thuyền", "She and her husband were planning to go on a round-the-world cruise.", "Cruise: du thuyền lớn chở hàng nghìn khách, thuộc công ty du lịch. Yacht: du thuyền sang trọng, thường thuộc sở hữu cá nhân."],
    ["cuisine", "n", "/kwɪˈziːn/", "ẩm thực", "He suggested that I should travel to Japan and learn to cook traditional Japanese cuisine.", "Cuisine: ẩm thực mang đặc trưng vùng miền. Delicacy: món ngon, hiếm, thể hiện sự tinh tế của một nền văn hóa."],
    ["delay", "v / n", "/dɪˈleɪ/", "trì hoãn; sự chậm trễ", "The flight had to be delayed due to the terrible weather.", "Danh từ: Despite repeated delays in construction, the new museum was completed on time."],
    ["depart", "v", "/dɪˈpɑːt/", "khởi hành", "The last bus to Cleveland departs at 8 p.m."],
    ["destination", "n", "/ˌdestɪˈneɪʃn/", "điểm đến", "The museum is a popular destination for art lovers.", "Destination còn được dùng như tính từ chỉ nơi đáng ghé thăm: a destination restaurant."],
    ["disembark", "v", "/ˌdɪsɪmˈbɑːk/", "rời (tàu, máy bay)", "Passengers are disembarking from a plane which has brought them from China."],
    ["dock", "n", "/dɒk/", "bến tàu", "There are plans to redevelop the old docks for new housing.", "Dock: khu vực khép kín trong cảng để bốc dỡ, sửa chữa tàu. Harbour: bến cảng nơi tàu thuyền neo đậu an toàn."],
    ["e-ticket", "n", "/ˈiː tɪkɪt/", "vé điện tử", "Next week, the airline will introduce its e-ticket selling system.", "Tiền tố e- chỉ những gì liên quan đến điện tử: e-bank, e-commerce, e-learning."],
    ["ecotourism", "n", "/ˈiːkəʊtʊərɪzəm/", "du lịch sinh thái", "If ecotourism is properly carried out, it can support conservation and environmental management.", "Tiền tố eco- liên quan đến sinh thái: ecology, ecosystem, ecosphere, eco-disaster."],
    ["entrance", "n", "/ˈentrəns/", "cổng vào, lối vào", "The building has two entrances — one at the front and one at the back.", "Động từ entrance /ɪnˈtrɑːns/: mê hoặc — He has entranced millions of girls with his sense of humor."],
    ["expedition", "n", "/ˌekspəˈdɪʃn/", "cuộc thám hiểm", "She has made three expeditions to Mexico to study exotic kinds of birds.", "Trip: chuyến đi ngắn từ A đến B rồi về A. Tour: chuyến đi thưởng ngoạn nhiều nơi. Excursion: chuyến tham quan ngắn, thường theo nhóm. Expedition: cuộc thám hiểm có mục đích cụ thể."],
    ["experience", "n / v", "/ɪkˈspɪəriəns/", "trải nghiệm; trải qua", "His famous novel is based on his own travel experience.", "Động từ: We experienced a lot of difficulties in dealing with complaints about hotel reservations."],
    ["explore", "v", "/ɪkˈsplɔː(r)/", "khám phá", "They are ready to set off to explore the world."],
    ["fare", "n", "/feə(r)/", "tiền vé (xe, tàu)", "The one-way fare to Oxford is approximately $25.", "Fee: phí cho dịch vụ đặc thù (học phí, phí đăng ký). Fare: phí đi phương tiện giao thông. Toll: lệ phí cầu đường."],
    ["foreign", "adj", "/ˈfɒrən/", "nước ngoài; xa lạ", "Learning a foreign language not only improves your communication skills but also increases your creativity.", "Foreign to sb: xa lạ, không quen thuộc — The idea of using recycled products is completely foreign to them."],
    ["guidebook", "n", "/ˈɡaɪdbʊk/", "sách hướng dẫn du lịch", "This guidebook provides much information about the tourist attractions and special services in Hanoi."],
    ["heritage", "n", "/ˈherɪtɪdʒ/", "di sản", "Xoan singing is recognized as an intangible cultural heritage of Vietnam."],
    ["highway", "n", "/ˈhaɪweɪ/", "đường cao tốc", "All citizens are entitled to use the public highway.", "Freeway: đường cao tốc hạn chế phương tiện, không thu phí, cho phép tốc độ cao hơn. Highway: đường cao tốc công cộng, có thể thu phí, lưu lượng lớn hơn."],
    ["itinerary", "n", "/aɪˈtɪnərəri/", "lịch trình, hành trình", "Visits to five different Asian countries are included in your itinerary."],
    ["landscape", "n", "/ˈlændskeɪp/", "cảnh quan", "Spain's desert landscape is desolate, yet stunning.", "Xuất hiện trong tiếng Anh năm 1603, gốc tiếng Trung Hà Lan landscap (khu vực)."],
    ["license", "n", "/ˈlaɪsns/", "giấy phép", "To hire a car you must have a passport and a valid driving license."],
    ["lounge", "n / v", "/laʊndʒ/", "phòng chờ; ngồi thư thái", "Passengers of the flight to New York, please wait in the departure lounge.", "Động từ: Several students were lounging around, reading books and magazines."],
    ["luggage", "n", "/ˈlʌɡɪdʒ/", "hành lý", "She is about to buy some new luggage for her summer vacation next month.", "Xuất hiện những năm 1590, từ lug (kéo) + hậu tố -age: thứ được kéo đi. Luggage là danh từ không đếm được."],
    ["navigate", "v", "/ˈnævɪɡeɪt/", "điều hướng, định hướng", "She is able to navigate her way through the forest."],
    ["overseas", "adv / adj", "/ˌəʊvəˈsiːz/", "ở nước ngoài", "She has been working overseas for a manufacturing company.", "Tính từ: There are a lot of overseas students studying at Cambridge University."],
    ["passenger", "n", "/ˈpæsɪndʒə(r)/", "hành khách", "Several car passengers received serious injuries in the crash."],
    ["remote", "adj", "/rɪˈməʊt/", "xa xôi; rất nhỏ; xa cách", "As technology has advanced, travelers can now travel to remote natural areas.", "Remote còn nghĩa: (1) rất ít, rất nhỏ — a remote chance; (2) xa cách, lạnh lùng — her voice sounds remote and cold."],
    ["rental", "n / adj", "/ˈrentl/", "việc thuê; (thuộc) cho thuê", "The price consists of accommodation and car rental.", "Tính từ: rental prices will increase rapidly in the next six months."],
    ["reserve", "v", "/rɪˈzɜːv/", "đặt trước", "She reserved a double room at the Rose Hotel last summer."],
    ["round-trip", "adj", "/ˌraʊnd ˈtrɪp/", "khứ hồi", "Vietnam Airlines offers customers up to 15% discount on round-trip tickets.", "Round-trip: hai chiều (round-trip ticket, round-trip flight). One-way: một chiều (one-way ticket)."],
    ["route", "n / v", "/ruːt/", "tuyến đường; gửi theo tuyến", "She showed me the quickest route to the museum by motorbike.", "Động từ route: (1) gửi hàng theo tuyến nhất định (Packages are routed via Paris); (2) chuyển thông tin qua mạng."],
    ["service", "n", "/ˈsɜːvɪs/", "dịch vụ", "The new digital system helps citizens access the service more easily.", "Service còn nghĩa: (1) cục, ban, ngành (diplomatic services); (2) quân chủng (Navy, Air Force); (3) buổi lễ."],
    ["shuttle", "n / v", "/ˈʃʌtl/", "phương tiện đưa đón", "You can take the shuttle from Sihanoukville airport to Sihanoukville centre.", "Động từ: đưa đón qua lại giữa hai nơi — A bus shuttles passengers from the station to the terminal."],
    ["sightseeing", "n", "/ˈsaɪtsiːɪŋ/", "việc ngắm cảnh, tham quan", "The campsite is an ideal destination for birdwatching and sightseeing."],
    ["souvenir", "n", "/ˌsuːvəˈnɪə(r)/", "quà lưu niệm", "I bought some clothes as souvenirs of Paris.", "Xuất hiện năm 1775 với nghĩa 'ký ức, sự tưởng nhớ' (gốc tiếng Pháp souvenir = ghi nhớ); sau này mới mang nghĩa đồ lưu niệm."],
    ["terminal", "n / adj", "/ˈtɜːmɪnl/", "nhà ga; giai đoạn cuối", "A new rail terminal will be constructed at King's Cross station.", "Tính từ: (1) giai đoạn cuối (terminal cancer); (2) cực kỳ khó chịu (terminal boredom)."],
    ["tourist", "n", "/ˈtʊərɪst/", "du khách", "This country annually attracts tourists from all over the world.", "Tourist: thường đi theo nhóm, theo lộ trình do công ty du lịch vạch sẵn. Traveller: thường đi một mình, tự do khám phá."],
    ["transportation", "n", "/ˌtrænspɔːˈteɪʃn/", "phương tiện đi lại, vận chuyển", "The government is providing free transportation to the theater from downtown."],
    ["valid", "adj", "/ˈvælɪd/", "có hiệu lực", "His bus pass is no longer valid."],
  ],
  quiz: [
    q("When you register for out-of-town conferences, make room ------- as soon as you decide to attend.", ["accommodate", "accommodations", "accommodating", "accommodated"], "B", "Room accommodations: chỗ ở (danh từ)."),
    q("Traveling alone into a jungle is -------.", ["adventurous", "compelling", "exotic", "dauntless"], "A", "Adventurous: phiêu lưu, mạo hiểm."),
    q("Arrangements for the excursion have now been -------.", ["accomplished", "done", "completed", "concluded"], "C", "Arrangements have been completed: việc sắp xếp đã hoàn tất."),
    q("The train for Cambridge departs ------- platform 9.", ["for", "from", "to", "in"], "B", "Depart from: khởi hành từ (sân ga)."),
    q("When the pilot turns off the seatbelt sign, passengers can get ready to ------- the plane.", ["abandon", "arrive", "land", "disembark"], "D", "Disembark the plane: rời máy bay."),
    q("The store designer's ------- of the art of different countries gave the store an exotic look.", ["explore", "exploration", "exploratory", "explorer"], "B", "Sau sở hữu cách cần danh từ exploration (sự khám phá)."),
    q("The advice found in a good ------- to Japan is priceless.", ["leaflet", "brochure", "handbook", "guidebook"], "D", "Guidebook to + địa điểm: sách hướng dẫn du lịch."),
    q("Folk songs are part of our ------- heritage.", ["typical", "usual", "common", "ordinary"], "C", "Common heritage: di sản chung."),
    q("He offered to arrange an ------- so that they could visit there in the festive season.", ["itinerary", "route", "path", "map"], "A", "Arrange an itinerary: sắp xếp lịch trình."),
    q("The ------- for the trial version of Exi 2.0 software is valid for the 30-day period immediately following the date of issue.", ["certificate", "allowance", "license", "permission"], "C", "Software license: giấy phép phần mềm."),
    q("To make sure that the canal is ------- year-round, measures will be taken to raise the water level.", ["navigator", "navigation", "navigate", "navigable"], "D", "Sau to be cần tính từ navigable (tàu bè đi lại được)."),
    q("Our airline is pleased to offer a variety of amenities designed to ensure ------- comfort.", ["staffs'", "conductors'", "attendants'", "passengers'"], "D", "Tiện nghi đảm bảo sự thoải mái của hành khách."),
    q("On the day that Sue tells us about the wedding, let's ------- the patio at Alfredo's Restaurant and celebrate with a late dinner.", ["reserve", "reserving", "reserved", "reservation"], "A", "Let's + V nguyên mẫu."),
    q("We ------- a sightseeing tour in Melbourne.", ["made", "created", "did", "formed"], "C", "Do sightseeing: đi tham quan."),
    q("The movie star requested private ------- to the theater.", ["transformation", "transition", "transportation", "transposition"], "C", "Private transportation: phương tiện đi lại riêng."),
    q("Weekend passes to Lawton Amusement Park are ------- for six months from the date of purchase.", ["valid", "accurate", "original", "actual"], "A", "Valid: có hiệu lực."),
  ],
  written: [],
};
