import type { IigTopic } from "@/lib/content/iig-vocab/types";
import { etsWords } from "./helpers";

/** ETS TOEIC 2026 Vol. 5 — từ vựng phần Nghe (Part 1–4), Test 01–10 (nghĩa tiếng Việt theo ngữ cảnh TOEIC của sách). */
export const ETS_LISTENING: IigTopic[] = [
  {
    slug: "lc-test-01",
    group: "Nghe (LC)",
    title: "LC Test 01",
    titleVi: "Nghe · Test 01",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 01.",
    words: etsWords([
      ["carry", "mang, vác; mang theo"],
      ["remove", "cởi ra, tháo ra"],
      ["pour", "rót, đổ"],
      ["beverage", "đồ uống"],
      ["light fixture", "đèn chiếu sáng (thiết bị đèn gắn cố định)"],
      ["install", "lắp đặt"],
      ["warehouse", "nhà kho"],
      ["meeting minutes", "biên bản cuộc họp"],
      ["accounting", "kế toán"],
      ["assistant", "trợ lý"],
      ["account", "tài khoản"],
      ["analyst", "nhà phân tích"],
      ["decoration", "đồ trang trí"],
      ["competent", "có năng lực, thành thạo"],
      ["retreat", "chuyến dã ngoại, chuyến đi ngắn (của công ty)"],
      ["solve", "giải quyết"],
      ["departure", "sự khởi hành, rời đi"],
      ["introduction", "phần giới thiệu, lời mở đầu"],
      ["retirement", "sự nghỉ hưu"],
      ["appointment", "cuộc hẹn, lịch hẹn"],
      ["borrow", "mượn"],
      ["brochure", "tờ rơi, sách giới thiệu"],
      ["confirmation", "sự xác nhận, giấy xác nhận"],
      ["process", "quy trình, quá trình"],
      ["expense", "chi phí, khoản chi"],
      ["finance", "tài chính"],
      ["correct", "đúng, chính xác"],
      ["demonstration", "buổi trình diễn, thao tác mẫu"],
      ["charge", "sạc (pin)"],
      ["device", "thiết bị"],
      ["cost", "tốn (chi phí)"],
      ["extra", "thêm, dư ra"],
      ["in charge of", "phụ trách"],
      ["crew", "đội, nhóm làm việc"],
      ["available", "có sẵn, có thể sử dụng"],
      ["depend on", "tùy thuộc vào"],
      ["addition", "phần bổ sung"],
      ["consider", "cân nhắc, xem xét"],
      ["lower", "hạ xuống, giảm"],
      ["headquarters", "trụ sở chính"],
      ["book", "đặt (chỗ, vé)"],
      ["regional", "thuộc khu vực"],
      ["performance", "thành tích, hiệu suất; buổi biểu diễn"],
      ["advance", "trước (đặt trước)"],
      ["payment", "sự thanh toán"],
      ["required", "bắt buộc, cần thiết"],
      ["sign up for", "đăng ký"],
      ["competition", "cuộc thi"],
      ["merchandise", "hàng hóa"],
      ["permit", "giấy phép"],
      ["agree", "đồng ý, thỏa thuận"],
      ["annual", "hằng năm, thường niên"],
      ["expand", "mở rộng"],
      ["take care of", "xử lý, lo liệu"],
      ["attendee", "người tham dự"],
      ["job opening", "vị trí tuyển dụng"],
      ["author", "tác giả"],
      ["reserve", "đặt trước"],
      ["revise", "chỉnh sửa, thay đổi"],
      ["budget", "ngân sách"],
      ["get rid of", "loại bỏ"],
      ["unfortunately", "thật không may"],
      ["operation", "sự vận hành, kinh doanh"],
      ["application", "đơn đăng ký, đơn xin việc"],
      ["directions", "chỉ đường"],
      ["owner", "chủ sở hữu"],
      ["location", "chi nhánh, địa điểm"],
      ["local", "thuộc địa phương"],
      ["advantage", "lợi thế"],
      ["rental", "sự thuê, cho thuê"],
      ["release", "phát hành, ra mắt"],
      ["issue", "vấn đề"],
      ["secure", "đảm bảo có được"],
      ["conduct", "tiến hành, thực hiện"],
      ["negotiate", "đàm phán"],
      ["maintenance", "sự bảo trì"],
      ["randomly", "ngẫu nhiên"],
      ["malfunction", "trục trặc"],
      ["complete", "hoàn thành"],
      ["increase", "tăng lên"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-02",
    group: "Nghe (LC)",
    title: "LC Test 02",
    titleVi: "Nghe · Test 02",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 02.",
    words: etsWords([
      ["hang", "treo, được treo"],
      ["luggage", "hành lý"],
      ["lean against", "dựa vào"],
      ["railing", "lan can"],
      ["vehicle", "xe cộ, phương tiện"],
      ["stack", "xếp chồng"],
      ["reach for", "với tay lấy"],
      ["shelf", "kệ"],
      ["set up", "chuẩn bị, lắp đặt"],
      ["postpone", "hoãn lại"],
      ["proposal", "đề xuất, bản đề xuất"],
      ["convenient", "thuận tiện"],
      ["take place", "diễn ra, được tổ chức"],
      ["last", "kéo dài"],
      ["rate", "giá cước, mức phí"],
      ["renovation", "sự cải tạo, sửa chữa"],
      ["material", "vật liệu"],
      ["fee", "phí, lệ phí"],
      ["discontinue", "ngừng (sản xuất, dịch vụ)"],
      ["instructor", "giảng viên, người hướng dẫn"],
      ["cafeteria", "nhà ăn, căng tin"],
      ["sold out", "bán hết, hết vé"],
      ["strategy", "chiến lược"],
      ["opposite", "đối diện"],
      ["submit", "nộp"],
      ["residential", "thuộc khu dân cư"],
      ["broken", "bị hỏng"],
      ["complain", "phàn nàn, khiếu nại"],
      ["instructions", "hướng dẫn, sách hướng dẫn"],
      ["expired", "hết hạn"],
      ["volunteer", "làm tình nguyện; tình nguyện viên"],
      ["approval", "sự phê duyệt"],
      ["access", "quyền truy cập, sử dụng"],
      ["transportation", "phương tiện giao thông"],
      ["promotional", "mang tính khuyến mãi, quảng bá"],
      ["currently", "hiện tại"],
      ["address", "giải quyết (vấn đề)"],
      ["decline", "sự sụt giảm; sụt giảm"],
      ["organize", "tổ chức, sắp xếp"],
      ["celebrity", "người nổi tiếng"],
      ["sponsor", "nhà tài trợ"],
      ["reduce", "giảm"],
      ["property", "tòa nhà, bất động sản"],
      ["reward", "thưởng"],
      ["demand", "nhu cầu"],
      ["potential", "tiềm năng"],
      ["candidate", "ứng viên"],
      ["competitor", "đối thủ cạnh tranh"],
      ["venue", "địa điểm tổ chức"],
      ["former", "cũ, trước đây"],
      ["résumé", "sơ yếu lý lịch"],
      ["arrange", "sắp xếp"],
      ["colleague", "đồng nghiệp"],
      ["appropriate", "phù hợp"],
      ["recruitment", "sự tuyển dụng"],
      ["reject", "từ chối"],
      ["assistance", "sự trợ giúp"],
      ["affordable", "giá cả phải chăng"],
      ["invitation", "lời mời, thiệp mời"],
      ["typically", "thường thì"],
      ["merger", "sự sáp nhập"],
      ["durable", "bền"],
      ["justify", "biện minh"],
      ["inspection", "sự kiểm tra"],
      ["prototype", "nguyên mẫu"],
      ["originally", "ban đầu, vốn dĩ"],
      ["share", "chia sẻ"],
      ["shorten", "rút ngắn"],
      ["accept", "chấp nhận"],
      ["loan", "khoản vay"],
      ["layout", "sơ đồ bố trí, cách sắp xếp"],
      ["proof", "bằng chứng"],
      ["insurance", "bảo hiểm"],
      ["upcoming", "sắp tới"],
      ["opportunity", "cơ hội"],
      ["brief", "ngắn gọn"],
      ["screen", "sàng lọc"],
      ["invoice", "hóa đơn"],
      ["incorrect", "sai, không chính xác"],
      ["frequent", "thường xuyên"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-03",
    group: "Nghe (LC)",
    title: "LC Test 03",
    titleVi: "Nghe · Test 03",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 03.",
    words: etsWords([
      ["fix", "sửa chữa, khắc phục"],
      ["pedestrian", "người đi bộ"],
      ["attend", "tham dự"],
      ["face", "hướng về, đối mặt"],
      ["certificate", "chứng chỉ, giấy chứng nhận"],
      ["press conference", "họp báo"],
      ["weigh", "nặng (bao nhiêu)"],
      ["quarter", "quý"],
      ["directory", "danh bạ, bảng chỉ dẫn"],
      ["be supposed to", "được cho là phải, có nhiệm vụ"],
      ["replace", "thay thế"],
      ["lead", "dẫn dắt, chủ trì; sự dẫn đầu"],
      ["award-winning", "từng đoạt giải"],
      ["supplies", "đồ dùng, vật tư"],
      ["storage", "sự lưu trữ, kho chứa"],
      ["manufacturer", "nhà sản xuất"],
      ["measures", "biện pháp"],
      ["success", "sự thành công; tác phẩm thành công"],
      ["upstairs", "ở tầng trên"],
      ["draft", "bản nháp"],
      ["appreciate", "cảm kích, biết ơn"],
      ["extend", "gia hạn, mở rộng"],
      ["warranty", "giấy bảo hành"],
      ["qualification", "trình độ chuyên môn, bằng cấp"],
      ["unexpected", "bất ngờ, không lường trước"],
      ["floor plan", "sơ đồ mặt bằng"],
      ["architect", "kiến trúc sư"],
      ["inspect", "kiểm tra"],
      ["approximately", "khoảng, xấp xỉ"],
      ["recommendation", "sự giới thiệu, lời khuyên"],
      ["patron", "khách hàng"],
      ["regular", "thông thường"],
      ["deposit", "tiền đặt cọc"],
      ["reschedule", "dời lịch, sắp xếp lại lịch"],
      ["prescription", "đơn thuốc"],
      ["inconvenient", "bất tiện"],
      ["medication", "thuốc"],
      ["inventory", "kiểm kê hàng tồn kho; hàng tồn kho"],
      ["drop", "giảm xuống"],
      ["stand out", "nổi bật"],
      ["input", "ý kiến đóng góp"],
      ["athlete", "vận động viên"],
      ["consult", "tham khảo ý kiến"],
      ["faulty", "bị lỗi"],
      ["understaffed", "thiếu nhân viên"],
      ["feature", "đăng bài đặc biệt; có đặc điểm nổi bật"],
      ["public", "công khai"],
      ["expire", "hết hạn"],
      ["archive", "kho lưu trữ hồ sơ"],
      ["verify", "xác minh"],
      ["confirm", "xác nhận"],
      ["deadline", "hạn chót"],
      ["apply for", "nộp đơn xin, đăng ký"],
      ["renew", "gia hạn"],
      ["subscription", "sự đăng ký dài hạn"],
      ["appear", "xuất hiện"],
      ["nominate", "đề cử"],
      ["refund", "tiền hoàn lại"],
      ["goods", "hàng hóa"],
      ["authority", "quyền hạn, người có thẩm quyền"],
      ["transaction", "giao dịch"],
      ["efficiently", "hiệu quả"],
      ["significant", "đáng kể"],
      ["advertisement", "quảng cáo"],
      ["regulation", "quy định"],
      ["organic", "hữu cơ"],
      ["entirely", "hoàn toàn"],
      ["individual", "cá nhân"],
      ["nutritional", "thuộc dinh dưỡng"],
      ["investment", "sự đầu tư"],
      ["donate", "quyên góp"],
      ["charity", "tổ chức từ thiện"],
      ["unavailable", "vắng mặt, không có sẵn"],
      ["participate in", "tham gia"],
      ["relocate", "di dời"],
      ["affect", "ảnh hưởng"],
      ["condition", "tình trạng, điều kiện"],
      ["reference", "thư giới thiệu; người giới thiệu"],
      ["hygienist", "chuyên viên vệ sinh răng miệng"],
      ["reimbursement", "sự hoàn trả chi phí"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-04",
    group: "Nghe (LC)",
    title: "LC Test 04",
    titleVi: "Nghe · Test 04",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 04.",
    words: etsWords([
      ["cross", "băng qua"],
      ["traffic", "giao thông"],
      ["put together", "lắp ráp"],
      ["empty", "làm trống, đổ hết"],
      ["reservation", "sự đặt chỗ"],
      ["commute", "đi làm, đi học"],
      ["usually", "thường thì"],
      ["negative", "tiêu cực"],
      ["job posting", "tin tuyển dụng"],
      ["council", "hội đồng"],
      ["review", "xem xét, đánh giá; bài đánh giá"],
      ["shift", "ca làm việc"],
      ["valid", "có hiệu lực"],
      ["identification", "giấy tờ tùy thân"],
      ["post", "đăng tải"],
      ["transfer", "chuyển, thuyên chuyển"],
      ["in time", "kịp lúc"],
      ["in person", "trực tiếp"],
      ["tenant", "người thuê nhà"],
      ["particular", "đặc biệt, cụ thể"],
      ["district", "quận, khu vực"],
      ["routinely", "thường xuyên"],
      ["congested", "tắc nghẽn"],
      ["temporarily", "tạm thời"],
      ["ingredient", "nguyên liệu, thành phần"],
      ["fairly", "khá"],
      ["guarantee", "sự bảo đảm"],
      ["forward", "chuyển tiếp"],
      ["household", "hộ gia đình; thuộc gia đình"],
      ["industrial", "thuộc công nghiệp"],
      ["textile", "hàng dệt may"],
      ["pharmaceutical", "dược phẩm"],
      ["skilled", "lành nghề"],
      ["details", "chi tiết"],
      ["overseas", "ở nước ngoài"],
      ["vendor", "nhà cung cấp, người bán hàng"],
      ["timeline", "tiến độ"],
      ["appearance", "sự xuất hiện"],
      ["act", "diễn xuất, hành động"],
      ["fill", "lấp đầy"],
      ["revised", "đã được sửa đổi"],
      ["workstation", "bàn làm việc"],
      ["unpredictability", "tính khó lường"],
      ["in advance", "trước"],
      ["collection", "bộ sưu tập"],
      ["positive", "tích cực"],
      ["contribution", "sự đóng góp"],
      ["recognize", "công nhận"],
      ["priority", "sự ưu tiên"],
      ["exceptional", "xuất sắc"],
      ["criticism", "sự chỉ trích"],
      ["accurate", "chính xác"],
      ["outcome", "kết quả"],
      ["encourage", "khuyến khích"],
      ["focus on", "tập trung vào"],
      ["definitely", "chắc chắn"],
      ["entire", "toàn bộ"],
      ["knowledgeable", "am hiểu"],
      ["own", "sở hữu"],
      ["stock", "nhập hàng; hàng tồn kho"],
      ["illustrator", "họa sĩ minh họa"],
      ["temporary", "tạm thời"],
      ["concerned", "lo lắng"],
      ["statement", "bảng sao kê"],
      ["abroad", "ở nước ngoài"],
      ["clarify", "làm rõ"],
      ["resource", "tài nguyên"],
      ["fertilizer", "phân bón"],
      ["tolerant", "chịu đựng được"],
      ["irrigation", "sự tưới tiêu"],
      ["disruption", "sự gián đoạn"],
      ["multiple", "nhiều"],
      ["discover", "khám phá"],
      ["restore", "khôi phục"],
      ["authentic", "đích thực"],
      ["recruit", "tuyển dụng"],
      ["challenging", "đầy thách thức"],
      ["unfavorable", "bất lợi"],
      ["prospective", "tiềm năng"],
      ["persuade", "thuyết phục"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-05",
    group: "Nghe (LC)",
    title: "LC Test 05",
    titleVi: "Nghe · Test 05",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 05.",
    words: etsWords([
      ["container", "hộp đựng"],
      ["information", "thông tin"],
      ["seal", "niêm phong"],
      ["rack", "giá, móc treo"],
      ["crowded", "đông đúc"],
      ["inspector", "thanh tra"],
      ["exterior", "bên ngoài"],
      ["due", "đến hạn"],
      ["bill", "hóa đơn"],
      ["fund-raising", "gây quỹ"],
      ["representative", "người đại diện"],
      ["promote", "thăng chức, quảng bá"],
      ["registration", "sự đăng ký"],
      ["quarterly", "hằng quý"],
      ["include", "bao gồm"],
      ["adjust", "điều chỉnh"],
      ["pitch", "bài thuyết trình chào hàng"],
      ["analysis", "sự phân tích"],
      ["greet", "chào đón"],
      ["current", "hiện tại"],
      ["estimate", "ước tính"],
      ["contract", "hợp đồng"],
      ["onboarding", "đào tạo hội nhập nhân viên mới"],
      ["institution", "tổ chức, cơ quan"],
      ["previous", "trước đây"],
      ["meet", "đáp ứng"],
      ["supplier", "nhà cung cấp"],
      ["target audience", "đối tượng mục tiêu"],
      ["develop", "phát triển"],
      ["launch", "ra mắt"],
      ["challenge", "thử thách"],
      ["doubtful", "nghi ngờ"],
      ["suggestion", "đề xuất"],
      ["associate", "đồng nghiệp, nhân viên"],
      ["highlight", "điểm nổi bật; làm nổi bật"],
      ["catch up", "bắt kịp"],
      ["organization", "tổ chức"],
      ["miss", "lỡ, bỏ lỡ"],
      ["avoid", "tránh"],
      ["bid", "giá thầu"],
      ["renovate", "cải tạo"],
      ["compile", "biên soạn, tổng hợp"],
      ["comment", "ý kiến"],
      ["recurring", "định kỳ, lặp lại"],
      ["complaint", "lời phàn nàn"],
      ["enlarge", "mở rộng"],
      ["take down", "tháo dỡ"],
      ["reception", "tiệc chiêu đãi"],
      ["recycling", "tái chế"],
      ["recent", "gần đây"],
      ["match", "khớp"],
      ["management", "ban quản lý"],
      ["progress", "tiến triển"],
      ["expedite", "đẩy nhanh"],
      ["explain", "giải thích"],
      ["attempt", "cố gắng"],
      ["resolve", "giải quyết"],
      ["assemble", "lắp ráp"],
      ["attract", "thu hút"],
      ["summary", "bản tóm tắt"],
      ["trim", "cắt tỉa"],
      ["figure", "con số"],
      ["branch", "chi nhánh"],
      ["achieve", "đạt được"],
      ["certification", "chứng chỉ"],
      ["submission", "bài nộp"],
      ["emphasize", "nhấn mạnh"],
      ["designated", "được chỉ định"],
      ["culinary", "thuộc ẩm thực"],
      ["a variety of", "nhiều loại"],
      ["original", "ban đầu, nguyên bản"],
      ["focus", "trọng tâm"],
      ["popularity", "sự phổ biến"],
      ["founder", "người sáng lập"],
      ["outstanding", "nổi bật"],
      ["lack", "sự thiếu hụt"],
      ["qualified", "đủ năng lực"],
      ["applicant", "ứng viên"],
      ["unique", "độc đáo"],
      ["income", "thu nhập"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-06",
    group: "Nghe (LC)",
    title: "LC Test 06",
    titleVi: "Nghe · Test 06",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 06.",
    words: etsWords([
      ["repair", "sửa chữa"],
      ["tie", "buộc, thắt"],
      ["board", "lên (tàu, xe, máy bay)"],
      ["doorway", "lối vào, ô cửa"],
      ["thorough", "kỹ lưỡng, tỉ mỉ"],
      ["ship", "gửi hàng, vận chuyển"],
      ["voucher", "phiếu quà tặng, phiếu giảm giá"],
      ["signature", "chữ ký"],
      ["lease", "hợp đồng thuê"],
      ["replacement", "đồ thay thế, sự thay thế"],
      ["recently", "gần đây"],
      ["elect", "bầu chọn"],
      ["mayor", "thị trưởng"],
      ["research", "nghiên cứu, khảo sát"],
      ["open position", "vị trí đang tuyển"],
      ["store", "cất giữ, lưu trữ"],
      ["protocol", "quy định, quy trình"],
      ["commercial", "quảng cáo (trên TV/radio)"],
      ["advertising", "quảng cáo"],
      ["exploration", "chuyến khám phá"],
      ["approve", "phê duyệt"],
      ["exit", "đi ra, thoát ra"],
      ["landscaping", "thiết kế cảnh quan"],
      ["reminder", "lời nhắc nhở"],
      ["vote", "bầu chọn, bỏ phiếu"],
      ["deserve", "xứng đáng"],
      ["honor", "giải thưởng, vinh dự"],
      ["attention", "sự quan tâm"],
      ["celebrate", "kỷ niệm, ăn mừng"],
      ["facility", "cơ sở, cơ sở vật chất"],
      ["list", "liệt kê, ghi vào danh sách"],
      ["coworker", "đồng nghiệp"],
      ["abstract", "trừu tượng"],
      ["pack", "đóng gói"],
      ["cover", "đưa tin, đề cập"],
      ["funding", "nguồn vốn, sự cấp vốn"],
      ["resident", "cư dân"],
      ["expansion", "sự mở rộng"],
      ["initiative", "sáng kiến, kế hoạch"],
      ["inquire", "hỏi, tìm hiểu"],
      ["specifications", "thông số kỹ thuật"],
      ["source", "nguồn, nhà cung cấp"],
      ["mechanic", "thợ máy"],
      ["accountant", "kế toán viên"],
      ["expedition", "chuyến thám hiểm"],
      ["overnight", "qua đêm"],
      ["rent", "thuê"],
      ["disagree", "không đồng ý"],
      ["route", "tuyến đường"],
      ["coordinator", "điều phối viên"],
      ["freezing", "lạnh cóng, dưới 0 độ"],
      ["temperature", "nhiệt độ"],
      ["fabric", "vải"],
      ["translate", "dịch"],
      ["rush", "gấp"],
      ["unusually", "khác thường"],
      ["additional", "bổ sung"],
      ["day off", "ngày nghỉ"],
      ["contain", "chứa đựng"],
      ["anniversary", "ngày kỷ niệm"],
      ["banquet", "tiệc lớn"],
      ["announcement", "thông báo"],
      ["host", "tổ chức, chủ trì"],
      ["destination", "điểm đến"],
      ["accommodate", "chứa được, đáp ứng"],
      ["exhibit", "cuộc triển lãm"],
      ["claim", "yêu cầu"],
      ["term", "thuật ngữ"],
      ["professional", "chuyên nghiệp"],
      ["inaccurate", "không chính xác"],
      ["profession", "nghề nghiệp"],
      ["definition", "định nghĩa"],
      ["managerial", "thuộc quản lý"],
      ["supervisor", "người giám sát, cấp trên"],
      ["consumer", "người tiêu dùng"],
      ["distribute", "phân phối, phát"],
      ["transport", "vận chuyển"],
      ["afford", "có đủ khả năng chi trả"],
      ["restoration", "sự phục hồi"],
      ["shortage", "sự thiếu hụt"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-07",
    group: "Nghe (LC)",
    title: "LC Test 07",
    titleVi: "Nghe · Test 07",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 07.",
    words: etsWords([
      ["garage", "ga ra, bãi đỗ xe"],
      ["liquid", "chất lỏng"],
      ["bulletin board", "bảng tin"],
      ["occupied", "đang có người sử dụng"],
      ["committee", "ủy ban"],
      ["layover", "điểm dừng quá cảnh"],
      ["astronomy", "thiên văn học"],
      ["astronaut", "phi hành gia"],
      ["fit", "vừa, phù hợp"],
      ["cookware", "dụng cụ nấu ăn"],
      ["agreement", "hợp đồng"],
      ["supervise", "giám sát"],
      ["forecast", "dự báo"],
      ["depart", "khởi hành"],
      ["short-staffed", "thiếu nhân viên"],
      ["storefront", "mặt tiền cửa hàng"],
      ["vacant", "trống"],
      ["analyze", "phân tích"],
      ["demonstrate", "trình diễn, thao tác mẫu"],
      ["itinerary", "lịch trình"],
      ["realize", "nhận ra"],
      ["distracting", "gây xao nhãng"],
      ["flavor", "hương vị"],
      ["expert", "chuyên gia; thuộc chuyên gia"],
      ["extension", "sự gia hạn, mở rộng"],
      ["overtime", "ngoài giờ"],
      ["exchange", "sự trao đổi; đổi hàng"],
      ["receipt", "biên lai"],
      ["ancient", "cổ đại"],
      ["civilization", "nền văn minh"],
      ["last-minute", "vào phút chót"],
      ["expertise", "chuyên môn"],
      ["memorable", "đáng nhớ"],
      ["immediately", "ngay lập tức"],
      ["fair", "hội chợ"],
      ["demolition", "sự phá dỡ"],
      ["involvement", "sự tham gia"],
      ["invest", "đầu tư"],
      ["substantial", "đáng kể"],
      ["press", "báo chí"],
      ["improve", "cải thiện"],
      ["partial", "một phần"],
      ["motivate", "thúc đẩy, tạo động lực"],
      ["reassurance", "sự trấn an"],
      ["misunderstanding", "sự hiểu lầm"],
      ["specific", "cụ thể"],
      ["guideline", "hướng dẫn, quy tắc"],
      ["practical", "thực tiễn"],
      ["disposal", "sự xử lý, vứt bỏ"],
      ["determine", "xác định"],
      ["protective", "bảo vệ"],
      ["represent", "đại diện"],
      ["approach", "đến gần"],
      ["yield", "sản lượng"],
      ["assembly", "sự lắp ráp"],
      ["authorize", "ủy quyền, cho phép"],
      ["margin", "khoảng dư, biên độ"],
      ["adjustment", "sự điều chỉnh"],
      ["broadcast", "phát sóng"],
      ["present", "hiện tại"],
      ["certainly", "chắc chắn"],
      ["policy", "chính sách"],
      ["achievement", "thành tích"],
      ["feedback", "phản hồi"],
      ["excuse", "lý do"],
      ["disappointment", "sự thất vọng"],
      ["aboard", "trên tàu, trên máy bay"],
      ["renowned", "nổi tiếng"],
      ["inconvenience", "sự bất tiện"],
      ["architectural", "thuộc kiến trúc"],
      ["landmark", "địa danh"],
      ["connection", "mối liên hệ"],
      ["express", "tốc hành"],
      ["caution", "sự thận trọng"],
      ["conservation", "sự bảo tồn"],
      ["catering", "dịch vụ ăn uống"],
      ["urban", "thuộc đô thị"],
      ["suburban", "thuộc ngoại ô"],
      ["rating", "xếp hạng"],
      ["organization", "tổ chức"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-08",
    group: "Nghe (LC)",
    title: "LC Test 08",
    titleVi: "Nghe · Test 08",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 08.",
    words: etsWords([
      ["flowerpot", "chậu hoa"],
      ["rug", "thảm"],
      ["covered", "có mái che"],
      ["patio", "sân hiên"],
      ["intersection", "ngã tư"],
      ["flyer", "tờ rơi"],
      ["ceiling", "trần nhà"],
      ["unload", "dỡ hàng"],
      ["climb", "leo lên"],
      ["rake", "cào (lá) bằng cào"],
      ["alert", "cảnh báo"],
      ["agenda", "chương trình nghị sự"],
      ["informational", "mang tính thông tin"],
      ["satisfaction", "sự hài lòng"],
      ["predict", "dự đoán"],
      ["assignment", "sự phân công"],
      ["productive", "có năng suất"],
      ["comfortable", "thoải mái"],
      ["laboratory", "phòng thí nghiệm"],
      ["worth", "đáng giá"],
      ["apply", "áp dụng"],
      ["calculate", "tính toán"],
      ["degree", "độ, mức độ"],
      ["monitor", "theo dõi, giám sát"],
      ["incomplete", "chưa hoàn chỉnh"],
      ["insufficient", "không đủ"],
      ["equipment", "thiết bị"],
      ["rare", "hiếm"],
      ["practice", "thực hành"],
      ["publicity", "sự quảng bá"],
      ["wing", "khu nhà phụ, cánh (tòa nhà)"],
      ["city hall", "tòa thị chính"],
      ["create", "tạo ra"],
      ["official", "quan chức, người có thẩm quyền"],
      ["construction", "xây dựng"],
      ["soil", "đất"],
      ["agriculture", "nông nghiệp"],
      ["curious", "tò mò"],
      ["improvement", "sự cải thiện"],
      ["script", "kịch bản"],
      ["episode", "tập (chương trình phát sóng)"],
      ["performer", "nghệ sĩ biểu diễn"],
      ["outdoor", "ngoài trời"],
      ["flat rate", "giá cố định"],
      ["varied", "đa dạng"],
      ["machinery", "máy móc"],
      ["automated", "tự động hóa"],
      ["transplant", "cấy ghép, trồng lại"],
      ["handle", "xử lý"],
      ["amazement", "sự kinh ngạc"],
      ["inclement weather", "thời tiết khắc nghiệt"],
      ["doubt", "nghi ngờ, không chắc (điều gì sẽ xảy ra)"],
      ["organizer", "người tổ chức"],
      ["rebook", "đặt lại"],
      ["misinformation", "thông tin sai lệch"],
      ["compliment", "lời khen"],
      ["pillow", "gối"],
      ["assist", "hỗ trợ"],
      ["position", "vị trí"],
      ["firm", "cứng, chắc"],
      ["pain", "cơn đau"],
      ["objection", "sự phản đối"],
      ["paperwork", "giấy tờ"],
      ["autonomous", "tự hành, tự động"],
      ["remotely", "từ xa"],
      ["operate", "vận hành"],
      ["maintain", "bảo trì, duy trì"],
      ["administer", "tiến hành, thực hiện (khảo sát, kiểm tra)"],
      ["compliance", "sự tuân thủ"],
      ["primarily", "chủ yếu"],
      ["exceed", "vượt quá"],
      ["standard", "tiêu chuẩn"],
      ["responsibility", "trách nhiệm"],
      ["respond", "phản hồi, trả lời"],
      ["control", "kiểm soát"],
      ["allow", "cho phép"],
      ["clinical", "lâm sàng"],
      ["alternative", "lựa chọn thay thế"],
      ["bulk", "số lượng lớn"],
      ["officially", "chính thức"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-09",
    group: "Nghe (LC)",
    title: "LC Test 09",
    titleVi: "Nghe · Test 09",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 09.",
    words: etsWords([
      ["shade", "che bóng râm"],
      ["bin", "thùng (đựng)"],
      ["frame", "khung (ảnh)"],
      ["dentist", "nha sĩ"],
      ["groceries", "thực phẩm, hàng tạp hóa"],
      ["select", "lựa chọn, tuyển chọn"],
      ["payroll", "bảng lương, bộ phận tính lương"],
      ["damaged", "bị hư hỏng"],
      ["purchase", "mua"],
      ["pass", "thẻ ra vào, vé sử dụng"],
      ["athletic", "thể thao"],
      ["question", "đặt nghi vấn, phản đối"],
      ["treatment", "sự điều trị"],
      ["personalized", "được cá nhân hóa"],
      ["nutrition", "dinh dưỡng"],
      ["previously", "trước đây"],
      ["sanitize", "vệ sinh, khử trùng"],
      ["sourcing", "tìm nguồn cung ứng, thu mua"],
      ["consideration", "điều cần cân nhắc"],
      ["cleanliness", "sự sạch sẽ"],
      ["attendance", "sự đi làm, chuyên cần"],
      ["attractive", "hấp dẫn"],
      ["inadequate", "không đủ, không phù hợp"],
      ["reassign", "phân công lại"],
      ["publish", "công bố, xuất bản"],
      ["retire", "nghỉ hưu"],
      ["opening", "vị trí trống"],
      ["intensive", "chuyên sâu"],
      ["encouragement", "sự khuyến khích"],
      ["praise", "khen ngợi"],
      ["decision", "quyết định"],
      ["intrigued", "rất tò mò, thích thú"],
      ["shred", "xé vụn"],
      ["discarded", "bị vứt bỏ"],
      ["watery", "loãng, nhiều nước"],
      ["mixture", "hỗn hợp"],
      ["unnecessary", "không cần thiết"],
      ["leftover", "còn thừa, còn lại"],
      ["eventually", "cuối cùng"],
      ["decrease", "giảm"],
      ["morale", "tinh thần"],
      ["acquire", "có được"],
      ["adopt", "áp dụng"],
      ["confident", "tự tin"],
      ["presence", "phong thái, sự hiện diện"],
      ["spokesperson", "người phát ngôn"],
      ["limited", "hạn chế"],
      ["availability", "tính khả dụng"],
      ["relevant", "liên quan"],
      ["retrieve", "lấy lại"],
      ["traditional", "truyền thống"],
      ["unusual", "khác thường"],
      ["contemporary", "đương đại"],
      ["inspiration", "nguồn cảm hứng"],
      ["combine", "kết hợp"],
      ["recipe", "công thức"],
      ["intend", "dự định"],
      ["measure", "đo lường"],
      ["method", "phương pháp"],
      ["sustainable", "bền vững"],
      ["ongoing", "đang diễn ra"],
      ["admission", "sự vào cửa, phí vào cửa"],
      ["sturdy", "chắc chắn"],
      ["promotion", "đợt khuyến mãi"],
      ["refer", "giới thiệu (người, nơi)"],
      ["obtain", "có được"],
      ["belongings", "đồ đạc"],
      ["exclusive", "độc quyền"],
      ["register", "quầy thu ngân"],
      ["enrollment", "sự ghi danh"],
      ["form", "biểu mẫu"],
      ["exercise", "bài tập, sự luyện tập"],
      ["installation", "sự lắp đặt"],
      ["lane", "làn đường, đường nhỏ"],
      ["publication", "ấn phẩm"],
      ["immediate", "tức thời, ngay lập tức"],
      ["comprehensive", "toàn diện"],
      ["handbook", "sổ tay"],
      ["procedure", "thủ tục"],
      ["pursue", "theo đuổi"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "lc-test-10",
    group: "Nghe (LC)",
    title: "LC Test 10",
    titleVi: "Nghe · Test 10",
    summary: "80 từ vựng phần Nghe (Part 1–4) trong ETS TOEIC 2026 Vol. 5 — Test 10.",
    words: etsWords([
      ["bucket", "xô"],
      ["stroll", "đi dạo"],
      ["hand", "đưa, trao"],
      ["tow", "kéo (xe)"],
      ["dock", "cập bến, neo đậu"],
      ["shore", "bờ biển"],
      ["downtown", "ở/đến trung tâm thành phố"],
      ["cuisine", "ẩm thực"],
      ["lightweight", "nhẹ"],
      ["sales", "doanh số, doanh thu"],
      ["edit", "biên tập, chỉnh sửa"],
      ["advanced", "tiên tiến, nâng cao"],
      ["result", "kết quả"],
      ["pharmacy", "nhà thuốc"],
      ["keynote speech", "bài phát biểu chính"],
      ["inspiring", "truyền cảm hứng"],
      ["technical", "kỹ thuật"],
      ["bookkeeping", "việc ghi sổ kế toán"],
      ["luncheon", "tiệc trưa"],
      ["indoors", "trong nhà"],
      ["outdoors", "ngoài trời"],
      ["retail", "bán lẻ"],
      ["private", "riêng, cá nhân"],
      ["craft", "đồ thủ công"],
      ["fade", "phai màu, mờ dần"],
      ["custom", "làm theo yêu cầu riêng"],
      ["accidentally", "vô tình"],
      ["boarding pass", "thẻ lên máy bay"],
      ["locate", "tìm ra vị trí"],
      ["describe", "mô tả"],
      ["benefits", "phúc lợi (nhân viên)"],
      ["walkway", "lối đi"],
      ["durability", "độ bền"],
      ["anticipate", "dự đoán"],
      ["negotiation", "sự đàm phán"],
      ["passenger", "hành khách"],
      ["bypass", "đường tránh, đường vòng"],
      ["correction", "sự sửa chữa"],
      ["alternate", "thay thế"],
      ["cause", "gây ra"],
      ["attendant", "nhân viên phục vụ"],
      ["sterile", "vô trùng"],
      ["separate", "riêng biệt, tách biệt"],
      ["radius", "bán kính"],
      ["proceeds", "tiền thu được"],
      ["go toward", "góp phần vào"],
      ["raffle", "cuộc rút thăm trúng thưởng"],
      ["donation", "sự quyên góp"],
      ["drawing", "buổi bốc thăm"],
      ["getaway", "chuyến đi nghỉ"],
      ["arrangement", "sự cắm (hoa), sự sắp xếp"],
      ["observe", "kỷ niệm (dịp lễ)"],
      ["mark", "đánh dấu, kỷ niệm"],
      ["completion", "sự hoàn thành"],
      ["decorative", "trang trí"],
      ["harvest", "thu hoạch"],
      ["feed", "thức ăn chăn nuôi"],
      ["hands-on", "thực hành"],
      ["grain", "ngũ cốc"],
      ["enable", "giúp, tạo khả năng"],
      ["direct", "hướng dẫn, chỉ đường"],
      ["factor", "yếu tố"],
      ["distance", "khoảng cách"],
      ["identity", "danh tính, nhân thân"],
      ["status", "tình trạng, tiến độ"],
      ["takeoff", "sự cất cánh"],
      ["fasten", "thắt (dây an toàn), gắn chặt"],
      ["overhead", "phía trên đầu"],
      ["compartment", "ngăn hành lý"],
      ["virtually", "trực tuyến, ảo"],
      ["fulfill", "thực hiện, đáp ứng"],
      ["assure", "đảm bảo"],
      ["remain", "vẫn, giữ nguyên"],
      ["showcase", "giới thiệu, trưng bày"],
      ["talented", "tài năng"],
      ["enter", "tham gia (cuộc thi), đi vào"],
      ["trend", "xu hướng"],
      ["informal", "thân mật, không trang trọng"],
      ["inappropriate", "không phù hợp"],
      ["recipient", "người nhận"],
    ]),
    quiz: [],
    written: [],
  },
];
