import type { IigTopic } from "@/lib/content/iig-vocab/types";
import { etsWords } from "./helpers";

/** ETS TOEIC 2026 Vol. 5 — từ vựng phần Đọc (Part 5–7), Test 01–10 (nghĩa tiếng Việt theo ngữ cảnh TOEIC của sách). */
export const ETS_READING: IigTopic[] = [
  {
    slug: "rc-test-01",
    group: "Đọc (RC)",
    title: "RC Test 01",
    titleVi: "Đọc · Test 01",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 01.",
    words: etsWords([
      ["take place", "diễn ra, được tổ chức"],
      ["attendee", "người tham dự"],
      ["antique", "đồ cổ"],
      ["organization", "tổ chức, đoàn thể"],
      ["suspicious", "đáng ngờ, khả nghi"],
      ["vary", "thay đổi, đa dạng hóa"],
      ["inventory", "hàng tồn kho"],
      ["expand", "mở rộng"],
      ["solicit", "kêu gọi, yêu cầu (ý kiến, đóng góp)"],
      ["intend", "dự định, có ý định"],
      ["prevent", "ngăn ngừa, phòng ngừa"],
      ["aim", "nhắm đến, đặt mục tiêu"],
      ["qualified", "đủ tiêu chuẩn, đủ năng lực"],
      ["resident", "cư dân"],
      ["agreement", "hợp đồng, thỏa thuận"],
      ["opposition", "sự phản đối"],
      ["extensive", "rộng rãi, bao quát"],
      ["guarantee", "đảm bảo, cam kết"],
      ["supplier", "nhà cung cấp"],
      ["landscaping", "thiết kế cảnh quan"],
      ["suggestion", "đề xuất, gợi ý"],
      ["expertise", "chuyên môn"],
      ["competitor", "đối thủ cạnh tranh"],
      ["anniversary", "lễ kỷ niệm (… năm)"],
      ["dedication", "sự cống hiến, tận tụy"],
      ["loyalty", "lòng trung thành"],
      ["contribute", "đóng góp"],
      ["gratitude", "lòng biết ơn"],
      ["refine", "tinh chỉnh, hoàn thiện; tinh chế"],
      ["spacious", "rộng rãi"],
      ["go through", "xem xét, rà soát"],
      ["various", "đa dạng, nhiều loại"],
      ["secure", "an toàn, chắc chắn"],
      ["remove", "dời đi, di chuyển (khỏi chỗ cũ)"],
      ["previous", "trước đó"],
      ["cooperation", "sự hợp tác"],
      ["upcoming", "sắp tới"],
      ["charge", "tính phí"],
      ["assign", "phân công, chỉ định"],
      ["administrator", "người quản lý, quản trị viên"],
      ["new hire", "nhân viên mới"],
      ["promote", "quảng bá"],
      ["advertise", "quảng cáo"],
      ["coordinator", "điều phối viên"],
      ["telescope", "kính thiên văn"],
      ["revise", "thay đổi, chỉnh sửa"],
      ["representative", "nhân viên (đại diện)"],
      ["inquiry", "câu hỏi, yêu cầu thông tin"],
      ["general", "chung, thông thường"],
      ["release", "phát hành, tung ra (sản phẩm)"],
      ["indicate", "cho thấy, biểu thị"],
      ["retain", "giữ lại, duy trì"],
      ["flavour", "hương vị"],
      ["sacrifice", "hy sinh"],
      ["obtain", "có được, giành được"],
      ["merger", "sự sáp nhập"],
      ["nutritious", "bổ dưỡng"],
      ["individual", "cá nhân, thành viên"],
      ["opportunity", "cơ hội"],
      ["substitute", "thay thế"],
      ["critical", "mang tính phê bình, chỉ trích"],
      ["colleague", "đồng nghiệp"],
      ["courtesy", "phép lịch sự"],
      ["get the word out", "lan truyền thông tin"],
      ["install", "lắp đặt"],
      ["significant", "quan trọng, đáng kể"],
      ["estimate", "ước tính"],
      ["liaison", "người liên lạc, đầu mối liên hệ"],
      ["successive", "liên tiếp"],
      ["expert", "chuyên gia"],
      ["diagnose", "chẩn đoán"],
      ["replace", "thay thế"],
      ["resemble", "giống với"],
      ["approve", "phê duyệt"],
      ["inspection", "sự kiểm tra, rà soát"],
      ["proactive", "chủ động"],
      ["procedure", "quy trình, thủ tục"],
      ["compete", "cạnh tranh"],
      ["instrumental", "có vai trò quan trọng"],
      ["combine", "kết hợp"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-02",
    group: "Đọc (RC)",
    title: "RC Test 02",
    titleVi: "Đọc · Test 02",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 02.",
    words: etsWords([
      ["reliability", "độ tin cậy"],
      ["reimbursement", "sự hoàn tiền, bồi hoàn chi phí"],
      ["accept", "chấp nhận"],
      ["candidate", "ứng viên"],
      ["master", "thành thạo"],
      ["power failure", "mất điện"],
      ["property", "bất động sản"],
      ["strategy", "chiến lược"],
      ["name", "bổ nhiệm"],
      ["warranty", "bảo hành"],
      ["workplace", "nơi làm việc"],
      ["postpone", "hoãn lại"],
      ["struggle", "chật vật, cố gắng"],
      ["ingredient", "nguyên liệu"],
      ["savory", "ngon, đậm đà"],
      ["eager", "háo hức, mong muốn"],
      ["artificial", "nhân tạo"],
      ["substance", "chất, vật liệu"],
      ["handy", "tiện dụng"],
      ["effective", "hiệu quả"],
      ["sustainable", "bền vững"],
      ["address", "giải quyết (vấn đề)"],
      ["porous", "xốp, thấm nước"],
      ["subscription", "sự đăng ký (gói, dài hạn)"],
      ["access", "truy cập, sử dụng"],
      ["valid", "có hiệu lực, hợp lệ"],
      ["expire", "hết hạn"],
      ["activate", "kích hoạt"],
      ["distribute", "phân phát, phân phối"],
      ["feature", "có, bao gồm (điểm nổi bật)"],
      ["reveal", "tiết lộ"],
      ["extension", "số máy lẻ"],
      ["complaint", "lời phàn nàn, khiếu nại"],
      ["issue", "cấp, phát hành"],
      ["maintenance", "bảo trì"],
      ["summarize", "tóm tắt"],
      ["notify", "thông báo"],
      ["requirement", "yêu cầu, điều kiện"],
      ["freight", "hàng hóa vận chuyển"],
      ["vehicle", "xe, phương tiện"],
      ["transport", "vận chuyển"],
      ["nationwide", "trên toàn quốc"],
      ["executive", "giám đốc điều hành, ban lãnh đạo"],
      ["commercial", "thuộc thương mại"],
      ["demand", "nhu cầu"],
      ["specialty", "lĩnh vực chuyên môn"],
      ["convert", "chuyển đổi"],
      ["virtual", "ảo, trực tuyến"],
      ["visualization", "sự trực quan hóa"],
      ["suggest", "đề xuất, gợi ý"],
      ["curate", "tuyển chọn"],
      ["highlight", "làm nổi bật, nhấn mạnh"],
      ["process", "xử lý"],
      ["sleek", "bóng bẩy, thanh lịch"],
      ["stabilization", "sự ổn định"],
      ["rough", "gồ ghề, thô ráp"],
      ["surface", "bề mặt, mặt đất"],
      ["discontinue", "ngừng (sản xuất, cung cấp)"],
      ["instruction", "sự hướng dẫn, giảng dạy"],
      ["residence", "nơi cư trú"],
      ["complimentary", "miễn phí"],
      ["accommodate", "đáp ứng, điều chỉnh cho phù hợp"],
      ["catch up", "bắt kịp"],
      ["customized", "theo yêu cầu riêng"],
      ["express", "nhanh, hỏa tốc"],
      ["preserve", "bảo tồn, giữ gìn"],
      ["auction", "cuộc đấu giá"],
      ["donate", "quyên góp"],
      ["operation", "sự vận hành, hoạt động"],
      ["thrilled", "rất vui mừng, phấn khích"],
      ["in advance", "trước"],
      ["indeed", "thực sự, quả thật"],
      ["typically", "thường thì"],
      ["smudge", "vết bẩn, vết nhòe"],
      ["found", "thành lập"],
      ["emphasize", "nhấn mạnh"],
      ["immediately", "ngay lập tức"],
      ["average", "mức trung bình"],
      ["navigate", "tìm đường, định hướng"],
      ["ultimately", "cuối cùng, rốt cuộc"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-03",
    group: "Đọc (RC)",
    title: "RC Test 03",
    titleVi: "Đọc · Test 03",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 03.",
    words: etsWords([
      ["youth", "tuổi trẻ, thanh niên"],
      ["conduct", "tiến hành, thực hiện"],
      ["regular", "đều đặn, thường xuyên"],
      ["a majority of", "phần lớn, đa số"],
      ["represent", "đại diện"],
      ["measure", "biện pháp"],
      ["submit", "nộp"],
      ["track", "theo dõi"],
      ["rapidly", "nhanh chóng"],
      ["committee", "ủy ban"],
      ["appendix", "phụ lục"],
      ["insight", "sự hiểu biết sâu sắc"],
      ["investment", "sự đầu tư"],
      ["result", "kết quả"],
      ["improve", "cải thiện"],
      ["appoint", "bổ nhiệm"],
      ["simultaneously", "đồng thời"],
      ["revenue", "doanh thu"],
      ["undergo", "trải qua"],
      ["take advantage of", "tận dụng"],
      ["transaction", "giao dịch"],
      ["potential", "tiềm năng"],
      ["attention", "sự chú ý"],
      ["dynamic", "năng động"],
      ["valuable", "quý giá, có giá trị"],
      ["convince", "thuyết phục"],
      ["audience", "khán giả"],
      ["acquire", "có được, thu được"],
      ["share", "cổ phần, phần"],
      ["strength", "điểm mạnh"],
      ["quote", "trích dẫn"],
      ["infusion", "sự rót (vốn), bơm thêm"],
      ["refrain", "kiềm chế, tránh"],
      ["preference", "sự ưu tiên, sở thích"],
      ["function", "chức năng"],
      ["gathering", "buổi họp mặt"],
      ["innovation", "sự đổi mới"],
      ["shareholder", "cổ đông"],
      ["productivity", "năng suất"],
      ["occur", "xảy ra"],
      ["optimize", "tối ưu hóa"],
      ["conventional", "thông thường, truyền thống"],
      ["commuter", "người đi làm hằng ngày (bằng phương tiện)"],
      ["relieved", "nhẹ nhõm"],
      ["desperate", "tuyệt vọng, liều lĩnh"],
      ["municipal", "thuộc thành phố"],
      ["entrance", "lối vào"],
      ["mural", "tranh tường"],
      ["commission", "đặt làm, ủy thác"],
      ["approximately", "khoảng, xấp xỉ"],
      ["publicize", "công bố, quảng bá"],
      ["significance", "tầm quan trọng"],
      ["official", "chính thức"],
      ["mingle", "giao lưu, hòa nhập"],
      ["invaluable", "vô giá"],
      ["accurate", "chính xác"],
      ["recruit", "tuyển dụng"],
      ["celebrity", "người nổi tiếng"],
      ["cater", "cung cấp đồ ăn"],
      ["equipment", "thiết bị"],
      ["distributor", "nhà phân phối"],
      ["component", "linh kiện"],
      ["facility", "cơ sở vật chất"],
      ["assembly", "sự lắp ráp"],
      ["launch", "sự ra mắt"],
      ["financial", "thuộc tài chính"],
      ["oversee", "giám sát"],
      ["permanently", "vĩnh viễn"],
      ["relocate", "di dời, chuyển địa điểm"],
      ["appreciate", "đánh giá cao"],
      ["perspective", "quan điểm, góc nhìn"],
      ["intrigue", "gây tò mò, hấp dẫn"],
      ["government", "chính phủ"],
      ["collaborate", "hợp tác"],
      ["commensurate", "tương xứng"],
      ["comply with", "tuân thủ"],
      ["essential", "thiết yếu"],
      ["relevant", "liên quan"],
      ["formal", "trang trọng, chính thức"],
      ["remote", "từ xa"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-04",
    group: "Đọc (RC)",
    title: "RC Test 04",
    titleVi: "Đọc · Test 04",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 04.",
    words: etsWords([
      ["retire", "nghỉ hưu"],
      ["applicant", "người nộp đơn, ứng viên"],
      ["contract", "hợp đồng"],
      ["liquid", "chất lỏng"],
      ["praise", "khen ngợi"],
      ["aesthetic", "thuộc thẩm mỹ"],
      ["maintain", "duy trì"],
      ["confidentiality", "tính bảo mật"],
      ["architecture", "kiến trúc"],
      ["thermostat", "bộ điều chỉnh nhiệt độ"],
      ["reflect", "phản ánh"],
      ["retreat", "buổi tĩnh tâm/đào tạo ngoại khóa; nơi nghỉ dưỡng"],
      ["in celebration of", "để kỷ niệm, chào mừng"],
      ["outline", "phác thảo, trình bày khái quát"],
      ["procurement", "sự thu mua"],
      ["pediatric", "thuộc nhi khoa"],
      ["accurately", "một cách chính xác"],
      ["authentic", "chính gốc, đích thực"],
      ["cuisine", "ẩm thực"],
      ["occupy", "chiếm (chỗ, không gian)"],
      ["enthusiasm", "sự nhiệt tình"],
      ["validate", "xác nhận, chứng thực"],
      ["at no charge", "miễn phí"],
      ["memoir", "hồi ký"],
      ["in person", "trực tiếp"],
      ["specialize in", "chuyên về"],
      ["bold", "táo bạo"],
      ["reciprocate", "đáp lại"],
      ["competitive", "có tính cạnh tranh"],
      ["knowledge", "kiến thức"],
      ["regulation", "quy định"],
      ["fluency", "sự lưu loát"],
      ["satellite", "vệ tinh"],
      ["grant", "khoản trợ cấp, tài trợ"],
      ["calculate", "tính toán"],
      ["snowpack", "lớp tuyết phủ"],
      ["prototype", "nguyên mẫu, mẫu thử"],
      ["fluctuation", "sự biến động"],
      ["enhance", "nâng cao"],
      ["domestic", "trong nước, nội địa"],
      ["prestigious", "danh tiếng, uy tín"],
      ["commitment", "sự tận tâm, cam kết"],
      ["tremendous", "to lớn"],
      ["headquarter", "đặt trụ sở chính"],
      ["facilitate", "tạo điều kiện thuận lợi"],
      ["ergonomic", "thuộc công thái học"],
      ["frequently", "thường xuyên"],
      ["initiate", "khởi xướng, bắt đầu"],
      ["appearance", "vẻ bề ngoài"],
      ["enclose", "gửi kèm"],
      ["commence", "bắt đầu"],
      ["elaborate", "công phu, tỉ mỉ"],
      ["insightful", "sâu sắc"],
      ["biography", "tiểu sử"],
      ["admire", "ngưỡng mộ, chiêm ngưỡng"],
      ["backdrop", "phông nền, bối cảnh"],
      ["refurbish", "tân trang"],
      ["prompt", "nhanh chóng"],
      ["engaging", "hấp dẫn, lôi cuốn"],
      ["functionality", "chức năng"],
      ["spectacular", "ngoạn mục, hoành tráng"],
      ["secluded", "hẻo lánh, yên tĩnh"],
      ["enchanted", "say mê, bị mê hoặc"],
      ["eclectic", "đa dạng, chiết trung"],
      ["audiovisual", "nghe nhìn"],
      ["durability", "độ bền"],
      ["versatile", "đa năng"],
      ["persist", "kéo dài, tiếp diễn"],
      ["commissioner", "ủy viên"],
      ["predecessor", "người tiền nhiệm"],
      ["step down", "từ chức"],
      ["suspension", "sự tạm ngừng"],
      ["inaugural", "đầu tiên, khai mạc"],
      ["proceeds", "tiền thu được"],
      ["submission", "sự nộp, bài nộp"],
      ["administration", "sự quản lý hành chính"],
      ["excel", "vượt trội, xuất sắc"],
      ["aspect", "khía cạnh"],
      ["verify", "xác minh"],
      ["convenient", "thuận tiện"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-05",
    group: "Đọc (RC)",
    title: "RC Test 05",
    titleVi: "Đọc · Test 05",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 05.",
    words: etsWords([
      ["accountant", "kế toán viên"],
      ["agenda", "chương trình nghị sự"],
      ["sudden", "đột ngột"],
      ["proofread", "hiệu đính, soát lỗi"],
      ["experiment", "thí nghiệm"],
      ["initial", "ban đầu"],
      ["sealant", "chất bịt kín"],
      ["refined", "tinh chế, tinh tế"],
      ["soundproof", "cách âm"],
      ["entrepreneur", "doanh nhân"],
      ["tenure", "nhiệm kỳ"],
      ["achievement", "thành tích"],
      ["forthcoming", "sắp tới"],
      ["consistently", "một cách nhất quán, liên tục"],
      ["implement", "thực hiện, triển khai"],
      ["accordingly", "theo đó, tương ứng"],
      ["align", "căn chỉnh, sắp xếp cho thẳng hàng"],
      ["tardiness", "sự đi trễ"],
      ["on behalf of", "thay mặt cho"],
      ["physiotherapy", "vật lý trị liệu"],
      ["inviting", "hấp dẫn, mời gọi"],
      ["objective", "mục tiêu"],
      ["resource", "tài liệu, nguồn lực"],
      ["informative", "nhiều thông tin hữu ích"],
      ["previously", "trước đây"],
      ["editorial", "thuộc biên tập"],
      ["prime", "tốt nhất, hàng đầu"],
      ["spread", "lan truyền"],
      ["overall", "tổng thể"],
      ["determine", "xác định, quyết định"],
      ["avoid", "tránh"],
      ["sanctuary", "nơi trú ẩn, chốn bình yên"],
      ["hectic", "bận rộn, hối hả"],
      ["bustle", "sự náo nhiệt"],
      ["excursion", "chuyến tham quan"],
      ["cover letter", "thư xin việc"],
      ["shortage", "sự thiếu hụt"],
      ["extract", "chiết xuất, tinh chất"],
      ["favorable", "thuận lợi"],
      ["crash", "gặp sự cố, bị sập (máy tính)"],
      ["compatible", "tương thích"],
      ["thrive", "phát triển mạnh"],
      ["figure out", "tìm ra, hiểu ra"],
      ["asset", "tài sản"],
      ["supportive", "hỗ trợ, ủng hộ"],
      ["presence", "sự có mặt"],
      ["persevere", "kiên trì"],
      ["explore", "khám phá, tìm hiểu"],
      ["primarily", "chủ yếu"],
      ["breach", "sự vi phạm"],
      ["first aid", "sơ cứu"],
      ["specific", "cụ thể"],
      ["administrative", "thuộc hành chính"],
      ["possess", "sở hữu"],
      ["subordinate", "cấp dưới"],
      ["crucially", "một cách quan trọng, mấu chốt"],
      ["proficiency", "sự thành thạo"],
      ["expenditure", "chi tiêu, chi phí"],
      ["statistical", "thuộc thống kê"],
      ["industrial", "thuộc công nghiệp"],
      ["description", "sự mô tả"],
      ["dependent", "phụ thuộc"],
      ["in stock", "còn hàng"],
      ["unfamiliar", "không quen thuộc"],
      ["questionnaire", "bảng câu hỏi khảo sát"],
      ["introductory", "giới thiệu, nhập môn"],
      ["subsequent", "tiếp theo, sau đó"],
      ["waive", "miễn (phí)"],
      ["prospective", "tiềm năng, tương lai"],
      ["confidential", "bảo mật"],
      ["certified", "được chứng nhận"],
      ["withdraw", "rút (tiền)"],
      ["owed", "còn nợ, phải trả"],
      ["participant", "người tham gia"],
      ["steady", "ổn định, đều đặn"],
      ["acceptable", "chấp nhận được"],
      ["capacity", "sức chứa"],
      ["authorize", "cho phép, ủy quyền"],
      ["faulty", "bị lỗi"],
      ["personnel", "nhân sự"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-06",
    group: "Đọc (RC)",
    title: "RC Test 06",
    titleVi: "Đọc · Test 06",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 06.",
    words: etsWords([
      ["composer", "nhà soạn nhạc"],
      ["politeness", "sự lịch sự"],
      ["practical", "thực tế, thiết thực"],
      ["workstation", "chỗ làm việc"],
      ["latest", "mới nhất"],
      ["quarterly", "hằng quý"],
      ["stakeholder", "bên liên quan, cổ đông"],
      ["biographer", "người viết tiểu sử"],
      ["distinctive", "đặc biệt, đặc trưng"],
      ["stationery", "văn phòng phẩm"],
      ["insurance", "bảo hiểm"],
      ["associated", "có liên quan"],
      ["ensure", "đảm bảo"],
      ["exterior", "bên ngoài"],
      ["incorporate", "kết hợp, đưa vào"],
      ["pleasure", "niềm vui"],
      ["corporate", "thuộc doanh nghiệp"],
      ["appliance", "thiết bị gia dụng"],
      ["innovative", "sáng tạo, đổi mới"],
      ["geographic", "thuộc địa lý"],
      ["electronics", "đồ điện tử"],
      ["patience", "sự kiên nhẫn"],
      ["uneven", "không bằng phẳng"],
      ["pavement", "mặt đường lát"],
      ["hygienist", "chuyên viên vệ sinh răng miệng"],
      ["handle", "xử lý"],
      ["benefit", "có lợi cho"],
      ["streamline", "tinh giản, hợp lý hóa"],
      ["unusually", "bất thường"],
      ["moderation", "sự điều tiết, kiểm duyệt"],
      ["regularly", "thường xuyên, định kỳ"],
      ["landscape", "cảnh quan"],
      ["optimal", "tối ưu"],
      ["reasonable", "hợp lý"],
      ["pathway", "lối đi"],
      ["rustic", "mộc mạc, phong cách đồng quê"],
      ["constitute", "cấu thành, tạo nên"],
      ["fulfill", "hoàn thành, thực hiện"],
      ["specification", "thông số kỹ thuật"],
      ["paperwork", "giấy tờ"],
      ["security", "an ninh"],
      ["intricate", "phức tạp, tinh xảo"],
      ["unprecedented", "chưa từng có"],
      ["tactile", "thuộc xúc giác"],
      ["exploit", "tận dụng, khai thác"],
      ["layover", "quá cảnh"],
      ["amenity", "tiện nghi"],
      ["awareness", "nhận thức"],
      ["conserve", "tiết kiệm, bảo tồn"],
      ["fundamental", "cơ bản"],
      ["specified", "được chỉ định"],
      ["eliminate", "loại bỏ"],
      ["reduction", "sự giảm"],
      ["contribution", "bài viết đóng góp"],
      ["alternate", "thay thế"],
      ["confident", "tự tin, chắc chắn"],
      ["incur", "phát sinh (chi phí)"],
      ["offset", "bù đắp"],
      ["placement", "sự sắp xếp, bố trí"],
      ["integral", "không thể thiếu"],
      ["guidance", "sự hướng dẫn"],
      ["botanical", "thuộc thực vật học"],
      ["society", "hội, hiệp hội"],
      ["theme", "chủ đề"],
      ["paradise", "thiên đường"],
      ["ambitious", "đầy tham vọng"],
      ["cultivate", "trồng trọt, canh tác"],
      ["privilege", "vinh dự, đặc quyền"],
      ["wildlife", "động vật hoang dã"],
      ["cordially", "một cách thân ái, trân trọng"],
      ["nourish", "nuôi dưỡng"],
      ["deterrence", "sự ngăn chặn"],
      ["harmful", "có hại"],
      ["recreation", "sự giải trí"],
      ["athletic", "thuộc thể thao"],
      ["adequate", "đầy đủ"],
      ["suitable", "phù hợp"],
      ["promptly", "đúng giờ, ngay lập tức"],
      ["joint", "chung"],
      ["profitable", "có lợi nhuận"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-07",
    group: "Đọc (RC)",
    title: "RC Test 07",
    titleVi: "Đọc · Test 07",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 07.",
    words: etsWords([
      ["commute", "đi làm (hằng ngày)"],
      ["understaffed", "thiếu nhân sự"],
      ["keep fit", "giữ dáng, giữ gìn sức khỏe"],
      ["completion", "sự hoàn thành"],
      ["concern", "mối lo ngại"],
      ["tuition", "học phí"],
      ["enroll in", "đăng ký học"],
      ["evaluate", "đánh giá"],
      ["milestone", "cột mốc"],
      ["responsive", "phản hồi nhanh"],
      ["chemistry", "hóa học"],
      ["rapid", "nhanh chóng"],
      ["hospitality", "ngành dịch vụ khách sạn - nhà hàng"],
      ["payroll", "bảng lương"],
      ["time sheet", "bảng chấm công"],
      ["container", "hộp đựng"],
      ["fancy", "thích, muốn"],
      ["savour", "thưởng thức"],
      ["socialise", "giao lưu"],
      ["reserve", "đặt trước"],
      ["opening", "vị trí trống"],
      ["renewal", "sự gia hạn"],
      ["assume", "cho rằng"],
      ["tenant", "người thuê nhà"],
      ["realty", "bất động sản"],
      ["peninsula", "bán đảo"],
      ["moderately", "vừa phải"],
      ["scatter", "phân tán, rải rác"],
      ["inexpensive", "rẻ"],
      ["flock to", "đổ xô đến"],
      ["alert", "cảnh báo, thông báo"],
      ["electronically", "bằng phương thức điện tử"],
      ["exclusively", "độc quyền, chỉ dành riêng"],
      ["creamery", "cửa hàng sữa"],
      ["physician", "bác sĩ"],
      ["remind", "nhắc nhở"],
      ["time off", "thời gian nghỉ phép"],
      ["adjust", "điều chỉnh"],
      ["custodian", "người trông coi, bảo vệ tòa nhà"],
      ["testimonial", "lời chứng thực, đánh giá của khách hàng"],
      ["satisfaction", "sự hài lòng"],
      ["detailed", "chi tiết"],
      ["reputation", "danh tiếng"],
      ["identify", "xác định"],
      ["persuade", "thuyết phục"],
      ["imminent", "sắp xảy ra"],
      ["undoubtedly", "chắc chắn, không nghi ngờ gì"],
      ["visible", "dễ thấy"],
      ["collaboration", "sự hợp tác"],
      ["corporation", "tập đoàn, công ty"],
      ["nonprofit", "phi lợi nhuận"],
      ["participation", "sự tham gia"],
      ["involve", "bao gồm, liên quan"],
      ["dedicate", "dành (thời gian), cống hiến"],
      ["spearhead", "dẫn đầu, chỉ đạo"],
      ["subcompact", "xe cỡ nhỏ"],
      ["stunning", "tuyệt đẹp, gây ấn tượng mạnh"],
      ["abundant", "dồi dào"],
      ["secondhand", "đồ cũ, đã qua sử dụng"],
      ["credential", "chứng chỉ, bằng cấp"],
      ["reliable", "đáng tin cậy"],
      ["unsightly", "khó coi"],
      ["merchandise", "hàng hóa"],
      ["possession", "quyền sở hữu"],
      ["drastically", "mạnh mẽ, đáng kể"],
      ["informed", "có đầy đủ thông tin"],
      ["vast", "rộng lớn"],
      ["bypass", "bỏ qua"],
      ["deboard", "xuống (máy bay, tàu)"],
      ["voucher", "phiếu quà tặng"],
      ["demonstration", "sự trình diễn"],
      ["unintentionally", "vô tình"],
      ["discard", "vứt bỏ"],
      ["lightweight", "nhẹ"],
      ["disposable", "dùng một lần"],
      ["receptacle", "thùng chứa"],
      ["overdue", "quá hạn"],
      ["withhold", "giữ lại, trì hoãn"],
      ["malfunction", "trục trặc"],
      ["expedite", "xúc tiến, đẩy nhanh"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-08",
    group: "Đọc (RC)",
    title: "RC Test 08",
    titleVi: "Đọc · Test 08",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 08.",
    words: etsWords([
      ["significantly", "đáng kể"],
      ["sturdy", "chắc chắn, bền"],
      ["brief", "ngắn gọn"],
      ["functional", "hoạt động được"],
      ["generate", "tạo ra"],
      ["extensively", "rộng rãi"],
      ["proceed", "tiến hành"],
      ["territory", "khu vực, lãnh thổ"],
      ["protocol", "quy trình, giao thức"],
      ["simplify", "đơn giản hóa"],
      ["directions", "chỉ dẫn đường đi"],
      ["laboratory", "phòng thí nghiệm"],
      ["undergraduate", "sinh viên đại học"],
      ["admission", "sự nhập học"],
      ["semester", "học kỳ"],
      ["transcript", "bảng điểm"],
      ["delighted", "vui mừng"],
      ["tendency", "xu hướng"],
      ["disclose", "tiết lộ, công bố"],
      ["hesitate", "do dự"],
      ["candid", "thẳng thắn"],
      ["unsuitable", "không phù hợp"],
      ["compact", "nhỏ gọn"],
      ["beautify", "làm đẹp"],
      ["integrity", "sự toàn vẹn"],
      ["extra", "thêm, dư"],
      ["residential", "thuộc khu dân cư"],
      ["paved", "được lát"],
      ["border", "giáp ranh"],
      ["subsidiary", "công ty con"],
      ["budget", "ngân sách"],
      ["distribution", "sự phân phối"],
      ["researcher", "nhà nghiên cứu"],
      ["capability", "khả năng"],
      ["vacancy", "vị trí trống, phòng trống"],
      ["cabin", "khoang máy bay"],
      ["compartment", "ngăn, khoang"],
      ["dimension", "kích thước"],
      ["permission", "sự cho phép"],
      ["foster", "thúc đẩy"],
      ["roughly", "khoảng"],
      ["unexpected", "bất ngờ"],
      ["fulfillment", "sự hoàn thành, thực hiện"],
      ["lodging", "chỗ ở"],
      ["intent", "ý định"],
      ["directly", "trực tiếp, ngay"],
      ["instructions", "hướng dẫn"],
      ["go over", "xem xét, rà soát"],
      ["convinced", "tin chắc"],
      ["personality", "cá tính, tính cách"],
      ["structure", "cấu trúc, tổ chức"],
      ["memorable", "đáng nhớ"],
      ["politician", "chính trị gia"],
      ["numerous", "nhiều"],
      ["straightforward", "thẳng thắn, đơn giản"],
      ["fascinating", "hấp dẫn"],
      ["portrait", "chân dung"],
      ["enigmatic", "bí ẩn"],
      ["anecdote", "giai thoại"],
      ["shortcoming", "thiếu sót"],
      ["credible", "đáng tin cậy"],
      ["fictional", "hư cấu"],
      ["quaint", "cổ kính, lạ mắt"],
      ["criticism", "sự chỉ trích"],
      ["surrounding", "môi trường xung quanh"],
      ["minutes", "biên bản cuộc họp"],
      ["earmark", "dành riêng (tiền) cho"],
      ["adjustment", "sự điều chỉnh"],
      ["recruitment", "sự tuyển dụng"],
      ["boulevard", "đại lộ"],
      ["adjournment", "sự hoãn/kết thúc cuộc họp"],
      ["utilities", "tiện ích (điện, nước, ga)"],
      ["easygoing", "dễ tính"],
      ["reasonably", "khá, tương đối"],
      ["satisfy", "thỏa mãn"],
      ["attune", "hòa hợp, điều chỉnh cho phù hợp"],
      ["resist", "chịu được"],
      ["adhere", "dính chặt"],
      ["striped", "có sọc"],
      ["outstanding", "nổi bật"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-09",
    group: "Đọc (RC)",
    title: "RC Test 09",
    titleVi: "Đọc · Test 09",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 09.",
    words: etsWords([
      ["vacant", "trống"],
      ["promotion", "sự thăng chức"],
      ["consumption", "sự tiêu thụ"],
      ["superintendent", "người quản lý (tòa nhà)"],
      ["renovation", "sự cải tạo"],
      ["manufacturer", "nhà sản xuất"],
      ["consideration", "sự xem xét"],
      ["critic", "nhà phê bình"],
      ["impressive", "ấn tượng"],
      ["choreography", "biên đạo múa"],
      ["ongoing", "đang diễn ra"],
      ["household", "thuộc hộ gia đình"],
      ["automotive", "thuộc ô tô"],
      ["eligible", "đủ điều kiện"],
      ["vendor", "người bán hàng"],
      ["variation", "biến thể"],
      ["imperfection", "khuyết điểm"],
      ["narrow", "hẹp"],
      ["detach", "tách rời"],
      ["abrasive", "có tính mài mòn"],
      ["residue", "cặn"],
      ["submerge", "nhúng nước"],
      ["utensil", "dụng cụ (nhà bếp)"],
      ["separately", "riêng biệt"],
      ["entrust", "giao phó"],
      ["convey", "truyền đạt"],
      ["timeless", "vượt thời gian"],
      ["precision", "độ chính xác"],
      ["costly", "đắt đỏ"],
      ["initially", "ban đầu"],
      ["acquisition", "sự mua lại"],
      ["insider", "người trong cuộc"],
      ["speculate", "suy đoán"],
      ["iconic", "mang tính biểu tượng"],
      ["reliably", "một cách đáng tin cậy"],
      ["fate", "số phận"],
      ["retirement", "sự nghỉ hưu"],
      ["deactivation", "sự vô hiệu hóa"],
      ["renew", "gia hạn"],
      ["displeasure", "sự không hài lòng"],
      ["promise", "hứa hẹn"],
      ["sufficient", "đủ"],
      ["regard", "xem như, đánh giá"],
      ["assistance", "sự trợ giúp"],
      ["unveil", "công bố"],
      ["advancement", "sự tiến bộ"],
      ["glimpse", "cái nhìn thoáng qua"],
      ["decay", "suy tàn, mục nát"],
      ["architectural", "thuộc kiến trúc"],
      ["transition", "sự chuyển đổi"],
      ["constructive", "mang tính xây dựng"],
      ["showcase", "trưng bày"],
      ["notable", "đáng chú ý"],
      ["concrete", "cụ thể"],
      ["overcome", "vượt qua"],
      ["preventive", "phòng ngừa"],
      ["gauge", "đánh giá"],
      ["respective", "tương ứng"],
      ["compensate", "bồi thường"],
      ["persistent", "kiên trì, dai dẳng"],
      ["narrative", "câu chuyện"],
      ["adjoining", "liền kề"],
      ["heritage", "di sản"],
      ["vintage", "cổ điển"],
      ["purified", "được lọc"],
      ["whimsical", "kỳ quặc, độc đáo"],
      ["infuse", "truyền vào"],
      ["biweekly", "hai tuần một lần"],
      ["affordably", "với giá phải chăng"],
      ["crease", "bị nhăn"],
      ["encyclopaedia", "bách khoa toàn thư"],
      ["enquiry", "câu hỏi"],
      ["inherit", "thừa kế"],
      ["onboarding", "quy trình hội nhập nhân viên mới"],
      ["interact", "tương tác"],
      ["enrollment", "sự đăng ký"],
      ["breathtaking", "ngoạn mục"],
      ["certification", "chứng chỉ"],
      ["precondition", "điều kiện tiên quyết"],
      ["authority", "cơ quan có thẩm quyền"],
    ]),
    quiz: [],
    written: [],
  },
  {
    slug: "rc-test-10",
    group: "Đọc (RC)",
    title: "RC Test 10",
    titleVi: "Đọc · Test 10",
    summary: "80 từ vựng phần Đọc (Part 5–7) trong ETS TOEIC 2026 Vol. 5 — Test 10.",
    words: etsWords([
      ["commend", "khen ngợi"],
      ["garment", "quần áo"],
      ["patron", "khách hàng quen"],
      ["majority", "đa số"],
      ["quarter", "quý"],
      ["diplomat", "nhà ngoại giao"],
      ["removal", "sự loại bỏ"],
      ["organizer", "người tổ chức"],
      ["sound", "vững chắc, hợp lý"],
      ["aspiring", "đầy tham vọng"],
      ["flourishing", "phát triển mạnh"],
      ["finalize", "hoàn tất"],
      ["caution", "cảnh báo"],
      ["inferior", "kém hơn"],
      ["adjustable", "có thể điều chỉnh"],
      ["argument", "lập luận"],
      ["shrink", "co lại"],
      ["collapsible", "có thể gấp lại"],
      ["durable", "bền"],
      ["replacement", "sự thay thế"],
      ["wholesaler", "người bán buôn"],
      ["whisper", "thì thầm"],
      ["illusion", "ảo ảnh"],
      ["argue", "tranh luận"],
      ["plotline", "cốt truyện"],
      ["abundance", "sự dồi dào"],
      ["challenging", "đầy thách thức"],
      ["recipe", "công thức nấu ăn"],
      ["separate", "riêng biệt"],
      ["promotional", "mang tính quảng cáo"],
      ["apparel", "quần áo"],
      ["involvement", "sự tham gia"],
      ["invention", "phát minh"],
      ["timely", "kịp thời"],
      ["customize", "tùy chỉnh"],
      ["punctuality", "sự đúng giờ"],
      ["performance", "hiệu suất"],
      ["tricky", "khó khăn"],
      ["stop by", "ghé qua"],
      ["compile", "biên soạn"],
      ["notification", "thông báo"],
      ["manuscript", "bản thảo"],
      ["margin", "lề"],
      ["ignore", "phớt lờ"],
      ["modification", "sự sửa đổi"],
      ["establish", "thiết lập"],
      ["diverse", "đa dạng"],
      ["negotiate", "đàm phán"],
      ["exceptionally", "đặc biệt"],
      ["exposure", "sự tiếp xúc"],
      ["triumph", "chiến thắng"],
      ["criteria", "tiêu chí"],
      ["exceptional", "xuất sắc"],
      ["extremely", "cực kỳ"],
      ["forefront", "vị trí hàng đầu"],
      ["endeavour", "nỗ lực"],
      ["spotless", "sạch sẽ"],
      ["subsequently", "sau đó"],
      ["disruption", "sự gián đoạn"],
      ["embrace", "đón nhận"],
      ["life-size", "kích thước thật"],
      ["synthetic", "tổng hợp"],
      ["perimeter", "chu vi"],
      ["dismantle", "tháo dỡ"],
      ["promising", "đầy hứa hẹn"],
      ["symbolise", "tượng trưng"],
      ["cement", "củng cố"],
      ["flavourful", "đậm đà"],
      ["shred", "thái sợi"],
      ["institute", "viện"],
      ["disease", "bệnh tật"],
      ["quality", "chất lượng cao"],
      ["appreciative", "biết ơn"],
      ["consignment", "sự ký gửi"],
      ["assess", "đánh giá"],
      ["deduct", "khấu trừ"],
      ["stipulate", "quy định"],
      ["identification", "giấy tờ tùy thân"],
      ["liability", "trách nhiệm pháp lý"],
      ["caterer", "đơn vị cung cấp đồ ăn"],
    ]),
    quiz: [],
    written: [],
  },
];
