import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "dai-tu";

export const DAI_TU_LESSONS: MasteryLesson[] = [
  {
    slug: "dai-tu-nhan-xung",
    chapter: CHAPTER,
    code: "Word Form",
    title: "Đại từ nhân xưng",
    summary: "Chọn đúng đại từ chủ ngữ, tân ngữ, tính từ sở hữu, đại từ sở hữu và đại từ phản thân.",
    blocks: [
      {
        type: "text",
        body: "Khi làm câu hỏi về đại từ nhân xưng, cần xác định đại từ đó **thay thế cho danh từ nào** ở trong câu, và **vị trí** của đại từ là gì (chủ ngữ, tân ngữ, tính từ sở hữu, đại từ sở hữu hay đại từ phản thân).",
      },
      {
        type: "table",
        title: "Learning point: Bảng đại từ nhân xưng",
        headers: ["Chủ ngữ", "Tân ngữ", "Tính từ sở hữu", "Đại từ sở hữu", "Đại từ phản thân"],
        rows: [
          ["I", "me", "my", "mine", "myself"],
          ["you", "you", "your", "yours", "yourself / yourselves"],
          ["we", "us", "our", "ours", "ourselves"],
          ["they", "them", "their", "theirs", "themselves"],
          ["he", "him", "his", "his", "himself"],
          ["she", "her", "her", "hers", "herself"],
          ["it", "it", "its", "—", "itself"],
        ],
      },
      {
        type: "list",
        title: "Cách sử dụng đại từ nhân xưng",
        items: [
          "**1. Đại từ làm chủ ngữ:** đứng trước động từ, làm chủ ngữ trong câu. He will go on a business trip tomorrow.",
          "**2. Đại từ làm tân ngữ:** đứng sau động từ hoặc giới từ. Please send me the memo. / It is important for us to cut costs.",
          "**3. Tính từ sở hữu:** đứng trước danh từ, diễn tả ý 'của ai, của cái gì'. The company has adopted a new strategy to improve its image. / He is working on his report.",
          "**4. Đại từ sở hữu** = tính từ sở hữu + danh từ. Your manager and my manager have met. → Your manager and mine have met. Cấu trúc cố định: danh từ + of + đại từ sở hữu: He is a friend of mine. (Anh ấy là một người bạn của tôi.)",
          "**5. Đại từ phản thân:** khi chủ ngữ và tân ngữ cùng là một người/vật (một số cấu trúc phổ biến: find oneself — thấy mình như thế nào; prove oneself — chứng tỏ bản thân): The company has proved itself a leading business. / He found himself in big trouble.",
          "Đại từ phản thân diễn tả ý **'tự làm gì'**: He finished the report himself. (đứng cuối câu) / He himself finished the report. (đứng ngay sau chủ ngữ)",
          "**by oneself:** một mình — I live by myself.",
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("Mr. Pigden said [-------] would go on a business trip.", ["he", "him"], "A", "Trước động từ would go cần chủ ngữ. Đại từ thay thế cho Mr. Pigden làm chủ ngữ là he."),
          q("Many people make decisions based on [-------] emotion.", ["their", "they"], "A", "Trước danh từ emotion cần tính từ sở hữu. Tính từ sở hữu tương ứng với many people là their."),
          q("Richard will attend the conference by [-------] this time.", ["him", "himself"], "B", "Cụm từ by oneself nghĩa là 'tự làm gì' hoặc 'một mình'."),
          q("The strategy has failed, but the director decided to give [-------] another try.", ["it", "its"], "A", "Đại từ thay thế cho the strategy và làm tân ngữ sau động từ give là it."),
          q("This is your pen, and that is [-------].", ["my", "mine"], "B", "'Đây là bút của bạn, và cái kia là (bút) của tôi' → mine (= my pen)."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("My staff and I would like to express ------- congratulations on your accomplishment.", ["our", "us", "we", "ours"], "A", "Đại từ ở vị trí tính từ sở hữu (+ danh từ) thay thế cho my staff and I. 'Nhân viên của tôi và tôi muốn gửi lời chúc mừng tới thành công của bạn.'"),
          q("Jeremy will leave the company and start ------- own business.", ["him", "his", "he", "himself"], "B", "Đại từ ở vị trí tính từ sở hữu (+ danh từ) thay thế cho Jeremy. 'Jeremy sẽ rời công ty và bắt đầu kinh doanh riêng.'"),
          q("The manager is going on a business trip by ------- this time.", ["himself", "he", "his", "him"], "A", "By himself: một mình. 'Lần này quản lý sẽ đi công tác một mình.'"),
          q("The director has asked that Andrea finish the report -------.", ["herself", "her", "hers", "she"], "A", "Câu nhấn mạnh việc Andrea phải tự hoàn thành báo cáo."),
          q("DANS Incorporation has decided to recall its products and upgrade ------- at no additional cost.", ["them", "theirs", "they", "themselves"], "A", "Đại từ ở vị trí tân ngữ thay thế cho danh từ products. 'Tập đoàn DANS quyết định thu hồi sản phẩm và nâng cấp chúng miễn phí.'"),
          q("The firm has proved ------- to be both effective and efficient in meeting clients' demands.", ["it", "its", "itself", "it's"], "C", "Prove oneself: chứng tỏ mình. 'Công ty đã chứng tỏ mình hiệu quả trong việc đáp ứng yêu cầu của khách hàng.'"),
          q("I don't want you to pay for me. I can pay for -------.", ["me", "my", "I", "myself"], "D", "'Tôi không cần bạn trả tiền cho tôi. Tôi sẽ tự trả tiền cho mình.' (chủ ngữ và tân ngữ là một → đại từ phản thân)"),
          q("I looked at the new car and wished it would be -------.", ["me", "mine", "my", "I"], "B", "Mine = my car. 'Tôi nhìn chiếc xe mới và ước gì nó là của tôi.'"),
          q("She was homeless, then a friend of ------- offered her a place to stay.", ["her", "herself", "hers", "she"], "C", "A friend of hers: một người bạn của cô ấy (danh từ + of + đại từ sở hữu)."),
          q("Rescuers pulled ------- from the rubble after 40 minutes of working.", ["her", "herself", "she", "hers"], "A", "Đại từ ở vị trí tân ngữ → her. 'Những người cứu hộ kéo cô ấy ra khỏi đống đổ nát sau 40 phút.'"),
          q("The government has a responsibility to protect ------- citizens from inflation.", ["its", "it's", "it", "their"], "A", "Đại từ ở vị trí tính từ sở hữu (+ danh từ) thay thế cho the government → its."),
          q("I see you met my assistant. ------- and I go back many years.", ["Her", "She", "Hers", "We"], "B", "Đại từ ở vị trí chủ ngữ thay thế cho my assistant → She."),
          q("Instead of filling these orders now, take care of ------- tomorrow morning.", ["them", "they", "their", "its"], "A", "Đại từ ở vị trí tân ngữ thay thế cho these orders. 'Thay vì xử lý những đơn hàng này bây giờ, hãy xử lý chúng vào sáng mai.'"),
          q("All of ------- have been invited to the boss's cocktail party this Friday evening.", ["us", "we", "our", "ours"], "A", "All of us: tất cả chúng tôi (sau giới từ of là đại từ làm tân ngữ)."),
          q("The idea for the new routing system wasn't Patterson's; it was -------.", ["me", "mine", "my", "I"], "B", "Mine = my idea. 'Ý tưởng về hệ thống đó không phải của Patterson, đó là ý tưởng của tôi.'"),
          q("Telling somebody that ------- is laid off is a very unpleasant task.", ["him", "his", "he", "they"], "C", "Đại từ ở vị trí chủ ngữ thay thế cho somebody (động từ is số ít) → he."),
          q("My computer has a lot of memory, but ------- has more.", ["she", "her", "hers", "it"], "C", "Hers = her computer. 'Máy tính của tôi có bộ nhớ lớn, nhưng máy của cô ấy còn nhiều hơn.'"),
          q("------- isn't a good business practice to arrive late for meetings.", ["He", "It", "She", "You"], "B", "Đại từ tương đương với a business practice (chủ ngữ giả) là It."),
          q("When ------- probation period is up, you'll be given the full benefits package.", ["you", "your", "yours", "our"], "B", "Đại từ ở vị trí tính từ sở hữu (+ danh từ) thay thế cho you."),
          q("The police were right when ------- advised us to get a new security system.", ["it", "she", "them", "they"], "D", "Đại từ ở vị trí chủ ngữ thay thế cho danh từ the police (số nhiều) → they."),
        ],
      },
    ],
  },
  {
    slug: "dai-tu-khac",
    chapter: CHAPTER,
    code: "Word Choice 1",
    title: "Các đại từ khác",
    summary: "Those; each other, one another; another, other, the other, others, the others.",
    blocks: [
      {
        type: "list",
        title: "Learning point 1: Those",
        items: [
          "Đại từ **those** dùng để nói về những người, vật chung chung, không cụ thể. Lưu ý **these** không có cách sử dụng này.",
          "Our storage devices are inexpensive compared to **those** of SunMacro. (Những thiết bị lưu trữ của chúng ta thì rẻ so với những sản phẩm của SunMacro.)",
          "This email is for **those** who couldn't attend the meeting last Friday. (Email này dành cho những ai không đến họp thứ Sáu tuần trước.)",
        ],
      },
      {
        type: "list",
        title: "Learning point 2: each other, one another, another, other, the other",
        items: [
          "**each other, one another:** lẫn nhau, qua lại. Each other: hai người/vật — We two sat next to each other during the conference. One another: ba người/vật trở lên — Team members should help one another.",
          "**another, other, the other là tính từ** (đi với danh từ phía sau):",
          "– **another:** một người/vật khác (+ danh từ số ít). I'm not happy with this apartment. I need to see another apartment before making a decision.",
          "– **other:** những người, những vật khác (+ danh từ số nhiều). Some employees were happy with the new policy while other employees were not.",
          "– **the other:** (những) người/vật còn lại (+ danh từ số ít/số nhiều). I have two sons: one studies law and the other son studies tourism. / Among the three projects, one is practical while the other projects are not.",
          "**another, others, the other, the others là đại từ** (không cần danh từ phía sau) vì danh từ đã được nhắc đến trước đó:",
          "– I'm not happy with this apartment. I need to see **another** before making a decision.",
          "– Some employees were happy with the new policy while **others** were not.",
          "– I have two sons: one studies law and **the other** studies tourism.",
          "– Among the three projects, one is practical while **the others** are not.",
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("[-------] who can't attend the workshop must notify their supervisor.", ["These", "Those"], "B", "Câu đưa ra thông tin chung 'Những ai không thể tham gia hội thảo phải thông báo với người quản lý' → Those."),
          q("You need to cancel your current order to purchase [-------] model.", ["another", "other"], "A", "Sau chỗ trống là danh từ số ít model → another (một cái khác)."),
          q("I have two brothers: one is a lawyer and [-------] is a teacher.", ["another", "the other"], "B", "'Tôi có hai anh trai. Một người là luật sư và người còn lại là giáo viên.' The other: người còn lại."),
          q("Some desks are new but [-------] desks are from a second-hand store.", ["other", "another"], "A", "Sau chỗ trống là danh từ số nhiều desks → other (những cái khác)."),
          q("Ben and I know [-------] very well.", ["other", "each other"], "B", "Each other: lẫn nhau. 'Ben và tôi rất hiểu nhau.'"),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("One of your agents sent us a discount rate, but ------- has just said we had to pay the full price.", ["any", "one another", "another", "other"], "C", "'Một nhân viên của bạn giảm giá cho chúng tôi, nhưng một người khác lại vừa nói chúng tôi phải trả đầy đủ.' Another (đại từ, số ít) = another agent."),
          q("Mr. Taylor was able to purchase tickets to the event, but ------- were not as fortunate as he was.", ["other", "others", "the other", "another"], "B", "Sau chỗ trống không có danh từ, động từ were số nhiều → others (= other people)."),
          q("------- interested in attending the special lecture must sign up for it no later than 3 o'clock today.", ["What", "Those", "This", "These"], "B", "'Những ai muốn tham gia bài giảng đặc biệt phải đăng ký trước 3 giờ hôm nay.' Those: những người (chung chung)."),
          q("Unsatisfied with the building, he asked to see -------.", ["other", "another", "one another", "some other"], "B", "'Không hài lòng với ngôi nhà này, anh ấy yêu cầu được xem một ngôi nhà khác.' Another (đại từ)."),
          q("Although the two proposals are both interesting, one is too complicated while ------- is manageable.", ["one another", "each other", "the other", "other"], "C", "Two proposals: one – the other (cái còn lại đã xác định vì chỉ có hai đề xuất)."),
          q("The conference room is quite small, so the attendees will have to sit close to -------.", ["another", "one another", "each other", "others"], "B", "One another dùng với nghĩa 'lẫn nhau' với số lượng từ 3 trở lên (the attendees). 'Phòng họp khá nhỏ nên những người tham dự phải ngồi sát nhau.'"),
          q("If customers are not happy with a purchase, they may replace it with ------- product of the same or lesser value.", ["other", "another", "each other", "others"], "B", "Sau chỗ trống là danh từ số ít product → another."),
          q("Aspirin is available for ------- with pains and aches.", ["those", "that", "these", "this"], "A", "'Thuốc aspirin có sẵn cho những người bị đau.' Those: những người (chung chung)."),
          q("This seminar is to keep employees in different branches in touch with -------.", ["another", "one another", "other", "the others"], "B", "'Hội thảo giúp những nhân viên ở các chi nhánh khác nhau liên lạc với nhau' (3 người trở lên) → one another."),
          q("The teacher told his students to cooperate with ------- when doing the project.", ["another", "one another", "other", "the others"], "B", "'Giáo viên nói với học sinh rằng họ cần hợp tác với nhau khi làm dự án' → one another."),
        ],
      },
    ],
  },
  {
    slug: "dai-tu-quan-he",
    chapter: CHAPTER,
    code: "Word Choice 2",
    title: "Đại từ quan hệ",
    summary: "Who, whom, which, that, whose, where; phân biệt đại từ quan hệ với từ để hỏi (what, how…).",
    blocks: [
      {
        type: "text",
        title: "Giới thiệu",
        body: "Mệnh đề quan hệ bổ nghĩa cho danh từ đứng trước. Đại từ quan hệ có thể làm **chủ ngữ** hoặc **tân ngữ** trong mệnh đề quan hệ.\n1. This is the man **who** we were talking about. (danh từ được bổ nghĩa là the man; who we were talking about là mệnh đề quan hệ: who là tân ngữ, we là chủ ngữ, were talking about là vị ngữ)\n2. This is the man **who** came here yesterday. (who là chủ ngữ, came here yesterday là vị ngữ)",
      },
      {
        type: "text",
        title: "Learning point 1: Đại từ quan hệ who, whom, which, that, whose",
        body: "Khi điền đại từ quan hệ, cần xem (1) trước chỗ trống là danh từ chỉ người hay chỉ vật, (2) đại từ quan hệ làm chủ ngữ hay tân ngữ trong câu, (3) trước chỗ trống có dấu phẩy hoặc giới từ hay không.",
      },
      {
        type: "table",
        headers: ["", "Làm chủ ngữ", "Làm tân ngữ", "Sở hữu (+ danh từ)"],
        rows: [
          ["Danh từ chỉ người", "who", "who, whom", "whose"],
          ["Danh từ chỉ vật", "which", "which", "whose"],
          ["Danh từ chỉ người hoặc vật", "that", "that", "whose"],
        ],
      },
      {
        type: "examples",
        title: "Ví dụ",
        items: [
          { en: "He is the presenter who will speak at our next week's meeting.", vi: "who làm chủ ngữ, will speak là vị ngữ." },
          { en: "He is the presenter who/whom we invited to speak at the meeting.", vi: "who/whom làm tân ngữ, we là chủ ngữ, invited là vị ngữ." },
          { en: "The accident which happened last night was very serious.", vi: "which làm chủ ngữ, happened là vị ngữ." },
          { en: "The accident which we saw last night was serious.", vi: "which làm tân ngữ, we là chủ ngữ, saw là vị ngữ." },
          { en: "The person whose laptop is red is my brother. / The hospital whose buildings are old is famous.", vi: "whose + danh từ." },
        ],
      },
      {
        type: "note",
        title: "Không dùng that trong hai trường hợp",
        body: "Ở các ví dụ trên, who, whom và which đều có thể thay bằng that. Tuy nhiên, không dùng that:\n• Sau giới từ: This is the man with whom (không dùng that) I work.\n• Sau dấu phẩy: This is Sandra, who (không dùng that) works in the same department with me.",
      },
      {
        type: "list",
        title: "Learning point 2",
        items: [
          "**Phân biệt which và where:** thông thường với danh từ chỉ địa điểm dùng where. Tuy nhiên nếu vị trí chỗ trống là **chủ ngữ** trong mệnh đề quan hệ hoặc trước chỗ trống có **giới từ** thì cần dùng which. The restaurant **where** we ate dinner has good service. / The restaurant **which** sells Chinese food has good service. (đại từ quan hệ làm chủ ngữ)",
          "**Phân biệt đại từ quan hệ với từ để hỏi thông thường** (who, what, where, how, why, which, when): để chọn đại từ quan hệ cần dựa vào danh từ phía trước chỗ trống, chức năng trong mệnh đề và dấu hiệu khác (dấu phẩy, giới từ). I don't like the story **which** you told me. / I don't know the person **who** is going to give a speech.",
          "Có một loại câu hình thức gần giống mệnh đề quan hệ nhưng **phía trước chỗ trống không có danh từ** — đây không phải mệnh đề quan hệ, cần dịch nghĩa để xem câu thiếu ý gì (who: ai, what: điều gì/cái gì, where: ở đâu, how: thế nào, why: tại sao, which: cái nào, when: khi nào). I don't like **what** you told me. / I don't know **who** is going to give a speech.",
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 1",
        kind: "practice",
        questions: [
          q("Is this the person [-------] came to meet me yesterday?", ["who", "whom"], "A", "Đại từ quan hệ thay cho danh từ chỉ người the person và làm chủ ngữ trong mệnh đề quan hệ (who – S, came – V) là who."),
          q("Have you received the package [-------] we sent you?", ["which", "whom"], "A", "Đại từ quan hệ thay cho danh từ chỉ vật the package là which. Whom thay thế cho danh từ chỉ người."),
          q("Ann, [-------] children are at school all day, is trying to get a job.", ["whose", "who"], "A", "Đại từ quan hệ chỉ sở hữu (Ann – những đứa con của cô ấy) là whose."),
          q("Peter comes from Whitney, [-------] is near Oxford.", ["which", "that"], "A", "Sau dấu phẩy dùng which để thay thế cho danh từ chỉ vật Whitney."),
          q("This is the gun with [-------] the murder was committed.", ["which", "that"], "A", "Sau giới từ dùng which để thay thế cho danh từ chỉ vật the gun."),
        ],
      },
      {
        title: "Diagnostic test 2",
        kind: "practice",
        questions: [
          q("I recently went back to Paris, [-------] is as beautiful as a pearl.", ["which", "where"], "A", "Đại từ quan hệ bổ nghĩa cho Paris và làm chủ ngữ trong mệnh đề quan hệ là which. Where không làm chủ ngữ."),
          q("I recently went back to Paris, [-------] I was born.", ["which", "where"], "B", "Đại từ quan hệ bổ nghĩa cho Paris và không làm chủ ngữ trong câu là where."),
          q("I am reading the newspaper [-------] I bought this morning.", ["which", "what"], "A", "Đại từ quan hệ bổ nghĩa cho the newspaper là which. What không phải là đại từ quan hệ."),
          q("[-------] you said to Ms. White was unprofessional.", ["What", "Which"], "A", "Trước chỗ trống không có danh từ nên đây không phải mệnh đề quan hệ. 'Những gì bạn nói với cô White là thiếu chuyên nghiệp' → what."),
          q("I want to know [-------] you feel about the movie.", ["what", "how"], "B", "Trước chỗ trống không có danh từ. 'Tôi muốn biết bạn cảm thấy thế nào về bộ phim' → how."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Passengers ------- wish to have vegetarian meals should notify our flight staff.", ["who", "whose", "when", "what"], "A", "Đại từ thay thế cho danh từ chỉ người và làm chủ ngữ. 'Những hành khách muốn ăn chay nên thông báo với nhân viên máy bay.'"),
          q("To stay competitive in the global market, we need to know ------- our customers need.", ["what", "that", "when", "which"], "A", "Câu không dùng mệnh đề quan hệ. 'Để cạnh tranh trên thị trường quốc tế, chúng ta cần biết khách hàng cần gì.'"),
          q("The training is for programmers ------- jobs involve entering data.", ["who", "whom", "whose", "that"], "C", "Đại từ quan hệ đứng trước danh từ (jobs) là whose. 'Buổi đào tạo dành cho những lập trình viên mà công việc liên quan đến nhập dữ liệu.'"),
          q("We would like to welcome Dr. Zhang, ------- made significant contributions to our company.", ["whom", "whose", "who", "that"], "C", "Đại từ thay thế cho danh từ chỉ người ở vị trí chủ ngữ (có dấu phẩy nên không dùng that)."),
          q("This is the place ------- the terrible car accident happened.", ["that", "which", "where", "what"], "C", "Trạng từ quan hệ thay thế cho danh từ chỉ địa điểm. 'Đây là nơi tai nạn xe hơi xảy ra.'"),
          q("Those of you ------- passports have expired should inform the travel agency.", ["who", "whom", "that", "whose"], "D", "Đại từ quan hệ đứng trước danh từ (passports) là whose."),
          q("Mr. Simon, ------- is the head of the main office, is responsible for all administrative functions.", ["whom", "who", "whose", "that"], "B", "Đại từ quan hệ thay thế cho danh từ chỉ người ở vị trí chủ ngữ (sau dấu phẩy)."),
          q("Describe any activities in ------- you participated for your community.", ["that", "who", "whom", "which"], "D", "Đại từ quan hệ thay thế cho danh từ chỉ vật activities và đứng sau giới từ là which."),
          q("The kitchen staff ------- work here are all on temporary contracts.", ["that", "whom", "which", "whose"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ người the kitchen staff và làm chủ ngữ là that."),
          q("The room ------- the training will take place is on the fourth floor.", ["where", "which", "that", "what"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ địa điểm (không làm chủ ngữ) là where."),
          q("------- should I talk to about the mistake in my bill?", ["Who", "What", "Which", "That"], "A", "Đây không phải câu dùng mệnh đề quan hệ. 'Tôi nên nói với ai về lỗi sai trong hóa đơn của tôi?'"),
          q("The cafeteria ------- we had lunch has just been closed by health inspectors.", ["which", "where", "that", "whose"], "B", "Đại từ quan hệ thay thế cho danh từ chỉ địa điểm cafeteria là where."),
          q("The show was held at the hall, ------- was renovated just last month.", ["what", "where", "that", "which"], "D", "Đại từ thay thế cho danh từ chỉ địa điểm và làm chủ ngữ (không chọn where) sau dấu phẩy (không chọn that) là which."),
          q("Most computers have software ------- enables us to create professional posters.", ["that", "who", "whom", "whose"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ vật software là that."),
          q("The project ------- is funded by the government is nearly complete.", ["that", "who", "whom", "what"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ vật the project là that."),
          q("------- was said during the meeting by the sales manager was very doubtful.", ["What", "That", "Which", "Whose"], "A", "Đây không phải câu dùng mệnh đề quan hệ. 'Những gì được nói trong buổi họp bởi người quản lý bán hàng thì rất đáng ngờ.'"),
          q("We are cooperating with Vector Corporation, ------- is developing at an amazing pace.", ["which", "that", "what", "whom"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ vật Vector Corporation và đứng sau dấu phẩy là which."),
          q("Most of the reports ------- are submitted by our sales staff suggest improvement.", ["which", "whose", "who", "what"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ vật reports là which."),
          q("We're looking for a new manager ------- responsibilities include international marketing.", ["who", "whom", "that", "whose"], "D", "Đại từ quan hệ đứng trước danh từ responsibilities là whose."),
          q("All workers ------- want to ask for an extended holiday should submit a written form.", ["who", "whom", "whose", "which"], "A", "Đại từ quan hệ thay thế cho danh từ chỉ người workers và làm chủ ngữ là who."),
        ],
      },
    ],
  },
  {
    slug: "dai-tu-review-test",
    chapter: CHAPTER,
    code: "Review Test",
    title: "Pronouns — Review Test",
    summary: "Bài kiểm tra tổng hợp 30 câu về đại từ nhân xưng, đại từ khác và đại từ quan hệ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: ["Từ / cụm từ", "Từ loại", "Nghĩa"],
        rows: [
          ["at no additional cost", "n", "miễn phí, không thêm phí"],
          ["belongings", "n", "đồ dùng tùy thân"],
          ["commute", "n, v", "đi làm (xa nhà)"],
          ["finding = result", "n", "kết quả"],
          ["flight attendant", "n", "tiếp viên hàng không"],
          ["lay off", "v", "sa thải, giảm biên chế"],
          ["make contribution to", "v", "đóng góp cho"],
          ["notify", "v", "thông báo"],
          ["product launch", "n", "giới thiệu sản phẩm"],
          ["takeoff and landing", "n", "cất cánh và hạ cánh"],
        ],
      },
    ],
    exercises: [
      {
        title: "Pronouns — Review Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Passengers are asked to secure ------- belongings during takeoff and landing.", ["them", "their", "they", "themselves"], "B", "Đại từ ở vị trí tính từ sở hữu (đứng trước danh từ belongings)."),
          q("You may return for full credit any products with ------- you are not satisfied.", ["who", "what", "which", "whose"], "C", "Đại từ quan hệ thay thế cho danh từ products, đứng sau giới từ with → which."),
          q("Staff members should work in pairs during the training workshop to help ------- master the skills.", ["one such", "each other", "yourself", "everything"], "B", "'Nhân viên cần làm việc theo cặp để giúp đỡ nhau nắm vững kỹ năng' → each other (hai người)."),
          q("Although the staff has grown, Mr. Lee continues to conduct all client meetings -------.", ["he", "him", "his", "himself"], "D", "'Mặc dù số nhân viên đã tăng, ông Lee vẫn tự tiến hành tất cả các cuộc họp khách hàng.'"),
          q("Dr. Tang has been chosen to accept ------- award on behalf of the development team.", ["our", "ours", "us", "we"], "A", "Đại từ ở vị trí tính từ sở hữu (đứng trước danh từ award)."),
          q("The sales manager ------- has the highest sales record by the end of this year will receive the Fowler Award.", ["whose", "someone", "who", "whom"], "C", "Đại từ quan hệ thay thế cho danh từ chỉ người the sales manager ở vị trí chủ ngữ là who."),
          q("Mr. Kang started ------- printing business 25 years ago in Pusan, South Korea.", ["he", "him", "his", "himself"], "C", "Đại từ ở vị trí tính từ sở hữu (đứng trước danh từ printing business)."),
          q("------- pleased the clients most was the effective customer service we provide.", ["Who", "That", "What", "This"], "C", "Đây không phải câu với mệnh đề quan hệ. 'Điều làm khách hàng hài lòng nhất là dịch vụ chăm sóc khách hàng hiệu quả của chúng tôi.'"),
          q("The expert ------- spoke at last month's seminar on environmental awareness has been nominated for a Flagler Prize.", ["whoever", "when", "whenever", "who"], "D", "Đại từ quan hệ thay thế cho danh từ chỉ người ở vị trí chủ ngữ là who."),
          q("The use of umbrellas is banned in the sports stadium because they obstruct the view of -------.", ["others", "one", "those", "other"], "A", "'Việc sử dụng ô bị cấm trong sân vận động vì chúng cản trở tầm nhìn của những người khác.' Others = other people."),
          q("Beware that candidates ------- applications are incomplete will not be considered for an interview.", ["who", "whom", "whose", "their"], "C", "Đại từ quan hệ đứng trước danh từ applications là whose."),
          q("Employees must return to ------- work stations immediately after the lunch break.", ["theirs", "them", "their", "they"], "C", "Tính từ sở hữu đứng trước danh từ work stations là their."),
          q("Dr. Schmidt is not sure that her research assistant can complete the required investigation by -------.", ["his", "him", "his own", "himself"], "D", "By himself: một mình anh ấy."),
          q("------- willingness to join the excavation team was highly appreciated.", ["Which", "His", "Whose", "Those"], "B", "Tính từ sở hữu đứng trước danh từ willingness là his (whose cũng đứng trước danh từ, nhưng trước chỗ trống không có danh từ nên không phải mệnh đề quan hệ)."),
          q("The officer has asked the research team to clarify ------- findings.", ["they", "them", "themselves", "their"], "D", "Tính từ sở hữu đứng trước danh từ findings là their."),
          q("To prepare ------- for the interview at Boyer Pharmaceuticals, Mr. Park read about the company's history.", ["yourselves", "ourselves", "himself", "itself"], "C", "Danh từ phía sau là Mr. Park nên đại từ phản thân tương ứng là himself."),
          q("After the news of ------- product launch appeared in the media, their sales increased dramatically.", ["them", "they", "their", "themselves"], "C", "Tính từ sở hữu đứng trước danh từ product launch là their."),
          q("Most of the findings ------- are written on these documents were confirmed by the police.", ["these", "those", "that", "what"], "C", "Đại từ quan hệ thay thế cho danh từ chỉ vật findings là that."),
          q("The manager has given ------- a detailed construction schedule for the factory.", ["we", "ours", "us", "ourselves"], "C", "Đại từ ở vị trí tân ngữ sau động từ has given → us."),
          q("A notice should be sent to ------- bank as soon as you move to a different area.", ["you", "your", "yours", "yourself"], "B", "Tính từ sở hữu đứng trước danh từ bank là your."),
          q("People who own pets are shown to be more cheerful than ------- who do not.", ["those", "such", "someone", "this"], "A", "Those chỉ 'những người mà' với ý nghĩa chung chung."),
          q("I enjoy working with John because his working style is similar to -------.", ["me", "myself", "I", "mine"], "D", "Mine = my working style."),
          q("Any accident should be reported to ------- supervisor promptly.", ["them", "they", "their", "themselves"], "C", "Tính từ sở hữu đứng trước danh từ supervisor."),
          q("We can present our opinions on the issue, but the final decision is -------.", ["you", "your", "yours", "yourself"], "C", "Yours = your decision."),
          q("She proved ------- to be a competent leader after the research.", ["her", "hers", "herself", "she"], "C", "Prove herself: chứng tỏ bản thân mình."),
          q("Nearly 70% of US workers began ------- commutes between 6 and 9 a.m.", ["they", "them", "their", "theirs"], "C", "Tính từ sở hữu đứng trước danh từ commutes là their."),
          q("------- who wear warm clothes could cope with the severe weather.", ["Those", "This", "These", "One"], "A", "Those chỉ 'những người mà' với ý nghĩa chung chung."),
          q("I do not have enough time to prepare ------- completely for the speech on June 28th.", ["me", "my", "mine", "myself"], "D", "Prepare myself: chuẩn bị (bản thân) sẵn sàng."),
          q("Of the fifty applicants ------- registered today, most had more than three years of experience in the field.", ["whom", "which", "where", "who"], "D", "Đại từ quan hệ thay thế cho danh từ chỉ người applicants và làm chủ ngữ là who."),
          q("The strike was planned by the flight attendants ------- believe that they do not receive appropriate benefits.", ["whom", "whose", "who", "which"], "C", "Đại từ quan hệ thay thế cho danh từ chỉ người flight attendants và làm chủ ngữ là who."),
        ],
      },
    ],
  },
];
