import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "danh-gia";
const VOCAB_HEADERS = ["Từ / cụm từ", "Từ loại", "Nghĩa"];

export const DANH_GIA_LESSONS: MasteryLesson[] = [
  {
    slug: "evaluation-test-1",
    chapter: CHAPTER,
    code: "Evaluation Test 1",
    title: "Nouns, Verbs, Adjectives, Adverbs",
    summary: "Bài đánh giá tổng hợp 40 câu về danh từ, động từ, tính từ và trạng từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["account for", "v", "chiếm (bao nhiêu %)"],
          ["confidential", "adj", "bảo mật"],
          ["congestion", "n", "tắc đường"],
          ["dependence on", "n", "sự phụ thuộc vào"],
          ["drawback", "n", "sự thiếu hụt / bất lợi"],
          ["expire", "v", "hết hạn"],
          ["overtime", "adj", "thêm giờ"],
          ["periodically", "adv", "định kỳ"],
          ["reminder", "n", "thông báo, nhắc nhở"],
          ["screen", "v", "thẩm tra, kiểm tra"],
          ["sick leave", "n", "nghỉ ốm"],
          ["transfer", "v", "chuyển (địa điểm)"],
        ],
      },
    ],
    exercises: [
      {
        title: "Evaluation Test 1",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Ms. Walters ------- to another branch, so your new financial advisor will be Mr. Merenda.", ["transfer", "transferring", "has transferred", "transferable"], "C", "Động từ ở vị trí vị ngữ; chủ ngữ Ms. Walters số ít → has transferred. 'Cô Walters đã chuyển sang chi nhánh khác, nên cố vấn tài chính mới của bạn sẽ là ông Merenda.'"),
          q("The park service asks visitors to behave ------- and show respect to wildlife.", ["responsible", "responsibly", "responsibility", "responsibilities"], "B", "Trạng từ bổ nghĩa cho động từ behave."),
          q("It is not the company policy to grant sick leave ------- overtime pay to part-time employees.", ["yet", "if", "but", "or"], "D", "'Công ty không có chính sách cho nhân viên bán thời gian ngày nghỉ ốm hay trả tiền làm thêm giờ.'"),
          q("The ------- of the Board of Directors is scheduled for Monday.", ["election", "elected", "elects", "electable"], "A", "Danh từ đứng đầu câu làm chủ ngữ."),
          q("Last year, the number of new university-level textbooks ------- by American publishers dropped for the second year in a row.", ["sold", "sell", "selling", "to sell"], "A", "Dựa vào cụm by American publishers → tính từ bị động sold."),
          q("Traffic congestion is ------- than usual because of road construction.", ["badly", "bad", "worse", "worst"], "C", "Sau chỗ trống có than nên điền so sánh hơn của bad là worse."),
          q("CTC announced on Monday that a European media group is expected to ------- its online music store.", ["buy", "buying", "bought", "has bought"], "A", "Expect to V."),
          q("In order to suppress harmful insects and weeds, garden maintenance companies must choose the right products and apply them -------.", ["correction", "corrected", "correctly", "correcting"], "C", "Trạng từ bổ nghĩa cho động từ apply."),
          q("The young fashion designer wanted to create dress styles ------- different from those of her contemporaries.", ["recognize", "recognizing", "recognizable", "recognizably"], "D", "Trạng từ bổ nghĩa cho tính từ different."),
          q("Many environmental analysts recommend that nations reduce their ------- on non-renewable energy resources.", ["dependently", "dependence", "dependent", "depend"], "B", "Sau tính từ sở hữu their là danh từ dependence."),
          q("A particularly ------- drawback of this book is the almost complete lack of useful illustrations or tables.", ["frustrating", "frustrated", "frustrate", "frustratingly"], "A", "Tính từ frustrating bổ nghĩa về tính chất cho danh từ drawback."),
          q("According to a survey ------- by the Fielding Institute, advertising on the Internet accounted for 10% of total advertising.", ["conducted", "conductor", "conducting", "conducts"], "A", "Dựa vào by the Fielding Institute → tính từ dạng bị động conducted."),
          q("Dr. Viella Diop is best known for her ------- contributions to the field of physics.", ["signify", "significance", "significant", "significantly"], "C", "Tính từ bổ sung ý nghĩa cho danh từ contributions."),
          q("The Fountainview Hotel has rooms available for anyone who plans on ------- in Detroit during the annual conference.", ["stay", "to stay", "staying", "stayed"], "C", "Sau giới từ on là V-ing."),
          q("The two companies are now ------- the price for the property.", ["negotiate", "negotiating", "negotiation", "negotiated"], "B", "Câu có trạng từ now → hiện tại tiếp diễn."),
          q("After ------- years of performing for live audiences, stage director Kenneth Ogozi is glad to be working behind the scenes again.", ["all", "many", "much", "every"], "B", "Many + danh từ số nhiều."),
          q("A local steel manufacturing ------- has purchased the riverfront lot in order to increase its production capacity.", ["facilitate", "facilitation", "facility", "facilitating"], "C", "Facility: cơ sở sản xuất."),
          q("When you ------- your loan application, please remember to sign and date the last page.", ["completed", "had completed", "are completing", "were completing"], "C", "Dựa vào động từ phía sau ở thì hiện tại, động từ ở chỗ trống cũng ở thì hiện tại."),
          q("Both financial advisors recommended investing in pharmaceutical companies, although Paul Laurinen is suggesting a wider ------- of stocks.", ["select", "selected", "selection", "selective"], "C", "Sau mạo từ a và tính từ wider là danh từ."),
          q("We do ------- receive requests for records that are housed off-site.", ["period", "periodical", "periodically", "periodic"], "C", "Trạng từ bổ nghĩa cho động từ receive."),
          q("Many analysts attribute Kramar Industries' ------- success to its state-of-the-art research department.", ["phenomenon", "phenomena", "phenomenally", "phenomenal"], "D", "Tính từ bổ nghĩa cho danh từ success."),
          q("Mr. Parker was deeply ------- with the answers of the job applicant.", ["impressed", "impressive", "impress", "impression"], "A", "Tính từ bổ sung ý nghĩa cảm xúc cho danh từ chỉ người → impressed."),
          q("This area of the bank is ------- to bank personnel only.", ["restrict", "restricted", "restrictive", "restrictions"], "B", "Is restricted: bị giới hạn."),
          q("We often screen the CVs of ------- to make sure that they are qualified for the openings.", ["applications", "applicants", "appliances", "applicable"], "B", "'Chúng tôi thường kiểm tra lý lịch của các ứng viên để đảm bảo họ đủ điều kiện cho vị trí đang tuyển.'"),
          q("Management has ------- to make a reasonable offer at the next contract bargaining session.", ["promised", "promises", "promise", "promising"], "A", "Trước chỗ trống là has nên phía sau chọn VpII."),
          q("In order to get a -------, you have to bring your defective product with a valid receipt.", ["refund", "receipt", "reimbursement", "return"], "A", "Tình huống: defective product, valid receipt → refund (hoàn tiền)."),
          q("The board of recruiting informs that the ------- candidates will go straight through the next round.", ["contacting", "contacted", "contact", "contactable"], "B", "Tính từ dạng bị động bổ nghĩa cho candidates: ứng viên được liên lạc."),
          q("Remember that feeling confident and ------- is an important part of giving an effective presentation.", ["relaxation", "relaxed", "relaxing", "relax"], "B", "Sau feel là tính từ chỉ cảm xúc relaxed."),
          q("While some people enjoy receiving calls from telemarketers, other people find such calls -------.", ["annoys", "annoying", "annoyed", "annoyance"], "B", "Sau find là tính từ dạng V-ing chỉ tính chất."),
          q("Lonan Imports will work ------- with any distributor to fulfill a customer request.", ["directly", "direct", "direction", "directness"], "A", "Trạng từ bổ nghĩa cho động từ work."),
          q("Grove Canoes' prices may ------- vary depending on changes in the cost of raw materials.", ["occasion", "occasionally", "occasional", "occasions"], "B", "Trạng từ bổ nghĩa cho động từ vary."),
          q("A 20 percent increase in revenue makes this the ------- year for the company.", ["more profitable", "most profitable", "profiting", "profitably"], "B", "Sau the là so sánh cao nhất."),
          q("The Moore Landmark Society has requested that city council members ------- the demolition of the historic library.", ["reconsider", "to reconsider", "reconsidering", "reconsidered"], "A", "Sau request that là động từ dạng nguyên thể."),
          q("We're waiting for verification that our water tank designs ------- legal specifications.", ["meet", "set", "fill", "miss"], "A", "Meet the specifications: đáp ứng yêu cầu."),
          q("------- to the amusement park is free during the weekdays for children under 10.", ["Addition", "Admission", "Address", "Addendum"], "B", "Admission: sự cho vào cửa."),
          q("Our goal is to develop ------- furniture while maintaining comfort and functions.", ["innovation", "innovative", "innovate", "innovatively"], "B", "Tính từ đứng trước và bổ nghĩa cho danh từ furniture."),
          q("To ------- the store that is nearest to you, select your state or country from the pull-down menu.", ["afford", "create", "locate", "provide"], "C", "Dựa vào nearest, state, country → locate (xác định địa điểm)."),
          q("The information you provide on this survey is completely ------- and will not be shared with any other vendors.", ["potential", "concentrated", "dedicated", "confidential"], "D", "Confidential information: thông tin mật."),
          q("Dhyana Home Improvement routinely offers discounts to local organizations that are ------- new buildings.", ["addressing", "constructing", "investing", "centering"], "B", "'Dhyana Home Improvement thường giảm giá cho những tổ chức địa phương đang xây dựng công trình mới.'"),
          q("This is a ------- to renew your membership, which expires on August 30.", ["purpose", "conclusion", "statement", "reminder"], "D", "'Đây là thông báo nhắc nhở bạn gia hạn thẻ thành viên sẽ hết hạn vào ngày 30 tháng 8.'"),
        ],
      },
    ],
  },
  {
    slug: "evaluation-test-2",
    chapter: CHAPTER,
    code: "Evaluation Test 2",
    title: "Nouns, Verbs, Adjectives, Adverbs",
    summary: "Bài đánh giá tổng hợp thứ hai, 40 câu.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["abroad", "adv", "nước ngoài"],
          ["appointment", "n", "sự bổ nhiệm"],
          ["at competitive prices", "n", "với giá cả cạnh tranh"],
          ["available / open to the public", "adj", "có sẵn cho mọi người"],
          ["be exposed to", "adj", "tiếp xúc với"],
          ["consistency", "n", "sự thống nhất, ổn định"],
          ["consumption", "n", "sự tiêu thụ"],
          ["disapproval", "n", "sự không chấp thuận"],
          ["exposure to something", "n", "sự tiếp xúc với"],
          ["negotiate", "v", "đàm phán"],
          ["originally", "adv", "ban đầu, lúc đầu"],
          ["resolve the problem", "v", "giải quyết vấn đề"],
          ["scheduling conflict", "n", "sự trùng lịch"],
          ["thoroughly", "adv", "một cách toàn diện"],
        ],
      },
    ],
    exercises: [
      {
        title: "Evaluation Test 2",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Dr. Maria Chilton told her patient to spend a minimum of thirty minutes ------- every day.", ["exerciser", "exercise", "exercising", "exercised"], "C", "Spend time + V-ing: dành thời gian vào việc gì."),
          q("HB Research Center's extraordinary ideas and ------- achievements provided us with interesting topics for further discussions.", ["remark", "remarkable", "remarks", "remarkably"], "B", "Tính từ remarkable đứng trước và bổ nghĩa cho danh từ achievements."),
          q("The Budget Travel Guide for student travelers focuses ------- on ways to save money while enjoying exotic locations around the country.", ["exclusively", "exclude", "excluding", "exclusive"], "A", "Focus exclusively: tập trung riêng vào."),
          q("Many workers are taking ------- of the language study program which has been designed specifically for company employees.", ["use", "inventory", "advantage", "place"], "C", "Take advantage of: tận dụng."),
          q("Radiologists are well aware that ------- exposure to x-rays can be harmful to one's health.", ["repeat", "repetition", "repeated", "repeating"], "C", "Tính từ bổ sung ý nghĩa bị động cho danh từ exposure: tiếp xúc lặp lại nhiều lần."),
          q("When employees were informed of the new regulations, they showed strong -------.", ["disapprove", "disapproving", "disapproved", "disapproval"], "D", "Sau tính từ strong là danh từ disapproval (sự không chấp thuận)."),
          q("The company purchased back-up generators to prevent information loss in case of a power -------.", ["fails", "failure", "to fail", "failed"], "B", "Sau giới từ of là cụm danh từ a power + N. Power failure: mất điện."),
          q("Delemark's profits are expected to rise ------- over the next ten years as the company begins to offer new services abroad.", ["closely", "lately", "cheaply", "significantly"], "D", "Rise significantly: tăng nhiều, đáng kể."),
          q("This flash memory card is widely used because of its ------- to climate changes.", ["resisted", "resistant", "resisting", "resistance"], "D", "Sau tính từ sở hữu là danh từ resistance."),
          q("We strive to meet your needs by helping ------- your problems within 48 hours.", ["resolve", "resume", "remain", "retain"], "A", "Help (to) V; resolve the problem: giải quyết vấn đề."),
          q("------- insignificant details should be handled carefully to ensure customers' satisfaction.", ["Seem", "Seems", "Seeming", "Seemingly"], "D", "Trạng từ bổ nghĩa cho tính từ insignificant: 'những chi tiết tưởng chừng không quan trọng'."),
          q("In order to respond ------- to customer complaints, the company management decided to set up a new team.", ["overtly", "intensely", "severely", "promptly"], "D", "'Để trả lời kịp thời những phàn nàn của khách hàng, ban quản lý quyết định thành lập đội mới.'"),
          q("While no analyst can ------- the market, it is clear that Asians will face a vastly different consumer market in the future.", ["predict", "to predict", "predicting", "predicted"], "A", "Sau can là động từ nguyên thể."),
          q("Children who are two years old and younger are ------- free of charge to most concerts and films.", ["admit", "admits", "admitted", "admitting"], "C", "Be admitted to: được cho vào cửa."),
          q("Although we have ------- not to offer you a position at this time, we will keep your résumé on file for future openings.", ["decided", "deciding", "decision", "decidedly"], "A", "Phía trước chỗ trống là have nên phía sau là VpII."),
          q("All passengers should present their ------- documents at the check-in counter.", ["boarded", "boarding", "board", "to board"], "B", "Boarding document: vé/thẻ lên máy bay."),
          q("The recent increase in tourism has done less to improve the business of small retailers in this area than we ------- predicted.", ["original", "originally", "originated", "originality"], "B", "Trạng từ bổ nghĩa cho động từ predict."),
          q("The cost of repairing the water damage to the museum ------- to be more than one million dollars.", ["expects", "is expecting", "is expected", "expected"], "C", "'Chi phí sửa chữa hư hại do nước gây ra cho bảo tàng được ước tính hơn một triệu đô la.'"),
          q("Once the berries are harvested, Green Fields Farms washes and packages the fruit for -------.", ["distribute", "distributed", "distribution", "distributional"], "C", "Sau giới từ for là danh từ."),
          q("Topics at the business communication workshop ------- defending an argument, synthesizing information, and writing precisely and concisely.", ["include", "includes", "including", "inclusion"], "A", "Động từ ở chỗ trống làm vị ngữ; chủ ngữ topics số nhiều → include."),
          q("Dr. Herbert's illustrations were clear enough to make her presentation ------- understandable.", ["easily", "easier", "easy", "ease"], "A", "Trạng từ đứng trước và bổ nghĩa cho tính từ understandable."),
          q("The apartments on the lower floors cost less because they are more exposed ------- dust and traffic noise.", ["to", "without", "from", "against"], "A", "Be exposed to: tiếp xúc với."),
          q("Next Thursday we will present ------- methods for learning about the history of your country.", ["specify", "specifying", "specific", "specifications"], "C", "Tính từ đứng trước và bổ nghĩa cho danh từ methods."),
          q("Since many people want to attend the ceremony, extra buses will be made ------- to the public.", ["additional", "frequent", "available", "employable"], "C", "Available to the public: có sẵn cho tất cả mọi người."),
          q("The guest speaker highlighted some ideas for ------- introducing change in the workplace.", ["success", "succeed", "succeeding", "successfully"], "D", "Trước động từ introducing là trạng từ."),
          q("The shop specializes in handcrafted items, each of which is unique and -------.", ["memory", "memorize", "memories", "memorable"], "D", "'Cửa hàng chuyên bán sản phẩm thủ công, mỗi sản phẩm đều độc đáo và đáng nhớ.'"),
          q("The forethought and planning ------- in each step of the project will have a direct impact on the chances of its acceptance.", ["invest", "invested", "investor", "investing"], "B", "Câu đã có vị ngữ will have; chỗ trống cần tính từ bổ nghĩa cho forethought and planning → invested."),
          q("The clothing shop is ------- because it sells quality uniforms at competitive prices.", ["successful", "success", "succeed", "successfully"], "A", "Sau to be là tính từ successful."),
          q("Our book recently ------- positive reviews from the readers.", ["receives", "received", "is received", "was receiving"], "B", "Recently: động từ chia quá khứ/hiện tại hoàn thành; book và receive → chủ động."),
          q("Costs for building materials, such as cement, steel and wood, rose ------- last quarter.", ["sharp", "sharply", "sharpness", "sharpen"], "B", "Bổ nghĩa cho động từ rise (rose) là trạng từ."),
          q("International experience is the main ------- that separates Mr. Sloan from the other candidates.", ["qualified", "qualification", "qualify", "qualifying"], "B", "Sau mạo từ the và tính từ main là danh từ qualification."),
          q("After Ms. Aglo's appointment to the board of directors, the firm's investment strategy was ------- reevaluated.", ["thoroughly", "thorough", "thoroughness", "more thorough"], "A", "Trạng từ bổ nghĩa cho động từ reevaluate."),
          q("Mr. Martin has decided to ------- the planning meeting because of a scheduling conflict.", ["evaluate", "postpone", "refer", "identify"], "B", "Postpone the meeting: hoãn cuộc họp."),
          q("Improvement in the manufacturing process resulted in greater ------- in the production of wood furniture.", ["consistency", "consisting", "consistently", "consistent"], "A", "Sau tính từ greater cần danh từ consistency (sự ổn định)."),
          q("The company handbook ------- the topics of compensation, bonuses and overtime.", ["has been covered", "covering", "is covered", "covers"], "D", "Chủ ngữ số ít the company handbook, động từ chủ động → covers."),
          q("In order to keep prices -------, Kim's Bakery will begin making its bread and cakes on the premises.", ["reasonable", "reasonably", "reasoning", "reason"], "A", "Sau keep (+ O) là tính từ."),
          q("Our contract terms are printed on the back cover of the manual so that you may ------- refer to it.", ["ease", "easy", "easiest", "easily"], "D", "Trước động từ là trạng từ easily."),
          q("Recent data showed that the ------- of water in Ordoom Valley has dropped over the last two months.", ["consume", "consumer", "consumption", "consumed"], "C", "Sau mạo từ the là danh từ consumption (sự tiêu thụ)."),
          q("Local manufacturers have been ------- to hire additional employees until productivity increases.", ["hesitate", "hesitation", "hesitating", "hesitant"], "D", "Sau động từ to be là tính từ hesitant (phân vân)."),
          q("If fuel costs rise -------, the terms of our contract may have to be renegotiated.", ["mainly", "significantly", "freshly", "sincerely"], "B", "Rise significantly: tăng đáng kể."),
        ],
      },
    ],
  },
];
