import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "danh-tu";
const VOCAB_HEADERS = ["Từ / cụm từ", "Từ loại", "Nghĩa"];

export const DANH_TU_LESSONS: MasteryLesson[] = [
  {
    slug: "nhan-biet-danh-tu",
    chapter: CHAPTER,
    code: "Word Form 1",
    title: "Câu hỏi nhận biết danh từ",
    summary: "Nhận biết danh từ dựa vào hậu tố, chức năng trong câu và các thành phần đứng trước danh từ.",
    blocks: [
      {
        type: "examples",
        title: "Introduction",
        items: [
          {
            en: "The signature indicated the manager's ------- of all the terms and conditions.\n(A) acceptance  (B) accept  (C) accepted  (D) acceptable",
            vi: "Khi làm một câu hỏi TOEIC Part 5-6, trước tiên nên đọc lướt các phương án. Ở câu trên, mỗi phương án thuộc một từ loại khác nhau: A là danh từ, B là động từ nguyên thể, C là động từ quá khứ, D là tính từ. Chỗ trống cần danh từ → đáp án A. Dạng câu này là câu hỏi nhận biết danh từ.",
          },
        ],
      },
      {
        type: "text",
        body: "Bài học cung cấp các kỹ năng làm dạng câu hỏi nhận biết danh từ:\n• cách nhận biết danh từ dựa vào **hậu tố**\n• cách nhận biết vị trí cần điền là danh từ dựa vào **chức năng** của danh từ\n• cách nhận biết vị trí cần điền là danh từ dựa vào các **định ngữ đứng trước** danh từ cho sẵn trong câu hỏi.",
      },
      {
        type: "qa",
        title: "Diagnostic test 1",
        instructions: "Gạch chân danh từ trong các cặp từ dưới đây.",
        items: [
          { q: "competition – compete", a: "**competition**: cuộc thi, sự cạnh tranh" },
          { q: "responsible – responsibility", a: "**responsibility**: trách nhiệm" },
          { q: "popular – popularity", a: "**popularity**: sự phổ biến" },
          { q: "encouragement – encourage", a: "**encouragement**: sự khích lệ" },
          { q: "satisfaction – satisfy", a: "**satisfaction**: sự hài lòng" },
          { q: "approval – approve", a: "**approval**: sự thông qua, chấp thuận" },
          { q: "advice – advise", a: "**advice**: lời khuyên" },
          { q: "delivery – deliver", a: "**delivery**: sự phân phát, giao hàng" },
          { q: "perform – performance", a: "**performance**: sự biểu diễn, hiệu suất công việc" },
          { q: "application – apply", a: "**application**: đơn xin việc" },
        ],
      },
      {
        type: "table",
        title: "Learning point 1: Nhận biết đáp án là danh từ dựa vào hậu tố cấu tạo nên danh từ",
        headers: ["Hậu tố", "Ví dụ"],
        rows: [
          ["-ance, -ence", "attendance, acceptance, insurance, assistance"],
          ["-ation, -tion", "evaluation, application, reservation, promotion, satisfaction, inspection"],
          ["-sion", "division, revision, impression, conclusion"],
          ["-ure", "departure, failure, enclosure"],
          ["-ment", "agreement, investment, employment, government, retirement"],
          ["-age", "package, marriage, baggage"],
          ["-ery, -ity, -gy, -iry", "delivery, strategy, security, priority, generosity, inquiry"],
          ["-y", "economy, penalty, ceremony, summary"],
          ["-sis", "basis, crisis"],
          ["-ness", "kindness, attentiveness"],
          ["-al", "arrival, denial, refusal, approval, proposal"],
          ["-ing", "writing, funding, briefing, finding, building"],
          ["-th", "strength, health"],
          ["-er", "worker, manager, waiter"],
          ["-ist", "receptionist, therapist"],
          ["-ian", "physician, electrician"],
          ["-or", "actor, contractor, author"],
          ["-ess", "actress, waitress"],
          ["-ee", "interviewee, employee, attendee"],
          ["-ant, -ent", "applicant, recipient, client"],
        ],
      },
      {
        type: "qa",
        title: "Check-up 1",
        instructions: "Điền vào chỗ trống các danh từ của các từ cho sẵn.",
        items: [
          { q: "apply", a: "application (đơn xin), applicant (người xin việc), appliance (đồ gia dụng)" },
          { q: "deliver", a: "delivery (sự vận chuyển)" },
          { q: "approve", a: "approval (sự đồng ý, sự thông qua)" },
          { q: "employ", a: "employee (người làm thuê), employer (người chủ), employment (việc làm)" },
          { q: "responsible", a: "responsibility (trách nhiệm)" },
          { q: "popular", a: "popularity (sự phổ biến)" },
          { q: "encourage", a: "encouragement (sự khích lệ)" },
          { q: "satisfy", a: "satisfaction (sự hài lòng)" },
          { q: "compete", a: "competition (cuộc thi, sự cạnh tranh)" },
          { q: "advise", a: "advice (lời khuyên)" },
          { q: "advertise", a: "advertisement (quảng cáo)" },
          { q: "perform", a: "performance (biểu hiện, năng suất)" },
          { q: "conclude", a: "conclusion (kết luận)" },
          { q: "assist", a: "assistance (sự trợ giúp)" },
          { q: "strategize", a: "strategy (chiến lược)" },
          { q: "evaluate", a: "evaluation (sự đánh giá)" },
          { q: "invest", a: "investment (sự đầu tư, khoản đầu tư)" },
          { q: "prior", a: "priority (sự ưu tiên)" },
          { q: "economic", a: "economy (nền kinh tế)" },
          { q: "inspect", a: "inspection (sự kiểm tra, điều tra)" },
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Xác định chỗ trống là danh từ dựa vào chức năng của danh từ trong câu",
        items: [
          "Danh từ làm **chủ ngữ** đứng trước động từ chính làm vị ngữ: **Competition** in the global market has increased. (câu có cấu trúc: … + cụm giới từ bổ nghĩa in the global market + động từ làm vị ngữ has increased)",
          "Danh từ làm **tân ngữ** sau động từ: We do not accept **responsibility** for lost items.",
          "Danh từ làm tân ngữ sau **giới từ**: The film has increased in **popularity**.",
        ],
      },
      {
        type: "list",
        title: "Learning point 3: Xác định vị trí cần điền là danh từ dựa vào các thành phần đứng trước danh từ",
        items: [
          "**Tính từ** (official, beautiful) đứng trước danh từ: official **approval**.",
          "**Mạo từ** (a/an/the) đứng trước danh từ: the **advertisement**.",
          "**Tính từ sở hữu** (my, your, his, her, its, their, our) và **sở hữu cách** (employees', John's) đứng trước danh từ: employees' **performance**.",
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["acceptance", "n", "sự chấp thuận, đồng ý"],
          ["appointment", "n", "cuộc hẹn"],
          ["immediate supervisor", "n", "người quản lý trực tiếp"],
          ["option", "n", "lựa chọn"],
          ["performance evaluation", "n", "đánh giá năng lực"],
          ["project", "n", "dự án, kế hoạch"],
          ["reliability", "n", "độ tin cậy"],
          ["success", "n", "sự thành công"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 2",
        kind: "practice",
        instructions: "Chọn một đáp án đúng để hoàn thành các câu sau.",
        questions: [
          q("[-------] in the global market has increased.", ["Compete", "Competition"], "B", "Câu có cấu trúc: … + cụm giới từ bổ nghĩa (in the global market) + động từ làm vị ngữ (has increased), nên chỗ trống cần một danh từ làm chủ ngữ → Competition."),
          q("We do not accept [-------] for lost items.", ["responsible", "responsibility"], "B", "Sau động từ accept cần điền danh từ làm tân ngữ → responsibility."),
          q("The film has increased in [-------].", ["popularity", "popular"], "A", "Sau giới từ in cần điền danh từ làm tân ngữ → popularity."),
        ],
      },
      {
        title: "Check-up 2",
        kind: "practice",
        instructions: "Chọn một đáp án đúng để hoàn thành các câu sau.",
        questions: [
          q("An important part of a manager's job is offering ------- to new employees.", ["encourage", "encouragement", "encouraging", "encourages"], "B", "Sau động từ offering cần danh từ làm tân ngữ. 'Một phần quan trọng trong công việc của người quản lý là đem lại sự khích lệ cho nhân viên.'"),
          q("------- is what we hope to bring to our customers.", ["Satisfaction", "Satisfy", "Satisfied", "Satisfactory"], "A", "Đứng trước động từ is cần danh từ làm chủ ngữ. 'Sự hài lòng chính là điều chúng tôi mong mỏi mang lại cho khách hàng.'"),
          q("You should receive ------- from your immediate supervisors to borrow books from the library.", ["approve", "approved", "approval", "approving"], "C", "Sau động từ receive cần danh từ làm tân ngữ. 'Bạn cần có được sự đồng ý từ người quản lý trực tiếp để mượn sách từ thư viện.'"),
          q("The new airline has increased ------- in the airline industry.", ["compete", "competition", "competitively", "competitive"], "B", "Sau động từ increase cần danh từ làm tân ngữ. 'Hãng hàng không mới đã làm tăng sự cạnh tranh trong ngành hàng không.'"),
          q("You should count on your supervisors for -------.", ["advised", "advisable", "advice", "advise"], "C", "Sau giới từ for cần danh từ làm tân ngữ. 'Bạn nên tin tưởng xin lời khuyên từ người quản lý.'"),
        ],
      },
      {
        title: "Diagnostic test 3",
        kind: "practice",
        instructions: "Chọn một đáp án đúng để hoàn thành các câu sau.",
        questions: [
          q("You should receive official [-------] for taking a day off.", ["approval", "approve"], "A", "Sau động từ receive cần danh từ làm tân ngữ. Hoặc có thể dựa vào tính từ official trước chỗ trống để điền danh từ."),
          q("I learned about the job vacancy through the [-------] in today's newspaper.", ["advertise", "advertisement"], "B", "Sau giới từ through cần danh từ làm tân ngữ. Hoặc có thể dựa vào mạo từ the đứng trước chỗ trống để điền danh từ."),
          q("Companies should evaluate employees' [-------].", ["performance", "perform"], "A", "Sau động từ evaluate cần danh từ làm tân ngữ. Hoặc có thể dựa vào sở hữu cách employees' đứng trước chỗ trống để điền danh từ."),
        ],
      },
      {
        title: "Check-up 3",
        kind: "practice",
        instructions: "Chọn một đáp án đúng để hoàn thành các câu sau.",
        questions: [
          q("You have to refuse the ------- of packages from unknown senders.", ["deliverable", "delivered", "delivery", "deliver"], "C", "Sau mạo từ the là danh từ. 'Bạn cần từ chối những bưu kiện gửi đến từ những người không quen.'"),
          q("You need to get your supervisor's ------- for the seminar.", ["approval", "approve", "appointed", "approving"], "A", "Sau sở hữu cách your supervisor's là danh từ. 'Bạn cần có được sự đồng ý từ quản lý để tham gia hội thảo.'"),
          q("Our bank will review your -------.", ["applicable", "application", "apply", "applied"], "B", "Sau tính từ sở hữu your là danh từ. 'Ngân hàng của chúng tôi sẽ xem xét đơn của bạn.'"),
          q("All members are looking forward to a fruitful -------.", ["conclude", "conclusive", "conclusion", "concluded"], "C", "Sau mạo từ a và tính từ fruitful là danh từ. 'Tất cả các thành viên đang mong chờ một kết quả tốt đẹp.'"),
          q("Please turn off your cell phone during the -------.", ["performance", "perform", "performable", "performed"], "A", "Sau mạo từ the cần danh từ. 'Làm ơn tắt điện thoại trong suốt buổi biểu diễn.'"),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Products made by Izmir Vitamins are designed to promote ------- and well-being.", ["health", "healthy", "healthful", "healthfully"], "A", "Sau động từ promote cần danh từ. Hoặc dựa vào từ and để suy ra chỗ trống cùng từ loại với danh từ well-being. 'Những sản phẩm của Izmir Vitamins được sản xuất để nâng cao sức khỏe và hạnh phúc.'"),
          q("Ulrich Electronics will provide free ------- of any entertainment system purchased by June 30.", ["assistance", "assist", "assistive", "assisted"], "A", "Sau tính từ free là danh từ. 'Ulrich Electronics sẽ trợ giúp miễn phí bất cứ sản phẩm giải trí nào được mua trước ngày 30 tháng 6.'"),
          q("Gyeong Designs recently changed its marketing ------- to target hotel and restaurant owners.", ["strategic", "strategize", "strategy", "strategically"], "C", "Sau tính từ sở hữu its là danh từ. 'Gyeong Designs gần đây đã thay đổi chiến lược marketing để hướng tới đối tượng chủ khách sạn và nhà hàng.'"),
          q("Performance ------- are conducted by many companies to check their employees' strengths and weaknesses.", ["evaluative", "evaluations", "evaluated", "evaluate"], "B", "Chỗ trống đứng đầu câu làm chủ ngữ nên cần danh từ. Performance evaluation là danh từ ghép, nghĩa là 'đánh giá năng lực'. 'Việc đánh giá năng lực được tiến hành bởi nhiều công ty để kiểm tra điểm mạnh và điểm yếu của nhân viên.'"),
          q("The construction of the new ------- was delayed due to a lack of funds.", ["build", "to build", "built", "building"], "D", "Sau tính từ new là danh từ building. 'Việc xây dựng tòa nhà mới đã bị trì hoãn vì thiếu vốn.'"),
          q("Many methods of making plastic are not safe for the -------.", ["environmentally", "environment", "environ", "environmental"], "B", "Sau mạo từ the là danh từ. 'Nhiều phương pháp sản xuất nhựa thì không an toàn cho môi trường.'"),
          q("The latest ------- from Rudolph Industries has great potential for capturing the domestic market.", ["apply", "applicable", "applicably", "appliance"], "D", "Sau tính từ latest là danh từ. 'Sản phẩm gia dụng mới nhất từ Rudolph có tiềm năng chiếm lĩnh thị trường trong nước.'"),
          q("Your signature below will represent your ------- of this contract.", ["accepted", "acceptance", "accept", "acceptable"], "B", "Sau tính từ sở hữu your là danh từ. 'Chữ ký ở bên dưới sẽ đại diện cho sự đồng ý của bạn với hợp đồng.'"),
          q("The ------- on who could be hired for that position did not seem legal.", ["restrictions", "restricted", "restricting", "restrict"], "A", "Chỗ trống đứng đầu câu làm chủ ngữ nên cần danh từ. 'Quy định về việc ai sẽ được tuyển dụng cho vị trí đó có vẻ không hợp pháp.'"),
          q("Employees' ------- in this company will prove beneficial for everyone.", ["invest", "invested", "investments", "invests"], "C", "Sau sở hữu cách employees' là danh từ. 'Sự đầu tư của nhân viên ở công ty này thì có lợi cho tất cả mọi người.'"),
          q("The contract calls for a $1,000 ------- for every day we go over the deadline.", ["penalize", "penalty", "penal", "penalizing"], "B", "Sau mạo từ a là danh từ. 'Hợp đồng này yêu cầu bồi thường 1.000 đô la với mỗi ngày chậm hạn.'"),
          q("The manager's ------- for next year's profits is very optimistic.", ["projected", "projecting", "project", "to project"], "C", "Sau sở hữu cách the manager's là danh từ. 'Kế hoạch/đề xuất của người quản lý cho lợi nhuận năm tới có vẻ rất khả quan.'"),
          q("We have no other ------- if we want to expand the company safely.", ["optimal", "optimum", "opt", "option"], "D", "Sau no other là danh từ. 'Chúng ta không còn sự lựa chọn nào khác nếu muốn mở rộng công ty một cách an toàn.'"),
          q("I missed breakfast and lunch, so my ------- right now is to get something to eat.", ["prior", "priority", "prioritize", "priors"], "B", "Sau tính từ sở hữu my là danh từ. 'Tôi đã bỏ bữa sáng và bữa trưa, do đó ưu tiên số một của tôi bây giờ là đi mua gì đó để ăn.'"),
          q("The restaurant is due for an ------- by the Health Department next week.", ["inspection", "inspecting", "inspect", "inspected"], "A", "Sau mạo từ an là danh từ inspection. 'Nhà hàng sẽ đến hạn kiểm tra bởi Sở Y tế vào tuần tới.'"),
          q("Our success is based completely on the ------- of our products.", ["rely", "reliable", "reliant", "reliability"], "D", "Sau mạo từ the là danh từ. 'Sự thành công của chúng ta phụ thuộc hoàn toàn vào độ tin cậy của sản phẩm.'"),
          q("The low profits we've had over the last quarters are due to the bad -------.", ["economical", "economize", "economic", "economy"], "D", "Sau tính từ bad là danh từ. 'Lợi nhuận thấp mà chúng ta thu được trong các quý trước là bởi vì nền kinh tế khó khăn.'"),
          q("I'm calling to cancel the ------- with Dr. Lee this Friday afternoon.", ["appointed", "appoints", "appointment", "to appoint"], "C", "Sau mạo từ the là danh từ. 'Tôi gọi để hủy cuộc hẹn với bác sĩ Lee chiều thứ Sáu tuần này.'"),
          q("A recent survey about customer ------- has been very positive.", ["satisfy", "satisfactory", "satisfaction", "satisfied"], "C", "Sau giới từ about cần danh từ làm tân ngữ. Cụm customer satisfaction nghĩa là 'sự hài lòng của khách hàng'. 'Một khảo sát gần đây về sự hài lòng của khách hàng đã có kết quả khả quan.'"),
          q("Your ------- was really appreciated by the whole board of management.", ["encourage", "encouraged", "encouragement", "discourage"], "C", "Sau tính từ sở hữu là danh từ. 'Sự khích lệ của bạn rất được cảm kích bởi cả ban quản lý.'"),
        ],
      },
    ],
  },
  {
    slug: "danh-tu-so-it-so-nhieu",
    chapter: CHAPTER,
    code: "Word Form 2",
    title: "Phân biệt danh từ số ít, số nhiều và danh từ không đếm được",
    summary: "Chọn đúng dạng danh từ dựa vào động từ (khi làm chủ ngữ) hoặc mạo từ / từ chỉ số lượng (khi làm tân ngữ).",
    blocks: [
      {
        type: "examples",
        title: "Introduction",
        items: [
          { en: "1. Our ------- have always tried their best to catch up with the latest trends in the market.\n(A) creator  (B) create  (C) creating  (D) creators", vi: "Loại các phương án không phải danh từ (B, C). Còn A là danh từ số ít, D là danh từ số nhiều. Dựa vào động từ have cần danh từ số nhiều → D." },
          { en: "2. This conference has seen an increase in -------.\n(A) attendee  (B) attendance  (C) attend  (D) attentive", vi: "Loại C, D. A là danh từ đếm được số ít, B là danh từ không đếm được. Danh từ ở vị trí tân ngữ và phía trước chỗ trống không có mạo từ → B." },
        ],
      },
      {
        type: "text",
        body: "Bài học cung cấp các kỹ năng làm câu hỏi phân biệt danh từ số ít, số nhiều và danh từ không đếm được:\n• Các danh từ đếm được và không đếm được phổ biến trong đề thi TOEIC\n• Cách lựa chọn danh từ ở vị trí **chủ ngữ**\n• Cách lựa chọn danh từ ở vị trí **tân ngữ**.",
      },
      {
        type: "list",
        title: "Learning point 1: Chỗ trống cần danh từ làm chủ ngữ",
        items: [
          "Nếu động từ chia ở số nhiều (are, were, have, động từ nguyên thể) → chọn danh từ số nhiều.",
          "Nếu động từ chia ở số ít (is, was, has, động từ thêm -s/-es) → chọn danh từ số ít hoặc danh từ không đếm được.",
        ],
      },
      {
        type: "table",
        title: "Các danh từ đếm được và không đếm được phổ biến trong đề thi TOEIC",
        headers: ["Danh từ không đếm được", "Danh từ đếm được", "Nghĩa"],
        rows: [
          ["advertising", "advertisement", "quảng cáo"],
          ["seating", "seat", "chỗ ngồi"],
          ["advice", "suggestion, recommendation", "lời khuyên, gợi ý"],
          ["feedback", "review, comment", "phản hồi"],
          ["baggage, luggage", "suitcase", "hành lý"],
          ["correspondence, mail", "letter", "thư tín"],
          ["merchandise", "product, item", "hàng hóa"],
          ["machinery", "machine", "máy móc"],
          ["research", "study, survey", "nghiên cứu"],
          ["planning", "plan", "kế hoạch"],
          ["management", "manager", "quản lý"],
          ["funding", "fund", "quỹ, vốn đầu tư"],
          ["information", "—", "thông tin"],
          ["equipment", "—", "thiết bị"],
          ["furniture", "—", "nội thất"],
          ["permission", "—", "sự cho phép"],
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Chỗ trống cần danh từ làm tân ngữ → dựa vào mạo từ hoặc từ chỉ số lượng",
        items: [
          "Sau **a/an** cần điền danh từ đếm được số ít (a funder, an approach).",
          "Sau **zero article (Ø)** — trước cụm danh từ không có mạo từ — cần điền danh từ đếm được số nhiều (request Ø shoppers) hoặc danh từ không đếm được (carry out Ø further research).",
          "Sau **từ chỉ số lượng** cần điền loại danh từ tương ứng với từ đó.",
        ],
      },
      {
        type: "table",
        title: "Từ chỉ số lượng tương ứng với loại danh từ",
        headers: ["Nghĩa", "Danh từ đếm được", "Danh từ không đếm được"],
        rows: [
          ["tất cả", "all", "all"],
          ["hầu hết", "most", "most"],
          ["nhiều", "a lot of, lots of, plenty of; a (large) number of, the number of, a variety of; many", "a lot of, lots of, plenty of; an amount of, a great deal of; much"],
          ["một vài", "some, any, several", "some, any"],
          ["một ít", "a few, few", "a little, little"],
          ["hai", "a pair of, both", "—"],
          ["mỗi, mọi, một", "every, each, one (+ danh từ số ít)", "—"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["bulletin board", "n", "bảng thông báo"],
          ["disputes", "n", "sự tranh cãi, cuộc tranh luận"],
          ["job opening", "n", "vị trí cần tuyển"],
          ["job opportunity", "n", "cơ hội việc làm"],
          ["manual", "n", "sách hướng dẫn"],
          ["productivity", "n", "năng suất"],
          ["progress", "n", "tiến trình, tiến độ"],
          ["promotion", "n", "sự thăng chức"],
          ["schedule", "n", "lịch trình"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 1",
        kind: "practice",
        questions: [
          q("Technological [-------] are giving us a lot of advantages.", ["advances", "advancement"], "A", "Danh từ ở chỗ trống làm chủ ngữ. Dựa vào động từ số nhiều are → danh từ số nhiều advances."),
          q("Mr. Suzuki's [-------] has complimented her on her excellent performance.", ["supervisor", "managers"], "A", "Danh từ làm chủ ngữ. Dựa vào động từ số ít has complimented → danh từ số ít supervisor."),
          q("Your [-------] is really appreciated.", ["suggestions", "advice"], "B", "Danh từ làm chủ ngữ. Dựa vào động từ số ít is → danh từ không đếm được advice."),
        ],
      },
      {
        title: "Check-up 1",
        kind: "practice",
        questions: [
          q("Careful ------- helps to minimize the possibility of failure.", ["planners", "planning", "plans", "planned"], "B", "Danh từ làm chủ ngữ, dựa vào động từ số ít helps → danh từ không đếm được planning (A và C là danh từ đếm được số nhiều). 'Lập kế hoạch cẩn thận sẽ giảm khả năng thất bại.'"),
          q("The slow ------- on this project has been a cause for concern.", ["progress", "progressive", "progresses", "progressed"], "A", "Danh từ làm chủ ngữ, dựa vào động từ số ít has been → progress (C là danh từ số nhiều). 'Tiến độ chậm của dự án là một mối lo ngại.'"),
          q("The ------- were settled on Saturday.", ["disputes", "to dispute", "disputable", "disputant"], "A", "Danh từ làm chủ ngữ, dựa vào động từ số nhiều were → disputes. 'Những cuộc tranh cãi đã được giải quyết vào thứ Bảy.'"),
          q("More ------- need to be carried out for successful launching of the new product.", ["studies", "studying", "student", "studied"], "A", "Danh từ làm chủ ngữ, dựa vào động từ số nhiều need → danh từ số nhiều studies. 'Cần tiến hành nhiều nghiên cứu hơn để việc tung ra sản phẩm mới được thành công.'"),
          q("Job ------- are being offered at Springfield Corporation.", ["opportunity", "openings", "open", "opportune"], "B", "Danh từ làm chủ ngữ, dựa vào động từ số nhiều are → openings (A là danh từ số ít). 'Những vị trí việc làm đang được tuyển tại tập đoàn Springfield.'"),
        ],
      },
      {
        title: "Diagnostic test 2",
        kind: "practice",
        questions: [
          q("Remember to request [-------] not to bring food or beverages into the store.", ["shopper", "shoppers"], "B", "Danh từ làm tân ngữ sau động từ request. Phía trước không có mạo từ → danh từ số nhiều shoppers (shopper là danh từ đếm được số ít)."),
          q("We need to carry out further [-------] to produce this commercially.", ["research", "study"], "A", "Danh từ làm tân ngữ sau carry out. Trước cụm further … không có mạo từ → danh từ không đếm được research (study là danh từ đếm được số ít)."),
          q("Make sure that you pay attention to every [-------].", ["students", "student"], "B", "Sau every → danh từ số ít student."),
          q("We need to find a new [-------] for the program.", ["funder", "funding"], "A", "Phía trước là mạo từ a → danh từ đếm được số ít funder (funding là danh từ không đếm được)."),
          q("The aim of the conference is to figure out an [-------] to the target market.", ["approach", "approaches"], "A", "Phía trước là mạo từ an → danh từ đếm được số ít approach."),
        ],
      },
      {
        title: "Check-up 2",
        kind: "practice",
        questions: [
          q("Thanks to careful -------, the scenes filmed on the city streets did not interrupt the flow of traffic.", ["plan", "planner", "planning", "planned"], "C", "Trước cụm careful ------- không có mạo từ → danh từ số nhiều hoặc không đếm được. plan, planner là danh từ đếm được số ít; planned không phải danh từ → planning. 'Nhờ lập kế hoạch cẩn thận mà những cảnh quay đường phố không hề cản trở giao thông.'"),
          q("The company offers a number of job -------.", ["vacancy", "openings", "open", "opportunity"], "B", "Sau a number of là danh từ số nhiều. 'Công ty đang có nhiều vị trí cần tuyển.'"),
          q("This is a good solution for middle income ------- to save their money.", ["earner", "earn", "earners", "earning"], "C", "Trước cụm middle income ------- không có mạo từ → danh từ số nhiều earners. 'Đây là giải pháp tiết kiệm tiền tốt dành cho những người có thu nhập trung bình.'"),
          q("The cashiers have asked ------- not to cut in line and patiently wait for their turn to check out.", ["shopping", "shoppers", "shopper", "shop"], "B", "Sau động từ asked là danh từ tân ngữ, không có mạo từ → danh từ số nhiều shoppers."),
          q("This manual should provide new ------- with some advice on how to take good pictures.", ["photograph", "photographic", "photographers", "photography"], "C", "Sau động từ provide cần danh từ làm tân ngữ, không có mạo từ → danh từ số nhiều photographers. 'Bản hướng dẫn này sẽ cung cấp cho những nhiếp ảnh gia mới lời khuyên chụp ảnh đẹp.'"),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Workers in the Accounting Department have a ------- to ensure that the company's funds are not wasted.", ["responsibly", "responsible", "responsibilities", "responsibility"], "D", "Sau mạo từ a là danh từ số ít. 'Nhân viên phòng kế toán có trách nhiệm đảm bảo quỹ của công ty không bị lãng phí.'"),
          q("------- have been sent to all of the individuals who requested them.", ["Invite", "Inviting", "Invitation", "Invitations"], "D", "Danh từ ở vị trí chủ ngữ. Dựa vào động từ số nhiều have been → Invitations. 'Thiệp mời đã được gửi đến tất cả những cá nhân có nhu cầu.'"),
          q("Please submit all project proposals for ------- no later than the third Monday of the month.", ["fund", "funded", "fundable", "funding"], "D", "Sau giới từ for là danh từ tân ngữ; không có mạo từ → danh từ không đếm được funding. 'Hãy nộp tất cả đề xuất xin tài trợ trước thứ Hai tuần thứ ba của tháng.'"),
          q("Dortel negotiated with several book ------- last year for his new travel memoir to be published.", ["publishing", "publication", "publishers", "publish"], "C", "Sau several là danh từ số nhiều. 'Dortel đã đàm phán với vài nhà xuất bản sách để xuất bản ký sự du lịch của anh ấy vào năm ngoái.'"),
          q("The ------- is now available on the company bulletin board.", ["scheduled", "schedule", "schedules", "schedulers"], "B", "Danh từ làm chủ ngữ; động từ số ít is → schedule. 'Lịch trình đã có trên bảng thông tin của công ty.'"),
          q("The newly-installed system requires that every ------- should have a savings account.", ["user", "useful", "uses", "using"], "A", "Sau every là danh từ số ít. 'Hệ thống mới cài đặt yêu cầu người truy cập phải có một tài khoản tiết kiệm.'"),
          q("We will introduce an innovative compensation plan to increase -------.", ["product", "produce", "productivity", "producer"], "C", "Sau động từ increase là danh từ tân ngữ; không có mạo từ → danh từ không đếm được productivity. Increase productivity: tăng năng suất."),
          q("Come and meet the best minds in technology; our ------- create more products than any other software company.", ["development", "developers", "develop", "developing"], "B", "Danh từ làm chủ ngữ; dựa vào động từ số nhiều create → developers. 'Những nhà phát triển phần mềm của chúng tôi tạo ra nhiều sản phẩm hơn bất kỳ công ty nào khác.'"),
          q("What was the ------- of inviting the media to last week's meeting?", ["aim", "aiming", "aims", "aimed"], "A", "Danh từ làm chủ ngữ; động từ số ít was → aim. 'Mục đích của việc mời truyền thông đến cuộc họp tuần trước là gì?'"),
          q("The new sport complex will accommodate many ------- including a fitness center and a spa.", ["facilities", "facilitate", "facility", "facilitation"], "A", "Sau many là danh từ số nhiều. 'Khu liên hợp thể thao mới bao gồm nhiều cơ sở như trung tâm thể hình và spa.'"),
          q("Leather ------- have been very trendy in the last two years.", ["clothes", "cloth", "accessory", "accessorize"], "A", "Danh từ làm chủ ngữ; động từ số nhiều have → danh từ số nhiều clothes."),
          q("We're welcoming ------- regarding our new proposal.", ["ideas", "idealize", "idea", "to idealize"], "A", "Sau động từ welcoming là danh từ tân ngữ; không có mạo từ → danh từ số nhiều ideas. 'Chúng tôi đang chào đón ý tưởng về dự án mới.'"),
          q("Our magazine always welcomes ------- from readers on any subject.", ["letter", "correspondence", "correspond", "lettering"], "B", "Sau động từ welcomes là tân ngữ; không có mạo từ → danh từ không đếm được correspondence. 'Tạp chí luôn chào đón thư phản hồi từ độc giả về bất kỳ chủ đề nào.'"),
          q("His ------- has come as no surprise to anyone in the company.", ["promotion", "promoted", "promoters", "promotional"], "A", "Danh từ làm chủ ngữ; động từ số ít has → promotion. 'Việc anh ấy được thăng chức không gây ngạc nhiên với ai trong công ty.'"),
          q("Residents' ------- to the construction of a new museum was so strong that the city had to postpone it.", ["objects", "objective", "objection", "objected"], "C", "Danh từ làm chủ ngữ; động từ số ít was → danh từ không đếm được objection. 'Sự phản đối của người dân về việc xây bảo tàng mới mạnh mẽ đến mức thành phố phải trì hoãn.'"),
          q("The manager will need a ------- of the press conference by the end of the day.", ["summarize", "summary", "summaries", "summarizing"], "B", "Sau mạo từ a là danh từ số ít. 'Quản lý cần một bản tóm tắt về cuộc họp báo vào cuối ngày.'"),
          q("As a new business, we always appreciate useful ------- on financial and operational issues.", ["advice", "advisable", "advices", "advise"], "A", "Advice là danh từ không đếm được nên không có dạng số nhiều advices."),
          q("We've received a large number of ------- for the position of customer service representative.", ["applicant", "applicable", "applications", "applicability"], "C", "Sau a number of là danh từ số nhiều. 'Chúng tôi vừa nhận được rất nhiều đơn ứng tuyển vị trí chăm sóc khách hàng.'"),
          q("Is it necessary that every ------- is insured?", ["package", "packaging", "packages", "packs"], "A", "Sau every là danh từ số ít. 'Có cần thiết phải bảo hiểm tất cả các gói hàng không?'"),
          q("When providing shipping and handling service, we should be aware that each ------- has a different requirement.", ["manufacturer", "manufacturing", "manufactured", "manufactures"], "A", "Sau each là danh từ số ít. 'Khi cung cấp dịch vụ vận chuyển, chúng tôi hiểu rằng mỗi nhà sản xuất có một yêu cầu khác nhau.'"),
        ],
      },
    ],
  },
  {
    slug: "danh-tu-chi-nguoi",
    chapter: CHAPTER,
    code: "Word Choice 1",
    title: "Phân biệt danh từ chỉ người/nghề nghiệp và danh từ chung",
    summary: "Phân biệt manufacturer – manufacture, subscriber – subscription… bằng cách dịch nghĩa hoặc dựa vào từ xung quanh.",
    blocks: [
      {
        type: "examples",
        title: "Introduction",
        items: [
          {
            en: "Even though the food was not as delicious as expected, the ------- was really friendly and courteous.\n(A) service  (B) server  (C) serve  (D) served",
            vi: "Sau khi loại các phương án không phải danh từ (C, D), còn A là danh từ chung (dịch vụ), B là danh từ chỉ người (người phục vụ). Dựa vào nghĩa 'Mặc dù đồ ăn không ngon như mong đợi nhưng ------- rất thân thiện và lịch sự' → B. Nếu không dịch được cả câu, có thể dựa vào từ friendly để suy ra đáp án là danh từ chỉ người.",
          },
        ],
      },
      {
        type: "text",
        body: "Bài học cung cấp kỹ năng làm câu hỏi phân biệt danh từ chỉ người/nghề nghiệp và danh từ chung:\n• các hậu tố của danh từ chỉ người/nghề nghiệp\n• các dấu hiệu nhận biết trong câu để lựa chọn danh từ chỉ người/nghề nghiệp hay danh từ chung/trừu tượng.",
      },
      {
        type: "qa",
        title: "Diagnostic test 1",
        instructions: "Gạch chân các danh từ chỉ người/nghề nghiệp trong các cặp danh từ dưới đây.",
        items: [
          { q: "subscription – subscriber", a: "**subscriber**: người đặt báo, người đăng ký" },
          { q: "manufacturer – manufacture", a: "**manufacturer**: nhà sản xuất" },
          { q: "electricity – electrician", a: "**electrician**: thợ điện" },
          { q: "investment – investor", a: "**investor**: nhà đầu tư" },
          { q: "interview – interviewee", a: "**interviewee**: người được phỏng vấn" },
          { q: "application – applicant", a: "**applicant**: ứng viên, người xin việc" },
          { q: "distributor – distribution", a: "**distributor**: nhà phân phối" },
          { q: "delegate – delegation", a: "**delegate**: đại diện" },
          { q: "representation – representative", a: "**representative**: người đại diện" },
          { q: "advice – advisor", a: "**advisor**: người cố vấn" },
        ],
      },
      {
        type: "table",
        title: "Learning point 1: Những danh từ chỉ người/nghề nghiệp thường kết thúc bằng các hậu tố",
        headers: ["Hậu tố", "Ví dụ"],
        rows: [
          ["-er", "worker, manager, subscriber"],
          ["-ist", "receptionist, therapist"],
          ["-ian", "physician, electrician"],
          ["-or", "actor, contractor, investor"],
          ["-ess", "actress, waitress"],
          ["-ee", "interviewee, employee, attendee"],
          ["-ant, -ent", "applicant, recipient, client"],
        ],
      },
      {
        type: "list",
        title: "Lưu ý",
        items: [
          "**Lưu ý 1:** Một số danh từ chỉ người có hậu tố đặc biệt: -ate: candidate (người xin việc, ứng viên), delegate (đại diện); -ive: representative (người đại diện).",
          "**Lưu ý 2:** Các hậu tố mang ý nghĩa đặc biệt: -ee mang ý bị động (employee: người được thuê hay người lao động; interviewee: người được phỏng vấn); -ess mang giới tính nữ (actress: diễn viên nữ; waitress: bồi bàn nữ).",
        ],
      },
      {
        type: "qa",
        title: "Check-up 1",
        instructions: "Gạch chân dưới các danh từ chỉ người/nghề nghiệp.",
        items: [
          { q: "negotiator – negotiation", a: "**negotiator**: người đàm phán" },
          { q: "respondent – response", a: "**respondent**: người trả lời" },
          { q: "delegation – delegate", a: "**delegate**: người đại diện" },
          { q: "attendee – attendance", a: "**attendee**: người tham dự" },
          { q: "consultation – consultant", a: "**consultant**: nhân viên tư vấn" },
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Khi câu hỏi có hai phương án là danh từ chỉ người/nghề nghiệp và danh từ chung/trừu tượng",
        items: [
          "Dịch nghĩa của câu và chọn đáp án phù hợp.",
          "Nếu không thể dịch nghĩa toàn bộ câu, có thể dựa vào tính từ, động từ đứng trước hoặc sau chỗ trống (server is friendly, cancel the subscription, communicate to investors, the advisor will tell).",
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["attribute A to B", "v", "cho rằng A là bởi vì B"],
          ["supplier", "n", "nhà cung cấp"],
          ["visitor's pass", "n", "thẻ dành cho khách đến thăm"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 2",
        kind: "practice",
        questions: [
          q("Please contact our Customer Service Department to cancel your [-------].", ["subscriber", "subscription"], "B", "Dịch nghĩa 'Hãy liên lạc với phòng chăm sóc khách hàng để hủy bỏ …' thì subscription (sự đặt báo, đăng ký) phù hợp; subscriber (người đặt báo) không phù hợp. Dựa vào động từ cancel (hủy bỏ) cũng suy ra danh từ chỉ người không phù hợp."),
          q("Janet's academic [-------] will tell her what to do with her assignment.", ["advisor", "advice"], "A", "'… chuyên môn của Janet sẽ gợi ý cho cô ấy phải làm gì với bài tập' → advisor (người cố vấn). Dựa vào động từ tell (nói) cũng suy ra danh từ chỉ người."),
          q("Communicating that idea to potential [-------] and customers is important.", ["investment", "investors"], "B", "Dựa vào cụm and customers phía sau → chỗ trống cũng là danh từ chỉ người (and nối hai danh từ cùng loại). Hoặc dựa vào communicate to (nói với ai) để suy ra danh từ chỉ người."),
        ],
      },
      {
        title: "Check-up 2",
        kind: "practice",
        questions: [
          q("Feel free to contact the ------- of this product should you have any problems operating it.", ["manufacturing", "manufacturer", "manufactured", "manufacture"], "B", "Động từ contact là 'liên hệ, nói chuyện' nên phía sau cần danh từ chỉ người. 'Đừng ngần ngại gọi cho nhà sản xuất nếu bạn gặp vấn đề khi sử dụng.'"),
          q("Renovating the hospital ------- can cost much more than we expected.", ["build", "builder", "building", "to build"], "C", "Renovate là 'sửa chữa, nâng cấp' nên phía sau không phải danh từ chỉ người. 'Việc nâng cấp tòa nhà bệnh viện có thể tốn nhiều hơn dự định.'"),
          q("Mr. Thompson's company is the main ------- of dairy products in the tri-state region.", ["distribution", "distributing", "distributor", "distribute"], "C", "Dịch nghĩa 'Công ty của ông Thompson là nhà cung cấp các sản phẩm bơ sữa chính của vùng' → distributor."),
          q("We guarantee ------- of your packages anywhere in the country within twenty-four hours or less.", ["deliverable", "deliverer", "deliver", "delivery"], "D", "Sau động từ guarantee (đảm bảo) là danh từ chung. 'Chúng tôi đảm bảo việc giao hàng tới mọi nơi trong nước trong vòng 24 tiếng hoặc ít hơn.'"),
          q("Your ------- to the company will be rewarded with a cash bonus.", ["serve", "service", "server", "serving"], "B", "Dịch nghĩa 'Sự cống hiến của bạn ở công ty sẽ được thưởng tiền mặt' → service."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("------- to our magazine this June will receive a 20% discount.", ["Subscribing", "Subscribe", "Subscription", "Subscribers"], "D", "Dựa vào động từ receive (nhận được) → danh từ chỉ người. 'Những người đặt báo vào tháng Sáu này sẽ được giảm giá 20%.'"),
          q("The key to success in an ------- is to remain confident and calm.", ["interviewer", "interview", "interviewing", "interviewed"], "B", "Dựa vào cụm success in (thành công về cái gì) → danh từ chung. 'Yếu tố quyết định thành công của cuộc phỏng vấn là tự tin và bình tĩnh.'"),
          q("The ------- from Westmore Corporation will speak at the conference this weekend.", ["delegates", "delegative", "delegation", "delegating"], "A", "Dựa vào động từ speak phía sau → danh từ chỉ người. 'Đại diện đến từ tập đoàn Westmore sẽ phát biểu ở hội nghị cuối tuần này.'"),
          q("Please speak to our customer service ------- if you have any questions.", ["representation", "represent", "representing", "representative"], "D", "Dựa vào động từ speak phía trước → danh từ chỉ người. 'Hãy nói chuyện với nhân viên chăm sóc khách hàng nếu bạn có bất kỳ câu hỏi nào.'"),
          q("The number of ------- reached 50,000 in the Music Festival last night.", ["attentive", "attendance", "attendees", "attend"], "C", "'Số lượng người tham dự lễ hội âm nhạc đêm qua đạt mốc 50.000.' (The number of + danh từ số nhiều chỉ người.)"),
          q("We're expecting the telephone -------. Until then, we cannot use our phones at all.", ["repair", "repairs", "repairing", "repairperson"], "D", "'Chúng tôi đang chờ người sửa điện thoại. Cho tới lúc đó, chúng tôi không thể dùng điện thoại.'"),
          q("The ------- was a big success because everyone enjoyed the party very much.", ["reception", "receptive", "receive", "receptionist"], "A", "Dựa vào từ success phía sau → danh từ chung. 'Buổi chiêu đãi đã thành công rực rỡ vì mọi người đều thích bữa tiệc.'"),
          q("They are negotiating the terms for the last time before signing the -------.", ["contractive", "contract", "contractor", "contracted"], "B", "Dựa vào động từ sign (ký kết) → contract. 'Họ đang đàm phán các điều khoản lần cuối trước khi ký hợp đồng.'"),
          q("The survey among our ------- revealed that they were satisfied with the salary and benefits the company offers.", ["employ", "unemployed", "employees", "employment"], "C", "'Cuộc khảo sát với các nhân viên cho thấy họ hài lòng với lương và phúc lợi của công ty.'"),
          q("The new director's ------- has proved to be effective in making this year more profitable than ever.", ["manager", "management", "manageable", "manage"], "B", "'Sự quản lý của giám đốc mới tỏ ra rất hữu ích trong việc tăng lợi nhuận năm nay.'"),
          q("We've decided to choose Westwood Company as our ------- of construction materials.", ["supply", "supplier", "supplying", "to supply"], "B", "'Chúng tôi quyết định chọn Westwood làm nhà cung cấp vật liệu xây dựng.'"),
          q("When entering the -------, please remember to present your visitor's pass.", ["building", "build", "built", "builder"], "A", "Dựa vào động từ enter (đi vào đâu) → danh từ chung. 'Khi đi vào tòa nhà, nhớ xuất trình thẻ dành cho khách.'"),
          q("The majority of the contract ------- takes place during the year.", ["negotiate", "negotiator", "negotiable", "negotiations"], "D", "Dựa vào động từ take place (diễn ra) → danh từ chung. 'Hầu hết các cuộc đàm phán hợp đồng diễn ra trong năm nay.'"),
          q("------- don't need to write their names on the survey sheet.", ["Responses", "Respondents", "Respond", "Responding"], "B", "Dựa vào write their names (viết tên mình) → danh từ chỉ người. 'Những người trả lời khảo sát không cần viết tên vào đó.'"),
          q("She attributed her success to the ------- she received from her parents during her university years.", ["supportive", "support", "supporter", "supported"], "B", "Dựa vào động từ receive (nhận được) → danh từ chung. 'Cô ấy cho rằng thành công của mình là nhờ sự giúp đỡ cô nhận được trong những năm đại học.'"),
          q("If you don't understand the instructions, feel free to ask one of our -------, who are here to help.", ["representatives", "representativeness", "represent", "to represent"], "A", "Dựa vào động từ ask (hỏi ai đó) → danh từ chỉ người. 'Nếu bạn không hiểu chỉ dẫn, hãy hỏi một trong những nhân viên của chúng tôi, những người luôn ở đây để giúp đỡ.'"),
          q("In this difficult economic situation, it is advisable to speak with a financial -------.", ["consultation", "consult", "consulting", "consultant"], "D", "Dựa vào động từ speak → danh từ chỉ người. 'Trong hoàn cảnh kinh tế khó khăn, bạn nên nói chuyện với một nhân viên tư vấn tài chính.'"),
          q("It was a successful ------- which received reviews in several prestigious magazines and newspapers.", ["perform", "performer", "performance", "performing"], "C", "'Đó là một buổi biểu diễn thành công, nhận được đánh giá tốt trên các báo và tạp chí nổi tiếng.'"),
          q("By offering a discount on enrolment fees, we can attract more ------- to our cycling program this year.", ["participate", "participation", "participants", "participated"], "C", "'Nhờ giảm phí đăng ký, chúng tôi thu hút được nhiều người tham gia chương trình đạp xe năm nay.'"),
          q("Press 1 to speak with our telephone ------- regarding your credit card mischarge problem.", ["operation", "operative", "operate", "operator"], "D", "'Hãy bấm phím 1 để nói chuyện với nhân viên trực điện thoại về vấn đề tính nhầm thẻ tín dụng.'"),
        ],
      },
    ],
  },
  {
    slug: "nghia-cua-danh-tu",
    chapter: CHAPTER,
    code: "Word Choice 2",
    title: "Câu hỏi dịch nghĩa của danh từ",
    summary: "Các cụm danh từ cố định, danh từ kết hợp với động từ và nhóm danh từ dễ nhầm trong đề thi TOEIC.",
    blocks: [
      {
        type: "text",
        body: "Khi làm câu hỏi với bốn phương án cùng là danh từ (cùng loại và dạng thức), cần chú ý tới **động từ, tính từ và danh từ ở xung quanh chỗ trống** vì câu hỏi thường kiểm tra các cụm danh từ cố định hoặc cấu trúc kết hợp danh từ và động từ.",
      },
      {
        type: "table",
        title: "1. Các cụm danh từ",
        headers: ["Cụm từ", "Nghĩa"],
        rows: [
          ["an illegal practice", "việc làm trái phép"],
          ["confidential information", "thông tin bảo mật"],
          ["free of charge", "miễn phí"],
          ["potential customer", "khách hàng tiềm năng"],
          ["near / foreseeable future", "tương lai gần"],
          ["affordable / reasonable price / rate", "giá cả hợp lý"],
          ["safety precaution", "cảnh báo an toàn"],
          ["job opening", "vị trí còn trống"],
          ["performance evaluation / appraisal", "đánh giá năng lực"],
          ["shipping charge", "phí vận chuyển"],
          ["hotel reservation", "đặt trước khách sạn"],
          ["apartment complex", "khu liên hợp căn hộ"],
          ["further notice", "thông báo tiếp theo, thông báo sau"],
        ],
      },
      {
        type: "table",
        title: "2. Danh từ kết hợp với động từ",
        headers: ["Cụm từ", "Nghĩa"],
        rows: [
          ["take advantage of", "tận dụng, lợi dụng"],
          ["raise awareness of", "nâng cao hiểu biết về"],
          ["take measures to V", "sử dụng biện pháp"],
          ["increase productivity", "tăng năng suất"],
          ["handle complaints", "giải quyết khiếu nại"],
          ["reduce expenses", "giảm chi phí"],
          ["submit an application form", "nộp đơn"],
          ["present a visitor's pass", "xuất trình giấy tờ / vé vào cửa"],
        ],
      },
      {
        type: "table",
        title: "3. Các danh từ khác",
        headers: ["Danh từ", "Nghĩa"],
        rows: [
          ["admission", "sự cho vào cửa"],
          ["subscription to a magazine", "đặt báo, tạp chí"],
          ["facility", "cơ sở hạ tầng (không dùng để ở)"],
          ["property", "nhà ở, bất động sản"],
          ["replacement", "hàng hóa thay thế, người thay thế"],
          ["refund", "hoàn tiền (khi mua hàng)"],
          ["return", "sự trả lại hàng"],
          ["receipt", "biên lai, hóa đơn"],
          ["reimbursement", "hoàn tiền (số tiền đã tiêu trước đó)"],
          ["compensation", "tiền bồi thường"],
          ["operation", "hoạt động (của công ty), vận hành (máy móc)"],
          ["regulation", "quy định, luật lệ"],
          ["access to", "có quyền sử dụng / truy cập"],
          ["agency", "= company"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["access to", "n", "tiếp cận, sử dụng, sự dễ dàng"],
          ["affordable rate", "n", "giá cả hợp lý"],
          ["defective product", "n", "hàng hóa lỗi"],
          ["operation", "n", "sự vận hành"],
        ],
      },
    ],
    exercises: [
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("To apply for the position, please submit the ------- with necessary documents to the HR department.", ["appliance", "application", "receipt", "boarding pass"], "B", "Submit the application: nộp đơn. 'Để ứng tuyển vị trí này, hãy nộp đơn cùng giấy tờ cần thiết cho phòng nhân sự.'"),
          q("Our current subscription rate will be effective until further -------.", ["formation", "notice", "memorandum", "quarter"], "B", "Until further notice: cho tới khi có thông báo tiếp theo. 'Giá đặt báo hiện tại vẫn có hiệu lực cho tới khi có thông báo tiếp theo.'"),
          q("Customers may request a refund or a ------- only if the merchandise is still unused.", ["replacement", "complaint", "receipt", "promotion"], "A", "'Khách hàng có thể yêu cầu hoàn tiền hoặc đổi hàng mới chỉ khi hàng hóa chưa được sử dụng.'"),
          q("Clearwater features a recreation ------- that includes a playground, a fishing pier and a camping area.", ["complication", "complexity", "complex", "complexion"], "C", "'Clearwater có một khu liên hợp giải trí bao gồm sân chơi, bến câu cá và khu cắm trại.'"),
          q("Pressure to reduce costs and increase profits has led managers to search for creative ways to improve staff -------.", ["productivity", "production", "manufacture", "profusion"], "A", "Improve/increase staff productivity: tăng năng suất lao động."),
          q("A study found that government ------- on building permits have led to better city planning.", ["regulations", "perceptions", "imitations", "distributions"], "A", "'Một nghiên cứu chỉ ra rằng quy định của chính phủ về việc cấp phép xây dựng đã đem lại quy hoạch đô thị tốt hơn.'"),
          q("With the ------- of Internet-based recording software, the traditional music industry faces a challenge.", ["culmination", "attitude", "development", "vantage"], "C", "'Với sự phát triển của phần mềm ghi âm sử dụng Internet, nền âm nhạc truyền thống đang gặp phải thử thách.'"),
          q("Maintaining an emergency account will ensure that you have ------- to cash when you need it.", ["contact", "access", "entry", "response"], "B", "'Duy trì tài khoản dự phòng sẽ đảm bảo bạn luôn có tiền để sử dụng khi cần.'"),
          q("In his current role in new product development, Mr. Kumar aims for ------- in new sports equipment.", ["innovation", "implication", "consideration", "intention"], "A", "'Với vai trò phát triển sản phẩm mới hiện tại, ông Kumar hướng tới sự đổi mới cho thiết bị thể thao.'"),
          q("For a brochure explaining the city's ------- to encourage recycling, please contact the secretary.", ["character", "program", "definition", "description"], "B", "'Để có tờ rơi về chương trình khuyến khích tái chế của thành phố, hãy liên hệ người thư ký.'"),
          q("Current job ------- at Elite Insurance Company have been posted on the internal website.", ["openings", "chances", "positions", "opportunity"], "A", "Job openings: những vị trí cần tuyển. 'Những vị trí cần tuyển hiện tại ở Elite Insurance đã được đăng lên trang web nội bộ.'"),
          q("Ms. Kim was the manager of an employment ------- in Seoul for five years.", ["collection", "agency", "destination", "departure"], "B", "Employment agency: công ty tuyển dụng, công ty việc làm."),
          q("The customer service department is handling numerous ------- from customers about the defective headlight bulbs.", ["referrals", "complaints", "repairs", "compensation"], "B", "Handle complaints: xử lý khiếu nại, phàn nàn."),
          q("To schedule ------- for your washing machine, please contact the customer service department.", ["processes", "actions", "developments", "repairs"], "D", "'Để sắp xếp lịch sửa chữa máy giặt, hãy liên hệ phòng chăm sóc khách hàng.'"),
          q("A 15 percent increase in staff ------- at our corporation is largely due to a recent investment in 25 new packaging machines.", ["advance", "frequency", "analysis", "productivity"], "D", "'Năng suất lao động tăng 15% chủ yếu là nhờ khoản đầu tư gần đây vào 25 máy đóng gói mới.'"),
          q("This guest house offers fine accommodations at an affordable -------.", ["income", "satisfaction", "worth", "rate"], "D", "Affordable rate: giá cả hợp lý."),
          q("The Kiruna Corporation has announced the ------- of its long-serving senior vice president.", ["facility", "retirement", "repetition", "competition"], "B", "'Tập đoàn Kiruna tuyên bố phó chủ tịch lâu năm đã nghỉ hưu.'"),
          q("According to the report, the ------- of the six new machines all reach full capacity.", ["operation", "omission", "obsession", "obligation"], "A", "'Theo báo cáo, sáu chiếc máy mới đều vận hành đạt công suất tối đa.'"),
          q("Over the years, businesses have developed and tested various methods to evaluate employee -------.", ["performance", "percolation", "production", "perception"], "A", "Performance evaluation: đánh giá năng lực."),
          q("The commuter train will provide convenient ------- to the central shopping district.", ["access", "effect", "advance", "position"], "A", "'Tàu cho người đi làm sẽ giúp việc di chuyển vào trung tâm mua sắm trở nên dễ dàng.'"),
        ],
      },
    ],
  },
  {
    slug: "danh-tu-review-test",
    chapter: CHAPTER,
    code: "Review Test",
    title: "Nouns — Review Test",
    summary: "Bài kiểm tra tổng hợp 30 câu về danh từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["concern (about)", "n", "mối lo ngại, quan tâm"],
          ["meet strict requirements", "v", "đáp ứng yêu cầu"],
          ["opposition (to)", "n", "sự phản đối"],
          ["seating capacity", "n", "số lượng chỗ ngồi"],
          ["speaker", "n", "người phát biểu, thuyết trình"],
        ],
      },
    ],
    exercises: [
      {
        title: "Nouns — Review Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("------- about the actual cost of the project have delayed the plans for expanding the arena.", ["Additions", "Manner", "Materials", "Concerns"], "D", "Câu hỏi về nghĩa của danh từ. Concern about: mối lo ngại về điều gì. 'Những mối lo ngại về chi phí thực sự của dự án khiến kế hoạch mở rộng bị trì hoãn.'"),
          q("Acrosa Design Ltd.'s printing ------- fit the individual client's requirement.", ["to service", "service", "serviced", "services"], "D", "Danh từ làm chủ ngữ; dựa vào động từ số nhiều fit → danh từ số nhiều services."),
          q("Major industries in this district include food processing and aircraft -------.", ["manufacturer", "manufactures", "manufactured", "manufacture"], "D", "And luôn nối hai từ có ý nghĩa và hình thức tương đương. Food processing là 'chế biến thực phẩm' nên phía sau cần danh từ tương ứng manufacture (sự sản xuất)."),
          q("Ms. Yasuda's ------- in managing difficult projects has earned her respect from colleagues.", ["succeed", "success", "succeeds", "successful"], "B", "Sau sở hữu cách Ms. Yasuda's là danh từ success."),
          q("The main ------- of the new electric notepad is Internet use.", ["function", "functions", "functioned", "functional"], "A", "Danh từ làm chủ ngữ, dựa vào động từ is → function."),
          q("A variety of training ------- have been offered to provide our workers with necessary skills.", ["sessions", "lecture", "course", "provision"], "A", "Danh từ làm chủ ngữ, dựa vào động từ have → sessions."),
          q("To become a member of the country club, applicants have to meet strict -------.", ["requirement", "requires", "requiring", "requirements"], "D", "Danh từ làm tân ngữ sau động từ meet; không có mạo từ → danh từ số nhiều requirements."),
          q("The customer representative department is eager to be under new -------.", ["manage", "manager", "management", "manageable"], "C", "Danh từ làm tân ngữ sau giới từ under; không có mạo từ → danh từ không đếm được management."),
          q("The slow ------- on this project has been a cause of concern.", ["progress", "progressive", "progresses", "progressed"], "A", "Danh từ làm chủ ngữ; dựa vào động từ has been → progress."),
          q("Several of Canada's largest ------- have decided to decrease their mortgage rates.", ["banking", "bankers", "banks", "bank"], "C", "Sau several là danh từ số nhiều. 'Vài ngân hàng lớn ở Canada quyết định giảm lãi suất thế chấp.'"),
          q("The new theater has a seating ------- of 250.", ["aptitude", "capacity", "demonstration", "compliance"], "B", "Seating capacity: số lượng chỗ ngồi."),
          q("Mr. Song's ------- to the position of division manager was announced at this morning's staff meeting.", ["promoter", "promotion", "promote", "promoted"], "B", "'Sự thăng chức của ông Song lên trưởng phòng được thông báo tại cuộc họp sáng nay.'"),
          q("In order to guarantee your ------- at the hotel, please reply to this email within 24 hours.", ["reserve", "reserved", "reservation", "to reserve"], "C", "'Để đảm bảo việc đặt phòng ở khách sạn, hãy trả lời email này trong vòng 24 giờ.'"),
          q("The president of Paterson Industrial Solutions has signed a number of important ------- this month.", ["contract", "contracts", "contracted", "contractor"], "B", "Sau a number of là danh từ số nhiều."),
          q("Last week, local ------- were forced to find alternative routes due to fallen trees on Route 309.", ["commuters", "commutes", "to commute", "commuting"], "A", "Danh từ làm chủ ngữ; dựa vào động từ số nhiều were → commuters."),
          q("Mr. Yamamoto voiced his ------- for the hard work and dedication of the advertising department.", ["appreciate", "appreciation", "appreciated", "appreciating"], "B", "Sau tính từ sở hữu his là danh từ."),
          q("After receiving a lot of -------, our customer service has agreed to issue full refunds.", ["referrals", "repairs", "compensations", "complaints"], "D", "Tình huống câu thể hiện qua customer service, refunds → complaints."),
          q("Mr. Daniels has mentioned ------- to retire from the board since May.", ["planned", "plans", "planner", "plan"], "B", "Sau động từ mention là danh từ tân ngữ; không có mạo từ → danh từ số nhiều plans."),
          q("Any changes to your reservation should be made at least three days prior to your ------- at the hotel.", ["arrive", "arrival", "arrives", "arrived"], "B", "Sau tính từ sở hữu your là danh từ."),
          q("Many residents of Alston have expressed their ------- to the construction of a new warehouse complex near Fieldspring Lake.", ["oppose", "opposing", "opposed", "opposition"], "D", "Sau tính từ sở hữu their là danh từ."),
          q("A signed order form indicates the advertiser's ------- of all stated terms and conditions.", ["accept", "accepting", "accepted", "acceptance"], "D", "Sau sở hữu cách the advertiser's là danh từ."),
          q("Our firm offers excellent ------- as a way to retain its valued employees.", ["benefits", "benefiting", "benefitted", "beneficial"], "A", "Sau tính từ excellent là danh từ; danh từ ở vị trí tân ngữ, không có mạo từ → danh từ số nhiều."),
          q("Ms. Gupta requested ------- to use Berkeley Hall for the seminar series that will start next month.", ["authorize", "authorized", "authorization", "to authorize"], "C", "Sau động từ request là danh từ làm tân ngữ."),
          q("------- have been met with nothing but disappointment.", ["Expectations", "Experience", "Experiments", "Expressions"], "A", "Dựa vào từ but, danh từ ở chỗ trống trái nghĩa với disappointment. 'Kỳ vọng không nhận lại được gì ngoài sự thất vọng.'"),
          q("Naomi Takeda was not able to attend the meeting but Claire Marsters gave her a ------- of the discussion.", ["summarily", "summary", "summarizer", "summarized"], "B", "Sau mạo từ a là danh từ."),
          q("The city development ------- includes the addition of more cycling access to our streets.", ["plan", "projects", "procedures", "projectors"], "A", "Danh từ làm chủ ngữ; dựa vào động từ số ít includes → danh từ số ít plan."),
          q("The ------- of the new ambassador to Portugal was confirmed by the committee on Monday.", ["appoint", "appoints", "appointed", "appointment"], "D", "Sau mạo từ the là danh từ. 'Việc bổ nhiệm đại sứ mới tới Bồ Đào Nha được ủy ban xác nhận vào thứ Hai.'"),
          q("We have invited Dr. Zhu to be the guest ------- for the seminar on workplace safety.", ["speak", "speaks", "speaker", "speakers"], "C", "Dựa vào cụm Dr. Zhu to be the guest … → danh từ chỉ người số ít speaker."),
          q("You should call to confirm your flight 48 hours before -------.", ["depart", "departed", "departure", "to depart"], "C", "Sau giới từ before là danh từ departure."),
          q("Half of our research projects depend on outside -------.", ["fund", "funding", "funder", "funded"], "B", "Sau giới từ on là danh từ tân ngữ; không có mạo từ → danh từ không đếm được funding."),
        ],
      },
    ],
  },
  {
    slug: "cum-danh-tu",
    chapter: CHAPTER,
    code: "Chuyên đề",
    title: "Noun Phrase — Cụm danh từ",
    summary: "Cấu trúc cụm danh từ, cách tìm head noun trong cụm dài và các danh từ ghép hay gặp trong TOEIC.",
    blocks: [
      {
        type: "text",
        title: "Noun Phrase là gì?",
        body: "Cụm danh từ là một nhóm từ **hoạt động như một danh từ duy nhất** trong câu. Nó có **danh từ chính (head noun)** làm trung tâm, được bổ nghĩa bởi các từ đứng trước (pre-modifiers) và/hoặc đứng sau (post-modifiers).",
      },
      {
        type: "list",
        title: "Các cấu trúc cụm danh từ hay xuất hiện trong TOEIC",
        items: [
          "**Determiner + Noun:** a report, the manager, this product, our company, every employee → rất phổ biến khi chọn từ điền vào chỗ trống (Part 5).",
          "**Determiner + Adjective + Noun:** a new employee, the latest technology, an important meeting, high-quality products → thường kiểm tra vị trí tính từ và danh từ.",
          "**Noun + Noun (danh từ ghép):** account number (số tài khoản), business trip (chuyến công tác), customer service (dịch vụ khách hàng), construction site (công trường), job performance (hiệu suất công việc), application form (đơn xin việc), baggage allowance (hành lý miễn cước), sales target (mục tiêu doanh số), office equipment (thiết bị văn phòng), market research (nghiên cứu thị trường).",
          "**Determiner + Adjective(s) + Noun + Noun:** a high-performance computer, the new marketing strategy, an excellent customer service team.",
          "**Cụm danh từ có bổ nghĩa sau (post-modifiers):** the manager of the sales department, a report on market trends, the meeting held last week, products made in Japan → hay gặp trong Part 7.",
        ],
      },
      {
        type: "list",
        title: "Kỹ năng làm bài TOEIC với cụm danh từ",
        items: [
          "Nhìn trước và sau chỗ trống → xem có cần **danh từ** không (thường có a/an/the/my/our/this/that/some/many).",
          "Nếu thấy **giới từ** → thường là **danh từ chính** + giới từ + danh từ 2 (the manager of …, the result of …).",
          "Nhớ khoảng 100–150 cụm danh từ ghép phổ biến nhất (account number, business meeting, delivery date, price list…).",
          "Khi thấy danh từ đứng trước danh từ khác → 90% là **noun + noun** (không phải tính từ).",
          "Part 7: xác định được danh từ chính của cụm dài.",
        ],
      },
      {
        type: "list",
        title: "Cách nhận biết head noun trong cụm danh từ dài",
        items: [
          "**Bước 1 — Xác định ranh giới của cụm:** cụm thường bắt đầu bằng determiner (a/an/the, this/that, my/our, some/many, every/all, no) và kết thúc khi gặp động từ, giới từ chính hoặc dấu câu. VD: \"**The annual sales report from the marketing department** is ready.\"",
          "**Bước 2 — Loại bỏ pre-modifiers:** determiner, tính từ, danh từ làm bổ ngữ, lượng từ, sở hữu (company's). Head noun thường là **danh từ cuối cùng** trong chuỗi pre-modifiers. VD: \"The customer service department **manager**\" → head: manager; \"High-quality office equipment **suppliers**\" → head: suppliers (số nhiều → động từ chia số nhiều).",
          "**Bước 3 — Xử lý post-modifiers:** of-phrase/cụm giới từ, mệnh đề quan hệ, phân từ (V-ing/V-ed), to + V. Head noun là danh từ **ngay trước** post-modifiers. VD: \"A **report** on market trends\", \"The **meeting** held in the conference room last week\", \"The **cause** of the delay in shipment\" (head là cause, không phải delay hay shipment).",
          "**Ví dụ phức tạp:** \"The latest financial **report** submitted by the accounting team to the board of directors\" → bỏ hết modifiers còn lại report.",
          "**Mẹo:** hỏi \"What/Who is the main thing?\" — \"A box of chocolates from Switzerland\" → head: box. Kiểm tra chia động từ: \"The team of experts **is** arriving\" (head: team, số ít). Trong danh từ ghép dài, head thường là danh từ cuối: \"Air traffic control **system**\".",
          "**Lỗi hay gặp:** nhầm head với modifier. \"Sales department **budget**\" → head là budget, không phải sales.",
          "Câu mẫu Part 5: \"The _____ of the new policy will be discussed.\" (implementation / implement / implementing) → cần danh từ: implementation.",
        ],
      },
      {
        type: "table",
        title: "Bảng tóm tắt ví dụ cụm dài trong TOEIC",
        headers: ["Cụm danh từ dài", "Head noun", "Lý do nhận biết", "Ngữ cảnh TOEIC"],
        rows: [
          ["The annual performance review meeting", "meeting", "Danh từ cuối trong cụm ghép; pre-modifiers: The annual performance review", "Đánh giá hiệu suất hàng năm"],
          ["A proposal for increasing sales targets", "proposal", "Head trước post-modifier (for increasing…)", "Kế hoạch kinh doanh"],
          ["Products manufactured in our factory", "products", "Head số nhiều; post-modifier: manufactured in…", "Mô tả sản phẩm"],
          ["The director of international operations", "director", "Head trước of-phrase", "Cấu trúc công ty"],
          ["An email about the upcoming conference", "email", "Head trước about-phrase", "Thông báo sự kiện"],
        ],
      },
      {
        type: "table",
        title: "Các danh từ ghép hay gặp trong TOEIC",
        headers: ["Nhóm", "Danh từ ghép"],
        rows: [
          ["Công ty & Bộ phận", "human resources (nhân sự), customer service (dịch vụ khách hàng), sales department (bộ phận bán hàng), marketing team (đội marketing), accounting department (bộ phận kế toán), head office (trụ sở chính), branch office (chi nhánh)"],
          ["Công việc & Hiệu suất", "job interview (phỏng vấn việc làm), job performance (hiệu suất công việc), work schedule (lịch làm việc), business trip (chuyến công tác), annual review (đánh giá hàng năm), performance evaluation (đánh giá hiệu suất)"],
          ["Tài liệu & Báo cáo", "sales report (báo cáo doanh số), financial statement (báo cáo tài chính), market research (nghiên cứu thị trường), business proposal (đề xuất kinh doanh), application form (đơn xin việc), expense report (báo cáo chi phí)"],
          ["Sản phẩm & Dịch vụ", "product launch (ra mắt sản phẩm), product range (dòng sản phẩm), high-quality products (sản phẩm chất lượng cao), after-sales service (dịch vụ hậu mãi), price list (bảng giá)"],
          ["Giao dịch & Thanh toán", "credit card (thẻ tín dụng), bank account (tài khoản ngân hàng), payment method (phương thức thanh toán), invoice number (số hóa đơn), purchase order (đơn đặt hàng)"],
          ["Thời gian & Lịch trình", "delivery date (ngày giao hàng), deadline extension (gia hạn hạn chót), meeting agenda (chương trình cuộc họp), board meeting (cuộc họp hội đồng quản trị), conference call (cuộc gọi hội nghị)"],
          ["Thiết bị & Văn phòng", "office equipment (thiết bị văn phòng), office supplies (văn phòng phẩm), conference room (phòng họp), parking lot (bãi đỗ xe)"],
          ["Khác", "business card (danh thiếp), travel agency (công ty du lịch), air ticket (vé máy bay), hotel reservation (đặt phòng khách sạn), sales target (mục tiêu doanh số), advertising campaign (chiến dịch quảng cáo), public relations (quan hệ công chúng), value-added tax – VAT (thuế giá trị gia tăng), stock market (thị trường chứng khoán), supply chain (chuỗi cung ứng), customer satisfaction (sự hài lòng của khách hàng), project manager (quản lý dự án)"],
        ],
      },
      {
        type: "qa",
        title: "Bài tập 1: Dịch từ tiếng Anh sang tiếng Việt",
        instructions: "Dịch các cụm sau sang tiếng Việt (nghĩa phổ biến trong ngữ cảnh kinh doanh/TOEIC).",
        items: [
          { q: "Customer service", a: "Dịch vụ khách hàng" },
          { q: "Business trip", a: "Chuyến công tác" },
          { q: "Sales target", a: "Mục tiêu doanh số" },
          { q: "Expense report", a: "Báo cáo chi phí" },
          { q: "Job performance", a: "Hiệu suất công việc" },
          { q: "Market research", a: "Nghiên cứu thị trường" },
          { q: "Office supplies", a: "Văn phòng phẩm" },
          { q: "Delivery date", a: "Ngày giao hàng" },
          { q: "Purchase order", a: "Đơn đặt hàng" },
          { q: "Human resources", a: "Nhân sự" },
          { q: "After-sales service", a: "Dịch vụ hậu mãi" },
          { q: "Board meeting", a: "Cuộc họp hội đồng quản trị" },
          { q: "Credit card", a: "Thẻ tín dụng" },
          { q: "Performance review", a: "Đánh giá hiệu suất" },
          { q: "Application form", a: "Đơn xin việc" },
          { q: "Advertising campaign", a: "Chiến dịch quảng cáo" },
          { q: "Conference room", a: "Phòng họp" },
          { q: "Product launch", a: "Ra mắt sản phẩm" },
          { q: "Supply chain", a: "Chuỗi cung ứng" },
          { q: "Customer satisfaction", a: "Sự hài lòng của khách hàng" },
        ],
      },
      {
        type: "qa",
        title: "Bài tập 2: Dịch từ tiếng Việt sang tiếng Anh",
        instructions: "Dịch các cụm sau sang tiếng Anh (dạng noun + noun phổ biến trong TOEIC).",
        items: [
          { q: "Bộ phận bán hàng", a: "Sales department" },
          { q: "Đánh giá hiệu suất", a: "Performance review / Performance evaluation" },
          { q: "Báo cáo tài chính", a: "Financial statement" },
          { q: "Chuyến công tác", a: "Business trip" },
          { q: "Dịch vụ khách hàng", a: "Customer service" },
          { q: "Mục tiêu doanh số", a: "Sales target" },
          { q: "Đơn đặt hàng", a: "Purchase order" },
          { q: "Nghiên cứu thị trường", a: "Market research" },
          { q: "Thiết bị văn phòng", a: "Office equipment" },
          { q: "Ngày giao hàng", a: "Delivery date" },
          { q: "Nhân sự", a: "Human resources" },
          { q: "Dịch vụ hậu mãi", a: "After-sales service" },
          { q: "Cuộc họp hội đồng quản trị", a: "Board meeting" },
          { q: "Thẻ tín dụng", a: "Credit card" },
          { q: "Đơn xin việc", a: "Application form / Job application" },
          { q: "Chiến dịch quảng cáo", a: "Advertising campaign" },
          { q: "Phòng họp", a: "Conference room" },
          { q: "Ra mắt sản phẩm", a: "Product launch" },
          { q: "Chuỗi cung ứng", a: "Supply chain" },
          { q: "Sự hài lòng của khách hàng", a: "Customer satisfaction" },
        ],
      },
      {
        type: "qa",
        title: "Bài tập 3: Điền cụm danh từ ghép vào chỗ trống (kiểu TOEIC Part 5)",
        instructions: "Chọn cụm danh từ ghép phù hợp nhất để hoàn thành câu.",
        items: [
          { q: "Please submit your __________ by the end of the month. (báo cáo chi phí)", a: "expense report" },
          { q: "The company is planning a new __________ next quarter. (ra mắt sản phẩm)", a: "product launch" },
          { q: "All employees must attend the __________ tomorrow. (cuộc họp hội đồng)", a: "board meeting" },
          { q: "We need to improve our __________ to increase loyalty. (sự hài lòng của khách hàng)", a: "customer satisfaction" },
          { q: "The __________ department handles recruitment and training. (nhân sự)", a: "human resources" },
          { q: "Don't forget to bring your __________ for the hotel check-in. (đặt phòng khách sạn)", a: "hotel reservation" },
          { q: "The manager asked for a detailed __________ on competitors. (nghiên cứu thị trường)", a: "market research" },
          { q: "Our new policy aims to meet the annual __________. (mục tiêu doanh số)", a: "sales target" },
          { q: "Customers can pay by cash, check, or __________. (thẻ tín dụng)", a: "credit card" },
          { q: "The delay was due to a problem in the __________. (chuỗi cung ứng)", a: "supply chain" },
        ],
      },
      {
        type: "qa",
        title: "Bài tập nâng cao 1: Xác định head noun trong cụm danh từ ghép dài",
        instructions: "Xác định head noun và dịch cụm sang tiếng Việt. Ví dụ mẫu: \"The latest financial statement preparation guidelines\" → head noun: guidelines (hướng dẫn chuẩn bị báo cáo tài chính mới nhất).",
        items: [
          { q: "The new customer relationship management software", a: "Head noun: **software** — Phần mềm quản lý quan hệ khách hàng mới" },
          { q: "An updated annual performance evaluation report", a: "Head noun: **report** — Báo cáo đánh giá hiệu suất hàng năm cập nhật" },
          { q: "The company's long-term strategic planning committee", a: "Head noun: **committee** — Ủy ban lập kế hoạch chiến lược dài hạn của công ty" },
          { q: "High-priority project deadline extension request", a: "Head noun: **request** — Yêu cầu gia hạn hạn chót dự án ưu tiên cao" },
          { q: "International sales and marketing department budget", a: "Head noun: **budget** — Ngân sách bộ phận bán hàng và marketing quốc tế" },
          { q: "After-sales service quality improvement plan", a: "Head noun: **plan** — Kế hoạch cải thiện chất lượng dịch vụ hậu mãi" },
          { q: "The board of directors meeting minutes", a: "Head noun: **minutes** — Biên bản cuộc họp hội đồng quản trị" },
          { q: "Supply chain management system upgrade", a: "Head noun: **upgrade** — Nâng cấp hệ thống quản lý chuỗi cung ứng" },
          { q: "Corporate social responsibility policy implementation", a: "Head noun: **implementation** — Thực hiện chính sách trách nhiệm xã hội doanh nghiệp" },
          { q: "Market share analysis and forecasting team", a: "Head noun: **team** — Đội ngũ phân tích và dự báo thị phần" },
        ],
      },
      {
        type: "qa",
        title: "Bài tập nâng cao 3: Sửa lỗi sai trong cụm danh từ",
        instructions: "Các câu sau có lỗi ở cụm danh từ ghép (sai thứ tự từ, sai dạng từ hoặc sai head noun). Sửa lại cho đúng.",
        items: [
          { q: "The department is preparing a report research market for Q4.", a: "market research report" },
          { q: "We need to improve our service customer satisfaction levels urgently.", a: "customer satisfaction levels" },
          { q: "The plan implementation of the new policy starts next month.", a: "The implementation plan" },
          { q: "All staff received training health and safety last week.", a: "health and safety training" },
          { q: "The target sales for this year has been increased by 15%.", a: "sales target (head: target)" },
          { q: "Please confirm your reservation hotel for the business conference.", a: "hotel reservation" },
          { q: "The team leader presented a propose project timeline yesterday.", a: "a proposed project timeline / a project proposal" },
          { q: "Our focus is on the develop skill of junior employees.", a: "skill development" },
          { q: "The meeting agenda includes a discuss about budget cuts.", a: "a discussion about budget cuts" },
          { q: "Company policy requires approval manager for all overtime requests.", a: "manager approval (hoặc managerial approval)" },
        ],
      },
    ],
    exercises: [
      {
        title: "Bài tập nâng cao 2: Chọn dạng từ đúng để hoàn thành cụm danh từ",
        kind: "practice",
        questions: [
          q("The manager requested a detailed ------- on competitor pricing strategies.", ["analyze", "analysis", "analytical", "analyst"], "B", "Sau a detailed cần danh từ: analysis (sự phân tích)."),
          q("All employees are required to attend the ------- training session next week.", ["safety workplace", "workplace safety", "safe workplace", "safety work"], "B", "workplace safety (an toàn nơi làm việc) — head noun đứng sau."),
          q("Due to the delay, we need an immediate ------- for the shipment.", ["reschedule", "rescheduling", "rescheduled", "reschedule date"], "B", "Sau an immediate cần danh từ: rescheduling (việc sắp xếp lại lịch)."),
          q("The committee approved the ------- for the new branch office.", ["construct plan", "construction plan", "constructing plan", "construction planning"], "B", "construction plan: kế hoạch xây dựng."),
          q("Please review the attached ------- before the board meeting.", ["propose budget", "proposal budget", "proposed budget", "proposing budget"], "C", "proposed budget: ngân sách được đề xuất."),
          q("Our team is working on a ------- to increase customer retention.", ["strategy develop", "development strategy", "strategic development", "strategy development"], "D", "strategy development: phát triển chiến lược."),
          q("The company launched a comprehensive ------- last quarter.", ["train program", "training program", "trained program", "program training"], "B", "training program: chương trình đào tạo."),
          q("We received positive feedback on the ------- of our products.", ["quality high", "high quality", "highly quality", "quality highly"], "B", "Tính từ đứng trước danh từ: high quality."),
          q("The ------- will be held via video conference due to travel restrictions.", ["annual shareholder meeting", "shareholder annual meeting", "meeting annual shareholder", "shareholders annual meeting"], "A", "annual shareholder meeting: cuộc họp cổ đông thường niên (tính từ + danh từ bổ nghĩa + head noun)."),
          q("Submit your ------- by Friday to avoid penalties.", ["expense claim form", "claim expense form", "form expense claim", "expenses claim form"], "A", "expense claim form: mẫu yêu cầu thanh toán chi phí."),
        ],
      },
    ],
  },
];
