import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "dong-tu";
const VOCAB_HEADERS = ["Từ / cụm từ", "Từ loại", "Nghĩa"];

export const DONG_TU_LESSONS: MasteryLesson[] = [
  {
    slug: "dong-tu-vi-ngu",
    chapter: CHAPTER,
    code: "Word Form 1",
    title: "Câu hỏi về động từ làm vị ngữ",
    summary: "Chọn đúng động từ theo chủ ngữ (số ít/số nhiều), thì (hiện tại, quá khứ, tương lai) và thể (chủ động/bị động).",
    blocks: [
      {
        type: "text",
        title: "Introduction",
        body: "Bài học này cung cấp các kỹ năng làm dạng câu hỏi nhận biết động từ:\n• Cách nhận biết đáp án đúng dựa vào **chủ ngữ** (số ít, số nhiều), **thì** (hiện tại, quá khứ, tương lai) và **thể** (chủ động, bị động) của câu\n• Cách nhận biết động tính từ (V-ing và VpII làm tính từ) — Word Form 2\n• Cách nhận biết khi nào điền to V, V-ing hoặc V — Word Form 3.",
      },
      {
        type: "list",
        title: "Learning point 1: Khi lựa chọn động từ làm vị ngữ, cần chú ý đến chủ ngữ",
        items: [
          "Danh từ số ít, danh từ không đếm được, đại từ bất định (some/no/any/every + thing/body/one): động từ chia ở **số ít**.",
          "Danh từ số nhiều: động từ chia ở **số nhiều**.",
          "Danh từ 1 + giới từ + danh từ 2: động từ chia theo **danh từ thứ nhất**.",
          "Danh từ + mệnh đề quan hệ (đầy đủ hoặc rút gọn): động từ chia theo **danh từ chính**.",
        ],
      },
      {
        type: "table",
        title: "Learning point 2: Dấu hiệu nhận biết các thì của động từ",
        headers: ["Thì", "Dấu hiệu nhận biết"],
        rows: [
          ["Hiện tại đơn", "always, usually, often, hardly, seldom, rarely, never; every day, each morning; once a month, twice a year, …"],
          ["Quá khứ đơn", "yesterday, last week, two days ago, previously"],
          ["Tương lai đơn", "tomorrow, next June, until / as soon as + hiện tại đơn"],
          ["Hiện tại tiếp diễn", "now, currently"],
          ["Tương lai hoàn thành / hoàn thành tiếp diễn", "by the time + hiện tại đơn"],
          ["Hiện tại hoàn thành / hoàn thành tiếp diễn", "since + quá khứ đơn, for + khoảng thời gian; ever, never, recently, just, yet, already"],
          ["Quá khứ hoàn thành / hoàn thành tiếp diễn", "before / by the time + quá khứ đơn, quá khứ hoàn thành; after + quá khứ hoàn thành, quá khứ đơn"],
        ],
      },
      {
        type: "list",
        title: "Learning point 3: Khi lựa chọn động từ làm vị ngữ, cần chú ý đến thể của động từ",
        items: [
          "Xác định thể của động từ bằng cách dịch nghĩa của danh từ làm chủ ngữ và động từ trong bốn phương án.",
          "**Thể chủ động:** chủ ngữ thực hiện hành động.",
          "**Thể bị động:** ai đó/cái gì thực hiện hành động lên chủ ngữ (dấu hiệu đặc trưng: không có tân ngữ phía sau động từ, và câu thường có cụm by + tân ngữ).",
        ],
      },
      {
        type: "table",
        title: "Công thức chủ động — bị động",
        headers: ["", "Chủ động", "Bị động"],
        rows: [
          ["Thì đơn giản", "S + V", "S + be + VpII"],
          ["Thì tiếp diễn", "S + be + V-ing", "S + be + being + VpII"],
          ["Thì hoàn thành", "S + have + VpII", "S + have + been + VpII"],
          ["Thì hoàn thành tiếp diễn", "S + have + been + V-ing", "—"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["background check", "n", "sự kiểm tra kiến thức, kinh nghiệm"],
          ["charge", "v", "tính phí, tính tiền"],
          ["charge", "n", "phí, giá tiền"],
          ["make suggestions", "v", "đưa ra gợi ý, đề xuất"],
          ["pass", "n", "thẻ ra vào, vé"],
          ["remind", "v", "nhắc nhở"],
          ["run the company", "v", "điều hành công ty"],
          ["show, reveal, indicate", "v", "cho thấy rằng, chỉ ra rằng"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 1",
        kind: "practice",
        questions: [
          q("Positive feedback [-------] obtained from the audience.", ["were", "was"], "B", "Feedback là danh từ không đếm được → động từ số ít was."),
          q("Anyone who [-------] not completed the application form should do it immediately.", ["has", "have"], "A", "Anyone là đại từ bất định → động từ số ít has."),
          q("Infant clothes [-------] among our new products this year.", ["is", "are"], "B", "Clothes là danh từ số nhiều (có -s) → are."),
          q("The annual reports of this fiscal year [-------] currently not available.", ["is", "are"], "B", "Chủ ngữ có hai danh từ reports và year nối bởi giới từ of; động từ chia theo danh từ thứ nhất reports (số nhiều) → are."),
          q("The men playing the piano on the stage [-------] quite popular.", ["is", "are"], "B", "Chủ ngữ có dạng danh từ (men) + mệnh đề quan hệ rút gọn (playing the piano on the stage); động từ chia theo danh từ chính men → are."),
        ],
      },
      {
        title: "Check-up 1",
        kind: "practice",
        questions: [
          q("The furniture you ordered ------- scheduled to be delivered on August 26.", ["is", "were", "been", "have"], "A", "Furniture: chủ ngữ là danh từ không đếm được → is. 'Nội thất bạn đặt được sắp xếp vận chuyển vào ngày 26 tháng 8.'"),
          q("Every business ------- to evaluate its strengths and weaknesses periodically.", ["need", "needs", "are needed", "needing"], "B", "Every business: chủ ngữ là danh từ số ít → needs. 'Mỗi công ty cần đánh giá định kỳ điểm mạnh và điểm yếu của mình.'"),
          q("The extra newspapers on the newsstand ------- been bought quickly.", ["have", "has", "is", "was"], "A", "The extra newspapers: chủ ngữ là danh từ số nhiều → have. 'Những tờ báo trên sạp đã được mua rất nhanh.'"),
          q("Representatives from both groups ------- still expected to attend the conference.", ["is", "are", "has", "was"], "B", "Representatives: chủ ngữ là danh từ số nhiều → are. 'Đại diện cả hai bên vẫn được mong chờ sẽ tham gia hội thảo.'"),
          q("Anyone who ------- the visitor's pass can enter the facility.", ["have", "has", "own", "owning"], "B", "Anyone: đại từ bất định → số ít has. 'Bất cứ ai có thẻ ra vào đều có thể vào cơ sở này.'"),
        ],
      },
      {
        title: "Diagnostic test 2",
        kind: "practice",
        questions: [
          q("He usually [-------] an hour reading newspapers.", ["spends", "is spending"], "A", "Câu có trạng từ usually → hiện tại đơn spends."),
          q("The clothing store [-------] experienced financial problems for the last three months.", ["has", "had"], "A", "Câu có trạng ngữ for the last three months → hiện tại hoàn thành has (experienced)."),
          q("Melisa [-------] working for me five years ago.", ["started", "has started"], "A", "Câu có ago → quá khứ đơn started."),
          q("By the time I leave the US, I [-------] the Grand Canyon.", ["will visit", "will have visited"], "B", "Câu có trạng ngữ By the time + hiện tại đơn → tương lai hoàn thành will have visited."),
          q("I [-------] many pictures of the pyramids before I went to Egypt.", ["saw", "had seen"], "B", "Câu có trạng ngữ before + quá khứ đơn → quá khứ hoàn thành had seen."),
        ],
      },
      {
        title: "Check-up 2",
        kind: "practice",
        questions: [
          q("For ten years, the number of college graduates majoring in computers ------- by almost 20%.", ["has risen", "rose", "rises", "will rise"], "A", "Câu có trạng ngữ for ten years → hiện tại hoàn thành. 'Trong mười năm nay, số sinh viên tốt nghiệp ngành máy tính đã tăng thêm gần 20%.'"),
          q("The construction materials ------- this morning, so we will be able to resume work next week.", ["have arrived", "arrived", "arrive", "will arrive"], "B", "Câu có trạng ngữ this morning → quá khứ đơn. 'Vật liệu xây dựng đã đến sáng nay, nên tuần sau chúng ta có thể tiếp tục công trình.'"),
          q("I ------- the table already. Come over for dinner.", ["have set", "set", "am setting", "will set"], "A", "Câu có trạng từ already → hiện tại hoàn thành. 'Tôi đã dọn bàn ra rồi. Hãy đến ăn tối.'"),
          q("Starting next month, we ------- salaries through a newly installed system.", ["pay", "paid", "have paid", "will pay"], "D", "Câu có next month → tương lai. 'Bắt đầu từ tháng sau, chúng tôi sẽ trả lương qua hệ thống mới thiết lập.'"),
          q("I usually ------- to wish my boss a happy birthday.", ["forget", "forgot", "will forget", "have forgotten"], "A", "Câu có trạng từ usually → hiện tại đơn. 'Tôi thường quên chúc mừng sinh nhật sếp.'"),
        ],
      },
      {
        title: "Diagnostic test 3",
        kind: "practice",
        questions: [
          q("Our company [-------] a business partnership with another company.", ["established", "was established"], "A", "'Công ty thiết lập mối quan hệ kinh doanh với một công ty khác.' Tập trung vào chủ ngữ company và cụm establish a relationship → chủ động established."),
          q("Three reference letters [-------] for the job.", ["are required", "require"], "A", "'Ba bức thư giới thiệu được yêu cầu cho công việc này' → bị động are required."),
          q("A new law to promote employment [-------] by the government.", ["has just passed", "has just been passed"], "B", "'Một luật mới để khuyến khích việc làm vừa được thông qua bởi chính phủ.' Dựa vào cụm by the government → bị động has just been passed."),
          q("The company [-------] several workers for the upcoming construction.", ["will be hired", "will hire"], "B", "'Công ty sẽ thuê vài công nhân cho công trình xây dựng sắp tới' → chủ động will hire."),
          q("Necessary changes [-------] about our program.", ["will make", "will be made"], "B", "'Những thay đổi cần thiết sẽ được tiến hành đối với chương trình của chúng ta' → bị động will be made."),
        ],
      },
      {
        title: "Check-up 3",
        kind: "practice",
        questions: [
          q("All of our products are ------- on the order sheet.", ["listing", "list", "listed", "lists"], "C", "Danh từ products (sản phẩm), động từ list (liệt kê) → bị động (sản phẩm được liệt kê). 'Tất cả sản phẩm của chúng tôi được liệt kê trong đơn đặt hàng.'"),
          q("The budget report ------- to the accounting office sometime this afternoon.", ["will have sent", "will send", "will be sent", "will be sending"], "C", "Danh từ budget report, động từ send (gửi) → bị động. 'Báo cáo ngân sách sẽ được chuyển tới phòng kế toán trong chiều nay.'"),
          q("Vacationists at the Bayview Hotel ------- to their room by the bellboy.", ["shown", "show", "are showing", "are shown"], "D", "Danh từ vacationists (du khách), động từ show (chỉ dẫn) → bị động. 'Du khách ở khách sạn Bayview được nhân viên hành lý chỉ dẫn tới phòng.'"),
          q("The director ------- all employees to wear required protective clothing.", ["advised", "is advised", "to advise", "has been advised"], "A", "Phía sau chỗ trống có tân ngữ all employees nên không thể là bị động → advised. 'Giám đốc đã đề nghị tất cả nhân viên mặc quần áo bảo hộ theo quy định.'"),
          q("A background check ------- before any employment decision shall be finalized.", ["is conducted", "is conducting", "conducts", "conduct"], "A", "Danh từ background check, động từ conduct (tiến hành) → bị động. 'Một cuộc kiểm tra lý lịch được tiến hành trước khi đưa ra quyết định tuyển dụng cuối cùng.'"),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("My friend was ------- from her job yesterday.", ["terminated", "terminating", "being terminated", "been terminated"], "A", "Chủ ngữ my friend, động từ terminate (sa thải) → bị động. 'Bạn tôi bị sa thải ngày hôm qua.'"),
          q("The printer ------- by a new model next week.", ["will be replaced", "will replace", "will be replacing", "replaced"], "A", "Dấu hiệu bị động là giới từ by. 'Máy in sẽ được thay thế bằng máy mới vào tuần tới.'"),
          q("The prices of breakfast and swimming pool ------- in the total hotel price.", ["have been included", "have included", "has included", "has been included"], "A", "Chủ ngữ the prices (số nhiều), động từ include → bị động số nhiều have been included. 'Giá bữa sáng và bể bơi được bao gồm trong tổng giá khách sạn.'"),
          q("The red light ------- that a message has been sent.", ["indicates", "indicating", "indicate", "indicator"], "A", "Chủ ngữ red light (số ít), động từ indicate (cho thấy) → chủ động số ít indicates. 'Đèn đỏ báo rằng tin nhắn đã được gửi đi.'"),
          q("This lawyer always ------- high fees for his consulting services.", ["charge", "charges", "charged", "charging"], "B", "Chủ ngữ the lawyer (số ít), động từ charge (tính phí) → chủ động số ít charges. 'Luật sư đó luôn tính phí cao cho dịch vụ tư vấn.'"),
          q("The memo ------- to the department managers after it had been checked.", ["was sent", "sent", "sends", "had been sent"], "A", "Chủ ngữ memo (số ít), động từ send. Câu có after it had been checked → chỗ trống chia quá khứ đơn, bị động → was sent. 'Thông báo đã được gửi tới các trưởng phòng sau khi được kiểm tra.'"),
          q("The sales department ------- sales goals for the last quarter.", ["reached", "reaching", "reach", "reachable"], "A", "Chủ ngữ the sales department (số ít), động từ reach → chủ động reached (C. reach là động từ chia số nhiều). 'Phòng bán hàng đã đạt doanh số quý trước.'"),
          q("I want translation software that ------- English and Japanese into Korean.", ["translate", "translates", "translating", "translated"], "B", "Chủ ngữ software (không đếm được), động từ translate → chủ động số ít translates."),
          q("A large percentage of graduates are ------- careers in high-tech industries such as IT security, programming and software development.", ["seeking", "sought", "to seek", "seeker"], "A", "Chủ ngữ graduates, động từ seek (tìm kiếm) → chủ động seeking (are seeking: hiện tại tiếp diễn; are sought: bị động)."),
          q("Kristen, who ------- the company's branch office in Washington, had a lunch meeting with the CEO yesterday.", ["run", "runs", "running", "were running"], "B", "Chủ ngữ Kristen (số ít), động từ run (điều hành) → chủ động số ít runs."),
          q("The mineral boom has brought about an economic boom, which in turn means that real estate values have ------- to record levels.", ["rose", "rise", "risen", "rising"], "C", "Câu đã có have nên phía sau là động từ dạng phân từ hai risen."),
          q("Many physicians ------- that exercise is beneficial to our health.", ["agreement", "agree", "to agree", "agreeing"], "B", "Chủ ngữ physicians (số nhiều), động từ agree → chủ động số nhiều agree."),
          q("The plant manager will be ------- a day-long safety workshop.", ["organizing", "to organize", "organization", "organized"], "A", "Chủ ngữ the plant manager, động từ organize → chủ động will be organizing (D. will be organized là bị động). 'Quản lý nhà máy sẽ tổ chức buổi đào tạo an toàn kéo dài cả ngày.'"),
          q("A training program for new employees ------- proposed by Mr. Taylor.", ["have been", "are being", "was", "will"], "C", "Chủ ngữ chính training program (số ít), động từ propose → bị động số ít was proposed."),
          q("Ideas regarding our new proposal ------- welcomed by the board of managers.", ["is", "are", "will", "has been"], "B", "Chủ ngữ chính ideas (số nhiều), động từ welcome → bị động số nhiều are welcomed."),
          q("A room for our two next conferences ------- to be reserved now.", ["need", "needs", "is needed", "are needed"], "B", "Chủ ngữ chính a room (số ít), động từ need (chủ động: need to be reserved) → needs. 'Một căn phòng cho hai buổi hội thảo sắp tới cần được đặt trước ngay bây giờ.'"),
          q("The survey carried out among the plant's employees ------- their objection to the new regulations.", ["reveals", "reveal", "have revealed", "revealing"], "A", "Chủ ngữ chính a survey (số ít), động từ reveal (cho thấy) → chủ động số ít reveals."),
          q("Applicants are ------- to submit their photo identification at the information desk.", ["reminded", "remind", "reminding", "to remind"], "A", "Chủ ngữ applicants (số nhiều), động từ remind (nhắc nhở) → bị động are reminded."),
          q("Opinions ------- about the issue of building a new parking garage.", ["are divided", "is dividing", "have divided", "will divide"], "A", "Chủ ngữ opinions (số nhiều), động từ divide (chia rẽ) → bị động are divided. 'Ý kiến về việc xây dựng khu đỗ xe mới chia ra nhiều hướng.'"),
          q("At yesterday's meeting, Ms. William ------- some suggestions to reduce expenditure.", ["makes", "make", "made", "has made"], "C", "Chủ ngữ Ms. William (số ít), make some suggestions, trạng từ yesterday → chủ động quá khứ made."),
        ],
      },
    ],
  },
  {
    slug: "phan-tu-lam-tinh-tu",
    chapter: CHAPTER,
    code: "Word Form 2",
    title: "Động tính từ (V-ing và VpII làm tính từ)",
    summary: "Phân biệt V-ing/VpII chỉ tính chất – cảm xúc và V-ing/VpII mang nghĩa chủ động – bị động.",
    blocks: [
      {
        type: "list",
        title: "Learning point 1: Tính từ dạng V-ing và VpII chỉ cảm xúc và tính chất",
        items: [
          "**VpII** chỉ cảm xúc (thường đi cùng với danh từ chỉ người); **V-ing** chỉ tính chất (thường đi cùng với danh từ chỉ vật).",
          "interested – interesting, excited – exciting, exhausted – exhausting, overwhelmed – overwhelming, frustrated – frustrating.",
          "**Lưu ý:** impressed – impressive, satisfied – satisfactory, pleased – pleasant, scared – scary.",
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Tính từ bổ sung ý nghĩa chủ động / bị động",
        items: [
          "publishing (publishing house: nhà xuất bản) — published (a newly published book: quyển sách mới được xuất bản).",
          "Một số tính từ bị động thường gặp: **enclosed** (đính kèm, gửi kèm), **conducted** (được tiến hành), **approved** (được thông qua), **revised** (được sửa đổi).",
          "Một số tính từ chủ động thường gặp: **existing** (tồn tại, có sẵn), **demanding** (đòi hỏi cao), **dining** (ăn uống), **rising** (tăng lên).",
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["come into effect", "v", "có hiệu lực"],
          ["complimentary", "adj", "miễn phí"],
          ["damage", "v", "làm hỏng"],
          ["enclose", "v", "đính kèm"],
          ["existing", "adj", "hiện hành, hiện có"],
          ["frustrating", "adj", "gây nản lòng"],
          ["make someone + adj", "v", "khiến ai đó cảm thấy thế nào"],
          ["revise", "v", "sửa đổi, sửa chữa"],
          ["sign", "v", "ký kết"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test 1",
        kind: "practice",
        questions: [
          q("[-------] candidates should contact Dr. Stuart as soon as possible.", ["Interesting", "Interested"], "B", "'Những ứng viên có hứng thú (với công việc) nên liên hệ ông Stuart càng sớm càng tốt.' Interested là tính từ chỉ cảm xúc; hoặc dựa vào candidates là danh từ chỉ người."),
          q("Another function of email is the ability to send friends an [-------] link.", ["interested", "interesting"], "B", "Link là danh từ chỉ vật → tính từ dạng V-ing interesting."),
          q("Whether traveling short or long distances, kids get [-------].", ["boring", "bored"], "B", "Kids là danh từ chỉ người → tính từ dạng phân từ hai bored."),
          q("Sometimes the songs were good, but mostly the albums are numbingly [-------].", ["boring", "bored"], "A", "Albums là danh từ chỉ vật → boring."),
          q("It's incredibly [-------] to be part of this reading project.", ["exciting", "excited"], "A", "Cấu trúc It is + tính từ (thật là … để làm gì) → tính từ dạng V-ing chỉ tính chất exciting."),
        ],
      },
      {
        title: "Check-up 1",
        kind: "practice",
        questions: [
          q("We are ------- to inform you that your application has been accepted.", ["pleasing", "pleasant", "pleased", "please"], "C", "Tính từ bổ nghĩa về cảm xúc cho we → phân từ hai. 'Chúng tôi rất hài lòng thông báo rằng đơn của bạn đã được chấp nhận.'"),
          q("The organizers were ------- about the low number of attendees.", ["disappoint", "disappointed", "disappointing", "disappointment"], "B", "Tính từ bổ nghĩa cảm xúc cho the organizers → disappointed."),
          q("My employer was ------- this morning when I went to work late.", ["annoying", "annoy", "annoyed", "annoys"], "C", "Tính từ bổ nghĩa cảm xúc cho danh từ chỉ người my employer → annoyed."),
          q("The ------- fans keep cheering for the winning team.", ["exciting", "excited", "excite", "excitement"], "B", "Tính từ bổ nghĩa cảm xúc cho danh từ chỉ người fans → excited."),
          q("The presentation was extremely -------.", ["boring", "bore", "bored", "boredom"], "A", "Tính từ bổ nghĩa tính chất cho danh từ chỉ vật the presentation → boring."),
        ],
      },
      {
        title: "Diagnostic test 2",
        kind: "practice",
        questions: [
          q("Lucy showed us her first [-------] book.", ["publishing", "published"], "B", "Quyển sách được xuất bản → bị động published."),
          q("The [-------] student will be asked to represent the school.", ["choosing", "chosen"], "B", "Học sinh được lựa chọn → bị động chosen."),
          q("The man [-------] over there is a new addition to the Customer Service Department.", ["walking", "walked"], "A", "Người đàn ông đi → chủ động walking."),
          q("The [-------] photocopier is on the floor.", ["breaking", "broken"], "B", "Máy photocopy bị hỏng → bị động broken."),
          q("Our [-------] candidate has at least three years of working experience.", ["preferring", "preferred"], "B", "Ứng viên được yêu thích/được lựa chọn → bị động preferred."),
        ],
      },
      {
        title: "Check-up 2",
        kind: "practice",
        questions: [
          q("Thanks to the newly ------- printer, we now have fewer problems.", ["purchase", "purchasing", "purchased", "purchases"], "C", "Danh từ printer, động từ purchase (mua) → bị động purchased."),
          q("With our restaurant's renovation, customers will enjoy a pleasant ------- experience.", ["diners", "dining", "dine", "dined"], "B", "Danh từ experience, động từ dine (ăn) → chủ động dining."),
          q("Anyone ------- our new laptop computer will receive a free optical mouse.", ["ordering", "order", "to order", "orders"], "A", "Danh từ anyone, động từ order (đặt hàng) → chủ động ordering."),
          q("The contract terms ------- by the manager will be confirmed by the CEO.", ["is signed", "signed", "sign", "signing"], "B", "Contract terms, động từ sign → bị động signed. Lưu ý: A. is signed cũng ở dạng bị động nhưng nếu chọn, câu sẽ có hai vị ngữ (is signed và will be confirmed) trong một mệnh đề."),
          q("Employees should submit a ------- report to their manager.", ["revision", "revised", "revise", "revising"], "B", "Danh từ report, động từ revise (sửa) → bị động revised."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("We are unable to process newly ------- books until next week.", ["publication", "published", "publishing", "to publish"], "B", "Danh từ book, động từ publish → bị động published. 'Chúng tôi không thể xử lý những quyển sách mới xuất bản cho tới tuần sau.'"),
          q("Please accept the ------- coupon book as thanks for opening your personal account.", ["enclose", "enclosed", "enclosing", "to enclose"], "B", "Danh từ coupon book, động từ enclose (đính kèm) → bị động enclosed."),
          q("You are required to review the ------- products before putting them on shelves.", ["finish", "finishing", "finished", "to finish"], "C", "Danh từ products, động từ finish (hoàn thiện) → bị động finished."),
          q("Since I am your long-term ------- customer, I hope you will give me complimentary coupons.", ["satisfying", "satisfactory", "satisfied", "satisfaction"], "C", "Tính từ chỉ cảm xúc của danh từ chỉ người customer → satisfied."),
          q("Did you hear the ------- news? Ann is going to be the new manager!", ["surprise", "surprised", "surprising", "to surprise"], "C", "Tính từ chỉ tính chất của vật news → surprising."),
          q("If ------- by Transit Authorities, additional regulation changes would come into effect.", ["approve", "approval", "approved", "approving"], "C", "Additional regulation changes được thông qua → bị động approved."),
          q("A survey ------- by a polling firm shows positive public responses to the city development plan.", ["conduct", "to conduct", "conducting", "conducted"], "D", "Survey được tiến hành → bị động conducted."),
          q("The decision to recruit more workers was based on concerns ------- by the management.", ["express", "expression", "expressing", "expressed"], "D", "Concerns được nêu lên (by the management) → bị động expressed."),
          q("Building a new industrial complex within the city is impossible because building regulations became too ------- to accommodate.", ["frustrate", "frustrating", "frustrated", "frustration"], "B", "Tính từ chỉ tính chất của danh từ chỉ vật building regulations → frustrating."),
          q("Mobile headsets were returned to the manufacturer because they arrived in ------- conditions.", ["damage", "damaged", "damaging", "damages"], "B", "Condition (bị hỏng) → bị động damaged."),
          q("The company strives to improve its ------- products and develop new product lines.", ["exist", "exists", "existed", "existing"], "D", "Tính từ bổ sung ý nghĩa chủ động existing (hiện có)."),
          q("Visa applications are processed within three days if ------- in person by the applicant.", ["submit", "to submit", "submitted", "submitting"], "C", "Đơn được nộp → bị động submitted."),
          q("Enclosed is the estimate of the factory construction ------- by Cowlick Inc.", ["request", "requested", "requesting", "to request"], "B", "Bản ước tính được yêu cầu (dựa vào by phía sau) → requested."),
          q("Despite the sign ------- that tourists are not allowed to take photos in the museum, some tourists still did it.", ["saying", "said", "say", "to say"], "A", "Biển báo cho biết (chủ động) → saying."),
          q("The prospect of working in that company is so ------- to Keila.", ["overwhelming", "overwhelmed", "overwhelm", "to overwhelm"], "A", "Tính từ chỉ tính chất cho danh từ chỉ vật the prospect → overwhelming."),
          q("Making our customers ------- is our top priority at Regean Hotel.", ["satisfactory", "satisfying", "satisfied", "to satisfy"], "C", "Tính từ chỉ cảm xúc cho customers (cấu trúc make + O + adj) → satisfied."),
          q("We can expect ------- cost in lumber this month.", ["rise", "rising", "risen", "rose"], "B", "Tính từ bổ sung ý nghĩa chủ động rising. 'Chúng ta có thể chờ giá gỗ tăng vào tháng này.'"),
          q("Please don't make me go to another ------- sales meeting.", ["boredom", "boring", "bored", "bore"], "B", "Tính từ chỉ tính chất cho danh từ chỉ vật sales meeting → boring."),
          q("These directions are very ------- and need rewriting.", ["confusing", "confused", "confuse", "confusion"], "A", "Tính từ chỉ tính chất cho danh từ chỉ vật directions → confusing."),
          q("Commuters ------- the highway should be prepared for heavy traffic jams.", ["using", "use", "used", "uses"], "A", "Commuters sử dụng (chủ động) → using."),
        ],
      },
    ],
  },
  {
    slug: "danh-dong-tu-to-v",
    chapter: CHAPTER,
    code: "Word Form 3",
    title: "Danh động từ và động từ nguyên mẫu",
    summary: "Khi nào dùng To V, V-ing hay V nguyên mẫu: chủ ngữ, bổ ngữ, sau động từ, sau giới từ và cấu trúc giả định.",
    blocks: [
      {
        type: "list",
        title: "Learning point",
        items: [
          "**To V, V-ing làm chủ ngữ:** Finding a job is difficult.",
          "**To V, V-ing làm bổ ngữ (sau to be):** My goal is to find a job.",
          "**To V, V-ing, V làm tân ngữ sau động từ khác** (xem bảng).",
        ],
      },
      {
        type: "table",
        title: "To V / V-ing / V",
        headers: ["Cấu trúc", "Động từ"],
        rows: [
          ["+ to V", "agree, refuse, decide, determine, expect, hope, plan, promise, need, want, would like, would love to V"],
          ["+ O + to V", "request, invite, ask, require, allow, encourage, force, remind + O + to V"],
          ["Từ để hỏi + to V", "how to do, what to say…"],
          ["+ V-ing", "consider, avoid, keep, admit, deny, postpone, finish, suggest + V-ing"],
          ["spend time / money + V-ing", "spend $20,000 remodeling"],
          ["to (giới từ) + V-ing", "look forward to, be subject to, get used to, object to + V-ing"],
          ["+ O + V", "make, let + O + V"],
          ["S1 + request / ask / recommend / suggest / advise / require / insist + (that) + S2 + V", "He requested that every corner of the company be cleaned."],
          ["It is + mandatory / important / vital / imperative / suggested / recommended that + S + V", "It is important that he be on time."],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["be responsible for", "adj", "chịu trách nhiệm cho việc gì"],
          ["maintain", "v", "duy trì"],
          ["navigation system", "n", "hệ thống định vị"],
          ["renew the license", "v", "gia hạn giấy phép"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("[-------] a job can be difficult due to increasing competition in the job market.", ["Finding", "Find"], "A", "Chỗ trống là chủ ngữ → danh động từ Finding."),
          q("Our company's goal is [-------] this contract successfully.", ["land", "to land"], "B", "Sau to be là to V chỉ mục đích: 'Mục tiêu của công ty chúng tôi là ký được hợp đồng thành công.'"),
          q("I'm considering [-------] my job.", ["to quit", "quitting"], "B", "Sau consider là V-ing (xem xét, cân nhắc việc gì). 'Tôi đang cân nhắc có nên bỏ việc hay không.'"),
          q("Any new business shouldn't expect [-------] profits in the first two years.", ["get", "to get"], "B", "Sau expect là to V (mong chờ điều gì). 'Bất cứ công ty mới nào cũng không nên mong thu được lợi nhuận trong hai năm đầu.'"),
          q("He requested that every corner of the company [-------] cleaned.", ["is", "be"], "B", "Sau request that là động từ nguyên thể → be. 'Anh ấy yêu cầu mọi ngóc ngách của công ty phải được lau sạch.'"),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("We all look forward ------- you very soon.", ["to see", "to seeing", "will see", "like seeing"], "B", "Sau look forward to là V-ing: mong chờ điều gì."),
          q("The company has spent $20,000 ------- the premises.", ["remodel", "remodeling", "to remodel", "remodeled"], "B", "Sau spend là V-ing: tiêu tiền/thời gian vào việc gì. 'Công ty đã chi 20.000 đô la vào việc nâng cấp tòa nhà.'"),
          q("The manager ------- us to return the DVD before noon today.", ["likes", "would like", "is liking", "liked"], "B", "Phía sau là to return nên chỗ trống là would like (would like + O + to V)."),
          q("My boss told me ------- the project by this Friday.", ["finish", "finishing", "to finish", "to finishing"], "C", "Tell somebody to V: yêu cầu ai đó làm gì."),
          q("Every employee, regardless of age, should consider ------- for retirement.", ["to invest", "invest", "investing", "invested"], "C", "Consider + V-ing: xem xét việc gì."),
          q("I look forward to ------- with you to discuss the ways my skills may best serve City Engineers.", ["meet", "meeting", "meets", "met"], "B", "Look forward to + V-ing."),
          q("As a manager, you are responsible for ------- these rules with your staff.", ["discussing", "discussion", "discuss", "discussed"], "A", "Sau giới từ là V-ing."),
          q("------- by the company, candidates should be well-prepared for possible interview questions.", ["To hire", "To be hired", "Hiring", "Being hired"], "B", "Để chỉ mục đích, dùng to V. Phía sau chỗ trống là by nên chọn dạng bị động. 'Để được công ty tuyển, ứng viên cần chuẩn bị kỹ cho các câu hỏi phỏng vấn.'"),
          q("In order to ------- the proofreading work, the editing team will need at least two more weeks.", ["complete", "completing", "completed", "be completed"], "A", "In order to V: để làm gì."),
          q("It is important ------- the computer's serial number when you call for technical support.", ["know", "to know", "knowing", "known"], "B", "It is + adj + to V."),
          q("Upon ------- the receipt, I noticed that I was charged for the product that I didn't purchase.", ["review", "to review", "reviewing", "reviewed"], "C", "Upon là giới từ nên sau đó là V-ing."),
          q("Major airlines are considering ------- the number of domestic flights to ease air traffic congestion.", ["reduce", "to reduce", "reducing", "reduced"], "C", "Consider + V-ing."),
          q("The Bureau of Licensing requires local restaurant owners ------- their licenses annually.", ["renews", "to renew", "renewing", "renewed"], "B", "Require somebody to V: yêu cầu ai đó làm gì. 'Cục cấp phép yêu cầu chủ nhà hàng địa phương gia hạn giấy phép mỗi năm.'"),
          q("A navigation system is efficient in ------- roads that are not easy to find.", ["location", "locate", "to locate", "locating"], "D", "Sau giới từ in là V-ing. 'Hệ thống định vị xác định hiệu quả những con đường khó tìm.'"),
          q("------- the market to be expanded in the future, businesses must take risks and find new opportunities.", ["For", "Besides", "If", "Through"], "A", "Cấu trúc For + O + to V (để cái gì được làm gì). 'Để thị trường được mở rộng trong tương lai, các công ty cần chấp nhận rủi ro và tìm cơ hội mới.'"),
          q("As a company committed to ------- good relationships with our customers, we offer you a 20% discount on all telephone orders.", ["maintain", "maintaining", "maintained", "maintenance"], "B", "Be committed to V-ing: cam kết với việc gì."),
          q("Andrew Barker suggested that an increase in monthly fee ------- applied on all lawn treatment and landscaping services.", ["be", "being", "is", "to be"], "A", "Sau cấu trúc suggest that là động từ nguyên thể."),
          q("We will need ------- new staff members to help with setting up and establishing operations.", ["add", "adding", "added", "to add"], "D", "Need to V: cần phải làm gì."),
          q("An agreement is expected ------- in the next few weeks.", ["to complete", "to be completed", "completing", "completed"], "B", "Expect + to V; an agreement và complete có quan hệ bị động → to be completed."),
          q("It has been requested that every worker ------- helmets at the construction site.", ["wear", "to wear", "wearing", "worn"], "A", "Sau cấu trúc It is requested that là động từ nguyên thể."),
        ],
      },
    ],
  },
  {
    slug: "nghia-cua-dong-tu",
    chapter: CHAPTER,
    code: "Word Choice",
    title: "Câu hỏi dịch nghĩa của động từ",
    summary: "Động từ đi với giới từ, các cặp động từ dễ nhầm và các cụm động từ + danh từ cố định.",
    blocks: [
      {
        type: "text",
        body: "Khi làm câu hỏi với bốn phương án là bốn động từ khác nhau, không nên dịch nghĩa của cả câu mà nên xem **giới từ hoặc danh từ ở phía sau chỗ trống**, vì thông thường các câu hỏi dạng này kiểm tra kiến thức về cụm động từ hoặc sự kết hợp của động từ với danh từ.",
      },
      {
        type: "table",
        title: "1. Các động từ đi với giới từ to + V-ing / Noun",
        headers: ["Cụm động từ", "Nghĩa", "Ví dụ"],
        rows: [
          ["be entitled to / be subject to", "hưởng / chịu cái gì", "be entitled to a bonus, be subject to change"],
          ["adhere to", "tuân thủ", "adhere to the laws"],
          ["contribute to", "đóng góp", "contribute to the company's success"],
          ["attribute something to something", "cho rằng cái gì là bởi vì", "attribute my success to my hard work"],
        ],
      },
      {
        type: "list",
        title: "2. Các động từ dễ nhầm lẫn",
        items: [
          "**expand – extend:** expand the market (mở rộng thị trường), expand the building (mở rộng tòa nhà); extend the warranty (kéo dài thời hạn bảo hành).",
          "**provide – give/offer:** cung cấp cho ai cái gì: provide somebody with something; give/offer somebody something.",
          "**discuss – talk about:** discuss something = talk about something (discuss changes = talk about changes); discuss with somebody about something = talk with somebody about something.",
          "**participate, take part, attend:** participate in, take part in = attend (participate in the seminar = attend the seminar).",
          "**conduct, carry:** conduct = carry out (conduct a study = carry out a study).",
          "**look, seek:** look for = seek: tìm kiếm (look for a job = seek a job).",
          "**indicate, point:** indicate = point out: chỉ ra rằng.",
          "**announce, inform, notify:** announce something: thông báo về điều gì (announce the company's policy changes); inform/notify somebody of something: thông báo với ai về điều gì (inform/notify company staff of policy changes).",
          "**take place – hold, organize:** take place: (sự kiện) diễn ra (The wedding will take place on Monday.); hold, organize: (sự kiện được) tổ chức (The wedding will be held/organized on Monday.).",
        ],
      },
      {
        type: "table",
        title: "3. Các cụm động từ + danh từ",
        headers: ["Động từ", "Cụm từ", "Nghĩa"],
        rows: [
          ["Meet", "meet the needs", "đáp ứng nhu cầu"],
          ["Meet", "meet the deadlines", "kịp thời hạn"],
          ["Meet", "meet the requirements / specifications", "đáp ứng yêu cầu"],
          ["Conduct", "conduct a study / a survey / an investigation", "tiến hành nghiên cứu / khảo sát / điều tra"],
          ["Renew", "renew the membership / the subscription / the contract", "gia hạn thẻ thành viên / đặt báo / hợp đồng"],
          ["Others", "alleviate concerns", "giảm bớt sự lo lắng"],
          ["Others", "reserve the right", "có quyền"],
          ["Others", "waive the right", "từ bỏ quyền"],
          ["Others", "implement strategies / policies", "thi hành chiến lược / chính sách"],
          ["Others", "handle / solve / address customers' requests", "giải quyết yêu cầu của khách hàng"],
          ["Others", "follow guidelines", "làm theo hướng dẫn"],
          ["Others", "introduce a new product", "giới thiệu sản phẩm mới"],
          ["Others", "discontinue a product", "ngừng sản xuất"],
        ],
      },
      {
        type: "table",
        title: "4. Các động từ khác",
        headers: ["Động từ", "Nghĩa"],
        rows: [
          ["admit", "cho vào cửa"],
          ["exceed", "vượt quá"],
          ["promote", "quảng bá, thăng chức"],
          ["charge", "tính phí, tính tiền"],
          ["generate", "tạo ra, gây ra"],
          ["acquire", "mua lại"],
          ["merge", "sáp nhập"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["acquire", "v", "mua lại"],
          ["analyze the needs", "v", "phân tích nhu cầu"],
          ["confirm reservation", "v", "xác nhận đặt chỗ"],
          ["enhance / increase productivity", "v", "tăng năng suất"],
          ["extend the warranty", "v", "kéo dài thời hạn bảo hành"],
          ["follow safety guidelines", "v", "tuân theo quy định an toàn"],
          ["introduce new products", "v", "giới thiệu sản phẩm mới"],
          ["meet specifications / needs", "v", "đáp ứng yêu cầu / nhu cầu"],
          ["operate the machine", "v", "vận hành máy móc"],
          ["present a document", "v", "xuất trình giấy tờ"],
          ["submit forms", "v", "nộp đơn"],
          ["take measures to V", "v", "tiến hành biện pháp để"],
        ],
      },
    ],
    exercises: [
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Warehouse employees must ------- the safety guidelines as outlined in the company manual.", ["take", "follow", "lead", "carry"], "B", "Follow the safety guidelines: tuân thủ quy định về an toàn."),
          q("Siesna Electronics products are evaluated for quality and ------- rigorous technical specifications.", ["transmit", "contact", "meet", "visit"], "C", "Meet the specifications: đáp ứng yêu cầu kỹ thuật."),
          q("Last year, our company ------- seven successful new phone models.", ["attended", "introduced", "acted", "caused"], "B", "Introduce new products: giới thiệu sản phẩm mới."),
          q("After ------- your business's operating needs, we will be able to help you choose the tools that enhance your results.", ["analyzing", "expecting", "depending", "visiting"], "A", "Analyze the needs: phân tích nhu cầu."),
          q("We paid $500 million to ------- the profitable computer software firm XBR Technologies.", ["acquire", "achieve", "yield", "realize"], "A", "Acquire: mua lại. 'Chúng tôi đã trả 500 triệu đô la để mua lại công ty phần mềm XBR Technologies.'"),
          q("All employees working in the assembly area will be ------- to take a course on machine operation.", ["recognized", "required", "given", "grown"], "B", "Be required to V: được yêu cầu làm gì."),
          q("We plan to ------- our service contract with INC Shipping for another two years.", ["prevent", "renew", "talk", "present"], "B", "Renew the contract: gia hạn hợp đồng."),
          q("New employees should ------- personal forms to their supervisors for extended holiday.", ["implement", "submit", "complete", "attribute"], "B", "Submit the form: nộp đơn."),
          q("All new employees have to ------- orientation on company policies.", ["participate", "attend", "take", "remain"], "B", "Participate in = attend: tham gia (participate cần giới từ in)."),
          q("The organizer will ------- all participants with a detailed conference schedule.", ["offer", "provide", "give", "submit"], "B", "Provide somebody with something = give somebody something."),
          q("The bank has taken necessary measures to ------- another computer system failure.", ["upgrade", "encourage", "prevent", "improve"], "C", "Prevent the failure: tránh sự cố."),
          q("All visitors are required to ------- photo identification before entering our research center.", ["notify", "assign", "permit", "present"], "D", "Present photo identification: xuất trình giấy tờ."),
          q("Our service representatives ------- committed to providing quality service to customers.", ["retain", "remember", "reimburse", "remain"], "D", "Remain + committed (adj): luôn luôn cam kết."),
          q("Flight reservations should be ------- at least three days before your departure.", ["connected", "saved", "continued", "confirmed"], "D", "Confirm flight reservations: xác nhận đặt vé máy bay."),
          q("To increase customer satisfaction, the company decided to ------- the warranty for its handset to three years.", ["extend", "spread", "intend", "expand"], "A", "Extend the warranty: kéo dài thời hạn bảo hành."),
          q("Survey shows that the company incentives actually ------- workers' productivity.", ["complies", "enhances", "removes", "complicates"], "B", "Enhance productivity: tăng năng suất."),
          q("All visitors are required to ------- their visitor pass before entering.", ["inform", "present", "assign", "allow"], "B", "Present a visitor's pass: trình thẻ ra vào."),
          q("The entire staff is working to ------- the assignment by the deadline.", ["invest", "complete", "suggest", "install"], "B", "Complete the assignment: hoàn thành nhiệm vụ."),
          q("Most businesses are taking advantage of the Internet to ------- their markets.", ["expand", "expose", "exhibit", "extend"], "A", "Expand the market: mở rộng thị trường."),
          q("Customers are required to complete the survey in order for the company to ------- their needs.", ["meet", "see", "fill", "respond"], "A", "Meet the needs: đáp ứng nhu cầu."),
        ],
      },
    ],
  },
  {
    slug: "dong-tu-review-test",
    chapter: CHAPTER,
    code: "Review Test",
    title: "Verbs — Review Test",
    summary: "Bài kiểm tra tổng hợp 30 câu về động từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["be responsible for", "adj", "chịu trách nhiệm cho việc gì"],
          ["feature = include", "v", "bao gồm"],
          ["maintain", "v", "duy trì"],
          ["motivated", "adj", "có động lực"],
          ["navigation system", "n", "hệ thống định vị"],
          ["price quote", "n", "bảng báo giá"],
          ["renew the license", "v", "gia hạn giấy phép"],
          ["result from", "v", "xuất phát từ, do"],
        ],
      },
    ],
    exercises: [
      {
        title: "Verbs — Review Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("We suggested that every employee first ------- the data bank for software they need.", ["check", "checks", "checked", "has checked"], "A", "Sau suggest that là động từ ở dạng nguyên thể."),
          q("If we can be of any assistance in the future, please ------- free to contact us.", ["feel", "feeling", "feels", "be felt"], "A", "Câu mệnh lệnh bắt đầu bằng động từ nguyên thể."),
          q("Since he was unable to attend the annual meeting, Mr. Yokomate requested that the minutes ------- to his office.", ["be sent", "were sent", "sent", "send"], "A", "Sau request that là động từ nguyên thể. The minutes (biên bản) được gửi → bị động be sent."),
          q("Portland Square Hotel ------- a complimentary breakfast to all of its guests.", ["providing", "provides", "provide", "be provided"], "B", "Chủ ngữ số ít, chủ động → provides. 'Khách sạn Portland Square cung cấp bữa sáng miễn phí cho tất cả khách.'"),
          q("Tickets to the tennis tournament in Seoul will ------- online soon.", ["to sell", "selling", "sold", "be sold"], "D", "Chủ ngữ chính tickets; vé được bán → bị động will be sold."),
          q("Price quotes for potential customers ------- taxes and shipping charges.", ["includes", "include", "including", "to include"], "B", "Chủ ngữ price quotes (số nhiều), chủ động → include."),
          q("Please don't use the copy machine in the supply room since the ink cartridges ------- unavailable now.", ["are", "is", "been", "being"], "A", "Ink cartridges là danh từ số nhiều → are."),
          q("A proposed change ------- a ban on riding a bike on a platform.", ["include", "includes", "including", "have included"], "B", "Chủ ngữ a proposed change (số ít), chủ động → includes."),
          q("The upcoming festival ------- a performance by famous pianist Julie Jung.", ["feature", "features", "featured", "will be featured"], "B", "Chủ ngữ số ít, chủ động → features (feature = include)."),
          q("Although the meeting ------- late, we were able to discuss the entire project.", ["begin", "began", "will begin", "beginning"], "B", "Dựa vào thì của mệnh đề còn lại (quá khứ) → began."),
          q("After the current model, the computer manufacturer MGV ------- five existing models and launch three new ones.", ["discontinue", "to discontinue", "will discontinue", "have discontinued"], "C", "Chủ ngữ số ít, chủ động → will discontinue (A, D chia số nhiều nên sai)."),
          q("The seminars on technology development ------- the knowledge and expertise of employees.", ["broadening", "broadened", "broadens", "broad"], "B", "Chủ ngữ chính seminars (số nhiều), chủ động → broadened (C. broadens chia theo số ít)."),
          q("The shopping mall is not responsible for any damage to products that ------- from customers' improper use.", ["result", "results", "resulted", "are resulted"], "B", "Danh từ chính damage (số ít), result from (do, bởi), thì hiện tại, chủ động → results."),
          q("Owing to damage caused by recent floods, the construction of the building ------- in three months.", ["will have completed", "complete", "completes", "will be completed"], "D", "Việc xây dựng được hoàn thành → bị động will be completed."),
          q("By the time he retires next September, Shawn ------- with the company for six years.", ["will have been", "had been", "to be", "will be"], "A", "By the time + hiện tại đơn → mệnh đề còn lại chia tương lai hoàn thành."),
          q("The number of employees hired on a yearly basis ------- increasing drastically.", ["is", "are", "have been", "has"], "A", "The number of employees là danh từ số ít → is increasing."),
          q("Until the bus route -------, the drivers will have to take another road.", ["is reconstructed", "have been reconstructed", "are reconstructed", "will be reconstructed"], "A", "Until + động từ chia thì hiện tại; the bus route (số ít) được xây dựng lại → is reconstructed."),
          q("Winthrop Strategies is seeking to employ ------- individuals who meet deadlines.", ["motivate", "motivated", "motivation", "motivations"], "B", "Motivated (adj): có động lực."),
          q("We have ------- your yearly subscription to our magazine.", ["renew", "renewal", "renewed", "renewing"], "C", "Trước chỗ trống là have nên chỉ có renewed phù hợp (have + VpII)."),
          q("The company-sponsored five-kilometer run will be held on October 15, and all employees ------- to participate.", ["to invite", "invite", "inviting", "are invited"], "D", "Động từ chia theo chủ ngữ số nhiều, dạng bị động."),
          q("No firms can ------- to rely forever on only the strength of its name to sell products.", ["require", "afford", "suppose", "depend"], "B", "Can afford to V: có khả năng làm gì."),
          q("Library patrons who fail to return an item by the due date ------- a fee.", ["charge", "will be charged", "have charged", "are charging"], "B", "Động từ chia dạng bị động 'bị tính phí'."),
          q("By the time Clear Blaze Technology's word processing program goes on the market, software engineers ------- its remaining flaws.", ["will have corrected", "had been correcting", "are correcting", "will correct"], "A", "By the time + hiện tại đơn là dấu hiệu của tương lai hoàn thành."),
          q("Taiwan Knitwear Corporation's board of directors ------- for two hours yesterday to review the annual report.", ["met", "meet", "meets", "meeting"], "A", "Câu có trạng từ yesterday → quá khứ đơn."),
          q("Funds raised by the local preservation society have helped ------- the historic Jasenville train station.", ["restoring", "to restore", "restored", "is restored"], "B", "Help to V."),
          q("Maria's keynote address at next month's symposium in Singapore ------- by a short video.", ["was preceded", "will be preceded", "would precede", "were to precede"], "B", "Câu có next month → tương lai; bài phát biểu được mở đầu bởi đoạn phim → bị động will be preceded."),
          q("Seating in the Bogor Stadium completely ------- the field so that all visitors are afforded excellent views of the event.", ["surround", "surrounds", "surrounding", "surrounded"], "B", "Mệnh đề còn lại chia hiện tại; seating (số ít) là chủ ngữ, surround là vị ngữ chủ động → surrounds."),
          q("Recent research on battery life shows that the battery in our newest mobile phone ------- better than those in similar products.", ["perform", "performs", "performing", "performance"], "B", "Chủ ngữ the battery (số ít) → performs."),
          q("Customers may return any item within 30 days if they are not ------- with their purchase.", ["satisfactory", "satisfied", "satisfaction", "satisfy"], "B", "Tính từ bổ nghĩa cảm xúc cho they là satisfied."),
          q("Visitors to the Sydney Lab facilities must ------- by an employee at all times.", ["be accompanied", "accompany", "to accompany", "accompanying"], "A", "Dựa vào by phía sau chỗ trống → bị động."),
        ],
      },
    ],
  },
];
