import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "lien-tu-gioi-tu";

export const LIEN_TU_GIOI_TU_LESSONS: MasteryLesson[] = [
  {
    slug: "lien-tu-vi-tri-chuc-nang",
    chapter: CHAPTER,
    code: "Word Form",
    title: "Vị trí và chức năng của các từ liên kết",
    summary: "Phân biệt liên từ chính phụ, liên từ đẳng lập, trạng từ liên kết và giới từ dựa vào thành phần đứng sau chỗ trống.",
    blocks: [
      {
        type: "text",
        body: "Khi làm câu hỏi điền từ liên kết vào chỗ trống, cần chú ý đến **cấu trúc của phần phía sau chỗ trống** (là cụm danh từ, mệnh đề hay một câu) vì tuy các từ liên kết trong bốn phương án có thể có cùng ý nghĩa nhưng cách kết hợp ngữ pháp trong câu lại không giống nhau.",
      },
      {
        type: "qa",
        title: "Diagnostic test",
        instructions: "Điền các từ thích hợp vào chỗ trống: but (2), although, however, despite.",
        items: [
          { q: "------- the price was high, she still bought that beautiful dress.", a: "**Although.** Phía sau chỗ trống là một mệnh đề (the price: chủ ngữ, was high: vị ngữ). Although là liên từ chính phụ (subordinator) nên đi với mệnh đề." },
          { q: "The price was high, ------- she still bought that beautiful dress.", a: "**but.** Phía sau chỗ trống là mệnh đề, trước đó là dấu phẩy, nên điền liên từ đẳng lập (coordinator) but." },
          { q: "------- the high price, she still bought that beautiful dress.", a: "**Despite.** Phía sau chỗ trống là cụm danh từ (the high price: mạo từ + tính từ + danh từ) nên điền giới từ (preposition) despite." },
          { q: "The price was high. -------, she still bought that beautiful dress.", a: "**However.** Chỗ trống cần từ nối giữa hai câu, nên điền trạng từ liên kết (conjunctive adverb) however." },
          { q: "The dress was expensive ------- beautiful.", a: "**but** — nối giữa hai tính từ." },
        ],
      },
      {
        type: "list",
        title: "Learning point 1: Các loại liên từ hoặc giới từ",
        items: [
          "**Subordinator (liên từ chính phụ):** đi với mệnh đề phụ, nối giữa hai mệnh đề trong cùng một câu, có thể đứng đầu hoặc giữa câu. Although the price was high, she still bought that beautiful dress. / She still bought that beautiful dress although the price was high.",
          "**Coordinator (liên từ đẳng lập):** nối giữa hai mệnh đề hoặc hai thành phần tương đương, không đứng ở đầu câu trong văn viết. FANBOYS: For (vì), And (và), Nor (không), But (nhưng), Or (hoặc), Yet (nhưng), So (do đó). The price was high, but she still bought that beautiful dress. (but nối hai mệnh đề) / The dress was expensive but beautiful. (but nối hai tính từ)",
          "**Conjunctive adverbs (trạng từ liên kết):** nối giữa hai câu (ngăn cách nhau bởi dấu chấm hoặc dấu chấm phẩy). The price was high. However, she still bought that beautiful dress.",
          "**Prepositions (giới từ):** đi với cụm danh từ hoặc V-ing. Despite the high price, she still bought that beautiful dress.",
        ],
      },
      {
        type: "table",
        title: "Learning point 2: Bảng tổng hợp từ liên kết theo loại và nghĩa",
        headers: ["Nghĩa", "Subordinators", "Coordinators", "Conjunctive adverbs", "Prepositions"],
        rows: [
          ["bởi vì", "because, since, as", "for", "—", "because of, thanks to, owing to, due to"],
          ["cho nên, do đó", "—", "so", "therefore, consequently, as a result, thus", "—"],
          ["nhưng, tuy nhiên", "although, even though, though, even if", "but, yet", "nevertheless, however, nonetheless", "despite, in spite of, regardless of"],
          ["thêm vào, hơn nữa", "—", "and", "also, furthermore, moreover, in addition, additionally", "in addition to, apart from, except for, besides"],
          ["thay vì, hoặc", "—", "or", "—", "instead of"],
          ["nếu", "if, provided, providing, as long as, once", "—", "—", "—"],
          ["nếu không", "unless", "—", "—", "—"],
        ],
      },
    ],
    exercises: [
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("We will move into the new headquarters ------- the building is finished.", ["once", "even", "besides", "however"], "A", "The building is finished là mệnh đề nên đi với once. 'Chúng ta sẽ chuyển sang văn phòng mới khi tòa nhà được hoàn thiện.'"),
          q("In the decade ------- it was founded, Liu and Wang Corporation has become a legend in creative advertising.", ["however", "therefore", "so", "since"], "D", "Phía sau chỗ trống, it was founded là mệnh đề nên đi với since. 'Trong thập kỷ kể từ khi thành lập, Liu & Wang đã trở thành huyền thoại trong quảng cáo sáng tạo.'"),
          q("Aya Kodura maintained a rigorous practice schedule ------- her national tour.", ["during", "when", "although", "while"], "A", "Phía sau chỗ trống, her national tour, là cụm danh từ nên đi với giới từ during."),
          q("------- Malone Heating can provide same-day installation of heating units, an extra fee will be charged.", ["But", "Though", "Despite", "However"], "B", "Phía sau chỗ trống là mệnh đề nên đi với liên từ though. 'Mặc dù Malone Heating có thể lắp đặt thiết bị sưởi trong ngày, sẽ tính phí phụ.'"),
          q("------- the hypothesis, the results show something contrary.", ["In spite of", "Even though", "Because", "If"], "A", "The hypothesis là cụm danh từ nên đi cùng giới từ in spite of. 'Bất chấp giả thuyết, kết quả đưa ra hoàn toàn trái ngược.'"),
          q("Sometimes the job search is by choice; -------, the job search may result from a layoff.", ["nevertheless", "so", "neither", "when"], "A", "Phía sau chỗ trống là một câu (ngăn cách với câu trước bằng dấu chấm phẩy) nên đi với trạng từ liên kết nevertheless."),
          q("Alcohol was thought to be bad. -------, moderate alcohol consumption could have some health benefits.", ["Although", "After", "However", "Despite"], "C", "Phía sau chỗ trống là một câu (ngăn cách bằng dấu chấm) nên đi với trạng từ liên kết however."),
          q("He will contact our office ------- the brochure needs changing.", ["prevented from", "if", "asking for", "about"], "B", "Sau chỗ trống là mệnh đề nên chọn liên từ if. 'Anh ấy sẽ liên hệ văn phòng nếu cuốn sách quảng cáo cần thay đổi.'"),
          q("We made a significant profit last year ------- the losses of our international office.", ["although", "however", "despite", "as a result"], "C", "Phía sau chỗ trống là cụm danh từ nên chọn giới từ despite."),
          q("Ms. Adam refused the promotion ------- the large raise.", ["because", "but", "despite", "neither"], "C", "Sau chỗ trống là danh từ the large raise nên chọn giới từ despite. 'Cô Adam từ chối thăng chức mặc dù được tăng lương cao.'"),
          q("Restaurant food handlers must wear latex gloves ------- health regulations.", ["because of", "since", "because", "though"], "A", "Sau chỗ trống là cụm danh từ health regulations nên chọn giới từ because of."),
          q("------- you listen to your body more, you will know when your body starts to break down.", ["Or", "And", "If", "Furthermore"], "C", "Phía sau chỗ trống là mệnh đề nên chọn liên từ if. Lưu ý or và and không đứng ở đầu câu."),
          q("The seminar is open to part-time ------- full-time employees.", ["and", "addition", "not", "to"], "A", "Part-time và full-time là hai từ có nghĩa và cách thức tương đương nên chọn and."),
          q("The theatre will raise ticket prices ------- the expensive new sound and lighting system.", ["when", "because", "due to", "despite of"], "C", "Phía sau chỗ trống là cụm danh từ nên chọn giới từ due to."),
          q("------- her experience in sales, Ms. Woo has a background in public relations.", ["Although", "Besides", "Whether", "Until"], "B", "Sau chỗ trống là cụm danh từ nên chọn giới từ besides. 'Ngoài kinh nghiệm bán hàng, cô Woo còn có kinh nghiệm trong lĩnh vực quan hệ công chúng.'"),
          q("------- this quarter's sales are high, we are all getting bonuses.", ["In case of", "After all", "Since", "Subsequent to"], "C", "Sau chỗ trống là mệnh đề nên chọn liên từ since."),
          q("------- the new office building is occupied, construction vehicles will not be allowed into the parking area.", ["Once", "Next", "On", "But"], "A", "Sau chỗ trống là mệnh đề nên chọn liên từ once."),
          q("------- repeated delays in construction, the new supermarket was finished in time.", ["Despite", "Although", "When", "After that"], "A", "Sau chỗ trống là cụm danh từ (repeated – adj, delays in construction – n) nên chọn giới từ despite."),
          q("------- she has been here for only two years, she has already worked on very high-profile projects.", ["Although", "Moreover", "Despite", "Yet"], "A", "Sau chỗ trống là mệnh đề nên chọn liên từ although (tuy rằng)."),
          q("We are going to replace the old elevator. -------, a new staircase will also be installed.", ["Moreover", "In", "And", "So"], "A", "Sau chỗ trống là một câu (ngăn cách bằng dấu chấm) nên chọn trạng từ liên kết moreover (hơn nữa)."),
        ],
      },
    ],
  },
  {
    slug: "lien-tu-nghia",
    chapter: CHAPTER,
    code: "Word Choice 1",
    title: "Câu hỏi về nghĩa của các từ liên kết",
    summary: "Khi có từ hai phương án đúng ngữ pháp trở lên, xét nghĩa; nắm chắc các cặp từ liên kết.",
    blocks: [
      {
        type: "text",
        body: "Nếu trong bốn phương án có ít nhất hai phương án phù hợp với cấu trúc ngữ pháp của câu, cần xét đến **nghĩa của câu** và nghĩa của các phương án đó. Nghĩa của các từ liên kết được chia thành hai nhóm: **từ liên kết đơn** và **từ liên kết đôi** (cặp từ liên kết luôn đi cùng với nhau).",
      },
      {
        type: "note",
        title: "Learning point 1: Nghĩa của các từ liên kết đơn",
        body: "Xem lại bảng tổng hợp liên từ ở bài Word Form (Vị trí và chức năng của các từ liên kết).",
      },
      {
        type: "table",
        title: "Learning point 2: Nghĩa của các cặp từ liên kết",
        headers: ["Cặp từ liên kết", "Nghĩa", "Ví dụ"],
        rows: [
          ["Either … or …", "một trong hai", "either the president or the manager"],
          ["Neither … nor …", "cả hai đều không", "neither the president nor the manager"],
          ["Both … and …", "cả hai", "both the president and the manager"],
          ["Not only … but also …", "không những … mà còn …", "not only the president but also the manager"],
          ["Between … and …", "giữa hai người/vật, từ … đến …", "choose between the president and the manager; between 10 p.m. and 11 p.m."],
          ["Whether … or …", "cho dù … hay là …", "whether you are buying or selling a house"],
        ],
      },
      {
        type: "note",
        body: "Khi làm câu hỏi kiểm tra các cặp từ liên kết, cần dựa vào từ liên kết đã cho sẵn trong câu và dịch nghĩa nếu cần thiết.",
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("[-------] profits have improved, we are all getting bonuses.", ["Since", "Although"], "A", "'Lợi nhuận tăng' và 'được thưởng' là hai ý mang quan hệ nguyên nhân – kết quả nên chọn since (bởi vì)."),
          q("Ms. Adam was not accepted to the position [-------] her rich experience.", ["because of", "despite"], "B", "'Không được nhận vào làm' và 'giàu kinh nghiệm' là hai ý trái ngược nên chọn despite (mặc dù)."),
          q("Smoking is bad for health. [-------], many smokers find it hard to give it up.", ["However", "Therefore"], "A", "'Hút thuốc có hại cho sức khỏe' và 'nhiều người rất khó bỏ' là hai ý đối lập nên chọn However (tuy nhiên)."),
          q("It's not our policy to grant sick leave [-------] overtime pay to part-time employees.", ["or", "but"], "A", "'Công ty không có chính sách cho nghỉ ốm hoặc trả tiền làm thêm giờ cho nhân viên bán thời gian' → or (hoặc)."),
          q("[-------] 9 a.m. and 12 p.m., we are going to welcome visitors.", ["Either", "Between"], "B", "Phía sau đã có từ and nên chọn between. Cụm between … and … nghĩa là 'giữa … và …, từ … đến …'."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("You can enter the club ------- you are a member.", ["if", "although", "despite", "before"], "A", "Phía sau chỗ trống là mệnh đề nên loại despite. Dịch nghĩa 'Bạn có thể vào câu lạc bộ nếu bạn là thành viên' → if."),
          q("She couldn't eat ------- she was hungry.", ["however", "even though", "because", "despite"], "B", "Phía sau là mệnh đề nên loại however và despite. Dịch nghĩa 'Cô ấy không thể ăn mặc dù rất đói' → even though."),
          q("The shop is open ------- 9:30 and 5:30.", ["between", "from", "both", "either"], "A", "Between … and …: từ lúc … đến lúc … 'Cửa hàng mở từ 9 rưỡi đến 5 rưỡi.'"),
          q("Neither Ms. Chen ------- Mr. Martinez was able to attend the seminar.", ["nor", "neither", "and", "or"], "A", "Neither … nor. 'Cả cô Chen và anh Martinez đều không thể tham gia buổi hội thảo được.'"),
          q("The outdoor ceremony won't be postponed ------- it looks like rain.", ["because", "though", "since", "neither"], "B", "Dịch nghĩa 'Buổi lễ ngoài trời sẽ không bị hoãn lại mặc dù trời có vẻ mưa' → though."),
          q("The hotel will accept no guests ------- it is being renovated.", ["while", "after", "therefore", "due to"], "A", "Phía sau chỗ trống là mệnh đề nên loại due to. Dịch nghĩa 'Khách sạn sẽ không nhận khách khi đang nâng cấp' → while."),
          q("------- to the airline tickets, Mr. Jones had to postpone his business trip to Rome.", ["Owed", "Because", "Due", "As"], "C", "Dựa vào từ to và cụm danh từ the airline tickets → Due (due to). 'Bởi vì vé máy bay mà ông Jones đã phải hoãn chuyến công tác tới Rome.'"),
          q("I think you would be great in recruiting ------- you are energetic and communicate well.", ["since", "due to", "unless", "even though"], "A", "Sau chỗ trống là mệnh đề nên loại due to. Dịch nghĩa 'Tôi nghĩ bạn sẽ làm tốt việc tuyển dụng vì bạn nhiệt tình và giao tiếp tốt' → since."),
          q("Candidates should have strong research skills, be fluent in English ------- have a college degree in business.", ["but", "either", "and", "both"], "C", "And nối giữa các động từ nguyên thể have, be, have. 'Ứng viên nên có kỹ năng nghiên cứu tốt, thành thạo tiếng Anh và có bằng cao đẳng kinh doanh.'"),
          q("Applicants should not only have a degree in social science ------- also have at least four years of experience in a research faculty.", ["and", "but", "or", "nor"], "B", "Not only … but also. 'Ứng viên không chỉ cần có bằng về khoa học xã hội mà còn cần ít nhất bốn năm kinh nghiệm làm việc ở một viện nghiên cứu.'"),
          q("The bank will maintain exceptional service ------- renovations are underway in several branches.", ["although", "despite", "in spite", "however"], "A", "Phía sau chỗ trống là mệnh đề nên loại despite, in spite và however. 'Ngân hàng sẽ duy trì dịch vụ tốt nhất mặc dù nhiều chi nhánh đang nâng cấp.'"),
          q("To prepare for the marathon, I ran 15 kilometers three ------- four days a week.", ["either", "only", "but", "or"], "D", "Three và four là hai từ có nghĩa tương đương (số) nên chọn or. 'Để chuẩn bị chạy marathon, tôi đã chạy 15 km ba hoặc bốn ngày một tuần.'"),
          q("------- the housekeeping staff was getting the room ready, I decided to wait outside.", ["Although", "While", "For", "But"], "B", "For và but không đứng đầu câu. 'Trong khi những người dọn phòng đang dọn dẹp, tôi quyết định đợi ở bên ngoài.'"),
          q("Those in research positions are responsible for compiling and ------- research data.", ["store", "storage", "storing", "to store"], "C", "And nối giữa hai từ có cấu tạo tương đương là compiling và storing."),
          q("Development expenditures are expected to grow in ------- the private and public sectors.", ["both", "either", "neither", "not only"], "A", "Both … and. 'Chi tiêu phát triển được kỳ vọng sẽ tăng ở cả khu vực tư nhân và nhà nước.'"),
          q("If this notice was sent in error, please contact us either by telephone ------- by email.", ["and", "or", "nor", "but"], "B", "Either … or."),
          q("I had to wait for an hour for my food ------- the fact that the restaurant was rather empty.", ["although", "nevertheless", "despite", "without"], "C", "Sau chỗ trống là cụm danh từ (the fact là danh từ chính, that the restaurant was rather empty là mệnh đề giải thích)."),
          q("The conference was postponed ------- the small number of attendees.", ["due to", "owed", "despite", "resulting in"], "A", "'Hội thảo bị hoãn vì số lượng người tham gia thấp.'"),
          q("The casual ------- professional environment will allow attendees to have an open conversation.", ["nor", "but", "as", "though"], "B", "Casual và professional là hai từ trái nghĩa (thoải mái – chuyên nghiệp) → but."),
          q("------- some oil in the state of Oklahoma is exported to the Far East, most of it is consumed within the country.", ["Because", "Both", "Yet", "While"], "D", "Phía sau là mệnh đề nên loại Both. Yet không đứng đầu câu. 'Trong khi dầu ở Oklahoma được xuất khẩu sang Viễn Đông, phần lớn được tiêu thụ ngay trong nước.'"),
        ],
      },
    ],
  },
  {
    slug: "gioi-tu-pho-bien",
    chapter: CHAPTER,
    code: "Word Choice 2",
    title: "Các giới từ phổ biến trong đề thi TOEIC",
    summary: "Giới từ chỉ thời gian, địa điểm và các cụm giới từ cố định hay gặp trong Part 5-6.",
    blocks: [
      {
        type: "table",
        title: "Learning point 1: Các giới từ chỉ thời gian",
        headers: ["Giới từ", "Nghĩa", "Kết hợp với", "Ví dụ"],
        rows: [
          ["in", "vào", "tháng, năm, mùa, quý", "in September, in 1990, in spring, in the second quarter"],
          ["on", "vào", "ngày, thứ", "on Monday, on April 7th"],
          ["at", "tại thời điểm", "thời gian chính xác", "at 7 o'clock, at noon, at night, at the beginning of the month"],
          ["during, throughout", "trong suốt", "danh từ chỉ khoảng thời gian", "during my stay at the hotel, throughout the day"],
          ["within", "trong vòng", "+ số + danh từ", "within 30 minutes, within 10 days of purchase"],
          ["prior to = before = by", "trước", "mốc thời gian", "prior to my visit, before my visit, by the time I visited"],
          ["after = following", "sau", "mốc thời gian", "following our disputes"],
        ],
      },
      {
        type: "table",
        title: "Learning point 2: Các giới từ chỉ địa điểm",
        headers: ["Giới từ", "Nghĩa", "Kết hợp với", "Ví dụ"],
        rows: [
          ["in", "ở, tại", "tên nước, thành phố, không gian", "in Korea, in Seoul, in the auditorium"],
          ["on", "phía trên", "địa điểm", "on the fourth floor of the building"],
          ["at", "ở, tại", "địa điểm nhỏ, xác định", "at the entrance of the conference room"],
          ["throughout", "trên khắp", "địa điểm", "throughout the world"],
          ["within", "trong", "địa điểm", "within our store"],
        ],
      },
      {
        type: "table",
        title: "Learning point 3: Các giới từ khác",
        headers: ["Giới từ", "Nghĩa", "Ví dụ"],
        rows: [
          ["by, through + phương tiện", "thông qua / bằng cách nào", "by train, through the use of the automated system"],
          ["decrease, fall, reduction / increase, rise, raise in something", "giảm / tăng về lĩnh vực gì", "the decrease in oil price, an increase in pay"],
          ["increase by + số lượng", "tăng thêm bao nhiêu", "increase by 50%"],
          ["regarding, concerning, on, over, about", "về, liên quan đến", "an agreement on trading policies"],
          ["come into effect", "có hiệu lực", "new laws coming into effect"],
          ["rely / depend on", "phụ thuộc vào", "depend on outside sources"],
          ["in accordance with / in compliance with / in line with + rules/laws", "phù hợp với, tuân theo", "The plan is in accordance with our company's policy."],
          ["comply with / abide by / adhere to + rules/laws", "tuân theo", "abide by the rules when doing business"],
          ["ahead of schedule / on schedule / behind schedule", "trước kế hoạch / đúng kế hoạch / chậm tiến độ", "We completed it ahead of schedule / on schedule / behind schedule."],
          ["on behalf of someone", "thay mặt cho", "I'm writing on behalf of my manager."],
          ["according to something", "theo như", "according to the terms of the contract"],
          ["in advance", "trước", "pay in advance"],
          ["at + price, cost", "với giá / chi phí bao nhiêu", "I got it at a cheap price."],
          ["as + job / position", "làm nghề / giữ chức vụ gì", "as a teacher, as a manager"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: ["Từ / cụm từ", "Từ loại", "Nghĩa"],
        rows: [
          ["(pay) raise", "n", "tăng lương"],
          ["admission", "n", "sự cho vào cửa"],
          ["casual", "adj", "thông thường, thoải mái"],
          ["health regulations", "n", "quy định an toàn sức khỏe"],
          ["occupied", "adj", "đã có người sử dụng"],
          ["production facility", "n", "cơ sở sản xuất"],
          ["professional", "adj", "chuyên nghiệp"],
          ["promotion", "n", "sự thăng chức"],
        ],
      },
    ],
    exercises: [
      {
        title: "Check-up 1 — Giới từ chỉ thời gian",
        kind: "practice",
        questions: [
          q("The presentation starts ------- 9:30 in the conference room.", ["at", "in", "on", "within"], "A", "Trước giờ dùng at. 'Bài thuyết trình bắt đầu lúc 9:30 ở phòng họp.'"),
          q("Please hand in that report ------- Friday afternoon.", ["by", "at", "in", "over"], "A", "By: trước, chậm nhất là. 'Hãy nộp bản báo cáo đó trước chiều thứ Sáu.'"),
          q("------- my stay at AZ hotel, I received excellent catering services.", ["Within", "During", "While", "Through"], "B", "'Trong suốt thời gian tôi ở khách sạn AZ, tôi đã nhận được dịch vụ phục vụ rất tốt.'"),
          q("------- months of little rain, the city announced a serious drought.", ["Following", "In", "When", "At"], "A", "Following = after. 'Sau nhiều tháng ít mưa, thành phố tuyên bố một đợt hạn hán nghiêm trọng.'"),
          q("------- the third quarter, we witnessed a significant increase in sales figures.", ["On", "To", "At", "In"], "D", "In + quarter. 'Trong quý ba, chúng ta đã chứng kiến doanh số tăng đáng kể.'"),
        ],
      },
      {
        title: "Check-up 2 — Giới từ chỉ địa điểm",
        kind: "practice",
        questions: [
          q("The mail carrier left the mail ------- the secretary's desk.", ["to", "on", "at", "above"], "B", "'Người đưa thư để lại thư trên bàn của thư ký.'"),
          q("The main office is located ------- the fifth floor.", ["at", "in", "on", "throughout"], "C", "On + tầng. 'Văn phòng chính ở tầng năm.'"),
          q("The flyers of the show were distributed ------- the region.", ["on", "at", "throughout", "from"], "C", "Throughout + địa điểm: trên khắp. 'Tờ rơi của chương trình được phát trên khắp vùng.'"),
          q("Though nice, the benefits package is only promoted ------- the company.", ["within", "with", "on", "through"], "A", "Within the company: trong nội bộ công ty."),
          q("I am going to have an appointment with my doctor ------- his office.", ["on", "to", "at", "with"], "C", "At + his office (địa điểm nhỏ). 'Tôi sắp có cuộc hẹn với bác sĩ tại văn phòng của ông ấy.'"),
        ],
      },
      {
        title: "Check-up 3 — Các giới từ khác",
        kind: "practice",
        questions: [
          q("Passengers are advised to arrive at least two hours ------- departure.", ["instead of", "behind", "prior to", "according to"], "C", "Prior to = before. 'Hành khách nên đến hai tiếng trước khi khởi hành.'"),
          q("We are collecting our defective products and upgrading them ------- no additional cost.", ["in", "with", "at", "on"], "C", "At no additional cost: không tính thêm phí."),
          q("------- a recent survey, the item is not very popular.", ["According to", "On behalf of", "With", "Regarding"], "A", "'Theo một khảo sát gần đây, mặt hàng này không phổ biến lắm.'"),
          q("------- behalf of the CEO, I present this award to Mr. Hu.", ["On", "In", "With", "To"], "A", "On behalf of: thay mặt cho."),
          q("Thanks to their hard work, they finished the report ------- schedule.", ["at", "ahead", "on", "beside"], "C", "On schedule: đúng kế hoạch, đúng thời hạn."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("The announcement stated that the office would close ------- 4:00 p.m. today due to heavy rain.", ["in", "on", "at", "for"], "C", "At + giờ. 'Thông báo nói rằng văn phòng sẽ đóng cửa lúc 4 giờ chiều vì mưa to.'"),
          q("If you are not happy with this audio set, you should return it ------- two weeks for a full refund.", ["within", "for", "until", "during"], "A", "Within đứng trước số liệu (two weeks)."),
          q("If you have a membership card number, you can make a purchase ------- phone.", ["by", "in", "to", "within"], "A", "By phone: bằng điện thoại."),
          q("The budget plan ------- the next five years has been sent to the board of directors.", ["by", "for", "since", "beyond"], "B", "For + khoảng thời gian. 'Kế hoạch ngân sách cho năm năm tới đã được gửi tới ban giám đốc.'"),
          q("The cost of the flight, rental car and hotel room will be paid ------- by the company.", ["before", "behind", "in advance", "prior"], "C", "In advance: trước. 'Tiền vé máy bay, thuê xe và khách sạn sẽ được công ty trả trước.'"),
          q("To take advantage of this special offer, customers must purchase our software ------- January 2 and March 3.", ["on", "in", "either", "between"], "D", "Between … and …: trong khoảng từ … đến …"),
          q("This website provides information ------- products and services offered by us.", ["regard", "regarding", "regards", "regarded"], "B", "Regarding = about: về."),
          q("HCB Bank cannot accept a loan application ------- the proper document.", ["upon", "until", "along", "without"], "D", "'Ngân hàng HCB sẽ không chấp nhận đơn vay tiền mà không có giấy tờ hợp lệ.'"),
          q("Tang Corporation has reserved a conference hall at the Darlington Hotel ------- the annual sales meeting.", ["from", "onto", "for", "off"], "C", "For: cho (mục đích). 'Tập đoàn Tang đã đặt phòng hội nghị cho cuộc họp doanh số thường niên.'"),
          q("------- the news article, the new drug could have a negative impact on our health.", ["In case", "Under", "According to", "Beyond"], "C", "'Theo như một bài báo, loại thuốc mới có tác động xấu tới sức khỏe.'"),
          q("The expansion ------- the international market will help us to find a way to survive in fierce competition.", ["except", "until", "as", "of"], "D", "Giữa hai danh từ là of: the expansion of the international market."),
          q("I am writing ------- behalf of Ms. Jackson to inform you of the annual sales meeting.", ["at", "on", "for", "to"], "B", "On behalf of: thay mặt cho ai."),
          q("The changes occurring ------- the electronics industry reflect the efforts to meet customers' needs.", ["into", "during", "as", "throughout"], "D", "'Những thay đổi diễn ra trên khắp ngành điện tử phản ánh nỗ lực đáp ứng nhu cầu khách hàng.'"),
          q("Jazz Friday will take place as usual ------- a ticket price of $9 per person.", ["at", "for", "with", "in"], "A", "At + price: với giá bao nhiêu."),
          q("------- company regulations, all employees will be considered for a yearly performance-based pay raise.", ["In case of", "On behalf of", "According to", "In advance"], "C", "'Theo quy định của công ty, tất cả nhân viên sẽ được xem xét tăng lương hàng năm dựa vào năng lực.'"),
          q("Those who have questions ------- the advertising job should consult the company's website.", ["in", "so", "about", "following"], "C", "About: về. 'Những ai có câu hỏi về công việc quảng cáo nên tham khảo trang web của công ty.'"),
          q("------- his service time as a faculty member, Professor Michelson developed the image of a dedicated researcher.", ["Into", "Upon", "Within", "During"], "D", "'Trong suốt thời gian làm thành viên của khoa, giáo sư Michelson đã tạo dựng hình ảnh một nhà nghiên cứu tận tâm.'"),
          q("The software company offers training to newly-recruited employees ------- Atlanta.", ["in", "on", "by", "to"], "A", "In + tên thành phố."),
          q("The book that you borrowed is due ------- Monday, but you can always renew it by coming to the check-out desk.", ["at", "by", "to", "in"], "B", "By + mốc thời gian: chậm nhất là. 'Sách bạn mượn sẽ hết hạn vào thứ Hai, nhưng bạn có thể gia hạn bằng cách đến quầy mượn sách.'"),
          q("Have you read this article ------- our competitors' new product launch?", ["regarding", "in", "above", "for"], "A", "Regarding = about."),
        ],
      },
    ],
  },
  {
    slug: "lien-tu-gioi-tu-review-test",
    chapter: CHAPTER,
    code: "Review Test",
    title: "Conjunctions and Prepositions — Review Test",
    summary: "Bài kiểm tra tổng hợp 30 câu về liên từ, trạng từ liên kết và giới từ.",
    blocks: [],
    exercises: [
      {
        title: "Conjunctions and Prepositions — Review Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Carro Rentals offers flexible rate plans that make renting a car easy, whether for business ------- pleasure.", ["or", "and", "if", "either"], "A", "Whether … or. 'Carro Rentals cung cấp giá linh hoạt khiến việc thuê xe dễ dàng, cho dù là đi công tác hay đi giải trí.'"),
          q("The producer decided to add more performances ------- positive response to early shows.", ["because of", "while", "in fact", "as soon as"], "A", "Sau chỗ trống là cụm danh từ nên chọn giới từ because of."),
          q("------- offering lightweight clothing, Hurvitz Travel Wear also sells stylish luggage.", ["Except", "Besides", "However", "Unless"], "B", "Giới từ besides (ngoài ra) đi với V-ing. 'Ngoài việc bán quần áo nhẹ, Hurvitz Travel Wear còn bán va li thời trang.'"),
          q("Mr. Gupta is ------- the few scientists who have received the award.", ["about", "from", "among", "as"], "C", "Among: một trong số nhiều … 'Ông Gupta là một trong số ít nhà khoa học nhận được giải thưởng.'"),
          q("Our company has maintained its popularity with customers ------- the growing competition from larger stores that have moved into the area.", ["until", "even though", "in case", "despite"], "D", "Sau chỗ trống là cụm danh từ the growing competition (danh từ chính) + định ngữ bổ sung → despite."),
          q("Employees must wear all the protective gear shown on the poster at the lab entrance, ------- safety regulations.", ["provided that", "now that", "extending", "in keeping with"], "D", "Safety regulations là cụm danh từ, nên chọn giới từ in keeping with (tuân thủ)."),
          q("The annual report indicates significant growth ------- the past several years.", ["onto", "over", "while", "than"], "B", "Over the past several years: trong vài năm vừa qua."),
          q("------- the Kendal company has been in business for only nine months, it has very quickly become profitable.", ["Although", "Unless", "Before", "During"], "A", "Phía sau chỗ trống là mệnh đề nên loại giới từ During. 'Mặc dù công ty Kendal mới kinh doanh 9 tháng nhưng đã thu được nhiều lợi nhuận.'"),
          q("Sleeping-car passengers will be provided ------- the bedding they need for the journey.", ["with", "for", "to", "of"], "A", "Provide somebody with something."),
          q("It has been projected that sales of organic food will increase ------- 20% this year.", ["by", "after", "from", "across"], "A", "Increase by: tăng thêm bao nhiêu."),
          q("------- project manager, Ms. Chung will be directly responsible to the company president.", ["Throughout", "Aside", "Plus", "As"], "D", "As + chức danh: giữ chức vụ gì."),
          q("The last shipment was refused by the buyer ------- damage during transit.", ["according to", "because of", "result", "since"], "B", "Phía sau chỗ trống là cụm danh từ nên loại result và since. 'Đơn hàng cuối bị người mua từ chối vì hư hỏng trong quá trình vận chuyển.'"),
          q("It is always advisable to verify departure times, ------- flight schedules may change after a ticket is issued.", ["therefore", "since", "against", "concerning"], "B", "Phía sau là mệnh đề nên loại giới từ against, concerning và trạng từ liên kết therefore."),
          q("------- or not Dr. Danawala accepts the position, we will need to hire at least two more physicians.", ["Whether", "So", "Either", "If"], "A", "Whether or not: cho dù có … hay không."),
          q("Ms. Kim is planning to attend the meeting, ------- it is not necessary for her to be there.", ["where", "due to", "although", "or"], "C", "Phía sau là mệnh đề, nghĩa đối lập → although."),
          q("Ms. Choi is not only a good public speaker ------- also a talented writer.", ["both", "if", "nor", "but"], "D", "Not only … but also."),
          q("------- rigorous coursework, the certificate program also includes 100 hours of training.", ["Since", "Along", "Besides", "Resulting"], "C", "Sau chỗ trống là danh từ nên chọn giới từ besides."),
          q("Not long ------- leaving our company, Mr. Saito began working at a government agency.", ["around", "off", "over", "after"], "D", "'Không lâu sau khi rời công ty chúng tôi, ông Saito đã làm việc ở một cơ quan chính phủ.'"),
          q("Admission is free for children three years of age and -------.", ["until", "through", "between", "under"], "D", "'Trẻ em từ ba tuổi trở xuống được miễn phí vào cửa.'"),
          q("Perhaps ------- their greater flexibility, smaller companies may be able to react more quickly to economic fluctuations.", ["even if", "owing to", "not", "as"], "B", "Phía sau là cụm danh từ nên chọn giới từ owing to = because of."),
          q("------- he arrives at the airport in the next ten minutes, Mr. Santini is going to have to take a later flight.", ["Regardless", "While", "Unless", "However"], "C", "Phía sau là mệnh đề nên loại regardless và however. 'Nếu không đến sân bay trong 10 phút tới, ông Santini sẽ phải đi chuyến muộn hơn' → Unless."),
          q("Ms. Ambani does not speak French, ------- she is fluent in Mandarin.", ["or", "but", "not", "what"], "B", "'Cô Ambani không nói tiếng Pháp, nhưng cô ấy nói thành thạo tiếng Quan Thoại.'"),
          q("Please read the instructions ------- start to finish before replacing the air filter yourself.", ["of", "from", "by", "during"], "B", "From … to: từ … đến …"),
          q("------- a lot of meetings, the board of directors finally agreed on the new product design.", ["Follow", "Following", "To follow", "Follows"], "B", "Following = after (giới từ)."),
          q("------- all applications for the position are received, the committee will determine a list of people to be interviewed.", ["About", "Except", "After", "With"], "C", "Phía sau là mệnh đề nên loại ba phương án là giới từ → After."),
          q("The company was reluctant to expand its production facilities ------- the rise in demand.", ["although", "even if", "despite", "nevertheless"], "C", "Phía sau là cụm danh từ nên chọn giới từ despite."),
          q("Please call our office to schedule your interview ------- six business days of receiving this notice.", ["with", "during", "while", "within"], "D", "Trước số từ six chọn within."),
          q("It is illegal to drive on public roads ------- a driver's license.", ["without", "unless", "even", "although"], "A", "'Lái xe trên đường công cộng mà không có bằng lái là trái phép.'"),
          q("Parking meters are in effect ------- the holiday season.", ["upon", "inside", "during", "along"], "C", "Giới từ chỉ thời gian đi với the holiday season là during."),
          q("------- a few flaws, Ms. Shaw's proposal for the local shopping mall construction project will probably be adopted.", ["Besides", "Unless", "Despite", "Towards"], "C", "Phía sau là danh từ nên loại liên từ Unless. 'Mặc dù có vài lỗi, đề xuất của cô Shaw có lẽ sẽ được chấp nhận.'"),
        ],
      },
    ],
  },
];
