import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "tinh-tu-trang-tu";
const VOCAB_HEADERS = ["Từ / cụm từ", "Từ loại", "Nghĩa"];

export const TINH_TU_TRANG_TU_LESSONS: MasteryLesson[] = [
  {
    slug: "vi-tri-tinh-tu-trang-tu",
    chapter: CHAPTER,
    code: "Word Form 1",
    title: "Xác định vị trí của tính từ hoặc trạng từ",
    summary: "Tính từ bổ nghĩa cho danh từ và đứng sau động từ liên kết; trạng từ bổ nghĩa cho động từ, tính từ, trạng từ và cả câu.",
    blocks: [
      {
        type: "text",
        title: "Introduction",
        body: "Bài học này cung cấp các kỹ năng làm bài dạng câu hỏi nhận biết tính từ và trạng từ:\n• Cách phân biệt vị trí của tính từ và trạng từ trong câu\n• Các tính từ và trạng từ đặc biệt\n• Cách phân biệt các dạng so sánh của tính từ và trạng từ.\nThông thường tính từ và trạng từ được phân biệt bởi dấu hiệu: phía sau trạng từ thường có hậu tố **-ly**, còn tính từ thì không.",
      },
      {
        type: "list",
        title: "Learning point 1: Vị trí của tính từ trong câu",
        items: [
          "Đứng **trước danh từ**: a foreseeable future, potential customers.",
          "Đứng sau các **động từ liên kết**: be, look, seem, get, become, prove, feel, remain, keep.",
          "Dùng trong các cấu trúc: **find + O + adj** (cảm thấy ai đó/điều gì như thế nào): I find my job rewarding; **make + O + adj** (khiến cho ai đó cảm thấy thế nào): Listening to music makes me relaxed.",
          "**Lưu ý:** Sau find thường là tính từ dạng V-ing chỉ tính chất, và sau make (+ người) là tính từ dạng VpII chỉ cảm xúc.",
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Vị trí của trạng từ trong câu",
        items: [
          "Bổ nghĩa cho **động từ**: increase dramatically, sit quietly.",
          "Bổ nghĩa cho **tính từ hoặc trạng từ khác**: extremely profitable, play fairly well.",
          "Bổ nghĩa cho **cả câu**: Luckily, I passed the test.",
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["aggressive", "adj", "quyết liệt, táo bạo"],
          ["collaboratively", "adv", "hợp tác"],
          ["confidential", "adj", "bảo mật"],
          ["currently", "adv", "hiện tại"],
          ["doubtful", "adj", "hoài nghi"],
          ["favorable", "adj", "thuận lợi"],
          ["merger", "n", "sự sáp nhập"],
          ["reduced", "adj", "(được) giảm"],
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("This survey is for [-------] customers.", ["potential", "potentially"], "A", "Tính từ đứng trước và bổ nghĩa cho danh từ customers → potential (tiềm năng)."),
          q("Please keep [-------] during the presentation.", ["silent", "silently"], "A", "Tính từ đứng sau động từ liên kết keep → silent (im lặng)."),
          q("She runs the company very [-------].", ["effective", "effectively"], "B", "Trạng từ bổ nghĩa cho cụm động từ run the company → effectively (một cách hiệu quả)."),
          q("I find it [-------] to be part of this project.", ["interesting", "interestingly"], "A", "Cấu trúc cố định find it + adj (thấy cái gì như thế nào) → interesting."),
          q("The new business contract is [-------] profitable.", ["extreme", "extremely"], "B", "Trước tính từ profitable cần trạng từ bổ nghĩa → extremely."),
          q("She plays the guitar [-------] well.", ["fair", "fairly"], "B", "Trạng từ well bổ nghĩa cho play the guitar; trước well là một trạng từ khác chỉ mức độ → fairly (tương đối, khá)."),
          q("[-------], there was a loud noise.", ["Sudden", "Suddenly"], "B", "Trạng từ đứng đầu và bổ nghĩa cho cả câu → Suddenly (một cách đột ngột)."),
          q("Writing reports makes me [-------].", ["tired", "tiredly"], "A", "Cấu trúc cố định make + O + adj (khiến ai đó cảm thấy thế nào) → tired (mệt mỏi)."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Leslie was extremely ------- to hear that his friend is now able to enjoy some leisure time.", ["happy", "happily", "happiness", "unhappily"], "A", "Tính từ đi sau động từ to be. 'Leslie cực kỳ vui khi nghe rằng bạn anh ấy cuối cùng cũng có thời gian nghỉ ngơi.'"),
          q("People agreed that John would have performed better under more ------- circumstances.", ["favorite", "favorable", "favor", "favorably"], "B", "Tính từ bổ nghĩa cho danh từ circumstances. favorite: ưa thích; favorable: thuận lợi → B."),
          q("Should there be any requests for schedule changes, please notify us -------.", ["prompt", "prompted", "promptly", "prompting"], "C", "Trạng từ bổ nghĩa cho động từ notify. 'Nếu có yêu cầu thay đổi lịch trình, hãy thông báo cho chúng tôi ngay lập tức.'"),
          q("The hard work put in during his younger years made him become ------- sound in his later years.", ["finance", "financial", "financially", "finances"], "C", "Become sound: trở nên ổn định (become đi với tính từ sound). Bổ nghĩa cho tính từ sound là trạng từ financially."),
          q("One of the reasons for constant training in our department is to help our employees keep up with the ------- change in the market.", ["continuous", "continuously", "continue", "continuity"], "A", "Tính từ bổ nghĩa cho danh từ change (trước chỗ trống là mạo từ the nên change là danh từ)."),
          q("The government issued a warning to local companies that all waste must be disposed of -------.", ["correct", "correcting", "corrects", "correctly"], "D", "Trạng từ bổ nghĩa cho động từ dispose of (vứt bỏ, xử lý)."),
          q("Jeff has been performing ------- better since the playoffs started.", ["significance", "significant", "significantly", "signify"], "C", "Trạng từ bổ nghĩa cho trạng từ better."),
          q("It is easy to read Sam because he ------- squints when he finds himself in an uncomfortable situation.", ["habitual", "habit", "habitually", "habits"], "C", "Trạng từ bổ nghĩa cho động từ squint."),
          q("Our ------- seminars allow staff members to develop their skills in various directions.", ["professional", "profession", "professionally", "professionalism"], "A", "Tính từ bổ nghĩa cho danh từ seminars."),
          q("The new director tries to run the company as ------- as possible to avoid bankruptcy.", ["efficient", "efficiently", "efficiency", "effective"], "B", "Trạng từ bổ nghĩa cho động từ run."),
          q("A recent survey showed that the tax increase has been ------- unpopular.", ["predict", "prediction", "to predict", "predictably"], "D", "Trạng từ bổ nghĩa cho tính từ unpopular."),
          q("These days managers and designers are expected to work ------- to a greater extent than in the past.", ["collaboratively", "collaborative", "collaboration", "collaborate"], "A", "Trạng từ bổ nghĩa cho động từ work."),
          q("It remains ------- that a merger will increase profitability in the medium term.", ["doubt", "doubts", "doubtful", "doubtfully"], "C", "Sau động từ remain là tính từ."),
          q("Aggressive marketing strategies will be implemented for a highly ------- novel from China.", ["anticipating", "anticipated", "anticipate", "anticipation"], "B", "Highly anticipated: rất được mong đợi (tính từ bổ sung ý nghĩa bị động)."),
          q("We are ------- recruiting new university graduates to join our team of successful sales representatives.", ["current", "currently", "currency", "currents"], "B", "Trạng từ bổ nghĩa cho động từ recruit."),
          q("A number of proposals for the museum relocation project have been submitted by ------- developers.", ["locate", "location", "local", "locally"], "C", "Tính từ local bổ nghĩa cho danh từ developers."),
          q("After ------- requests by local residents, the city government opened the private library to the public.", ["repeated", "repeating", "repeat", "repetition"], "A", "Tính từ bổ sung ý nghĩa bị động (by local residents)."),
          q("As you are ordering a large quantity, we will offer you the item at ------- reduced prices.", ["substantial", "substantially", "substantiality", "substantiate"], "B", "Trạng từ bổ nghĩa cho tính từ reduced."),
          q("The actor was ------- unknown, but his work on the original design was brilliant.", ["relative", "relatively", "relate", "relativity"], "B", "Trạng từ bổ nghĩa cho tính từ unknown."),
          q("The results of the study should remain ------- until they are released to the public.", ["confidential", "confidentially", "confidentiality", "confide"], "A", "Tính từ đứng sau động từ remain."),
        ],
      },
    ],
  },
  {
    slug: "tinh-tu-trang-tu-dac-biet",
    chapter: CHAPTER,
    code: "Word Form 2",
    title: "Các trường hợp đặc biệt của tính từ và trạng từ",
    summary: "Tính từ tận cùng -ly, trạng từ có hình thức giống tính từ (hard, late, fast) và cặp hard – hardly, late – lately.",
    blocks: [
      {
        type: "list",
        title: "Learning point 1: Các tính từ đặc biệt",
        items: [
          "Một số tính từ tận cùng bằng đuôi **-ly**: lovely, costly, friendly.",
          "Phân biệt với trạng từ: **tính từ + -ly = trạng từ** (beautiful-ly, slow-ly); **danh từ + -ly, động từ + -ly = tính từ** (order-ly, friend-ly, like-ly).",
          "Một số tính từ tận cùng bằng -ing hoặc ở dạng phân từ hai: interesting – interested, breaking – broken.",
        ],
      },
      {
        type: "list",
        title: "Learning point 2: Các trạng từ đặc biệt",
        items: [
          "Trạng từ và tính từ có cách viết giống nhau: **hard, fast, early, late, wrong, right, long, far**.",
          "**Lưu ý:** hardly = seldom (hiếm khi, hầu như không); lately = recently (gần đây).",
        ],
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("Yesterday, I went to bed [-------].", ["late", "lately"], "A", "Câu cần trạng từ bổ nghĩa cho động từ go. Tính từ late (muộn) không thay đổi cách viết khi chuyển thành trạng từ; còn lately nghĩa là 'gần đây'."),
          q("I can view the lake from the window very [-------].", ["well", "goodly"], "A", "Câu cần trạng từ bổ nghĩa cho động từ view. Tính từ good chuyển sang trạng từ là well."),
          q("It isn't very [-------] to rent a car.", ["cost", "costly"], "B", "Sau động từ to be cần tính từ. Costly (đắt đỏ) là tính từ."),
          q("I worked very [-------] these days.", ["hard", "hardly"], "A", "Sau động từ work cần trạng từ. Tính từ hard (chăm chỉ) không đổi cách viết khi chuyển sang trạng từ; còn hardly nghĩa là 'hiếm khi'."),
          q("The economy is growing very [-------] in the third quarter.", ["fast", "fastly"], "A", "Sau động từ grow cần trạng từ. Trạng từ fast không thay đổi cách viết."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("He worked so ------- for his achievement today.", ["hardly", "hard", "hardy", "hardship"], "B", "Tính từ và trạng từ của hard (chăm chỉ) có cùng cách viết. 'Anh ấy đã làm việc rất chăm chỉ cho thành tựu ngày hôm nay.'"),
          q("I find the new manual of the new printer quite -------.", ["confuse", "confusing", "confused", "confusion"], "B", "Cấu trúc find + O + adj; cần tính từ dạng V-ing chỉ tính chất. 'Tôi cảm thấy quyển hướng dẫn này rất rắc rối.'"),
          q("It's important to keep your office desk -------.", ["order", "ordered", "orderly", "orderness"], "C", "Sau keep là tính từ. Orderly là tính từ. 'Việc giữ cho bàn làm việc ngăn nắp là rất cần thiết.'"),
          q("Photocopying can be -------, so please make copies only when necessary.", ["costly", "precious", "cheap", "important"], "A", "Cả bốn từ đều là tính từ (costly tận cùng -ly nhưng là tính từ); costly nghĩa là 'tốn kém, đắt đỏ'."),
          q("I tried ------- to remember the new secretary's name but I couldn't.", ["hardly", "hard", "hardship", "harder"], "B", "'Tôi đã rất cố gắng để nhớ tên của người thư ký mới, nhưng tôi không thể.'"),
          q("The price of the cotton shirt seems reasonably -------.", ["cheap", "cheaply", "cheaper", "cheapest"], "A", "Sau seem là tính từ cheap. 'Giá của chiếc áo cotton có vẻ rẻ hợp lý.'"),
          q("You are in good shape. Have you worked out in the gym -------?", ["late", "later", "lately", "latter"], "C", "Trạng từ lately: gần đây. 'Dạo này trông bạn khỏe đấy. Gần đây bạn đi tập thể hình phải không?'"),
          q("The video of the conference will be posted ------- after it finishes.", ["right", "righteous", "rightly", "rightness"], "A", "Trạng từ đứng trước và bổ nghĩa cho after it finishes. 'Đoạn phim hội thảo sẽ được đăng ngay sau khi kết thúc.'"),
          q("Anyone ------- in attending the annual conference should register at the reception desk.", ["interested", "interesting", "interestingly", "interest"], "A", "Tính từ chỉ cảm xúc của người anyone là interested."),
          q("The ------- revisions to the proposal should be completed before getting approval from the project manager.", ["suggestive", "suggesting", "suggested", "suggestion"], "C", "Tính từ bổ sung ý nghĩa bị động suggested."),
          q("When ------- a map provided on the Internet, you should check whether the information is updated.", ["using", "use", "to use", "used"], "A", "'Khi sử dụng một bản đồ trên mạng, cần kiểm tra xem thông tin có cập nhật không.'"),
          q("The company's business is developing -------.", ["fastly", "fast", "quick", "fastened"], "B", "Trạng từ của fast không thay đổi cách viết."),
          q("Even though the acting workshop is -------, participants felt they learned a lot from it.", ["tiring", "tired", "tire", "tiredness"], "A", "Tính từ chỉ tính chất cho danh từ workshop là tiring."),
          q("We ------- used that room for any company event after the construction of a new conference hall.", ["seldom", "hard", "don't", "usual"], "A", "Seldom = hardly: hiếm khi."),
          q("It remains ------- to participate in our annual meeting this year.", ["exciting", "excited", "excitingly", "excitedly"], "A", "Sau remain là tính từ chỉ tính chất exciting."),
        ],
      },
    ],
  },
  {
    slug: "so-sanh-tinh-tu-trang-tu",
    chapter: CHAPTER,
    code: "Word Form 3",
    title: "Dạng so sánh của tính từ và trạng từ",
    summary: "So sánh ngang bằng, so sánh hơn, so sánh nhất, trạng từ nhấn mạnh và các trường hợp đặc biệt.",
    blocks: [
      {
        type: "list",
        title: "Learning point",
        items: [
          "**So sánh ngang bằng:** as + adj/adv + as.",
          "**So sánh hơn:** adj-er/adv-er + than; more + adj/adv + than.",
          "**Nhấn mạnh so sánh hơn:** even, much, far, slightly, still + so sánh hơn.",
          "**So sánh cao nhất:** the adj-est/adv-est; the most + adj/adv.",
        ],
      },
      {
        type: "table",
        title: "Các trường hợp so sánh đặc biệt",
        headers: ["Nguyên dạng", "So sánh hơn", "So sánh nhất"],
        rows: [
          ["good, well (tốt)", "better", "the best"],
          ["bad, badly (xấu)", "worse", "the worst"],
          ["little (ít)", "less", "the least"],
          ["many, much (nhiều)", "more", "the most"],
          ["far (xa)", "farther, further", "the farthest"],
        ],
      },
      {
        type: "note",
        title: "Lưu ý",
        body: "further có nghĩa là \"thêm, nâng cao, sau này\" chứ không có nghĩa là \"xa về khoảng cách\" (further information: thêm thông tin; further practice: luyện tập nâng cao; further notice: các thông báo sau).",
      },
    ],
    exercises: [
      {
        title: "Diagnostic test",
        kind: "practice",
        questions: [
          q("Life was not [-------] it is nowadays.", ["as easy as", "so easy"], "A", "Cấu trúc so sánh ngang bằng as + tính từ/trạng từ + as."),
          q("He would look much [-------] if his hair was short.", ["better", "best"], "A", "Trước so sánh hơn là trạng từ nhấn mạnh much với ý 'hơn rất nhiều'."),
          q("This armchair is much cheaper [-------] the sofa.", ["than", "as"], "A", "Giới từ trong so sánh hơn là than."),
          q("She owns the [-------] diamond in the world.", ["most expensive", "more expensive"], "A", "Sau the là so sánh cao nhất; câu có in the world (trên toàn thế giới) → so sánh cao nhất."),
          q("Feel free to call me if you need [-------] information.", ["further", "farther"], "A", "Further information: thêm thông tin."),
        ],
      },
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("Kriski Corn Cereal is made from only the ------- of ingredients and contains no artificial flavorings.", ["freshest", "freshen", "fresh", "freshly"], "A", "The + so sánh cao nhất. 'Kriski Corn Cereal được làm từ những nguyên liệu tươi nhất và không có hương liệu nhân tạo.'"),
          q("The recent economic recession has forced many companies to work more ------- to get in new business.", ["active", "actively", "activity", "act"], "B", "Trạng từ actively bổ nghĩa cho động từ work."),
          q("Every person in the department has been ------- more productive since the new system was installed.", ["very", "much", "greatly", "too"], "B", "Để nhấn mạnh trong so sánh hơn, dùng much."),
          q("The new animation produced by Universal Studios was received ------- by the public than critics originally anticipated.", ["large", "largely", "largest", "more largely"], "D", "Phía sau có than nên chọn so sánh hơn."),
          q("Some people consider a certificate in accounting to be as ------- business management.", ["important as", "importantly", "more important", "importance"], "A", "Câu sử dụng so sánh ngang bằng as … as. 'Vài người cho rằng chứng chỉ kế toán cũng quan trọng như quản lý kinh doanh.'"),
          q("This project is the ------- assignment that our department has ever undertaken.", ["demanding", "more demanding", "most demanding", "demanded"], "C", "The + so sánh cao nhất."),
          q("Successful applicants must have no ------- than three years of advertising experience as well as a bachelor's degree.", ["little", "a little", "less", "at least"], "C", "No less than: không dưới. 'Ứng viên phải có không dưới ba năm kinh nghiệm quảng cáo cũng như bằng cử nhân.'"),
          q("Joe Reinhold, who has a high customer service rating, is one of the ------- successful employees at the company.", ["very", "most", "more", "much"], "B", "One of the + so sánh cao nhất."),
          q("The national park is known for its very ------- garden, where there are a variety of flowers and trees.", ["largely", "large", "larger", "largest"], "B", "Sau very dùng tính từ nguyên dạng. 'Công viên quốc gia được biết đến với khu vườn rất rộng.'"),
          q("Cable television brings you ------- channels and better reception than any other receptions of broadcast television.", ["many", "good", "more", "great"], "C", "Vì có than nên chọn so sánh hơn."),
          q("You can find the slightly ------- model in section B.", ["cheap", "cheapest", "the cheapest", "cheaper"], "D", "Slightly + so sánh hơn. 'Bạn có thể tìm thấy sản phẩm rẻ hơn một chút ở khu B.'"),
          q("Paul is ------- candidate for that position. He hates speaking in public.", ["the bad", "worse", "worst", "the worst"], "D", "'Paul là ứng viên tệ nhất cho vị trí đó. Anh ấy không thích nói trước công chúng.'"),
          q("------- sales month in the year is usually January or February.", ["More slow", "Slower", "Slowest", "The slowest"], "D", "In the year: dấu hiệu của so sánh cao nhất. 'Tháng bán hàng chậm nhất trong năm là tháng Một hoặc tháng Hai.'"),
          q("Please don't call us between noon and one. That is our ------- time of day.", ["busy", "a busier", "busiest", "the busiest"], "C", "Vì đã có tính từ sở hữu our nên không cần the trong so sánh cao nhất."),
          q("The interior lights seem ------- than they usually do.", ["more brightly", "brighter", "bright", "the brighter"], "B", "Sau seem là tính từ; phía sau là than → so sánh hơn của tính từ."),
        ],
      },
    ],
  },
  {
    slug: "nghia-cua-tinh-tu",
    chapter: CHAPTER,
    code: "Word Choice 1",
    title: "Câu hỏi về nghĩa của tính từ",
    summary: "Một số tính từ phổ biến trong đề thi TOEIC: overdue, timely, extensive, available, valid, limited…",
    blocks: [
      {
        type: "table",
        title: "Learning point: Một số tính từ phổ biến trong đề thi TOEIC",
        headers: ["Tính từ", "Nghĩa / cách dùng"],
        rows: [
          ["overdue", "quá hạn trả (sách)"],
          ["timely", "kịp thời (in a timely manner: giải quyết kịp thời)"],
          ["extensive", "nhiều, rộng (extensive knowledge: nhiều hiểu biết; extensive experience: nhiều kinh nghiệm)"],
          ["available (to the public)", "có sẵn, công cộng"],
          ["considerable", "nhiều, đáng kể (a considerable increase: tăng đáng kể)"],
          ["comprehensive, thorough", "toàn diện, kỹ, đầy đủ"],
          ["essential, necessary, mandatory, obligatory", "cần thiết — It's necessary/essential/obligatory that S + V nguyên thể: It's necessary that every employee wear a uniform."],
          ["innovative", "tiến bộ, mới"],
          ["valid", "(ticket, card) còn giá trị, còn thời hạn sử dụng"],
          ["limited", "có hạn (limited warranty, limited seating capacity)"],
          ["be aware of", "hiểu, biết về"],
          ["additional", "thêm, bổ sung"],
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["a limited time", "n", "thời gian ngắn, có hạn"],
          ["additional", "adj", "thêm, bổ sung"],
          ["fine", "n", "tiền phạt"],
          ["fulfill an order", "v", "hoàn thiện đơn hàng"],
          ["in a timely manner", "n", "một cách kịp thời"],
          ["make someone aware of something", "v", "khiến ai đó nhận thức điều gì"],
          ["product promotion", "n", "quảng bá sản phẩm"],
          ["prospective customer", "n", "khách hàng tiềm năng"],
        ],
      },
    ],
    exercises: [
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("From the first day the book becomes -------, fines have to be paid at the rate of $2 per day.", ["overdue", "valid", "expired", "sold-out"], "A", "'Kể từ ngày đầu tiên quyển sách quá hạn, tiền phạt sẽ được tính là 2 đô la một ngày.'"),
          q("Joe Hopkins was praised for taking a much-needed restructuring measure in a ------- manner.", ["timely", "stagnant", "bad", "available"], "A", "In a timely manner: một cách kịp thời."),
          q("The stereo equipment you ordered is currently -------, so we will fulfill your order immediately.", ["out", "sold-out", "available", "outdated"], "C", "'Thiết bị âm thanh bạn đặt đang có sẵn, nên chúng tôi sẽ hoàn thành đơn hàng ngay lập tức.'"),
          q("Rose Chemical Corporation is proud to present an ------- selection of new materials.", ["expensive", "extensive", "especial", "experienced"], "B", "'Tập đoàn Rose Chemical tự hào mang đến nhiều sự lựa chọn vật liệu mới.'"),
          q("Scientists around the world are making ------- efforts to develop the new vaccine.", ["proficient", "considerable", "secondary", "present"], "B", "'Các nhà khoa học trên toàn thế giới đang có những nỗ lực đáng kể để phát triển vắc-xin mới.'"),
          q("Local officials will present a(n) ------- plan for financing much-needed improvement on the high-speed rail line.", ["variable", "apparent", "comprehensive", "regretful"], "C", "'Quan chức địa phương sẽ trình bày một kế hoạch toàn diện cho việc cấp vốn nâng cấp đường sắt cao tốc.'"),
          q("It is ------- that candidates prepare themselves to work on any shift.", ["essential", "secluded", "disinterested", "competent"], "A", "'Điều cần thiết là mỗi ứng viên phải chuẩn bị làm việc bất kỳ ca nào.'"),
          q("The report suggests that ------- advertising be planned in order to increase sales.", ["anxious", "impressed", "eligible", "effective"], "D", "'Báo cáo đề xuất cần lên kế hoạch quảng cáo hiệu quả để tăng doanh số bán hàng.'"),
          q("------- plans are always welcomed here in our department.", ["Innovative", "Limited", "Valid", "Compared"], "A", "'Những kế hoạch mới, táo bạo luôn được chào đón ở phòng ban chúng tôi.'"),
          q("Visas for non-business travel to Brazil are ------- for five years from the date of first entry.", ["vary", "valid", "valuable", "various"], "B", "Đối với các loại thẻ, giấy tờ thường dùng tính từ valid (có hiệu lực)."),
          q("Our new system will result in a ------- reduction in the consumer heating bills.", ["safe", "substantial", "valuable", "useful"], "B", "Substantial reduction: giảm đáng kể."),
          q("We're hiring ------- workers for the upcoming project.", ["additive", "additional", "advert", "advertent"], "B", "Additional workers: thêm công nhân."),
          q("We're trying to make people ------- of the value of public service activities.", ["aware", "grateful", "serious", "watchful"], "A", "Make people aware of something: khiến mọi người nhận thức được."),
          q("Direct mail service produces a quick and timely message for product promotion that ------- customers can easily appreciate.", ["economic", "durable", "prospective", "further"], "C", "Prospective customer: khách hàng tiềm năng."),
          q("The museum display of Chinese paintings will remain open for a ------- time only.", ["shortened", "limited", "updated", "lasting"], "B", "For a limited time: trong một thời gian có hạn."),
        ],
      },
    ],
  },
  {
    slug: "nghia-cua-trang-tu",
    chapter: CHAPTER,
    code: "Word Choice 2",
    title: "Câu hỏi về nghĩa của trạng từ",
    summary: "Trạng từ chỉ mức độ, trạng từ đứng trước số liệu và trạng từ đứng trước trạng ngữ thời gian/địa điểm.",
    blocks: [
      {
        type: "list",
        title: "Learning point: Các trạng từ thường xuất hiện trong đề thi TOEIC",
        items: [
          "**1. Trạng từ chỉ mức độ:** đi với các từ mang nghĩa 'tăng' (increase, rise, grow, go up), 'giảm' (decrease, fall, go down, reduce), 'nhiều, lớn' (large), 'nhỏ' (small), 'cao' (high), 'thấp' (low): **slightly** (nhẹ); **relatively, moderately, comparatively** (khá, tương đối); **considerably, significantly, dramatically, substantially** (đáng kể, nhiều).",
          "**2. Trạng từ đi trước số liệu:** approximately, roughly, about, nearly, almost, precisely.",
          "**3. Trạng từ đứng trước các trạng ngữ chỉ thời gian/địa điểm:** promptly, immediately, right, shortly, directly (ngay lập tức, ngay khi, ngay tại đâu).",
        ],
      },
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["confirmation letter", "n", "thư xác nhận"],
          ["opening speech", "n", "bài phát biểu mở màn"],
          ["refund", "n", "hoàn tiền"],
          ["replacement", "n", "đổi hàng mới"],
        ],
      },
    ],
    exercises: [
      {
        title: "Progress Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("In my opinion, the company's stock price is ------- low compared to its annual earnings.", ["audibly", "relatively", "plentifully", "anonymously"], "B", "Relatively low: tương đối thấp."),
          q("Our profits are expected to grow ------- thanks to the aggressive management of our new director.", ["precisely", "promptly", "significantly", "cheaply"], "C", "Grow significantly: tăng đáng kể."),
          q("Our meeting will take place ------- at 3 p.m., so please be on time.", ["precisely", "exact", "as soon as possible", "slightly"], "A", "'Cuộc họp sẽ diễn ra vào đúng ba giờ chiều, nên hãy đến đúng giờ.'"),
          q("You need to recharge the device after ------- use.", ["important", "significant", "steady", "crucial"], "B", "'Bạn cần sạc điện lại thiết bị sau mỗi lần sử dụng nhiều (significant use).'"),
          q("Please go to the information desk ------- after we finish the session to return your visitor's pass.", ["right", "rightly", "righteous", "righteously"], "A", "Right + trạng ngữ chỉ thời gian after we finish the session: ngay sau khi."),
          q("This year our company has witnessed a ------- growth in expanding our business to other Asian countries.", ["significant", "necessary", "ordinary", "mutual"], "A", "Significant growth: sự tăng trưởng đáng kể."),
          q("Lawton has announced that it will ------- increase its nonstop service from Crasen to Hopley.", ["exactly", "finely", "importantly", "substantially"], "D", "Substantially increase: tăng mạnh."),
          q("The owner of Pergini Builders estimates that the construction will take ------- eighteen months to complete.", ["approximately", "slowly", "eagerly", "spaciously"], "A", "Approximately + số từ eighteen: khoảng 18 tháng."),
          q("When it comes to financing your vehicle, leasing has no ------- advantage over purchasing.", ["really", "real", "realistically", "realism"], "B", "Tính từ real bổ nghĩa cho danh từ advantage. 'Khi nói đến việc tài chính cho xe, thuê không thực sự có lợi hơn mua.'"),
          q("As you are ordering a large quantity, we will offer you the items at ------- reduced prices.", ["considerably", "neatly", "roughly", "repeatedly"], "A", "Considerably reduced price: giá giảm mạnh."),
          q("The award ceremony will begin ------- at 2:30, following the opening speech by the vice president.", ["promptly", "orderly", "soon", "decently"], "A", "Promptly + trạng ngữ chỉ thời gian: đúng lúc."),
          q("Because our profit rose -------, our employees will receive their first-ever year-end bonus.", ["dramatically", "successfully", "straightforwardly", "approximately"], "A", "Rise dramatically: tăng mạnh."),
          q("Today most newspapers are focusing ------- on the influence of the tight domestic labor market.", ["finally", "respectively", "very", "exclusively"], "D", "Focus exclusively on: tập trung riêng vào."),
          q("If the package is missing, we will begin processing your refund or replacement -------.", ["promptly", "especially", "increasingly", "unexpectedly"], "A", "'Nếu bưu kiện bị thất lạc, chúng tôi sẽ bắt đầu hoàn tiền hoặc đổi hàng mới ngay lập tức.'"),
          q("A confirmation letter will be mailed ------- three weeks prior to your visit.", ["relatively", "largely", "approximately", "temporarily"], "C", "Approximately + số liệu: 'Thư xác nhận sẽ được gửi khoảng ba tuần trước khi bạn đến.'"),
        ],
      },
    ],
  },
  {
    slug: "tinh-tu-trang-tu-review-test",
    chapter: CHAPTER,
    code: "Review Test",
    title: "Adjectives & Adverbs — Review Test",
    summary: "Bài kiểm tra tổng hợp 30 câu về tính từ và trạng từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["adversely affect", "v", "tác động xấu"],
          ["affordable / reasonable price", "n", "giá cả hợp lý"],
          ["customer base", "n", "nguồn khách hàng"],
          ["department store", "n", "cửa hàng bách hóa"],
          ["feedback", "n", "phản hồi, bình luận"],
          ["optimal performance", "n", "hiệu suất / công suất tối đa"],
          ["replacement", "n", "người thay thế"],
          ["specifically = exclusively", "adv", "nhất là, riêng"],
          ["temporarily", "adv", "tạm thời"],
          ["typically = usually", "adv", "thường"],
        ],
      },
    ],
    exercises: [
      {
        title: "Adjectives & Adverbs — Review Test",
        kind: "test",
        instructions: "Chọn đáp án đúng để hoàn thành câu.",
        questions: [
          q("If an item in your order is not available, it may be shipped ------- at a later date.", ["separately", "separate", "separating", "separates"], "A", "Trạng từ bổ nghĩa cho động từ ship. 'Nếu món hàng không còn sẵn, nó sẽ được gửi riêng vào lần sau.'"),
          q("According to the most recent report, sales of snacks have increased by ------- five percent.", ["firmly", "nearly", "strongly", "completely"], "B", "Nearly đứng trước số liệu five."),
          q("Elena is a Barcelona-based architect known for ------- incorporating practical and aesthetic elements in her designs.", ["taste", "tasteful", "tastefully", "tasting"], "C", "Tastefully bổ nghĩa cho động từ incorporating."),
          q("With its lightweight and comfortable handle, the latest Apurage vacuum cleaner is ------- to carry.", ["easy", "ease", "easily", "eases"], "A", "Sau to be là tính từ."),
          q("Any problems with the new software system should be reported to the system administrator -------.", ["prompt", "promptness", "prompts", "promptly"], "D", "Trạng từ bổ nghĩa cho động từ report."),
          q("Due to its need for ------- repairs, the conveyor belt is scheduled to be replaced by a more efficient model.", ["frequent", "frequently", "frequency", "frequents"], "A", "Sau giới từ for thì repairs là danh từ; trước đó cần tính từ bổ nghĩa."),
          q("Because of a ------- increase in profits this quarter, we all get a bonus.", ["dramatically", "dramatize", "dramatic", "drama"], "C", "A … increase nên increase là danh từ; trước đó là tính từ."),
          q("Director Jun Iwate auditioned twenty actors before making the ------- decision about whom to cast in the main role.", ["final", "finals", "finally", "finalize"], "A", "Tính từ bổ nghĩa cho danh từ decision."),
          q("The city council ------- approved the highway extension project pending the results of an environmental review.", ["conditions", "conditioned", "conditional", "conditionally"], "D", "Trạng từ bổ nghĩa cho động từ approve."),
          q("In order to be more ------- to its customers, the Jeness Department Store has added a customer feedback section to its website.", ["response", "responded", "responsive", "respondent"], "C", "Tính từ đứng sau to be."),
          q("For optimal performance of your Rydor clothes dryer, clean the filter -------.", ["extremely", "regularly", "deeply", "heavily"], "B", "'Để máy sấy quần áo Rydor hoạt động ở công suất tối đa, hãy vệ sinh bộ lọc thường xuyên.'"),
          q("Some researchers believe that multi-tasking ------- affects workers' concentration and productivity.", ["adverse", "adversity", "adversities", "adversely"], "D", "Trạng từ bổ nghĩa cho động từ affect."),
          q("Janning Footwear's marketing campaign was ------- aimed at young adults in an attempt to broaden its customer base.", ["specify", "specific", "specifically", "specifies"], "C", "Trạng từ bổ nghĩa cho động từ aim."),
          q("Customers may return any item within 30 days if they are not ------- with their purchase.", ["satisfactory", "satisfying", "satisfied", "satisfaction"], "C", "Tính từ satisfied chỉ cảm xúc cho they."),
          q("Please adjust the volume knob ------- so the sound is not too loud.", ["slight", "slighter", "slightly", "to slight"], "C", "Trạng từ slightly bổ nghĩa cho động từ adjust."),
          q("Hamer Construction employs a group of contractors whose ------- knowledge and experience translate into quality workmanship.", ["collect", "collectively", "collective", "collection"], "C", "Tính từ collective bổ nghĩa cho danh từ knowledge."),
          q("The energy commission has suggested that constructing roofs in a lighter color will ------- reduce the amount of heat in urban areas.", ["significantly", "extremely", "utterly", "countlessly"], "A", "Trạng từ significantly bổ nghĩa cho động từ reduce (giảm)."),
          q("The Watdee Marketing Firm will guide you in ------- promoting your product to the most desirable business customers.", ["creatively", "create", "creative", "created"], "A", "Trạng từ creatively bổ nghĩa cho động từ promoting."),
          q("Human resources director Erika Nikata understands that employee recruitment and retention are ------- important.", ["equal", "equally", "equality", "equalize"], "B", "Trạng từ equally bổ nghĩa cho tính từ important."),
          q("Alpha Clothing Store is a family-owned business offering high-quality men's clothing at ------- prices.", ["affordably", "affordable", "afford", "afforded"], "B", "Tính từ bổ nghĩa cho danh từ prices."),
          q("In April, Petersen will hold ------- sessions on gardening basics.", ["introduce", "introducing", "introductions", "introductory"], "D", "Tính từ bổ nghĩa cho danh từ sessions."),
          q("Chang is ------- regarded as one of the company's most competent vice presidents.", ["wide", "wider", "widest", "widely"], "D", "Trạng từ bổ nghĩa cho động từ regarded."),
          q("The main office will soon be able to send out packages more ------- because of the updated processing procedures.", ["quick", "quicker", "quickly", "quickest"], "C", "Trạng từ bổ nghĩa cho động từ send out."),
          q("Franklin Catering Company offers a ------- range of menu choices for both lunch and dinner.", ["satisfied", "hopeful", "dividing", "broad"], "D", "A broad range of = many."),
          q("Orders from the warehouse in Perth ------- arrive in five to seven days.", ["typified", "typical", "typify", "typically"], "D", "Trạng từ bổ nghĩa cho động từ arrive."),
          q("Applications for scholarships should be submitted to the selection committee in a ------- manner.", ["time", "timed", "timely", "timing"], "C", "Timely là tính từ bổ nghĩa cho danh từ manner."),
          q("Ms. Mendoza has agreed to work ------- as a weekend chef until a suitable replacement can be found.", ["easily", "arbitrarily", "enormously", "temporarily"], "D", "'Cô Mendoza đồng ý làm đầu bếp tạm thời vào cuối tuần cho đến khi tìm được người thay thế thích hợp.'"),
          q("Kristi Driver's services are very ------- priced.", ["strongly", "internally", "reasonably", "repeatedly"], "C", "Trạng từ reasonably bổ nghĩa cho priced: giá hợp lý."),
          q("Jurassite Series 3 bicycles are designed ------- for long-distance travel.", ["specifies", "specified", "specifics", "specifically"], "D", "Trạng từ specifically bổ nghĩa cho động từ designed."),
          q("Weekend passes to Lawton Amusement Park are ------- for six months from the date of purchase.", ["valid", "accurate", "original", "actual"], "A", "Danh từ pass (vé, thẻ) đi cùng với tính từ valid (có giá trị, có thời hạn)."),
        ],
      },
    ],
  },
];
