import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const diningOut: IigTopic = {
  slug: "dining-out",
  title: "Dining Out",
  titleVi: "Ăn uống ngoài hàng",
  summary: "Nhà hàng, thực đơn, món ăn, đặt bàn, phục vụ và thanh toán — thường gặp trong Part 3/4 và Part 6/7.",
  words: [
    ["affordable", "adj", "/əˈfɔːdəbl/", "giá cả phải chăng", "The prices in this restaurant are very affordable.", "Động từ afford: đủ tiền để chi cho cái gì. Tính từ affordable: rẻ, có thể chi trả được."],
    ["appetizer", "n", "/ˈæpɪtaɪzə(r)/", "món khai vị", "French fries, chicken strips and other fried appetizers are available at the bar.", "Có 2 cách viết: appetizer / appetiser. Trong tiếng Anh-Anh, starter cũng có nghĩa là món khai vị."],
    ["bacon", "n", "/ˈbeɪkən/", "thịt xông khói", "This is the restaurant's special bacon produced by one of the world's famous chefs.", "Bacon: thịt lưng hoặc lườn heo thái mỏng, chiên lên, dùng làm món ăn kèm. Ham: thịt đùi heo ướp muối, một số loại có thể ăn sống."],
    ["banquet", "n", "/ˈbæŋkwɪt/", "yến tiệc", "The restaurant serves a special banquet dinner on weekend evenings.", "Banquet: bữa ăn trang trọng tổ chức để vinh danh cá nhân hoặc sự kiện. Buffet: thức ăn bày ở khu vực chung để thực khách tự phục vụ, trả một số tiền nhất định."],
    ["bartender", "n", "/ˈbɑːtendə(r)/", "người pha chế", "I work part-time as a bartender in a local pub.", "Tender trong bartender là tính từ chỉ người ân cần, chu đáo — thể hiện yêu cầu mà nghề pha chế đặt ra."],
    ["bistro", "n", "/ˈbiːstrəʊ/", "nhà hàng bình dân", "A wide range of pizzas and pastas are served all day in this Italian bistro.", "Bistro: nhà hàng nhỏ, bình dân. Restaurant: nơi thực khách được phục vụ tại bàn và trả tiền, thường là sau khi ăn."],
    ["budget", "adj / n", "/ˈbʌdʒɪt/", "giá rẻ; ngân sách", "Budget airlines have forced major airlines to lower some of their prices.", "Bên cạnh nghĩa “rẻ”, budget còn là danh từ “ngân sách”."],
    ["busboy", "n", "/ˈbʌsbɔɪ/", "nhân viên dọn bàn", "Ask the busboy to help you bring out all of the food.", "Busboy: dọn dẹp bàn, dự trữ đồ dùng, phục vụ món ăn nhẹ, khai vị. Waiter: chăm sóc, phục vụ thực khách, đôi khi dọn và sắp xếp bàn cho khách tiếp theo."],
    ["cafeteria", "n", "/ˌkæfəˈtɪəriə/", "nhà ăn", "Employees have four different lunch sets to choose from in the company cafeteria.", "Cafeteria thường dùng trong Anh-Mỹ để chỉ nhà ăn ở công ty, trường học, khu quân sự; Anh-Anh thường dùng canteen."],
    ["centrepiece", "n", "/ˈsentəpiːs/", "phần quan trọng nhất; vật trang trí giữa bàn", "The centrepiece of most environmental studies is conservation.", "Viết centrepiece (Anh-Anh) hoặc centerpiece (Anh-Mỹ)."],
    ["chef", "n", "/ʃef/", "bếp trưởng, đầu bếp", "Gordon Ramsay is one of the top chefs in Britain.", "Chef và chief viết gần giống nhau nên dễ nhầm: chief là “lãnh đạo”, chef mới là “bếp trưởng”."],
    ["classy", "adj", "/ˈklɑːsi/", "sang trọng", "This is the classiest restaurant in this city."],
    ["combo", "n", "/ˈkɒmbəʊ/", "suất ăn kết hợp", "A McDonald's combo meal includes a burger, fries and a soft drink."],
    ["compliment", "n", "/ˈkɒmplɪmənt/", "lời khen", "“That was an excellent meal!” — “My compliments to the chef.”"],
    ["complimentary", "adj", "/ˌkɒmplɪˈmentri/", "miễn phí", "The desserts are complimentary because the dinner took so long.", "Đừng nhầm complimentary (miễn phí) với complementary (bổ sung, hỗ trợ)."],
    ["condiment", "n", "/ˈkɒndɪmənt/", "gia vị, nước chấm", "This restaurant has a large bar with various condiments for customers' food.", "Spice: hương liệu gốc thực vật (quả, hạt, rễ), mùi mạnh, thường sấy khô và nghiền bột. Condiment: gia vị thêm vào món ăn như muối, hạt tiêu, nước sốt."],
    ["convenient", "adj", "/kənˈviːniənt/", "thuận tiện, tiện lợi", "The online reservation service is extremely convenient.", "Handy: tiện lợi, dùng cho đồ vật (a handy-sized dictionary). Convenient: dùng cho cả đồ vật lẫn hoàn cảnh (I'll call back at a more convenient time)."],
    ["decoration", "n", "/ˌdekəˈreɪʃn/", "sự trang trí", "She's good at cake decoration."],
    ["dessert", "n", "/dɪˈzɜːt/", "món tráng miệng", "We had apple pie with ice cream for dessert.", "Phân biệt dessert (tráng miệng) với desert (sa mạc)."],
    ["etiquette", "n", "/ˈetɪket/", "quy tắc ứng xử, phép lịch sự", "I had to learn all the etiquette before my first business trip to Europe.", "Étiquette ban đầu là danh từ tiếng Pháp nghĩa là “nhãn”; thế kỷ 16 có thêm nghĩa quy tắc ứng xử, giữa thế kỷ 18 được dùng trong tiếng Anh với nghĩa này."],
    ["flavour", "n", "/ˈfleɪvə(r)/", "hương vị", "This wine has a light, fruity flavour.", "Viết flavour (Anh-Anh) hay flavor (Anh-Mỹ) đều đúng."],
    ["flavourful", "adj", "/ˈfleɪvəfl/", "thơm ngon, đậm đà", "This restaurant has a very flavourful beer."],
    ["flour", "n", "/ˈflaʊə(r)/", "bột mì", "The noodles were made with raw eggs, flour, and water.", "Xuất hiện giữa thế kỷ 13 như một nghĩa khác của flower (phần tốt nhất của hạt). Năm 1830 cách viết đổi thành flour để tránh nhầm lẫn."],
    ["grill", "n / v", "/ɡrɪl/", "vỉ nướng; nướng", "The healthiest way to prepare meat is on a grill."],
    ["highchair", "n", "/ˈhaɪtʃeə(r)/", "ghế ăn cho trẻ em", "The party is for ten plus a highchair.", "Vào thế kỷ 17, highchair còn có bánh xe để tiện di chuyển giữa các phòng."],
    ["hospitable", "adj", "/hɒˈspɪtəbl/", "hiếu khách, thân thiện", "The restaurant's waitresses are very hospitable and helpful."],
    ["host", "n", "/həʊst/", "người tiếp đón (ở nhà hàng); chủ nhà", "Please wait and the host will seat you."],
    ["ingredient", "n", "/ɪnˈɡriːdiənt/", "nguyên liệu, thành phần", "In Europe the seeds are used as an ingredient in soups.", "Ingredient còn mang nghĩa thành phần, yếu tố: Commodities, such as steel, are important ingredients in building wind turbines."],
    ["leftover", "n / adj", "/ˈleftəʊvə(r)/", "thức ăn thừa; còn thừa", "You've always got good ideas for using up leftovers.", "Tính từ: We should use any leftover meat to make a curry."],
    ["mouth-watering", "adj", "/ˈmaʊθ wɔːtərɪŋ/", "ngon lành, hấp dẫn", "This restaurant is famous for a mouth-watering seafood dish."],
    ["napkin", "n", "/ˈnæpkɪn/", "khăn ăn", "After having dinner, she stood up and wiped her mouth with a napkin.", "Tissue: giấy mỏng hơn napkin, thường dùng để xì mũi. Napkin: khăn dùng trong bữa ăn."],
    ["nutrient", "n", "/ˈnjuːtriənt/", "chất dinh dưỡng", "Tomatoes contain a lot of nutrients, among them vitamins C and B-complex and the minerals iron and potassium."],
    ["nutritious", "adj", "/njuˈtrɪʃəs/", "bổ dưỡng", "My mother chose this restaurant because it serves tasty and nutritious dishes."],
    ["organic", "adj", "/ɔːˈɡænɪk/", "hữu cơ", "The menu includes organic meats, fresh seafood and fresh vegetables."],
    ["pastry", "n", "/ˈpeɪstri/", "bánh ngọt (làm từ bột nướng)", "The restaurant offered a wide selection of pastries for dessert.", "Pastry: tất cả các loại bánh làm từ bột, trứng, chất béo rồi nướng lên; người chuyên làm gọi là pastry chef. Cake chỉ là một loại hẹp trong pastry."],
    ["patio", "n", "/ˈpætiəʊ/", "khu ngồi ngoài trời", "We closed the patio because it looks like it's going to rain.", "Gốc tiếng Tây Ban Nha (1764) nghĩa là “sân nhà”; đến thế kỷ 19 được dùng trong tiếng Anh với nghĩa khu ăn uống ngoài trời."],
    ["patron", "n", "/ˈpeɪtrən/", "khách quen", "My best friend is a patron of a Japanese restaurant.", "Patron (khách quen) và patrol (tuần tra) có cách viết, cách phát âm gần giống nhau nên dễ nhầm."],
    ["recipe", "n", "/ˈresəpi/", "công thức nấu ăn", "You can check out vegan recipes on this website.", "Xuất hiện năm 1580, ban đầu dùng bởi dược sĩ trên đầu đơn thuốc; năm 1743 mới có nghĩa “hướng dẫn chế biến món ăn”."],
    ["requirement", "n", "/rɪˈkwaɪəmənt/", "yêu cầu", "A special guest has a small requirement for his party at the restaurant.", "Requirement: yêu cầu bắt buộc, có thể dựa trên quy tắc, luật lệ. Request: mong muốn, thường do cá nhân đưa ra."],
    ["reservation", "n", "/ˌrezəˈveɪʃn/", "sự đặt trước (bàn, phòng)", "I'd like to make a table reservation for two people for nine o'clock."],
    ["reserve", "v", "/rɪˈzɜːv/", "đặt trước", "To get a table at this restaurant, you have to reserve well in advance.", "Book: thường dùng khi khách thanh toán trước (book a hotel room). Reserve: yêu cầu giữ chỗ/dịch vụ, thanh toán sau khi sử dụng (reserve a table in a restaurant)."],
    ["starving", "adj", "/ˈstɑːvɪŋ/", "đói cồn cào", "I'm starving! I haven't eaten anything since breakfast."],
    ["sauce", "n", "/sɔːs/", "nước sốt", "Sushi can be eaten plain, without soy sauce or wasabi.", "Sauce xuất hiện từ thế kỷ 14, gốc Latin salsa (nước muối). Sausage cùng thời, gốc Latin salsicium (món làm từ thịt muối)."],
    ["sommelier", "n", "/səˈmeliə(r)/", "chuyên gia rượu vang (nếm, phục vụ rượu)", "Wine is tested by sommeliers and beverage experts.", "Thời trung cổ, sommelier là người vận chuyển hành lý; ở nhà địa chủ, họ còn nếm thử đồ ăn, rượu trước khi phục vụ chủ nhân."],
    ["spacious", "adj", "/ˈspeɪʃəs/", "rộng rãi", "The Japanese restaurant where we often eat is very spacious.", "Large: to lớn về kích cỡ/số lượng. Huge: to lớn hơn large. Spacious: rộng rãi, thường dùng để mô tả không gian."],
    ["season", "v", "/ˈsiːzn/", "nêm gia vị", "The chef seasoned the meat with plenty of salt and pepper."],
    ["speciality", "n", "/ˌspeʃiˈæləti/", "đặc sản, món đặc trưng", "Oysters are a local speciality of the area.", "Anh-Mỹ viết specialty."],
    ["tip", "n / v", "/tɪp/", "tiền boa; boa tiền", "We gave the waiter a small tip before we left.", "Tip: tiền khách cảm ơn người phục vụ. Bonus: tiền thưởng thêm vào lương. Allowance: tiền phụ cấp, trợ cấp. Commission: tiền hoa hồng."],
    ["vegetarian", "n / adj", "/ˌvedʒəˈteəriən/", "người ăn chay", "I cannot have any meat because I am a vegetarian.", "Vegetarian: không ăn thịt nhưng vẫn dùng sản phẩm từ động vật như trứng, sữa, mật ong. Vegan: ăn thuần chay, không dùng bất kỳ sản phẩm nào từ động vật. Veganism: chủ nghĩa thuần chay."],
    ["waiter", "n", "/ˈweɪtə(r)/", "người phục vụ (nam)", "The waiter handed me the menu with a flourish.", "Một số từ phân theo giới tính: waiter – waitress, count – countess, actor – actress."],
  ],
  quiz: [
    q("Chanel collections are usually clean, ------- and elegant.", ["classy", "classified", "classical", "classicified"], "A", "Classy: sang trọng — cùng nghĩa với clean, elegant."),
    q("Find the wrong word: This restaurant also offer all white-meat chicken nuggets which come in either 3 or 5 by themselves, or in combos.", ["offer", "in", "by", "combos"], "A", "Chủ ngữ số ít This restaurant → offers."),
    q("To assess a restaurant fairly, you should look at all the complaints and ------- on its website.", ["compliments", "complements", "complementary", "complimentary"], "A", "Complaints and compliments: lời phàn nàn và lời khen."),
    q("True or False? Decoration does not refer to the activity of making something look more attractive.", ["True", "False"], "B", "Sai — decoration chính là việc trang trí để làm cho thứ gì đó trông đẹp hơn."),
    q("Find the wrong word: A dinner can be divided into parts such as a salad, a main course, and a desert.", ["be", "divided", "main course", "desert"], "D", "Món tráng miệng là dessert; desert là sa mạc."),
    q("Coconut flour provides you with a unique and ------- cooking method to expand your gluten-free menu.", ["flavour", "flavouring", "flavourful", "flavourite"], "C", "Sau unique and cần một tính từ → flavourful (thơm ngon)."),
    q("What is “grill”?", ["Food cooked quickly above a heat source in a skillet or on a metal grate over a fire", "Cooking food by hot air in an oven", "To quickly cook food directly under a heat source", "Foods cooked by vapors from boiling water"], "A", "Grill: nướng nhanh trên nguồn nhiệt, trên vỉ kim loại đặt trên lửa. (B) là bake/roast, (C) là broil, (D) là steam."),
    q("TUNG dining breaks through all the limits and barriers of traditional fine dining with the most welcoming, warm-hearted and ------- experience.", ["hospitability", "hospitably", "hospital", "hospitable"], "D", "Bổ nghĩa cho danh từ experience cần tính từ → hospitable."),
    q("What are the host's responsibilities?", ["Taking reservations", "Greeting customers", "Seating customers", "All are correct"], "D", "Host ở nhà hàng nhận đặt bàn, chào đón và xếp chỗ cho khách."),
    q("Find the wrong word: Puddings feature various types of ice-cream, including a mouth-watered hazelnut confection, a wicked chocolate truffle and the Indian ice-cream, kulfi.", ["Puddings", "types", "mouth-watered", "wicked"], "C", "Tính từ đúng là mouth-watering (ngon lành)."),
    q("True or False? Plants or animals need nutrients in order to live and grow.", ["True", "False"], "A", "Đúng — nutrient là chất dinh dưỡng cần cho sự sống và phát triển."),
    q("True or False? “Nutritious” means something that contains many of the substances needed for life and growth.", ["True", "False"], "A", "Đúng — nutritious: bổ dưỡng, chứa nhiều chất cần thiết cho cơ thể."),
    q("True or False? Organic foods are charged at a higher price than non-organic ones.", ["True", "False"], "A", "Đúng — thực phẩm hữu cơ thường có giá cao hơn."),
    q("Find the wrong word: Without inform me, the restaurant decided to cancel my reservation to make room for other customers.", ["inform", "decided", "cancel", "make"], "A", "Sau giới từ without là V-ing → informing."),
    q("Green rice flakes are among the must-try ------- when visiting Hanoi in autumn.", ["specialists", "specialist", "specialities", "speciality"], "C", "Among the must-try + danh từ số nhiều → specialities (đặc sản)."),
  ],
  written: [
    { q: "Chọn TẤT CẢ các từ đồng nghĩa với “starving”: (A) full  (B) famished  (C) satisfied  (D) ravenous  (E) overfed", a: "B & D — famished, ravenous" },
    { q: "Chia dạng đúng của từ “season”: Steak (season) ------- refers to any herbs, spices, or spice blend mixtures you use on your steak to boost its flavor profile. Although many people (season) ------- their steaks before cooking them, they may not know the benefits behind steak (season) -------.", a: "(1) seasoning; (2) season; (3) seasoning" },
  ],
};
