import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const entertainment: IigTopic = {
  slug: "entertainment",
  title: "Entertainment",
  titleVi: "Giải trí",
  summary: "Báo chí, truyền thông, phim ảnh, âm nhạc, biểu diễn nghệ thuật và khán giả.",
  words: [
    ["anthology", "n", "/ænˈθɒlədʒi/", "tuyển tập", "The story first appeared in an anthology of literary works for children."],
    ["applaud", "v", "/əˈplɔːd/", "vỗ tay, tán thưởng", "They rose to applaud the keynote speaker.", "Applaud sb for sth: khen ngợi, tán thưởng ai vì điều gì."],
    ["article", "n", "/ˈɑːtɪkl/", "bài báo", "There was an informative article in the paper yesterday."],
    ["artistic", "adj", "/ɑːˈtɪstɪk/", "thuộc về nghệ thuật, có khiếu nghệ thuật", "She was born into a very artistic family."],
    ["audience", "n", "/ˈɔːdiəns/", "khán giả", "The audience was excited to see the play.", "Audience: khán giả tại hội trường (rạp chiếu phim, vở kịch, buổi thuyết giảng). Spectator: khán giả theo dõi trực tiếp sự kiện thể thao. Viewer: khán giả xem truyền hình."],
    ["auditorium", "n", "/ˌɔːdɪˈtɔːriəm/", "hội trường, khán phòng", "The play will be performed in the school auditorium.", "Liên quan đến auditory (thính giác): auditorium là nơi “có thể nghe thấy điều gì đó” như buổi hòa nhạc hay vở kịch."],
    ["award-winning", "adj", "/əˈwɔːd wɪnɪŋ/", "đoạt giải thưởng", "His award-winning popular books have been made into movies."],
    ["biographical", "adj", "/ˌbaɪəˈɡræfɪkl/", "thuộc về tiểu sử", "There was some biographical information about the author on the first page of the novel."],
    ["broadcast", "v / n", "/ˈbrɔːdkɑːst/", "phát sóng; chương trình phát sóng", "The football championship is broadcast live to 50 countries."],
    ["broadsheet", "n", "/ˈbrɔːdʃiːt/", "báo khổ lớn (báo chính luận)", "The Washington Post is a broadsheet newspaper.", "Broadsheet xuất hiện ở Anh thế kỷ 18. Khi chính phủ đánh thuế báo theo số trang, các nhà xuất bản làm báo khổ lớn hơn để chứa nhiều nội dung trên một trang."],
    ["celebrity", "n", "/səˈlebrəti/", "người nổi tiếng", "She became a celebrity after winning an international dance award."],
    ["censorship", "n", "/ˈsensəʃɪp/", "sự kiểm duyệt", "Press censorship has been a heated issue in recent years.", "Impose censorship on sth: áp đặt sự kiểm duyệt lên cái gì."],
    ["character", "n", "/ˈkærəktə(r)/", "nhân vật; tính cách", "He likes drawing and creating his own cartoon characters.", "Character còn có nghĩa là đặc tính riêng của người/nơi chốn: Honesty is traditionally part of the Japanese character."],
    ["collaboration", "n", "/kəˌlæbəˈreɪʃn/", "sự cộng tác", "The two musicians are working in collaboration with each other to create a new song."],
    ["comedy", "n", "/ˈkɒmədi/", "hài kịch", "His latest play is described as a romantic comedy.", "Comedy bắt nguồn từ tiếng Hy Lạp cổ, ghép giữa “revel” (vui vẻ) và “singing” (ca hát)."],
    ["compose", "v", "/kəmˈpəʊz/", "sáng tác", "Beethoven started composing at the age of 10."],
    ["coverage", "n", "/ˈkʌvərɪdʒ/", "sự đưa tin", "The US midterm election was given widespread coverage."],
    ["critic", "n", "/ˈkrɪtɪk/", "nhà phê bình", "Her gripping performance was praised by critics.", "Họ từ: criticize (v) phê bình, criticism (n) sự phê bình, critical (adj) mang tính phê bình."],
    ["delight", "v / n", "/dɪˈlaɪt/", "làm vui thích; sự vui sướng", "My academic success at college delighted my parents.", "Danh từ: The news was greeted with great delight."],
    ["documentary", "n", "/ˌdɒkjuˈmentri/", "phim tài liệu", "The documentary contains many interesting facts."],
    ["evaluate", "v", "/ɪˈvæljueɪt/", "đánh giá", "The study will evaluate whether this machine is useful.", "Danh từ: evaluation (sự đánh giá)."],
    ["genre", "n", "/ˈʒɒnrə/", "thể loại", "He has written books in various genres throughout his career."],
    ["headline", "n", "/ˈhedlaɪn/", "tiêu đề (bài báo)", "The newspaper carried an alarming headline about global warming.", "Make the headlines: trở thành tin nổi bật trên báo."],
    ["humorous", "adj", "/ˈhjuːmərəs/", "hài hước", "The book takes a humorous look at teenage life.", "Danh từ humor/humour: sự hài hước — a good sense of humor."],
    ["inspiration", "n", "/ˌɪnspəˈreɪʃn/", "nguồn cảm hứng", "The joy of love provided the inspiration for the song.", "Draw inspiration from sth: lấy cảm hứng từ điều gì."],
    ["instrument", "n", "/ˈɪnstrəmənt/", "nhạc cụ; dụng cụ", "The instrument sounds like a piano.", "Instrument còn có nghĩa là dụng cụ: Dr. Otto is an inventor of some surgical instruments and appliances."],
    ["issue", "n", "/ˈɪʃuː/", "số báo (ấn bản phát hành)", "The latest issue of the journal features interviews with twelve famous singers."],
    ["journalist", "n", "/ˈdʒɜːnəlɪst/", "nhà báo", "My sister has made a name for herself as a talented journalist."],
    ["nominate", "v", "/ˈnɒmɪneɪt/", "đề cử", "She has been nominated by the party as their candidate in the next election.", "Be nominated for an award: được đề cử cho một giải thưởng."],
    ["orchestra", "n", "/ˈɔːkɪstrə/", "dàn nhạc", "The orchestra performed “Make A Wish” with great spirit.", "Conduct an orchestra: chỉ huy dàn nhạc."],
    ["paparazzi", "n", "/ˌpæpəˈrætsi/", "thợ săn ảnh", "Celebrities have to deal with screaming fans, paparazzi and a lack of privacy.", "Bắt nguồn từ phim La Dolce Vita với nhân vật nhiếp ảnh gia Paparazzo luôn bám theo các ngôi sao. Từ này dựa trên một từ địa phương tiếng Ý mô tả tiếng vo ve khó chịu của con ruồi."],
    ["performance", "n", "/pəˈfɔːməns/", "buổi biểu diễn; màn trình diễn", "This was a very impressive performance by the youngster, who won two acting awards at the age of 14."],
    ["periodical", "n", "/ˌpɪəriˈɒdɪkl/", "tạp chí xuất bản định kỳ", "The library has a number of periodicals related to the arts and sciences."],
    ["portrait", "n", "/ˈpɔːtreɪt/", "chân dung", "She got an artist to paint her portrait.", "Have one's portrait drawn/painted: nhờ người vẽ chân dung cho mình."],
    ["premiere", "v / n", "/ˈpremieə(r)/", "công chiếu, ra mắt; buổi công chiếu", "The play has been premiered in Washington.", "Danh từ: The film was given its premiere by the New Orleans Theater."],
    ["press", "n", "/pres/", "báo chí, truyền thông", "The accident has been widely reported in the press.", "Get a good/bad press: được báo chí đánh giá tốt/xấu."],
    ["publisher", "n", "/ˈpʌblɪʃə(r)/", "nhà xuất bản", "The firm has built up a reputation as an independent publisher."],
    ["readership", "n", "/ˈriːdəʃɪp/", "lượng độc giả", "The newspaper has a readership of over 100,000.", "Hậu tố -ship (membership, scholarship, championship…) thường chỉ tình trạng, trạng thái hoặc vị thế."],
    ["recital", "n", "/rɪˈsaɪtl/", "buổi độc tấu, buổi biểu diễn nhỏ", "I went to a piano recital yesterday.", "Recital: buổi biểu diễn nhỏ, thường do học sinh biểu diễn ở địa điểm nhỏ. Concert: buổi biểu diễn lớn với nghệ sĩ nổi tiếng ở địa điểm lớn."],
    ["recreational", "adj", "/ˌrekriˈeɪʃənl/", "thuộc về giải trí", "This health center provides recreational activities for senior citizens."],
    ["rehearse", "v", "/rɪˈhɜːs/", "diễn tập", "At this time tomorrow, we'll be rehearsing the final scene.", "Rehearse for sth: diễn tập cho cái gì."],
    ["release", "v / n", "/rɪˈliːs/", "phát hành", "A new mix of their hit single will be released early next month.", "Release còn có nghĩa là trả tự do: He was released from prison after serving a 44-year sentence."],
    ["repertoire", "n", "/ˈrepətwɑː(r)/", "danh mục tiết mục (có thể biểu diễn)", "Her repertoire includes a number of folk songs.", "An extensive repertoire: vốn tiết mục phong phú."],
    ["skillfully", "adv", "/ˈskɪlfəli/", "một cách khéo léo", "Some people are unable to use computers skillfully."],
    ["soundtrack", "n", "/ˈsaʊndtræk/", "nhạc phim", "The soundtrack is the best thing about this movie."],
    ["subscription", "n", "/səbˈskrɪpʃn/", "sự đăng ký (dài hạn)", "Since I have a streaming subscription, I can watch a variety of programs and movies.", "Take out a subscription to sth: đăng ký dài hạn (báo, tạp chí, dịch vụ)."],
    ["tabloid", "n", "/ˈtæblɔɪd/", "báo lá cải", "The tabloids often attract readers with shocking titles.", "Tabloid ban đầu chỉ một loại thuốc viên nén; sau đó dùng cho báo khổ nhỏ với tin tức cô đọng về tội phạm, tin đồn, chiêm tinh."],
    ["theatergoer", "n", "/ˈθɪətəɡəʊə(r)/", "khán giả (người hay đi xem kịch)", "When the play ended, theatergoers began applauding."],
    ["theme", "n", "/θiːm/", "chủ đề", "The theme of unhappy marriage runs through most of her novels."],
    ["viewership", "n", "/ˈvjuːəʃɪp/", "lượng người xem", "This channel developed a new program to increase viewership."],
  ],
  quiz: [
    q("His ------- will be published next week.", ["information", "detail", "anthology", "quality"], "C", "Anthology: tuyển tập — thứ có thể được xuất bản."),
    q("All employees were applauded ------- their contribution to the advertising campaign.", ["at", "for", "of", "to"], "B", "Applaud sb for sth: tán thưởng ai vì điều gì."),
    q("I am ------- an interesting article about the subject of heart diseases.", ["creating", "making", "doing", "designing"], "C", "Theo đáp án tài liệu: do an article (làm, thực hiện một bài báo)."),
    q("She showed her ------- abilities at a very young age.", ["artist", "artistic", "artistry", "artistically"], "B", "Bổ nghĩa cho danh từ abilities cần tính từ → artistic."),
    q("Find the wrong word: The premiere was attended by many celebrities including award-won artists, journalists and influencers.", ["premiere", "attended", "including", "award-won"], "D", "Tính từ đúng là award-winning (đoạt giải)."),
    q("The book contains a few ------- details of the last King of France.", ["biographical", "biography", "biographer", "autobiographical"], "A", "Bổ nghĩa cho details cần tính từ; nói về tiểu sử người khác → biographical (autobiographical là tự truyện)."),
    q("Live election coverage is ------- simultaneously on radio and television.", ["spread", "broadcast", "appear", "emerge"], "B", "Be broadcast on radio and television: được phát sóng trên đài và truyền hình."),
    q("The movie's success made her an overnight -------.", ["celebration", "celebrity", "celebratory", "celebrate"], "B", "An overnight celebrity: người nổi tiếng chỉ sau một đêm."),
    q("The government ------- heavy censorship of the media.", ["offered", "imposed", "provided", "started"], "B", "Impose censorship: áp đặt sự kiểm duyệt."),
    q("There is a need for close ------- between military decision-makers and the government.", ["maintenance", "permission", "collaboration", "attention"], "C", "Close collaboration between A and B: sự cộng tác chặt chẽ."),
    q("A song ------- to celebrate a wedding is called an epithalamium.", ["composing", "to compose", "composed", "composes"], "C", "Rút gọn mệnh đề quan hệ bị động (which is composed) → composed."),
    q("Media ------- focused on the war that broke out.", ["coverage", "journalist", "report", "freedom"], "A", "Media coverage: sự đưa tin của truyền thông."),
    q("Roger Ebert is a demanding -------, but he is totally impressed with the movie.", ["critical", "criticism", "critic", "criticize"], "C", "A demanding + danh từ chỉ người → critic (nhà phê bình)."),
    q("Our Planet, a ------- depicting natural beauty, won a top prize at the arts festival.", ["documentation", "document", "documentary", "documentalist"], "C", "Documentary: phim tài liệu."),
    q("Performance ------- are conducted to check the strengths and weaknesses of actors.", ["evaluative", "evaluations", "evaluated", "evaluators"], "B", "Chủ ngữ số nhiều chỉ hoạt động được tiến hành → evaluations (các buổi đánh giá)."),
    q("The mayor is now ------- the headlines with her proposal to drastically reduce local taxes.", ["doing", "making", "writing", "creating"], "B", "Make the headlines: trở thành tin nổi bật."),
    q("The advertisement states they are looking for someone who has excellent communication skills and a good sense of -------.", ["humor", "humorous", "humorously", "humorist"], "A", "A sense of humor: khiếu hài hước."),
    q("Both songs ------- their inspiration from her school life.", ["drew", "caused", "did", "made"], "A", "Draw inspiration from sth: lấy cảm hứng từ điều gì."),
    q("An advertising campaign of a tech company appears in the latest ------- of Entrepreneur Magazine.", ["communication", "promulgation", "release", "issue"], "D", "The latest issue: số báo mới nhất."),
    q("------- have been reporting live from the site of the war since early morning.", ["Journalists", "Editors", "Celebrities", "Directors"], "A", "Journalists: nhà báo đưa tin trực tiếp từ hiện trường."),
    q("Jean, who was nominated ------- an Employee of the Year Award, will deliver a keynote speech tonight.", ["to", "with", "of", "for"], "D", "Be nominated for an award: được đề cử cho giải thưởng."),
    q("He is trained to ------- an orchestra.", ["conduct", "work", "guide", "instruct"], "A", "Conduct an orchestra: chỉ huy dàn nhạc."),
    q("He has recently returned to the music scene, giving a few live ------- since May.", ["performances", "perform", "performers", "performing"], "A", "Give a live performance: biểu diễn trực tiếp; a few + danh từ số nhiều."),
    q("The library subscribes to several ------- related to climate and environment.", ["period", "periodically", "periodicals", "periodic"], "C", "Subscribe to + danh từ; several + số nhiều → periodicals (tạp chí định kỳ)."),
    q("When he had his portrait -------, he couldn't move for a few hours while the artist drew an image of him.", ["to draw", "drawing", "draw", "drawn"], "D", "Have sth done (bị động sai khiến) → have his portrait drawn."),
    q("His movies didn't ------- a very good press.", ["make", "do", "get", "build"], "C", "Get a good press: được báo chí đánh giá tốt."),
    q("She had difficulty finding ------- for her first novel.", ["publishers", "residents", "suppliers", "managers"], "A", "Tìm nhà xuất bản cho cuốn tiểu thuyết → publishers."),
    q("The town has a small man-made dam surrounded by a ------- park.", ["recreational", "recreation", "recreationally", "recreate"], "A", "Bổ nghĩa cho park cần tính từ → recreational (giải trí)."),
    q("We're rehearsing ------- the show.", ["at", "in", "during", "for"], "D", "Rehearse for sth: diễn tập cho cái gì."),
    q("They have an ------- repertoire of over 50 songs.", ["intensive", "extensive", "expansive", "thorough"], "B", "An extensive repertoire: vốn tiết mục phong phú, rộng."),
    q("“Sherlock Holmes” has been ------- written to be full of clues and provides the reader with a little misdirection.", ["skillful", "skilled", "skillfully", "unskilled"], "C", "Bổ nghĩa cho động từ written cần trạng từ → skillfully."),
    q("The ------- will be composed to match the mood of the movie.", ["cinematography", "scene", "soundtrack", "script"], "C", "Thứ được “compose” (sáng tác) để hợp không khí phim → soundtrack (nhạc phim)."),
    q("My mother ------- a subscription to “Horticulture” magazine because she loves gardening.", ["takes off", "takes up", "takes out", "takes on"], "C", "Take out a subscription: đăng ký dài hạn."),
    q("The director of the film asks ------- not to record during the performance.", ["theatergoers", "spectators", "playwrights", "editors"], "A", "Khán giả xem buổi biểu diễn tại rạp → theatergoers (spectators dùng cho thể thao)."),
    q("The major ------- of this novel is growing in love.", ["discussion", "theme", "argument", "color"], "B", "Theme: chủ đề của tác phẩm."),
    q("The People Meter is a device which is used to ------- television viewership.", ["see", "write", "show", "measure"], "D", "Measure viewership: đo lượng người xem."),
  ],
  written: [
    { q: "Sắp xếp thành câu: genre / Historical / interesting / is / containing / stories / fiction / a / some.", a: "Historical fiction is a genre containing some interesting stories." },
  ],
};
