import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const MANUFACTURING: IigTopic = {
  slug: "manufacturing",
  title: "Manufacturing",
  titleVi: "Sản xuất",
  summary: "Nhà máy, nguyên liệu, máy móc, năng suất, xuất nhập khẩu và kho vận.",
  words: [
    ["allocate", "v", "/ˈæləkeɪt/", "phân phối, phân bổ", "The company allocated 5,000 USD for developing the new product."],
    ["automatically", "adv", "/ˌɔːtəˈmætɪkli/", "một cách tự động", "The camera focuses automatically."],
    ["absorb", "v", "/əbˈzɔːb/", "hấp thụ", "The clay soil in this area doesn't absorb water well."],
    ["adjustment", "n", "/əˈdʒʌstmənt/", "sự điều chỉnh", "She made some adjustments to her uniform so that it looks more stylish.", "Alteration: thay đổi một phần (diện mạo, quy mô) nhưng giữ đặc tính cơ bản. Adjustment: sắp xếp, chỉnh sửa lại một chút cho phù hợp. Adaptation: thay đổi để phù hợp với điều kiện mới."],
    ["accumulate", "v", "/əˈkjuːmjəleɪt/", "tích tụ, chất đống", "The company's debt was accumulated during the Covid-19 pandemic since its turnover was insignificant."],
    ["analysis", "n", "/əˈnæləsɪs/", "bản phân tích, sự phân tích", "Clare's analysis of the situation was interesting.", "Họ từ: analyse/analyze (v) phân tích; analyser (n) máy phân tích; analyst (n) người phân tích; analytic (adj) thuộc phân tích; analysable (adj) có thể phân tích."],
    ["bankrupt", "v / adj", "/ˈbæŋkrʌpt/", "làm phá sản; phá sản", "Many businesses went bankrupt during the Great Depression.", "Gốc tiếng Ý banca rotta = 'băng ghế bị gãy': người buôn tiền làm việc trên băng ghế; hết tiền thì băng ghế bị bẻ gãy và phải ngừng kinh doanh."],
    ["crucial", "adj", "/ˈkruːʃl/", "then chốt, cực kỳ quan trọng", "It is crucial that all the machines are turned off before you leave.", "Essential: cần thiết, phẩm chất cơ bản (vitamin A is essential for eyes). Crucial: cực kỳ quan trọng vì ảnh hưởng đến những điều khác (research into renewable energy is crucial)."],
    ["consumption", "n", "/kənˈsʌmpʃn/", "sự tiêu thụ", "Consumption of electricity may be lower during the winter months because people don't use air-conditioners."],
    ["catalogue", "n", "/ˈkætəlɒɡ/", "danh mục sản phẩm", "I bought the television advertised in the catalogue.", "Xuất hiện từ những năm 1400, gốc Hy Lạp katálogos (danh sách) và katalégein (liệt kê)."],
    ["commodity", "n", "/kəˈmɒdəti/", "hàng hóa", "Clean water is a precious commodity in Africa."],
    ["carriage", "n", "/ˈkærɪdʒ/", "phí vận chuyển; toa hành khách", "You can buy a whole side of salmon for €30, including carriage.", "Carriage còn là toa hành khách: the first-class carriage (toa hạng nhất)."],
    ["construct", "v", "/kənˈstrʌkt/", "xây dựng", "A new bridge will be constructed next month.", "Construct trang trọng hơn build và không dùng cho quan hệ tình cảm: build a relationship (đúng), construct a relationship (sai)."],
    ["classify", "v", "/ˈklæsɪfaɪ/", "phân loại", "The librarians are rearranging books and classifying them by subject."],
    ["diminution", "n", "/ˌdɪmɪˈnjuːʃn/", "sự giảm bớt", "This steel company suffered a diminution in profits."],
    ["distribute", "v", "/dɪˈstrɪbjuːt/", "phân phối, phân phát", "According to the statistics, products are unevenly distributed."],
    ["export", "v", "/ɪkˈspɔːt/", "xuất khẩu", "Vietnam is considered one of the countries which export the most rice in the world."],
    ["employer", "n", "/ɪmˈplɔɪə(r)/", "người sử dụng lao động", "A reference from your previous employer can impress the recruiter."],
    ["employee", "n", "/ɪmˈplɔɪiː/", "người lao động, nhân viên", "The number of employees in the company has doubled over the past 5 years."],
    ["equipment", "n", "/ɪˈkwɪpmənt/", "máy móc, trang thiết bị", "Accidents due to unsafe equipment are no longer common nowadays.", "State-of-the-art equipment: thiết bị hiện đại nhất; electronic equipment: thiết bị điện tử; capital equipment: thiết bị sản xuất."],
    ["establish", "v", "/ɪˈstæblɪʃ/", "thành lập", "Established in 1995, this organization has gained a lot of achievements.", "Establish: thành lập, nhấn mạnh sự tồn tại lâu dài; dùng cả với giá trị vô hình (establish our friendship, reputation). Found: sáng lập; xây dựng một niềm tin, ý tưởng."],
    ["filter", "v", "/ˈfɪltə(r)/", "lọc", "You should filter out all the dirt before using the water."],
    ["invoice", "n", "/ˈɪnvɔɪs/", "hóa đơn", "Please review the invoice to ensure all information is correct."],
    ["initiate", "v", "/ɪˈnɪʃieɪt/", "khởi xướng", "He was blamed for initiating the violence among employees.", "Initiate còn có nghĩa làm lễ kết nạp (v) và người đã được kết nạp (n)."],
    ["industry", "n", "/ˈɪndəstri/", "ngành công nghiệp", "Post Covid-19, the tourism industry, especially the hotel sector, suffered from a lack of human resources.", "Họ từ: industrial (adj) thuộc công nghiệp; industrialize (v) công nghiệp hóa; industrialization (n) sự công nghiệp hóa."],
    ["import", "v", "/ɪmˈpɔːt/", "nhập khẩu", "Clothes are imported to Vietnam from China at reasonable prices."],
    ["inventory", "v / n", "/ˈɪnvəntri/", "kiểm kê; hàng tồn kho", "All products should be inventoried carefully before sales.", "Đừng nhầm với họ từ của invent: inventor (nhà phát minh), inventive (có óc sáng tạo)."],
    ["index", "n", "/ˈɪndeks/", "chỉ số", "According to the World Happiness Report 2022, Finland has the highest happiness index in the world.", "Index còn là động từ: lập bảng chú dẫn (David organized and indexed the material by computer)."],
    ["infrastructure", "n", "/ˈɪnfrəstrʌktʃə(r)/", "cơ sở hạ tầng", "Hanoi's infrastructure was badly damaged in Operation Linebacker II.", "Gốc tiếng Pháp; đến thời Chiến tranh Lạnh mới phổ biến để chỉ căn cứ quân sự, đường sắt, sân bay của NATO."],
    ["labor", "n", "/ˈleɪbə(r)/", "người lao động, nhân công", "Unskilled labor is acceptable for this position."],
    ["location", "n", "/ləʊˈkeɪʃn/", "địa điểm", "The hotel is in a beautiful location overlooking the lake.", "Position: một điểm cụ thể có quan hệ với người/vật khác (the sofa is in a different position). Location: điểm cụ thể trong không gian vật lý, địa lý (the location of a business)."],
    ["materials", "n", "/məˈtɪəriəlz/", "nguyên vật liệu", "Britain exports building materials to Japan.", "Material không đếm được khi chỉ vật liệu nói chung (How much material will you need?); đếm được khi chỉ vật liệu cho mục đích cụ thể (raw materials for industry)."],
    ["manpower", "n", "/ˈmænpaʊə(r)/", "nhân lực", "The company has implemented numerous policies to deal with the manpower shortage."],
    ["manufacturer", "n", "/ˌmænjuˈfæktʃərə(r)/", "nhà sản xuất", "It is believed that buying direct from the manufacturer is much cheaper.", "Manufacture (v) sản xuất; manufacture (n) sự sản xuất; manufacturable (adj) có thể sản xuất được."],
    ["monopolize", "v", "/məˈnɒpəlaɪz/", "giữ độc quyền", "The USA used to monopolize nuclear weapons.", "Monopoly (n) sự độc quyền; monopolist (n) người độc quyền; monopolization (n) sự giữ độc quyền."],
    ["mechanic", "n", "/məˈkænɪk/", "thợ máy, công nhân cơ khí", "Wilson is one of the most skillful mechanics in my workshop."],
    ["outlet", "n", "/ˈaʊtlet/", "ổ cắm điện; lối thoát", "We need to install more outlets in the office because the current quantity can't meet the demand.", "Outlet còn có nghĩa chỗ thoát, lối ra: an outlet of water."],
    ["productivity", "n", "/ˌprɒdʌkˈtɪvəti/", "năng suất", "If a working environment is pleasant and friendly, productivity will increase.", "Đồng nghĩa: productiveness."],
    ["productive", "adj", "/prəˈdʌktɪv/", "có năng suất", "I think Peter will be rewarded since he has worked the most productively this year."],
    ["processing", "n", "/ˈprəʊsesɪŋ/", "sự gia công, xử lý", "The data processing may take some time."],
    ["package", "v", "/ˈpækɪdʒ/", "đóng gói", "The picture stand is packaged carefully in a carton box."],
    ["plant", "n", "/plɑːnt/", "nhà máy", "More than three motor-assembly plants were closed due to the strike.", "Factory: nơi sản xuất ra sản phẩm. Plant: nơi thực hiện một quy trình sản xuất (đóng gói, xử lý vật liệu…)."],
    ["revolutionize", "v", "/ˌrevəˈluːʃənaɪz/", "cách mạng hóa", "Machines revolutionized agriculture, saving labor power and increasing productivity.", "Không có danh từ 'revolutionization'; revolutionary vừa là tính từ (mang tính cách mạng) vừa là danh từ (nhà cách mạng)."],
    ["substandard", "adj", "/ˌsʌbˈstændəd/", "không đạt tiêu chuẩn", "Substandard products will be removed before being brought to the rubbish dump.", "Tiền tố sub- = ở dưới, ít hơn: subway (tàu điện ngầm), submarine (tàu ngầm)."],
    ["system", "n", "/ˈsɪstəm/", "hệ thống", "Only authorized personnel have access to the computer system."],
    ["strike", "v / n", "/straɪk/", "đình công", "Employees strike for better pay and improved safety standards.", "Strike upon an idea: nảy ra ý tưởng; strike up sth/sb: bắt đầu điều gì, làm quen với ai."],
    ["schedule", "n", "/ˈʃedjuːl/", "kế hoạch, lịch trình", "The meeting will be held as scheduled no matter what happens."],
    ["supplier", "n", "/səˈplaɪə(r)/", "nhà cung cấp", "We can buy in bulk since we have relationships with suppliers."],
    ["transport", "v", "/trænˈspɔːt/", "vận chuyển", "We transport cloth by truck."],
    ["warehouse", "n", "/ˈweəhaʊs/", "nhà kho", "The goods have been sitting in the warehouse for months because of a strike which has prevented distribution."],
  ],
  quiz: [
    q("Find the wrong word: The equipment are automatically distributed and arranged.", ["Equipment", "are", "automatically", "arranged"], "B", "Equipment là danh từ không đếm được → động từ số ít is."),
    q("What does \"it\" refer to? Human activity decreases forests and increases the usage of fuels; therefore, the gas of carbon dioxide is output more and more and there are not enough plants to absorb it.", ["The usage of fuels", "The gas of carbon dioxide", "Activity", "Forests"], "B", "Cây xanh hấp thụ khí CO2 → it = the gas of carbon dioxide."),
    q("On TV, the weatherman is calling for at least six inches of snow -------, but we don't know the actual amount of the build-up outside our house.", ["accumulate", "accumulating", "accumulated", "accumulation"], "D", "Snow accumulation: lượng tuyết tích tụ (danh từ)."),
    q("The meat was declared unfit for human -------.", ["use", "depletion", "consumption", "eating"], "C", "Unfit for human consumption: không thích hợp cho người dùng."),
    q("Perhaps 100 years ago, it was daydreaming that we could today obtain information as well as ------- via the Internet.", ["commodity", "material", "materials", "commodities"], "D", "Commodities: hàng hóa (số nhiều, song song với information)."),
    q("The Ogam alphabet shows some knowledge of phonetics and some attempt ------- the sounds accordingly.", ["classifying", "to classify", "be classified", "being classified"], "B", "Attempt to V: nỗ lực làm gì."),
    q("Find the antonym of \"diminution\".", ["decrease", "reduction", "growth", "lessening"], "C", "Diminution (sự giảm) trái nghĩa với growth (sự tăng)."),
    q("At university, you need to learn how to ------- your study time and acquire the capability of learning by yourself.", ["to distribute", "distribute", "distributing", "to distributing"], "B", "How to + V nguyên mẫu."),
    q("------- are so satisfied with the opportunities to progress in the business that they don't leave the company.", ["Director", "Customer", "Employees", "Labor"], "C", "Động từ are số nhiều, chỉ người làm trong công ty → Employees."),
    q("By using some tools, we can save a lot of time to ------- and ------- the useful information.", ["distinguish – filter", "filter – distinguish", "distinguishing – filtering", "filtering – distinguishing"], "A", "To + V nguyên mẫu: phân biệt rồi lọc thông tin hữu ích."),
    q("It seems that the electricity ------- is always lower than the water one.", ["invoice", "check", "payment", "bill"], "D", "Electricity bill: hóa đơn tiền điện (gửi cá nhân)."),
    q("Find the wrong word: After you import a car into the U.S. from Canada, make sure you understand the process.", ["After", "import", "into", "process"], "A", "Phải hiểu quy trình trước khi nhập khẩu → After sửa thành Before."),
    q("Before his occupational accident, he used to be a good -------.", ["mechanics", "mechanical", "mechanic", "both A & C"], "C", "A good + danh từ số ít chỉ người → mechanic."),
    q("To make employees more productive, many companies provide them with on-the-job training. Choose the antonym of \"productive\".", ["valuable", "unproductive", "dynamic", "redundant"], "B", "Unproductive: không hiệu quả."),
    q("Before the raisins -------, they are sorted by size.", ["packages", "package", "are packaged", "packaged"], "C", "Nho khô được đóng gói → bị động are packaged."),
    q("Choose the antonym of \"supplier\".", ["buyer", "consumer", "manufacturer", "employer"], "B", "Theo đáp án tài liệu: consumer (người tiêu dùng) đối lập với supplier (người cung cấp)."),
    q("The ------- was badly damaged by fire and two employees inventorying products were missing.", ["house", "garage", "warehouse", "station"], "C", "Kiểm kê hàng hóa → warehouse (nhà kho)."),
  ],
  written: [
    { q: "Sắp xếp thành câu: children / Money / allocated / of the / each / sale / the / concert / from / ticket / to / was / the", a: "Money from the sale of the concert ticket was allocated to each of the children." },
    { q: "Sắp xếp thành câu: market / coffee / is / Brazil / to / export / develop / planning.", a: "Brazil is planning to develop its coffee export market." },
    { q: "Sắp xếp thành câu: recently / necessary / have / employment / graduates / that / Some / the / in / suggested / the / employers / many / of / world / lack / tools / survive / to.", a: "Some employers have recently suggested that many graduates lack the necessary tools to survive in the world of employment." },
    { q: "Sắp xếp thành câu: The labor / capitalist / In / and / the capital / there / countries, / conflict / is / serious / a / between.", a: "In capitalist countries, there is a serious conflict between the labor and the capital." },
    { q: "Sắp xếp thành câu: turnover, / the / will be / 20% / Due to / the / manpower / decrease / by / in / company's / reduced", a: "Due to the decrease in the company's turnover, manpower will be reduced by 20%." },
    { q: "Sắp xếp thành câu: Nowadays, / processing / used / more and more / natural / are / computers / language / for.", a: "Nowadays, more and more computers are used for natural language processing." },
    { q: "Sắp xếp thành câu: second / for / Students / the / class / are / their / planning / semester / schedules", a: "Students are planning their class schedules for the second semester." },
    { q: "Sắp xếp thành câu: Public / key / congestion / for / is / traffic / the / transport / solution.", a: "Public transport is the key solution for traffic congestion." },
  ],
};
