import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const OFFICES: IigTopic = {
  slug: "offices",
  title: "Offices",
  titleVi: "Văn phòng",
  summary: "Từ vựng về công việc văn phòng: hợp đồng, phòng ban, nhân sự, lương thưởng, chính sách.",
  words: [
    ["access", "v", "/ˈækses/", "tiếp cận, truy cập", "Visitors can access the internet through the guest Wi-Fi network."],
    ["accessible", "adj", "/əkˈsesəbl/", "dễ tiếp cận", "These advertising campaigns are not accessible to the public."],
    ["agency", "n", "/ˈeɪdʒənsi/", "cơ quan, đại lý", "The programme gets considerable support from international agencies."],
    ["allocate", "v", "/ˈæləkeɪt/", "phân bổ", "The fund allocated $10 thousand to upgrade the computer system."],
    ["appointment", "n", "/əˈpɔɪntmənt/", "cuộc hẹn", "Would you like to make an appointment?"],
    ["assessment", "n", "/əˈsesmənt/", "sự đánh giá", "All new employees are required to take an English assessment test.", "Phân biệt: assessment — sự đánh giá của một người sau khi suy nghĩ rất cẩn thận; judgement — sự đánh giá, quyết định từ tòa án; appraisal — sự đánh giá mức độ thành công của ai đó."],
    ["assistant", "n", "/əˈsɪstənt/", "trợ lý", "He worked as an assistant to the head of the department.", "Ngoài vai trò danh từ, assistant còn được dùng như tính từ khi nói về vai trò trợ lý: My mother is an assistant director at a company in Washington, D.C."],
    ["assign", "v", "/əˈsaɪn/", "phân công", "Two senior officers have been assigned to the case."],
    ["benefit", "n", "/ˈbenɪfɪt/", "phúc lợi, lợi ích", "The new system will be a great benefit to the company."],
    ["co-worker", "n", "/ˌkəʊˈwɜːkə(r)/", "đồng nghiệp", "She has been described by former co-workers as a passionate content writer.", "Tiền tố co- (gốc Latin) mang nghĩa cùng nhau, phối hợp: exist → co-exist (cùng tồn tại), workers → co-workers (đồng nghiệp)."],
    ["commute", "v", "/kəˈmjuːt/", "đi lại thường xuyên giữa nơi ở và nơi làm việc", "She commutes from Cau Giay to Thai Ha every day.", "Trong ngữ cảnh tòa án, commute còn mang nghĩa giảm án: His sentence was commuted from death to life imprisonment."],
    ["contract", "n", "/ˈkɒntrækt/", "hợp đồng", "Most employees sign an official contract after a two-month trial period."],
    ["consumer", "n", "/kənˈsjuːmə(r)/", "người tiêu dùng", "The company has launched a successful marketing campaign after carefully studying consumer insight.", "Phân biệt: consumer — người sử dụng cuối cùng hàng hóa/dịch vụ, không có quyền bán lại; customer — người mua sản phẩm (cá nhân, công ty, tập thể), có quyền bán lại."],
    ["compete", "v", "/kəmˈpiːt/", "cạnh tranh", "It's difficult to compete against international competitors."],
    ["client", "n", "/ˈklaɪənt/", "khách hàng (sử dụng dịch vụ)", "May a lawyer defend a client whom he knows to be guilty?", "Client là khách hàng sử dụng dịch vụ nhằm nhận được lời khuyên, tư vấn."],
    ["data", "n", "/ˈdeɪtə/", "dữ liệu", "The data were collected by a group of professional researchers.", "Data là dạng số nhiều; datum là dạng số ít — không có 'datas'."],
    ["document", "n", "/ˈdɒkjumənt/", "tài liệu", "The project documents are managed by the PM."],
    ["deadline", "n", "/ˈdedlaɪn/", "hạn chót", "If you miss the deadline, your application won't be considered.", "Thời nội chiến Mỹ, deadline chỉ hàng rào trong khuôn viên nhà tù ('ranh giới chết'); đầu thế kỷ 20 nghĩa là vạch không được vượt qua; ngày nay dùng với nghĩa hạn chót công việc."],
    ["deal", "v / n", "/diːl/", "thỏa thuận, giao dịch; giải quyết (deal with)", "Rumor has it that the company is dealing with 3 agencies to market its products."],
    ["department", "n", "/dɪˈpɑːtmənt/", "phòng ban", "Our department has more than 60 employees."],
    ["elevator", "n", "/ˈelɪveɪtə(r)/", "thang máy", "I took the elevator to my office on the third floor.", "Elevator là tiếng Anh Mỹ; tiếng Anh Anh dùng lift. Thường đi với động từ take: I would rather take the elevator instead of the stairs."],
    ["employee", "n", "/ɪmˈplɔɪiː/", "nhân viên, người lao động", "All of the employees in this company have insurance.", "Các từ có hậu tố -ee (employee, trainee…) chỉ người; trọng âm luôn rơi vào -ee."],
    ["executive", "adj / n", "/ɪɡˈzekjətɪv/", "điều hành, quản lý; người điều hành", "His executive skills will be very useful to the company.", "Executive còn là danh từ chỉ người giữ chức vụ cao trong công ty, tổ chức (chief, director, principal)."],
    ["establish", "v", "/ɪˈstæblɪʃ/", "thành lập", "The New York City branch of the firm has just been established."],
    ["explain", "v", "/ɪkˈspleɪn/", "giải thích", "It is difficult to explain exactly how the system works.", "Từ đồng nghĩa: clarify — làm sáng tỏ; define — giải thích, mô tả chính xác; justify — biện minh để chứng minh là đúng."],
    ["foundation", "n", "/faʊnˈdeɪʃn/", "tổ chức (quỹ); nền móng", "The research centre was set up by a charitable foundation.", "Foundation còn có nghĩa nền móng, nền tảng: From firm foundations we will continue to grow the business."],
    ["helpdesk", "n", "/ˈhelpdesk/", "bộ phận hỗ trợ", "Please contact the helpdesk in case you have any problem with your computer."],
    ["insurance", "n", "/ɪnˈʃʊərəns/", "bảo hiểm", "All employees' medical expenses are covered by insurance."],
    ["management", "n", "/ˈmænɪdʒmənt/", "sự quản lý; ban quản lý", "The company has suffered from several years of poor management."],
    ["manager", "n", "/ˈmænɪdʒə(r)/", "người quản lý", "If you have any question, feel free to ask your manager.", "Có thể thay bằng: supervisor — người giám sát; boss — sếp."],
    ["performance", "n", "/pəˈfɔːməns/", "hiệu suất", "The team has continued to improve their overall performance.", "Khi mang nghĩa hiệu suất, performance là danh từ không đếm được."],
    ["pension", "n", "/ˈpenʃn/", "lương hưu", "He retired at 60 with a good amount of pension.", "Phân biệt: wage — tiền công theo ngày/giờ/tuần; salary — tiền lương cố định theo tháng; pension — lương hưu cho người hết tuổi lao động."],
    ["petition", "n / v", "/pəˈtɪʃn/", "đơn kiến nghị; kiến nghị", "The company staff signed a petition against the layoff.", "Petition còn là động từ: They're petitioning for updating the whole computer system of the company."],
    ["policy", "n", "/ˈpɒləsi/", "chính sách", "No smoking is the company policy.", "Phân biệt: policy — do tổ chức, cá nhân lập ra để đạt mục tiêu công việc; regulation — luật lệ do cơ quan nhà nước đặt ra để kiểm soát hành vi."],
    ["retirement", "n", "/rɪˈtaɪəmənt/", "sự nghỉ hưu", "He announced his retirement in September."],
    ["suit", "v", "/suːt/", "phù hợp", "We can hang out this afternoon or any time that suits you.", "Phân biệt: fit — vừa vặn về hình dáng, kích cỡ (my trousers don't fit me); suit — phù hợp, khiến ai thấy thoải mái/trông hợp hơn (working time from 1 p.m. suits me best)."],
    ["portfolio", "n", "/pɔːtˈfəʊliəʊ/", "hồ sơ năng lực", "You can send your portfolio to the HR department via email.", "CV là danh mục kỹ năng, thành tựu; portfolio dùng để chứng minh những thành tựu đó."],
    ["recruit", "v", "/rɪˈkruːt/", "tuyển dụng", "He's responsible for recruiting new employees at all levels."],
    ["recur", "v", "/rɪˈkɜː(r)/", "tái diễn, lặp lại", "If the problem recurs, you will be fined."],
    ["remind", "v", "/rɪˈmaɪnd/", "nhắc nhở", "Remind me to phone Musk before I go out."],
    ["report", "v", "/rɪˈpɔːt/", "báo cáo, trình báo", "We called the police to report the theft."],
    ["resolve", "v", "/rɪˈzɒlv/", "giải quyết", "The conflict must be resolved thoroughly before proceeding to the next step."],
    ["staple", "v", "/ˈsteɪpl/", "ghim, kẹp (giấy)", "Could you help me staple the invoice and the receipt together?"],
    ["salary", "n", "/ˈsæləri/", "tiền lương hàng tháng", "The starting salary for a fresh graduate might be below average."],
    ["schedule", "n", "/ˈʃedjuːl/", "thời gian biểu", "The course schedule is available on the website."],
    ["scheme", "v / n", "/skiːm/", "dự tính, mưu tính; kế hoạch", "He schemed to become the top salesperson.", "Scheme còn là danh từ chỉ một kế hoạch được lên chi tiết, cụ thể."],
    ["specialist", "n", "/ˈspeʃəlɪst/", "chuyên gia", "She works as a finance specialist for a large commercial bank."],
    ["staff", "n", "/stɑːf/", "nhân viên (tập thể)", "There is a good relationship between the staff and students in this school.", "Staff là danh từ tập hợp chỉ toàn thể nhân viên nên thường dùng như danh từ số nhiều."],
    ["treasurer", "n", "/ˈtreʒərə(r)/", "thủ quỹ", "The treasurer is responsible for financial reporting.", "Phân biệt: treasurer — giám sát dòng tiền chi tiêu hằng ngày, đảm bảo minh bạch tài chính; accountant — thu thập, ghi chép, xử lý và báo cáo thông tin tài chính."],
    ["warrant", "v", "/ˈwɒrənt/", "bảo đảm", "We do not warrant the consistent functioning of the machine in case any component is replaced."],
  ],
  quiz: [
    q("------- to the services of these systems was extremely limited, so you can ask the IT Department for help.", ["Access", "Accessing", "Accession", "Accesses"], "A", "Chỗ trống làm chủ ngữ, cụm access to: quyền truy cập vào."),
    q("Computers should be made readily ------- to office workers.", ["accessed", "accession", "accessible", "access"], "C", "Make + O + adj; accessible to: dễ tiếp cận với."),
    q("Find the wrong word: When a customer place an order, it is forwarded to the appropriate agency.", ["place", "forwarded", "to", "agency"], "A", "Chủ ngữ a customer số ít → places."),
    q("More funds will now be ------- charitable organizations.", ["allocated to", "allocating to", "allocated for", "allocating for"], "A", "Bị động be allocated to: được phân bổ cho."),
    q("I'd like to ------- an appointment with Dr Evans, please.", ["make", "set", "get", "create"], "A", "Make an appointment: đặt lịch hẹn."),
    q("She has just been assigned ------- the office in Washington, D.C.", ["for", "to", "in", "with"], "B", "Be assigned to: được phân công đến."),
    q("A ------- package must cover the full detail of pay, insurance and vacation time available to an employee.", ["benefits", "benefit", "benefiting", "beneficial"], "A", "Benefits package: gói phúc lợi."),
    q("Find the wrong word: He signed a four-year contraction with an annual salary of $1.2 million.", ["four-year", "contraction", "with", "of"], "B", "Sign a contract: ký hợp đồng → contraction sửa thành contract."),
    q("Startup companies must compete ------- established companies which have had many years to build up their markets.", ["against", "with", "to", "at"], "A", "Compete against: cạnh tranh với (đối thủ)."),
    q("Find the wrong word: Researchers analysed datas on 2,515 customer visits to their website.", ["datas", "on", "customer", "visits"], "A", "Data đã là dạng số nhiều (số ít là datum) → không có 'datas'."),
    q("Please read and sign the attached -------.", ["documentary", "documention", "documentory", "document"], "D", "Sau tính từ attached cần danh từ document (tài liệu)."),
    q("The two issues ------- with separately.", ["can deal", "is dealing", "have dealt", "should be dealt"], "D", "Hai vấn đề được giải quyết → bị động should be dealt with."),
    q("Contact our sales ------- for more information.", ["departmental", "department", "departion", "departure"], "B", "Sales department: phòng kinh doanh."),
    q("The committee of public safety ------- in 1912.", ["has established", "established", "was established", "was establishing"], "C", "Ủy ban được thành lập năm 1912 → bị động quá khứ was established."),
    q("What services can an airport helpdesk NOT provide?", ["ticket change", "flight schedule information", "transit facility", "ticket refund"], "C", "Helpdesk hỗ trợ đổi vé, thông tin chuyến bay, hoàn vé — không cung cấp cơ sở trung chuyển."),
    q("General ------- covers all risks except life.", ["insurable", "insurance", "insured", "insurability"], "B", "General insurance: bảo hiểm phi nhân thọ."),
    q("Find the wrong word: We shall be implementing a new manager structure in order to deal with the changed sales environment.", ["be", "implementing", "manager", "changed"], "C", "Management structure: cơ cấu quản lý → manager sửa thành management."),
    q("Find the wrong word: He has been praising the recent excellent performances of the sales team for 2 hours.", ["recent", "praising", "performances", "for"], "C", "Performance mang nghĩa hiệu suất là danh từ không đếm được → performance."),
    q("Ten new members were recruited ------- the secretary teams.", ["into", "for", "to", "as"], "C", "Theo đáp án tài liệu: recruited to the teams (được tuyển vào nhóm)."),
    q("This theme ------- several times throughout the book.", ["recurs", "recurred", "recurring", "recursion"], "B", "Theo đáp án tài liệu: recurred (chủ đề này đã lặp lại nhiều lần)."),
    q("Find the wrong word: Reading the note suddenly reminding me of my appointment with Angela.", ["Reading", "suddenly", "reminding", "of"], "C", "Câu thiếu động từ chính → reminding sửa thành reminded."),
    q("My neighbours ------- me to the police for firing my rifle in the garden.", ["informed", "described", "reported", "announced"], "C", "Report somebody to the police: trình báo ai với cảnh sát."),
    q("Find the wrong word: We hope to resolved the matter as soon as possible.", ["hope", "as", "resolved", "possible"], "C", "Hope to + V nguyên mẫu → resolve."),
    q("The ------- plan guarantees a pension based on final salary and years of service.", ["retirement", "working", "business", "holiday"], "A", "Retirement plan: kế hoạch hưu trí."),
    q("Remember to staple the payment slip ------- the financial report.", ["to", "with", "over", "into"], "A", "Staple A to B: ghim A vào B."),
    q("The ------- goes directly to his bank account on the last Friday of each month.", ["income", "wage", "payroll", "salary"], "D", "Salary: tiền lương trả cố định hàng tháng."),
    q("All planned work has been completed; the project is right ------- schedule.", ["on", "in", "at", "now"], "A", "(Right) on schedule: đúng tiến độ."),
    q("A therapist is a ------- who can treat a particular type of mental or physical illness.", ["doctor", "healer", "specialist", "nurse"], "C", "Specialist: chuyên gia về một lĩnh vực cụ thể (a particular type)."),
    q("The ------- covers the photocopier mechanically for a year, with unlimited mileage.", ["warranty", "warrantee", "warrantation", "warrantist"], "A", "Warranty: phiếu/chế độ bảo hành."),
  ],
  written: [],
};
