import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const PERSONNEL: IigTopic = {
  slug: "personnel",
  title: "Personnel",
  titleVi: "Nhân sự",
  summary: "Tuyển dụng, phỏng vấn, đánh giá, thăng chức, đào tạo và phúc lợi nhân viên.",
  words: [
    ["abundant", "adj", "/əˈbʌndənt/", "dồi dào, nhiều", "The recruiters are surprised by the abundant number of potential candidates."],
    ["ability", "n", "/əˈbɪləti/", "năng lực, khả năng", "The designer's ability was obvious from his portfolio.", "Ability: khả năng có được do rèn luyện. Capacity: khả năng đặc biệt, thiên bẩm."],
    ["achievement", "n", "/əˈtʃiːvmənt/", "thành tựu", "The company is going to throw a party to celebrate their achievements in the last quarter."],
    ["appraisal", "n", "/əˈpreɪzl/", "sự đánh giá", "Millions of employees undergo formal appraisal."],
    ["appointment", "n", "/əˈpɔɪntmənt/", "cuộc hẹn", "I've got a two o'clock appointment with my colleagues."],
    ["apprentice", "n", "/əˈprentɪs/", "người học việc", "Most of the work was done by apprentices."],
    ["apply", "v", "/əˈplaɪ/", "nộp đơn xin việc; áp dụng", "After graduating from university, she applied for three jobs and received only one offer."],
    ["assignment", "n", "/əˈsaɪnmənt/", "nhiệm vụ", "Our next assignment will be to find missing persons in the earthquake."],
    ["branch", "n", "/brɑːntʃ/", "chi nhánh", "I used to work in the local branch of a large bank.", "Branch còn có nghĩa cành cây hoặc nhánh sông: Da River, Lo River and Thao River are three main branches of the Red River."],
    ["compensate", "v", "/ˈkɒmpenseɪt/", "trả công; bồi thường", "Employees must be compensated for any extra hours worked.", "Compensate còn có nghĩa đền bù: Victims of the crash will be compensated for their injuries."],
    ["consult", "v", "/kənˈsʌlt/", "tham khảo ý kiến", "I have to consult the manager about the matter."],
    ["collaborator", "n", "/kəˈlæbəreɪtə(r)/", "cộng tác viên", "This is a new product by Andrew Davies and his collaborators."],
    ["conduct", "v", "/kənˈdʌkt/", "thực hiện, tiến hành", "The training in how to use the new machine will be conducted this weekend."],
    ["candidate", "n", "/ˈkændɪdət/", "ứng viên", "The firm will only invite the candidates who passed the phone interview for an on-site interview."],
    ["duty", "n", "/ˈdjuːti/", "nhiệm vụ, bổn phận", "His duties included photographing engineering projects such as bridges and airfields.", "Duty: bổn phận, trách nhiệm mang tính đạo đức hoặc pháp lý. Mission: nhiệm vụ, sứ mệnh khi đại diện cho quốc gia, tổ chức."],
    ["dedication", "n", "/ˌdedɪˈkeɪʃn/", "sự cống hiến", "He has inspired everyone with his dedication and hard work."],
    ["designate", "v", "/ˈdezɪɡneɪt/", "bổ nhiệm, chỉ định", "The President's designated successor is his daughter.", "Designate còn là tính từ đặt sau danh từ: được bổ nhiệm nhưng chưa chính thức nhậm chức (the director designate)."],
    ["expertise", "n", "/ˌekspɜːˈtiːz/", "chuyên môn", "Software is not really my area of expertise."],
    ["eligible", "adj", "/ˈelɪdʒəbl/", "đủ tiêu chuẩn", "I would consider myself eligible for a promotion."],
    ["flexibly", "adv", "/ˈfleksəbli/", "một cách linh hoạt", "In today's competitive market, businesses need to work flexibly to adapt to market conditions."],
    ["guidance", "n", "/ˈɡaɪdns/", "sự hướng dẫn", "The consultant offers guidance to employers on employment law."],
    ["hesitation", "n", "/ˌhezɪˈteɪʃn/", "sự do dự", "After a slight hesitation, she began to speak.", "Collocation: a moment of hesitation — vài giây do dự."],
    ["intern", "n", "/ˈɪntɜːn/", "thực tập sinh", "After I graduate, I plan to work as an intern at an advertising agency."],
    ["interview", "v / n", "/ˈɪntəvjuː/", "phỏng vấn", "I was interviewed by a manager yesterday."],
    ["offer", "v / n", "/ˈɒfə(r)/", "đề nghị", "She was offered a job in Paris."],
    ["negotiate", "v", "/nɪˈɡəʊʃieɪt/", "đàm phán", "I've managed to negotiate a five percent pay increase with my boss.", "Negotiate còn có nghĩa trao đổi, chuyển nhượng: We can negotiate any single cheque up to the value of £2000."],
    ["professional", "adj / n", "/prəˈfeʃənl/", "chuyên nghiệp; người chuyên nghiệp", "Appearing in the meeting, Mrs. Wallace looks very professional in her suit.", "Danh từ professional: người lành nghề — Many people don't get professionals to paint their houses."],
    ["presentable", "adj", "/prɪˈzentəbl/", "ăn mặc chỉnh tề, lịch sự", "My boss was looking quite presentable in a suit and tie."],
    ["present", "v", "/prɪˈzent/", "trình bày", "The documentary presented us with a balanced view of the issue.", "Present (n) /ˈpreznt/: món quà; present (adj): hiện tại; present (v) /prɪˈzent/: trình bày, đưa ra."],
    ["probation", "n", "/prəˈbeɪʃn/", "thời gian thử việc", "He's on probation this semester, so he has really got to study hard."],
    ["permanent", "adj", "/ˈpɜːmənənt/", "lâu dài, cố định", "Getting married to a U.S. citizen, he entered the United States as a permanent resident."],
    ["promote", "v", "/prəˈməʊt/", "thăng chức; quảng bá", "She's just been promoted to senior sales rep.", "Promote còn có nghĩa quảng bá (= advertise): This new laptop model seems to be heavily promoted."],
    ["qualification", "n", "/ˌkwɒlɪfɪˈkeɪʃn/", "tiêu chuẩn, bằng cấp", "One of the qualifications you need for this job is cleverness."],
    ["reputation", "n", "/ˌrepjuˈteɪʃn/", "danh tiếng", "The company has a worldwide reputation for quality."],
    ["reject", "v", "/rɪˈdʒekt/", "từ chối, loại", "I applied for a job as a mechanic in a local garage, but I was rejected."],
    ["representative", "n", "/ˌreprɪˈzentətɪv/", "người đại diện (của doanh nghiệp)", "Many representatives of the older generation were at the conference."],
    ["responsibility", "n", "/rɪˌspɒnsəˈbɪləti/", "trách nhiệm", "It's her responsibility to ensure the project finishes on time."],
    ["résumé", "n", "/ˈrezjumeɪ/", "sơ yếu lý lịch", "She gave us a brief résumé of the project so far.", "Gốc tiếng Pháp résumé = summary (bản tóm tắt) → bản tóm tắt lý lịch và công việc."],
    ["reference", "n", "/ˈrefrəns/", "nguồn tham khảo; thư giới thiệu", "In academic writing, you need to make a reference list below your essay.", "Collocation: make a reference to sth — đề cập/tham khảo điều gì."],
    ["recruiter", "n", "/rɪˈkruːtə(r)/", "nhà tuyển dụng", "The recruiters gained a small pay bonus for every man they brought in."],
    ["supervisor", "n", "/ˈsuːpəvaɪzə(r)/", "người giám sát", "It is possible that your supervisor doesn't realize that he or she is underutilizing your talents."],
    ["submission", "n", "/səbˈmɪʃn/", "sự đệ trình, đề xuất", "My leader assigned me to write a proposal for submission to the board of directors.", "Submission còn có nghĩa sự phục tùng, quy phục."],
    ["staff", "n", "/stɑːf/", "nhân viên", "The staff are not very happy about the latest pay increase.", "Staff vừa dùng như danh từ số ít vừa như số nhiều: There are over a hundred staff in the company."],
    ["shift", "n", "/ʃɪft/", "ca, kíp làm việc", "I've just finished an eight-hour shift.", "Shift còn là động từ đồng nghĩa với change (thay đổi, dịch chuyển)."],
    ["submit", "v", "/səbˈmɪt/", "nộp, gửi (tài liệu)", "Candidates are required to submit their application forms via Google Form."],
    ["training", "n", "/ˈtreɪnɪŋ/", "sự đào tạo", "New recruits will receive intensive training once they start working."],
    ["temporary", "adj", "/ˈtemprəri/", "tạm thời", "The meeting only provides a temporary solution to the crisis."],
    ["undergraduate", "n", "/ˌʌndəˈɡrædʒuət/", "sinh viên chưa tốt nghiệp", "Undergraduate students, despite their lack of work experience, are extremely enthusiastic.", "Graduate student: sinh viên cao học; postgraduate student: học viên sau đại học."],
    ["vacancy", "n", "/ˈveɪkənsi/", "vị trí trống", "There's a vacancy in the accounts department."],
    ["welfare", "n", "/ˈwelfeə(r)/", "phúc lợi", "We are a progressive employer concerned with employee welfare."],
  ],
  quiz: [
    q("There is ------- that cars have a harmful effect on the environment.", ["abundant evidence", "any evidence", "evident abundance", "few evidence"], "A", "Abundant evidence: rất nhiều bằng chứng."),
    q("Which word is an antonym of \"achievement\"?", ["success", "triumph", "defeat", "accomplishment"], "C", "Defeat (thất bại) trái nghĩa với achievement (thành tựu)."),
    q("Which word is a synonym of \"appraisal\"?", ["approach", "evaluation", "appeal", "ignorance"], "B", "Appraisal = evaluation: sự đánh giá."),
    q("Mr. Delagua's ability to implement necessary changes and ------- new business methods to meet new challenges impressed the Board of Directors.", ["applied", "be applied", "apply", "applying"], "C", "And nối hai động từ nguyên mẫu song song: to implement … and (to) apply."),
    q("I haven't the least idea what I am to do; I wanted to ------- you seriously.", ["consult", "consults", "consulted", "consulting"], "A", "Want to + V nguyên mẫu."),
    q("The presentation was ------- seamlessly, giving an impressive image of the team.", ["conduct", "conducted", "conducting", "conductor"], "B", "Bị động was conducted: được tiến hành."),
    q("He's highly regarded and has certainly been mentioned as a potential -------.", ["employers", "candidate", "employee", "recruiter"], "B", "Potential candidate: ứng viên tiềm năng."),
    q("Hard work and ------- will help you move up the corporate ladder.", ["dedicated", "dedicates", "dedication", "dedicating"], "C", "And nối hai danh từ: hard work and dedication."),
    q("Choose the synonym of \"eligible\".", ["qualified", "edible", "unacceptable", "changeable"], "A", "Eligible = qualified: đủ tiêu chuẩn."),
    q("Sometimes the manager is too -------, and his workers take advantage of him.", ["flex", "flexible", "flexibly", "flexibility"], "B", "Sau to be + too cần tính từ flexible."),
    q("Find the wrong word: After finishing this intern, would you consider applying for the company as an official employee?", ["intern", "consider", "for", "employee"], "A", "Sau this cần danh từ chỉ đợt thực tập → internship."),
    q("Our recruiter will be travelling to several universities to ------- graduate students for occupations in the marketing department.", ["interview", "interviewing", "interviewee", "interviewer"], "A", "To + V nguyên mẫu chỉ mục đích."),
    q("Though I was not qualified for this job as an official employee, the manager ------- me an internship.", ["offer", "offered", "was offered", "offers"], "B", "Quá khứ đơn, chủ động: offered somebody something."),
    q("Many organizations operate a three-month ------- period before making a position permanent.", ["probational", "probation", "probative", "probatiative"], "B", "Probation period: thời gian thử việc."),
    q("The applicants who ------- will be flown to the corporate office and interviewed there.", ["qualification", "qualify", "qualifying", "qualifies"], "B", "Who thay cho applicants (số nhiều) → qualify."),
    q("The newspaper has a reputation ------- updating news the fastest and most accurately.", ["by", "on", "for", "to"], "C", "Have a reputation for: nổi tiếng về."),
    q("The committee will decide whether to accept or ------- the offer.", ["rejected", "reject", "rejects", "rejecting"], "B", "Or nối hai động từ nguyên mẫu: to accept or (to) reject."),
    q("Find the wrong word: He acts as the sole representatives of Neptune Oil after Mrs. Elena leaves.", ["acts", "as", "sole", "representatives"], "D", "The sole + danh từ số ít → representative."),
    q("Find the wrong word: Jenny, you have responsibility of collecting the books after the class.", ["responsibility", "of", "collecting", "books"], "B", "Responsibility for (doing) sth → of sửa thành for."),
    q("The company hired a professional ------- to fill the vacant position.", ["recruited", "recruiting", "recruitment", "recruiter"], "D", "A professional + danh từ chỉ người → recruiter."),
    q("After ------- all his materials, he had no option but to sit back and wait for some response.", ["submitting", "submitted", "submission", "submit"], "A", "Sau giới từ after là V-ing."),
    q("In all my years of -------, I have never seen such a motivated group of new hires.", ["trainee", "training", "trains", "trainer"], "B", "Years of training: những năm làm công tác đào tạo."),
    q("School administrators are trying to fill the ------- before the beginning of the school year.", ["vacant", "vacancy", "vacancies", "vacantly"], "C", "Fill the vacancies: lấp các vị trí trống (nhiều vị trí)."),
  ],
  written: [
    { q: "Sắp xếp thành câu: appointment / , but / Ms. Clark / doctor / on / Tuesday / she / had / an / it / missed / with / Traynor.", a: "Ms. Clark had an appointment with doctor Traynor on Tuesday, but she missed it." },
    { q: "Sắp xếp thành câu: at least / must / An / a training / years of age / to enroll in / be / apprentice / program / 16.", a: "An apprentice must be at least 16 years of age to enroll in a training program." },
    { q: "Sắp xếp thành câu: assignments / sent / a / on / Lena / was / abroad / diplomatic.", a: "Lena was sent abroad on a diplomatic assignment." },
    { q: "Sắp xếp thành câu: Wallace / needs / On / her / lecturer / academic / new / collaborators / project / several.", a: "On her new project, lecturer Wallace needs several academic collaborators." },
    { q: "Sắp xếp thành câu: will / expertise / You / confusing / someone / with / to handle / technical / the / need / regulations.", a: "You will need someone with the expertise to handle the confusing technical regulations." },
    { q: "Sắp xếp thành câu: never / She / got / she / any guidance / needed / when / it.", a: "She never got any guidance when she needed it." },
    { q: "Sắp xếp thành câu: I / get / ready / to / Since / boyfriend's / meeting / my / with / family / it / the / presentable / want / make / to / myself / in / first / takes / me / one / hour.", a: "Since I want to make myself presentable in the first meeting with my boyfriend's family, it takes me one hour to get ready." },
    { q: "Sắp xếp thành câu: brain / the / to / The / disease / can / permanent / cause / damage.", a: "The disease can cause permanent damage to the brain." },
    { q: "Sắp xếp thành câu: equal / should / Supervisors / relating / employment / familiar / be / with / opportunities / policy / to.", a: "Supervisors should be familiar with policy relating to equal employment opportunities." },
    { q: "Sắp xếp thành câu: These delays / temporary / negative effects / on / are / should not / have / the / any / , and / project.", a: "These delays are temporary, and should not have any negative effects on the project." },
    { q: "Sắp xếp thành câu: The / of / stake / all / the / orphans / welfare / at / was.", a: "The welfare of all the orphans was at stake." },
  ],
};
