import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const PURCHASING: IigTopic = {
  slug: "purchasing",
  title: "Purchasing",
  titleVi: "Mua sắm",
  summary: "Mua bán, thanh toán, khuyến mãi, giao hàng, hóa đơn và nhà cung cấp.",
  words: [
    ["advertisement", "n", "/ədˈvɜːtɪsmənt/", "quảng cáo", "They have started to place advertisements in popular magazines.", "Advertisement: quảng cáo dạng tờ rơi, trên tạp chí, biển quảng cáo… Commercial: quảng cáo phát trên truyền hình, radio."],
    ["bargain", "v / n", "/ˈbɑːɡɪn/", "mặc cả; món hời", "Customers can usually bargain with antique dealers.", "Bargain còn là danh từ nghĩa món hời."],
    ["behavior", "n", "/bɪˈheɪvjə(r)/", "hành vi", "He conducted a survey on whether consumer behavior differs between men and women.", "Behavior (Anh Mỹ) = behaviour (Anh Anh)."],
    ["billboard", "n", "/ˈbɪlbɔːd/", "bảng quảng cáo", "There is an eye-catching image of the iPhone 14 on the billboards.", "Billboard còn là tên bảng xếp hạng âm nhạc nổi tiếng thế giới."],
    ["cash", "n / v", "/kæʃ/", "tiền mặt; đổi/rút tiền", "Payments can be made by card or in cash.", "Động từ cash: đổi séc lấy tiền — The company cashed my cheque but then failed to send the goods I'd ordered."],
    ["cashier", "n", "/kæˈʃɪə(r)/", "thu ngân", "I handed the cashier a $10 bill.", "Xuất hiện khoảng thế kỷ 16, gốc từ caissier trong tiếng Pháp."],
    ["catalogue", "n", "/ˈkætəlɒɡ/", "danh mục sản phẩm", "You may also check our catalogue to make sure we have the items you need."],
    ["change", "n", "/tʃeɪndʒ/", "tiền thừa; tiền lẻ", "It costs $17 and you gave me $20, so here's your $3 change.", "Change còn có nghĩa tiền xu, tiền lẻ."],
    ["checkout", "n", "/ˈtʃekaʊt/", "quầy thanh toán", "The line at this checkout is too long, so I decide to look for another.", "Khi mua hàng online, bước thanh toán cũng gọi là checkout: Click on your selections and proceed to checkout."],
    ["cheque / check", "n", "/tʃek/", "ngân phiếu, séc", "Could I pay for this sofa by cheque?"],
    ["clerk", "n", "/klɑːk/", "nhân viên bán hàng", "Take your purchases to the clerk, and he will wrap them for you.", "Clerk / sales clerk dùng nhiều trong Anh Mỹ; Anh Anh hay dùng shop assistant."],
    ["cost", "n", "/kɒst/", "chi phí, giá", "The average cost of a new house has gone up by 5 percent to £76,500.", "Cost: giá người mua thực tế trả. Price: giá người bán đặt ra."],
    ["coupon", "n", "/ˈkuːpɒn/", "phiếu giảm giá", "Clip this coupon for $10 off your next purchase.", "Coupon: do doanh nghiệp/nhà bán lẻ phát hành để giảm giá theo % hoặc số tiền cố định. Voucher: phiếu mua hàng có giá trị cố định, cần đáp ứng điều kiện ghi trên phiếu."],
    ["debt", "n", "/det/", "khoản nợ", "He got into debt after losing his job."],
    ["delivery", "n", "/dɪˈlɪvəri/", "sự giao hàng", "We offer free delivery on orders over $200.", "Delivery còn là cách truyền tải nội dung: Good storytelling made the effective delivery of his speech."],
    ["demand", "n", "/dɪˈmɑːnd/", "nhu cầu; yêu cầu", "There was huge demand for Taylor's concert tickets."],
    ["discount", "n", "/ˈdɪskaʊnt/", "chiết khấu, giảm giá", "Members receive a 10% discount on our general training courses.", "Discount: áp dụng cho sản phẩm/đối tượng khách nhất định (khách trung thành, mua số lượng lớn…). Sale: sự kiện giảm giá vào thời điểm nhất định, mọi sản phẩm đều được ưu đãi (Shopee 10.10, 11.11)."],
    ["distributor", "n", "/dɪˈstrɪbjətə(r)/", "nhà phân phối", "The paper company found a European distributor for their specialty products."],
    ["e-wallet", "n", "/ˈiː wɒlɪt/", "ví điện tử", "Payment can be made using a card or your e-wallet.", "Tiền tố e- liên quan đến điện tử: e-commerce (thương mại điện tử), e-book (sách điện tử)."],
    ["expand", "v", "/ɪkˈspænd/", "mở rộng", "The new manager has decided to expand the store's inventory."],
    ["expense", "n", "/ɪkˈspens/", "chi phí", "We need to cut down on our living expenses."],
    ["export", "v / n", "/ɪkˈspɔːt/ (v), /ˈekspɔːt/ (n)", "xuất khẩu", "French cheeses are exported to many different countries."],
    ["fee", "n", "/fiː/", "lệ phí", "The KOL's contents are good, but they charge huge fees.", "Fee: khoản tiền trả cho cá nhân/tổ chức chuyên nghiệp để nhận dịch vụ đặc thù (tuition fee, parking fee). Charge: chi phí cho hàng hóa hoặc dịch vụ nói chung."],
    ["import", "v / n", "/ɪmˈpɔːt/ (v), /ˈɪmpɔːt/ (n)", "nhập khẩu", "Vietnam imports a large number of cars from Japan."],
    ["installment", "n", "/ɪnˈstɔːlmənt/", "khoản trả góp", "I agreed to pay for the car in installments.", "Installment (Anh Mỹ) = instalment (Anh Anh)."],
    ["inventory", "n", "/ˈɪnvəntri/", "hàng tồn kho", "The inventory lists many rare items.", "Stock: thành phẩm sẵn sàng bán tới người tiêu dùng. Inventory: gồm cả nguyên liệu tạo ra thành phẩm và thành phẩm."],
    ["leaflet", "n", "/ˈliːflət/", "tờ rơi", "They were handing out leaflets about the school board election outside the supermarket.", "Leaflet: tờ giấy nhỏ hoặc gấp lại, không đầy đủ thông tin. Booklet: cuốn sách nhỏ giới thiệu sản phẩm, bìa giấy."],
    ["manufacture", "n / v", "/ˌmænjuˈfæktʃə(r)/", "sự sản xuất; sản xuất", "Boeing is one of the largest manufacturers of airplanes in the world."],
    ["material", "n / adj", "/məˈtɪəriəl/", "nguyên liệu; quan trọng", "Clay is a very plastic material.", "Tính từ material đồng nghĩa với important: information that is material to the investigation."],
    ["merchandise", "n", "/ˈmɜːtʃəndaɪs/", "hàng hóa", "The truck took the merchandise in containers from the factory to the airport.", "Merchandise là danh từ không đếm được."],
    ["mortgage", "n", "/ˈmɔːɡɪdʒ/", "khoản vay thế chấp", "They took out a $100,000 mortgage to buy the house."],
    ["order", "v / n", "/ˈɔːdə(r)/", "đặt hàng; đơn hàng", "I ordered some pasta and a mixed salad."],
    ["owe", "v", "/əʊ/", "nợ", "Don't forget that you owe me $10."],
    ["payment", "n", "/ˈpeɪmənt/", "sự thanh toán", "It's difficult for them to meet the payments on their car."],
    ["purchase", "v / n", "/ˈpɜːtʃəs/", "mua; sự mua", "Concert tickets must be purchased two weeks in advance."],
    ["queue", "v / n", "/kjuː/", "xếp hàng; hàng người", "We had to queue for three hours to buy a new phone.", "Gốc tiếng Pháp, ban đầu chỉ cái đuôi của động vật."],
    ["receipt", "n", "/rɪˈsiːt/", "biên lai, giấy biên nhận", "Please keep your receipt as proof of purchase.", "Invoice: hóa đơn yêu cầu thanh toán (gửi doanh nghiệp) trong thời hạn nhất định. Bill: hóa đơn yêu cầu thanh toán ngay (gửi cá nhân). Receipt: biên lai xác nhận đã thanh toán."],
    ["recommend", "v", "/ˌrekəˈmend/", "gợi ý, khuyến nghị", "I recommend the book to all my friends."],
    ["refund", "v / n", "/rɪˈfʌnd/ (v), /ˈriːfʌnd/ (n)", "hoàn tiền; khoản hoàn tiền", "If you are not satisfied with the goods, the price will be refunded to you.", "Danh từ: I took the radio back to the shop and asked for a refund."],
    ["retailer", "n", "/ˈriːteɪlə(r)/", "nhà bán lẻ", "Traditional retailers are complaining about online retailers stealing their customers.", "Gốc động từ retailler (tiếng Pháp, thế kỷ 15) = cắt nhỏ, phân chia → bán số lượng nhỏ."],
    ["sample", "n", "/ˈsɑːmpl/", "hàng mẫu, hàng dùng thử", "Would you like a sample of the fabric to take home?"],
    ["self-service", "adj", "/ˌself ˈsɜːvɪs/", "tự phục vụ", "To keep costs down, the cafeteria is self-service.", "Tiền tố self- = tự mình: self-control (tự chủ), self-educated (tự học)."],
    ["shipping", "n", "/ˈʃɪpɪŋ/", "sự vận chuyển, gửi hàng", "We offer different shipping options with different delivery speeds and costs."],
    ["stockroom", "n", "/ˈstɒkruːm/", "kho chứa hàng (của cửa hàng)", "The store has a large stockroom in the back.", "Stockroom: nơi chứa hàng của một cửa hàng. Warehouse: nhà kho lớn."],
    ["supplier", "n", "/səˈplaɪə(r)/", "nhà cung cấp", "The restaurant is our main supplier of frozen food.", "Supplier: cung cấp nguyên liệu sản xuất số lượng lớn cho doanh nghiệp. Vendor: người cung cấp mặt hàng thành phẩm."],
    ["trade", "n", "/treɪd/", "buôn bán, thương mại", "There are several local companies taking part in a trade mission."],
    ["trolley", "n", "/ˈtrɒli/", "xe đẩy", "In supermarkets, customers will be provided with trolleys to carry their goods.", "Trolley (Anh Anh) = cart (Anh Mỹ)."],
    ["vendor / vender", "n", "/ˈvendə(r)/", "bên bán, người bán", "They are the nation's leading vendor of organic dairy products."],
    ["warehouse", "n", "/ˈweəhaʊs/", "kho chứa", "Goods are sent from the warehouse to the customers."],
    ["warranty", "n", "/ˈwɒrənti/", "phiếu bảo hành", "The car needs to be fixed, but it's still under warranty.", "Warranty: phiếu/chế độ bảo hành. Guarantee: sự cam kết về chất lượng."],
  ],
  quiz: [
    q("Find the wrong word: If you order good from the catalogue, they usually arrive within a week.", ["good", "catalogue", "within", "arrive"], "A", "Hàng hóa là goods (danh từ số nhiều) → good sửa thành goods."),
    q("True or False? A cheque is a document that directs the bank to deduct money from your account and make a payment.", ["True", "False"], "A", "Đúng — séc là lệnh yêu cầu ngân hàng trích tiền từ tài khoản để thanh toán."),
    q("The government is unlikely to agree to the rebels' demands ------- independence.", ["to", "for", "on", "by"], "B", "Demand for sth: yêu cầu, đòi hỏi điều gì."),
    q("They are Japan's largest software -------.", ["distribution", "distributor", "distributary", "distributorship"], "B", "Largest + danh từ chỉ người/đơn vị → distributor (nhà phân phối)."),
    q("They ------- their retail operations during the 1980s.", ["expanded", "expand", "has expanded", "had expanded"], "A", "During the 1980s → quá khứ đơn expanded."),
    q("The cost of goods or services such as rent, groceries, bills… is called:", ["charge", "expense", "price", "revenue"], "B", "Expense: chi phí (tiền thuê nhà, thực phẩm, hóa đơn…)."),
    q("------- is the activity of sending goods or services to another country.", ["Exported", "Export", "Exportation", "Exportable"], "B", "Chỗ trống làm chủ ngữ, cần danh từ chỉ hoạt động → Export (xuất khẩu)."),
    q("Vietnam's ------- sector grew by nearly 9% in 2021.", ["manufacturer", "produce", "manufacture", "manufactured"], "C", "Manufacture/manufacturing sector: ngành sản xuất."),
    q("Find the wrong word: This store has a wide selection of merchandises for sale.", ["has", "selection", "merchandises", "for"], "C", "Merchandise là danh từ không đếm được → không có dạng merchandises."),
    q("The word 'mortgage' is closest in meaning to:", ["a loan", "a credit", "a payment method", "a place"], "A", "Mortgage: khoản vay thế chấp."),
    q("Find the wrong word: There are no shirts left in this size but we could ordered one for you.", ["are", "in", "ordered", "but"], "C", "Could + V nguyên mẫu → order."),
    q("I ------- money to my cousin. He lent me $100 last week.", ["spend", "take", "borrow", "owe"], "D", "Owe money to sb: nợ tiền ai."),
    q("Find the wrong word: Homeowners will be given 90 days to make back payments, to save the home from go to auction.", ["given", "make back payments", "save", "go"], "D", "Sau giới từ from là V-ing → going."),
    q("The tickets can only be ------- in advance from our website.", ["purchase", "purchasing", "purchased", "purchases"], "C", "Bị động can be purchased."),
    q("This is the package that we recommend ------- most clients.", ["to", "for", "by", "on"], "A", "Recommend sth to sb: giới thiệu cái gì cho ai."),
    q("Find the wrong word: We looked at sample books to chose the fabric.", ["looked", "sample", "chose", "fabric"], "C", "To + V nguyên mẫu → choose."),
    q("We offer free ------- on orders to customers in South East Asia.", ["deliver", "shipping", "shipness", "shipper"], "B", "Free shipping: miễn phí vận chuyển."),
    q("What is 'trade'?", ["The import and export of goods only", "The activity of buying and selling or exchanging goods/services between people or countries", "The exchange of goods without using money", "A system of money use in a country"], "B", "Trade: hoạt động mua bán, trao đổi hàng hóa/dịch vụ giữa người hoặc quốc gia."),
    q("True or False? A vendor supplies products or services to companies.", ["True", "False"], "B", "Sai — vendor bán sản phẩm cho cả người tiêu dùng lẫn công ty, không chỉ cho công ty."),
    q("True or False? A warehouse is a large building where materials are stored before they are distributed for sale.", ["True", "False"], "A", "Đúng — warehouse là nhà kho lớn chứa hàng trước khi phân phối."),
  ],
  written: [
    { q: "Điền từ: According to data released from the Federal Reserve's New York district in 2021, US consumer (1) ------- was high, with record-level defaults on (2) ------- cards and (3) ------- loans. (Gợi ý: mortgage, credit, debt, deficit)", a: "(1) debt; (2) credit; (3) mortgage" },
    { q: "Chia dạng đúng của động từ: In 2020, Vietnam (import) ------- $178M in tea, becoming the 12th largest importer of tea in the world. Vietnam (import) ------- tea primarily from China, Hong Kong, Malaysia, Singapore, and Indonesia.", a: "(1) imported; (2) imports" },
  ],
};
