import { q } from "@/lib/content/mastery/helpers";
import type { IigTopic } from "./types";

export const TECHNOLOGY: IigTopic = {
  slug: "technology",
  title: "Technology",
  titleVi: "Công nghệ",
  summary: "Thiết bị, phần mềm, mạng, đổi mới công nghệ và bảo trì máy móc.",
  words: [
    ["appliance", "n", "/əˈplaɪəns/", "thiết bị (gia dụng)", "Are all of the kitchen appliances included in the price of the house?"],
    ["artificial intelligence", "n", "/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/", "trí tuệ nhân tạo", "We will need workers to make and maintain all those new robots and artificial intelligence systems.", "Trí tuệ nhân tạo (AI) là trí thông minh được thể hiện bằng máy móc, trái ngược với trí thông minh tự nhiên của con người."],
    ["automatic", "adj", "/ˌɔːtəˈmætɪk/", "tự động", "I was thinking of buying an automatic car."],
    ["breakthrough", "n", "/ˈbreɪkθruː/", "sự đột phá", "The Polaroid camera was a technological breakthrough.", "Breakthrough (n): sự đột phá. Break through + sth (v): lần đầu đạt được thành công, khám phá ra điều gì."],
    ["browse", "v", "/braʊz/", "đọc lướt, duyệt (web)", "I was browsing through magazines to find a new hairstyle."],
    ["database", "n", "/ˈdeɪtəbeɪs/", "cơ sở dữ liệu", "The database is updated daily.", "A database for (doing) sth: cơ sở dữ liệu cho việc gì; enter/put sth into/onto a database: nhập dữ liệu."],
    ["capacity", "n", "/kəˈpæsəti/", "dung lượng; sức chứa", "Storage capacity refers to how much disk space a storage device provides.", "Capacity còn chỉ sức chứa: The stadium has a seating capacity of 50,000."],
    ["commerce", "n", "/ˈkɒmɜːs/", "thương mại", "We are trying to develop a model for best practice in electronic commerce."],
    ["compatible", "adj", "/kəmˈpætəbl/", "tương thích", "This software may not be compatible with older operating systems."],
    ["complicated", "adj", "/ˈkɒmplɪkeɪtɪd/", "phức tạp", "The rescue operation has been complicated by bad weather."],
    ["connection", "n", "/kəˈnekʃn/", "sự kết nối", "You need a fast internet connection."],
    ["control", "v / n", "/kənˈtrəʊl/", "kiểm soát; sự kiểm soát", "It's hard to control your temper when you're two years old.", "Danh từ: He felt he was losing control of events."],
    ["crash", "v", "/kræʃ/", "đột ngột ngừng hoạt động (máy tính)", "My computer crashed when I was writing my essay."],
    ["creator", "n", "/kriˈeɪtə(r)/", "người sáng tạo", "Who was the creator of the smartphone?"],
    ["cutting-edge", "adj", "/ˌkʌtɪŋ ˈedʒ/", "rất hiện đại, tiên tiến", "Apple products are considered to have the most cutting-edge design.", "Danh từ: the cutting edge of sth — Our new mobile phone is at the cutting edge of technology."],
    ["develop", "v", "/dɪˈveləp/", "phát triển", "I'm looking for a job which will enable me to develop my skills."],
    ["development", "n", "/dɪˈveləpmənt/", "sự phát triển", "The development of computer science has brought about lots of benefits to our lives."],
    ["duplicate", "v / adj", "/ˈdjuːplɪkeɪt/", "tạo bản sao; giống hệt", "Please duplicate the information in these DVDs for me!", "Tính từ: We will not be able to return the documents, so keep a duplicate copy."],
    ["electricity", "n", "/ɪˌlekˈtrɪsəti/", "điện", "The electricity has been turned off."],
    ["energy-saving", "adj", "/ˈenədʒi ˌseɪvɪŋ/", "tiết kiệm năng lượng", "The heat-recycling system provides an energy-saving solution."],
    ["function", "n", "/ˈfʌŋkʃn/", "chức năng", "The website benefits from a highly efficient search function."],
    ["grant", "v", "/ɡrɑːnt/", "cấp, ban cho", "They granted her an entry visa.", "Take sb/sth for granted: coi là điều hiển nhiên; take it for granted (that…): coi đó là chuyện đương nhiên."],
    ["gadget", "n", "/ˈɡædʒɪt/", "đồ dùng, thiết bị nhỏ", "This handy gadget separates egg yolks from whites.", "Gadget: thiết bị điện tử/cơ học nhỏ, tinh vi hoặc mới lạ (sạc dự phòng, loa bluetooth). Device: vật được tạo ra cho mục đích nhất định (thiết bị thu âm, máy tính bảng). Machine: thiết bị gồm nhiều bộ phận chuyển động, dùng năng lượng (máy may, máy giặt)."],
    ["hardware", "n", "/ˈhɑːdweə(r)/", "phần cứng", "The cost of MacBook hardware has dramatically grown in the last five years.", "Phần cứng máy tính gồm: keyboard, mouse, screen…"],
    ["impact", "n", "/ˈɪmpækt/", "tầm ảnh hưởng, tác động", "These are the technological advances that have had the biggest impact on the way we live."],
    ["innovative", "adj", "/ˈɪnəveɪtɪv/", "có tính đổi mới", "Steve Jobs was an innovative CEO of Apple."],
    ["install", "v", "/ɪnˈstɔːl/", "lắp đặt, cài đặt", "The plumber is coming tomorrow to install the new washing machine."],
    ["interact", "v", "/ˌɪntərˈækt/", "tương tác", "Nowadays, it's very easy to interact with your relatives through email or Messenger."],
    ["interruption", "n", "/ˌɪntəˈrʌpʃn/", "sự gián đoạn", "The game continued after a short interruption because of rain.", "Interruption to/in sth: sự gián đoạn của việc gì; without interruption: không bị gián đoạn."],
    ["machinery", "n", "/məˈʃiːnəri/", "máy móc", "The machinery is currently operating at full capacity to produce more products.", "Machinery for doing sth: bộ máy, cơ chế để làm gì (There is no machinery for resolving this problem)."],
    ["manufacturer", "n", "/ˌmænjuˈfæktʃərə(r)/", "nhà sản xuất", "Germany is a major manufacturer of motor cars."],
    ["maintenance", "n", "/ˈmeɪntənəns/", "sự bảo dưỡng", "Old machines need a lot of maintenance.", "Maintenance còn có nghĩa tiền chu cấp: He refused to pay maintenance for his children."],
    ["mechanical", "adj", "/məˈkænɪkl/", "thuộc về máy móc, cơ khí", "The company produces mechanical parts for airplane engines."],
    ["modern", "adj", "/ˈmɒdn/", "hiện đại", "In this modern society, a smartphone is an essential thing."],
    ["modify", "v", "/ˈmɒdɪfaɪ/", "chỉnh sửa", "I modified my laptop by adding more memory and a faster processor.", "Change: thay đổi nói chung. Modify: chỉnh sửa nhỏ để phù hợp mục đích (This building has been modified to become a warehouse). Vary: biến đổi theo tình huống (Our prices can vary)."],
    ["outdated", "adj", "/ˌaʊtˈdeɪtɪd/", "lỗi thời", "Nowadays this technique is completely outdated.", "Đồng nghĩa: out of date — The information in the book is out of date."],
    ["printer", "n", "/ˈprɪntə(r)/", "máy in; nhà in", "You can use the printer here to print all your necessary materials.", "Printer còn chỉ người, công ty làm nghề in ấn: We are a commercial printer offering pre-press, printing, and bindery services."],
    ["programmer", "n", "/ˈprəʊɡræmə(r)/", "lập trình viên", "This was difficult to interpret, even for the experienced programmer."],
    ["register", "v", "/ˈredʒɪstə(r)/", "đăng ký", "I registered the house in my name."],
    ["screen", "n", "/skriːn/", "màn hình", "Write the letter on the computer, then you can make changes easily on screen.", "The small screen: màn hình TV. The big screen: màn ảnh rộng ở rạp chiếu phim."],
    ["software", "n", "/ˈsɒftweə(r)/", "phần mềm", "He's written a piece of software that does your taxes for you.", "Software là danh từ không đếm được: a piece of software — một phần mềm."],
    ["source", "n", "/sɔːs/", "nguồn", "The Internet is a vital source of knowledge about education, technology, medicine and many other fields.", "Sources close to sb: nguồn tin thân cận; at source: từ gốc (It is better to solve such problems at source)."],
    ["system", "n", "/ˈsɪstəm/", "hệ thống", "The system keeps crashing and no one is able to figure out why.", "Education system, criminal justice system, healthcare system, legal/financial/political system."],
    ["technology", "n", "/tekˈnɒlədʒi/", "công nghệ", "Technology is advancing at such a rate that it's difficult to imagine what our lives will be like in 20 years' time."],
    ["technophile", "n", "/ˈteknəfaɪl/", "người yêu công nghệ", "These are the top-ten gadget gifts under $50 for the technophile."],
    ["upgrade", "v", "/ˌʌpˈɡreɪd/", "nâng cấp", "It's very simple to upgrade the software.", "Upgrade from … to … (from version 4.2 to version 4.5); upgrade with (upgraded with the new programs)."],
    ["user-friendly", "adj", "/ˌjuːzə ˈfrendli/", "thân thiện với người dùng", "This software is very user-friendly."],
    ["virtual", "adj", "/ˈvɜːtʃuəl/", "ảo", "In the game, players simulate real life in a virtual world."],
    ["wireless", "adj", "/ˈwaɪələs/", "không dây", "The setup instructions show how to secure your wireless broadband network."],
    ["warrant", "v", "/ˈwɒrənt/", "bảo đảm", "We do not warrant the consistent functioning of the machine in case any component is replaced."],
  ],
  quiz: [
    q("Today, we have started to use home ------- in house-cleaning, laundry and ironing.", ["things", "machines", "appliances", "robots"], "C", "Home appliances: đồ gia dụng."),
    q("You get an ------- promotion after two years.", ["automatic", "useful", "helpful", "convenient"], "A", "Automatic promotion: thăng chức tự động."),
    q("When I was ------- in the bestsellers section, I found that book you were telling me about.", ["reading", "looking", "browsing", "unnecessary"], "C", "Browse: xem lướt (các kệ sách)."),
    q("Online ------- is expected to continue to increase.", ["trade", "buy", "purchase", "commerce"], "D", "Online commerce: thương mại trực tuyến."),
    q("The cartridges can be used in any ------- printer.", ["compatible", "match", "suitable", "purchase"], "A", "Compatible printer: máy in tương thích."),
    q("Just calm down — shouting will make everything more -------.", ["overreact", "react", "complicated", "do"], "C", "Make sth + adj: làm mọi thứ phức tạp hơn."),
    q("I'm having problems with my wired network -------.", ["Wi-Fi", "software", "connection", "hardware"], "C", "Network connection: kết nối mạng."),
    q("My laptop's ------- again.", ["crashed", "crushed", "renewed", "saved"], "A", "Crash: (máy tính) bị treo, sập."),
    q("He's the ------- of a successful cartoon series.", ["person", "father", "mother", "creator"], "D", "Creator: người sáng tạo."),
    q("You have to look for a job to ------- your talents.", ["offer", "develop", "provide", "let"], "B", "Develop your talents: phát triển tài năng."),
    q("All our profits are invested in research and -------.", ["development", "develop", "progress", "process"], "A", "Research and development (R&D): nghiên cứu và phát triển."),
    q("They lived on an island with no ------- and no running water.", ["keyboard", "mouse", "screen", "electricity"], "D", "Không có điện và nước máy."),
    q("Environmentally friendly investment should be promoted, along with clean energy and ------- installations.", ["start", "energy-saving", "sleep", "install"], "B", "Energy-saving installations: thiết bị tiết kiệm năng lượng."),
    q("The ------- of the veins is to carry blood to the heart.", ["benefit", "function", "usefulness", "quality"], "B", "Function: chức năng."),
    q("The anti-smoking campaign had made quite an ------- on young people.", ["advantage", "help", "impact", "cause"], "C", "Make an impact on: tạo ảnh hưởng đến."),
    q("In recent years, the company has relied more on creative repackaging than on ------- design.", ["innovative", "beautiful", "complicate", "hard"], "A", "Innovative design: thiết kế đổi mới."),
    q("Can you help me ------- this software?", ["install", "fix", "begin", "try"], "A", "Install software: cài đặt phần mềm."),
    q("It's interesting at parties to see how people ------- socially.", ["see", "watch", "hear", "interact"], "D", "Interact socially: giao tiếp, tương tác xã hội."),
    q("A ------- is a company that produces goods in large numbers.", ["producer", "artist", "manufacturer", "musician"], "C", "Manufacturer: nhà sản xuất (số lượng lớn)."),
    q("The plane appeared to have crashed because of a ------- issue.", ["mechanical", "laptop", "desktop", "software"], "A", "Mechanical issue: sự cố cơ khí."),
    q("The building was made using ------- construction techniques.", ["modern", "awful", "great", "ugly"], "A", "Modern construction techniques: kỹ thuật xây dựng hiện đại."),
    q("He used to work as a computer ------- for a software company.", ["employer", "accountant", "programmer", "provider"], "C", "Computer programmer: lập trình viên."),
    q("The regulations require doctors and patients to ------- in a database.", ["register", "write", "fill", "sign"], "A", "Register in a database: đăng ký vào cơ sở dữ liệu."),
    q("With computer -------, even people working on their own can produce professional-looking documents.", ["screen", "keyboard", "mouse", "technology"], "D", "Computer technology: công nghệ máy tính."),
    q("My brother is a true ------- and can tell you about every new gadget on the market.", ["technophobe", "technophile", "lover", "hate"], "B", "Technophile: người yêu công nghệ (technophobe: người sợ công nghệ)."),
    q("The company's high-tech tools help manufacturers make their appliances more ------- for consumers.", ["friendly", "addicted", "user-friendly", "attractive"], "C", "User-friendly: thân thiện, dễ dùng với người dùng."),
    q("Thanks to technological advances, you can take a ------- tour of the museum.", ["real", "full", "virtual", "honest"], "C", "Virtual tour: chuyến tham quan ảo."),
    q("Information is communicated through ------- modems between a host computer and the on-board computer of the mobile.", ["complex", "easy", "fill in", "wireless"], "D", "Wireless modems: modem không dây."),
    q("The ------- covers the photocopier mechanically for a year, with unlimited mileage.", ["warranty", "warrantee", "warrantation", "warrantist"], "A", "Warranty: chế độ bảo hành."),
  ],
  written: [],
};
