import { q } from "./helpers";
import type { MasteryLesson } from "./types";

const CHAPTER = "practice-tests";
const VOCAB_HEADERS = ["Từ / cụm từ", "Từ loại", "Nghĩa"];
const INSTRUCTIONS = "Đề thi 40 câu dạng TOEIC Part 5. Làm hết rồi bấm nộp bài để xem đáp án và giải thích.";

export const PRACTICE_TEST_LESSONS: MasteryLesson[] = [
  {
    slug: "practice-test-1",
    chapter: CHAPTER,
    code: "Practice Test 1",
    title: "Đề luyện tập số 1",
    summary: "40 câu tổng hợp danh từ, động từ, tính từ, trạng từ, đại từ, liên từ và giới từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["advancement", "n", "sự thăng chức, thăng tiến"],
          ["employment insurance", "n", "bảo hiểm lao động"],
          ["expand the building", "v", "mở rộng tòa nhà"],
          ["fitness facility", "n", "trung tâm thể hình"],
          ["optimal", "adj", "tốt nhất, cao nhất"],
          ["reference letter", "n", "thư giới thiệu"],
          ["staff lounge", "n", "phòng nghỉ cho nhân viên"],
        ],
      },
    ],
    exercises: [
      {
        title: "Practice Test 1",
        kind: "test",
        instructions: INSTRUCTIONS,
        questions: [
          q("Author Ken Yabuki wrote a magazine article based on ------- recent visit to Iceland.", ["he", "him", "his", "himself"], "C", "Đứng trước danh từ visit là tính từ sở hữu his. 'Tác giả Ken Yabuki đã viết một bài báo dựa vào chuyến đi gần đây đến Iceland.'"),
          q("Ms. Harriet contributed greatly ------- helping the institute attract funding and increase productivity.", ["for", "to", "in", "at"], "B", "Contribute to: đóng góp. 'Cô Harriet đã đóng góp nhiều trong việc giúp viện thu hút đầu tư và tăng năng suất.'"),
          q("Mr. Connelly will serve ------- the project coordinator for the next three months.", ["on", "as", "of", "in"], "B", "Trước danh từ chỉ chức danh dùng giới từ as. 'Ông Connelly sẽ giữ chức điều phối viên dự án trong ba tháng tới.'"),
          q("------- many achievements is the invention of a breakthrough medicine called Vivamax.", ["Except", "By", "Among", "Over"], "C", "Among: trong số. 'Trong số nhiều thành tựu là việc phát minh một loại thuốc đột phá gọi là Vivamax.'"),
          q("------- the laboratory technicians all used sophisticated instruments to evaluate the samples, they could not reach the same opinion.", ["Regarding", "Despite", "Although", "In spite"], "C", "Sau chỗ trống là mệnh đề nên chọn liên từ although. 'Mặc dù các kỹ thuật viên đều dùng thiết bị tối tân để đánh giá mẫu, họ không thể đưa ra cùng một ý kiến.'"),
          q("Employees can expect all travel expenses to be covered by the company, but entertainment expenses must first be approved by ------- immediate supervisors.", ["their", "theirs", "them", "they"], "A", "Trước danh từ immediate supervisors là tính từ sở hữu their."),
          q("Qualified candidates may apply for the vacant position ------- their religion, sexual orientation, ethnicity or country of origin.", ["regards", "without regard", "regarding", "regardless of"], "D", "Phía sau là danh từ nên chọn regardless of (bất kể). 'Ứng viên đủ tiêu chuẩn có thể nộp đơn bất kể tôn giáo, giới tính, dân tộc hay quốc gia.'"),
          q("Proposals for ------- the building include a new staff lounge and a fitness facility.", ["expanding", "excluding", "expressing", "extending"], "A", "Expand the building: mở rộng tòa nhà. 'Kế hoạch mở rộng tòa nhà bao gồm một phòng nghỉ cho nhân viên và một trung tâm thể hình.'"),
          q("National Life will investigate the billing errors only when ------- are submitted in writing.", ["complaints", "complain", "complaining", "complains"], "A", "Danh từ làm chủ ngữ; dựa vào động từ are → danh từ số nhiều complaints."),
          q("All students registering for the summer semester should be ------- for their student ID.", ["photograph", "photographs", "photography", "photographed"], "D", "Câu ở dạng bị động nên chọn phân từ hai. 'Tất cả sinh viên đăng ký học kỳ hè cần được chụp ảnh để làm thẻ sinh viên.'"),
          q("The train bound for Crawford will be suspended for three days to complete minor ------- on its rails.", ["constructs", "constructive", "constructed", "construction"], "D", "Minor là tính từ nên phía sau là danh từ construction."),
          q("Rosebush Stationery ------- yesterday that it is anticipating at least twenty percent growth in revenue.", ["announcing", "announces", "announced", "have announced"], "C", "Câu có yesterday nên động từ chia quá khứ đơn."),
          q("The data Mr. Warren requested can be found ------- the Deleon Research Institute.", ["on", "at", "below", "by"], "B", "The Deleon Research Institute là địa điểm nhỏ nên dùng at."),
          q("Denver is a famous tourist attraction and famous for its food and ------- scenery.", ["attracts", "attracting", "attractive", "attraction"], "C", "Trước danh từ scenery là tính từ attractive."),
          q("All students are encouraged to ------- the ball organized by the school.", ["participate", "attend", "perform", "admit"], "B", "Attend = participate in (participate cần giới từ in)."),
          q("Employees ------- donate to local charities by hosting fundraising parties.", ["regularity", "regularize", "regularly", "regular"], "C", "Trạng từ bổ nghĩa cho động từ donate."),
          q("You are required to hand in ------- your medical records and registration form.", ["as well as", "as soon as", "compared to", "both"], "D", "Both … and."),
          q("Our company publishes information on the latest printing equipment from companies ------- America.", ["in", "at", "for", "to"], "A", "In + tên quốc gia. 'Công ty chúng tôi xuất bản thông tin về thiết bị in từ các công ty ở Mỹ.'"),
          q("The committee decided to allocate specific tasks to members to achieve its goals more -------.", ["effective", "effectiveness", "effect", "effectively"], "D", "Trạng từ bổ nghĩa cho động từ achieve."),
          q("Because this year's prize is bigger, the contest has become more -------.", ["competitions", "competitive", "compete", "competitively"], "B", "Sau become là tính từ."),
          q("The tourist information center helps travelers easily ------- famous landmarks.", ["remind", "locate", "guide", "advance"], "B", "Locate landmarks: định vị, tìm ra các địa điểm."),
          q("The new medicine developed by Crawson is the ------- of experience and hard work.", ["producer", "producing", "product", "produced"], "C", "Danh từ tương ứng với the new medicine là product (sản phẩm)."),
          q("For ------- results, please follow the instructions written on the back of the product.", ["optimal", "optimizing", "optimize", "optimally"], "A", "Tính từ bổ nghĩa cho danh từ results."),
          q("The personnel department is currently considering three people from the marketing team for ------- to managerial positions.", ["advancement", "openings", "vacancy", "challenges"], "A", "Advancement = promotion: sự thăng chức."),
          q("The new president is employing much ------- approaches to management.", ["boldest", "bolder", "bold", "boldly"], "B", "Much là từ nhấn mạnh, dấu hiệu của so sánh hơn."),
          q("All employees are encouraged to notify their manager ------- they feel that they have been discriminated against by anyone else.", ["which", "if", "despite", "because of"], "B", "'Nhân viên nên thông báo với quản lý nếu họ cảm thấy bị phân biệt đối xử.'"),
          q("Please remember to save important files in your individual folder before ------- the office.", ["leave", "left", "leaving", "leaves"], "C", "Giới từ before + V-ing."),
          q("Mr. Homes suggested that we ------- reference letters from applicants.", ["request", "requesting", "requested", "requests"], "A", "Sau suggest that là động từ nguyên thể."),
          q("------- increase productivity, management decided to implement a new manufacturing process.", ["Because", "In regard to", "In the order of", "In order to"], "D", "In order to + V: để làm gì."),
          q("The Community Library decided to open a computer lab to the public ------- of Christina, who has served as a librarian for more than 50 years.", ["to honor", "honoring", "in honor", "honor"], "C", "In honor of: để vinh danh ai."),
          q("Nelly is a ------- nurse who specializes in prenatal care.", ["qualification", "qualify", "qualifier", "qualified"], "D", "Tính từ qualified bổ nghĩa cho danh từ nurse."),
          q("The annual meeting was ------- scheduled for September 4, but due to an unexpected visit from an important guest, it was postponed.", ["originally", "original", "origins", "originality"], "A", "Trạng từ originally bổ nghĩa cho động từ schedule."),
          q("The local labor office approved of ------- improved working safety standards.", ["ourselves", "our", "us", "we"], "B", "Improved working safety standards là cụm danh từ nên trước đó là tính từ sở hữu."),
          q("For the ------- three years, the Greys have been donating regularly to charities.", ["past", "late", "once", "aged"], "A", "For the past three years: trong ba năm vừa qua."),
          q("The Alabama factory has become old and outdated, so management decided to modernize the -------.", ["facilitating", "facilitator", "facilitate", "facility"], "D", "Facility: cơ sở vật chất."),
          q("Employees are ------- to submit a newly issued medical examination report to renew their employment insurance.", ["required", "expired", "respected", "emphasized"], "A", "Be required to V: được yêu cầu làm gì."),
          q("Katherine had to leave work ------- than usual because her plans suddenly changed.", ["early", "earlier", "earliest", "earliness"], "B", "Sau chỗ trống có than nên chọn so sánh hơn."),
          q("We're sorry that there will be at least five days' ------- in our shipments because of an unexpected storm.", ["decisions", "delays", "options", "contracts"], "B", "'Chúng tôi xin lỗi vì đơn hàng sẽ bị trì hoãn ít nhất 5 ngày vì một trận bão bất ngờ.'"),
          q("Because Mr. Jackson's secretary was on sick leave, he had to schedule every meeting -------.", ["his", "him", "himself", "his own"], "C", "'Vì thư ký nghỉ ốm, ông ấy phải tự lên lịch mọi cuộc họp.'"),
          q("Our company is currently recruiting those ------- in marketing medical products.", ["interest", "interesting", "interests", "interested"], "D", "Tính từ interested bổ nghĩa cho đại từ those phía trước."),
        ],
      },
    ],
  },
  {
    slug: "practice-test-2",
    chapter: CHAPTER,
    code: "Practice Test 2",
    title: "Đề luyện tập số 2",
    summary: "40 câu tổng hợp danh từ, động từ, tính từ, trạng từ, đại từ, liên từ và giới từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["abide by the law", "v", "tuân theo pháp luật"],
          ["be equipped with", "adj", "được trang bị với"],
          ["durable", "adj", "bền"],
          ["heavy traffic", "n", "giao thông đông đúc"],
          ["leading", "adj", "hàng đầu, đứng đầu"],
        ],
      },
    ],
    exercises: [
      {
        title: "Practice Test 2",
        kind: "test",
        instructions: INSTRUCTIONS,
        questions: [
          q("The results of the medical examination ------- in the package sent to Dr. Dalton.", ["includes", "were included", "including", "included"], "B", "Be included in: được bao gồm trong."),
          q("------- who have exceeded their personal sales record will be given a bonus.", ["That", "Those", "Their", "Them"], "B", "Those who: những ai. 'Những ai vượt doanh số cá nhân trước đó sẽ được thưởng.'"),
          q("Our promotional event will focus ------- on our award-winning brewing methods.", ["promptly", "happily", "doubtfully", "specifically"], "D", "'Sự kiện khuyến mại sẽ tập trung riêng vào phương pháp ủ đạt giải thưởng.'"),
          q("------- all fifteen branches, the one in India is doing best in terms of production.", ["By", "About", "Of", "Out"], "C", "Câu có so sánh nhất, dùng of để giới thiệu 'trong số bao nhiêu … thì … nhất'."),
          q("Regular check-ups, ------- conducted by a qualified dentist, will ensure good oral hygiene.", ["of", "if", "about", "with"], "B", "If + mệnh đề rút gọn (conducted by a qualified dentist). Ba phương án còn lại là giới từ nên loại."),
          q("Atena news agency ------- a charity ball to raise funds for its ongoing \"Save the Children\" campaign.", ["holding", "hold", "will hold", "be held"], "C", "Động từ làm vị ngữ chia theo chủ ngữ số ít (news agency), chủ động → will hold."),
          q("------- Levin will join the newly formed political party or not is a hot topic enthusiastically debated among politicians.", ["Whether", "As soon as", "Considering", "Regarding"], "A", "Whether … or not."),
          q("------- to providing home care service to the physically handicapped, the local public health center holds annual campaigns on raising public awareness of the rights of the disabled.", ["In addition", "As soon as", "Compared", "Furthermore"], "A", "In addition to + N/V-ing: ngoài … ra."),
          q("------- a report published by the province, 3% of businesses are suffering from severe financial difficulties.", ["In case of", "Resulting in", "According to", "Away from"], "C", "According to: theo như."),
          q("Personal medical records are securely protected and ------- only to individuals with matching identifications.", ["responsible", "profitable", "replaceable", "accessible"], "D", "Accessible to someone: ai đó được quyền truy cập."),
          q("The traffic policy formulated by the city council ------- as planned next month.", ["implements", "had implemented", "to implement", "will be implemented"], "D", "Câu chia thì tương lai (next month) và dạng bị động (chính sách được thi hành)."),
          q("Ms. Rosebush must ------- her application form to Bear City University by September 5.", ["is sending", "sending", "sent", "send"], "D", "Sau động từ khuyết thiếu là động từ nguyên thể."),
          q("Mr. Cline requested his boss to authorize ------- to organize the event.", ["himself", "him", "his", "he"], "B", "Đại từ ở vị trí tân ngữ (sau động từ authorize)."),
          q("Some of the administrative staff ------- on a business trip to conclude a contract with a business partner.", ["went", "prepared", "began", "started"], "A", "Go on a business trip: đi công tác."),
          q("As an ------- teacher, Mr. Grant gave a speech on the importance of fostering the habit of reading.", ["experiencing", "experience", "experienced", "experiences"], "C", "Tính từ experienced (có kinh nghiệm) bổ nghĩa cho danh từ teacher."),
          q("Winn Furniture, ------- has been in business for more than 150 years, strives to provide our customers with functional and durable furniture.", ["what", "which", "where", "whom"], "B", "Đại từ quan hệ which bổ nghĩa cho danh từ chỉ vật Winn Furniture."),
          q("All workers must be equipped with safety devices such as helmets ------- entering the construction site.", ["about", "during", "from", "before"], "D", "'Công nhân phải được trang bị thiết bị an toàn như mũ bảo hiểm trước khi vào công trường.'"),
          q("Guests must show the invitation ------- received at the entrance to be escorted to their seats.", ["their", "them", "they", "theirs"], "C", "Trước động từ received cần đại từ làm chủ ngữ (the invitation they received)."),
          q("According to a public opinion survey, there is a ------- preference for a new mayor rather than the old one.", ["clarify", "clearly", "clear", "clarity"], "C", "Tính từ bổ nghĩa cho danh từ preference."),
          q("Letson University's Floyd Medical School is a ------- academic institute which has produced many capable doctors.", ["deliberate", "durable", "practical", "leading"], "D", "Leading: hàng đầu."),
          q("Researchers are currently ------- new medicine consisting only of natural ingredients.", ["developing", "develop", "developed", "develops"], "A", "Trạng từ currently là dấu hiệu của thì hiện tại tiếp diễn."),
          q("------- firms must abide by the laws of the respective state they belong to when conducting an audit.", ["Accounting", "Accounted", "Accountable", "Accountant"], "A", "Accounting firm: công ty kế toán."),
          q("The final draft for our newly developed product must be ------- so it can be displayed at the board of trustees meeting.", ["preparation", "prepared", "prepare", "prepares"], "B", "Bản cuối được chuẩn bị → bị động must be prepared."),
          q("You cannot make additional orders for office supplies as the budget has ------- been finalized.", ["eventually", "soon", "around", "already"], "D", "Already đứng giữa has và been (thì hiện tại hoàn thành)."),
          q("Applicants for the opening must have the ------- to categorize different presentation materials and carry out administrative work.", ["range", "ability", "amount", "array"], "B", "Ability to V: khả năng làm gì."),
          q("Our railway service ------- conducts technical examinations on all our tracks and trains to ensure safe trips.", ["period", "periodic", "periodical", "periodically"], "D", "Trạng từ bổ nghĩa cho động từ conduct."),
          q("Volunteers must ------- identification cards before carrying out any kind of assistance.", ["present", "announce", "dispose", "place"], "A", "Present the card: xuất trình thẻ."),
          q("The quarterly revenue of Delci Hair Products increased 10 percent ------- the new marketing strategy they employed.", ["besides", "according to", "otherwise", "due to"], "D", "Sau chỗ trống là cụm danh từ (the new marketing strategy + mệnh đề quan hệ) → due to."),
          q("Students are required to summarize what they ------- for their graduation thesis.", ["have researched", "have been researched", "researching", "will be researched"], "A", "'Sinh viên được yêu cầu tóm tắt những gì họ đã nghiên cứu để viết luận văn tốt nghiệp.'"),
          q("Ferry service at Leaton Island charges 20% more on weekends ------- on weekdays.", ["onto", "above", "than", "within"], "C", "Giới từ trong so sánh hơn là than."),
          q("An incentive program is being implemented ------- employees' productivity.", ["facilitated", "facilitate", "to facilitate", "facilitation"], "C", "To V chỉ mục đích."),
          q("After Jonathan ------- the proposal for the project more than five times with his colleague, he finally handed it over to his boss.", ["is revising", "will revise", "revises", "revised"], "D", "Câu chia quá khứ (dựa vào mệnh đề sau) và chủ động."),
          q("My boss was not satisfied with my work, so she fired me and gave ------- one month's notice.", ["mine", "me", "I", "my"], "B", "Sau động từ gave là tân ngữ."),
          q("The company's ------- only took an hour because they skipped the opening speech and some unnecessary formalities.", ["ceremony", "group", "winner", "title"], "A", "'Lễ kỷ niệm của công ty chỉ mất một tiếng vì họ bỏ qua bài phát biểu mở đầu.'"),
          q("Due to ------- traffic, John has to wake up early every morning to make it to work on time.", ["heaviness", "heavily", "heaviest", "heavy"], "D", "Tính từ bổ nghĩa cho danh từ traffic (heavy traffic: giao thông đông đúc)."),
          q("Max complained to his boss that it's been 10 years since the office has been ------- and it needs some changes to promote a better work environment.", ["renovation", "renovate", "renovating", "renovated"], "D", "Trước chỗ trống có has been, văn phòng được nâng cấp (bị động) → phân từ hai."),
          q("------- the past two years, the number of car accidents has gone up by 15%.", ["In", "Of", "At", "On"], "A", "Giới từ đi với khoảng thời gian trong bốn phương án là in."),
          q("The store was ------- located, so it has a huge advantage in exposing its goods to the public.", ["central", "center", "centrally", "centrality"], "C", "Trạng từ bổ nghĩa cho động từ locate."),
          q("The company announced it would merge with Tyrell Incorporated, ------- it said the opposite only two days later.", ["or", "and", "but", "if"], "C", "Hai ý đối lập → but."),
          q("BWS Corporation's employees were advised ------- the training session because only those who completed the session would be considered for the promotion.", ["attend", "attended", "to attend", "is attending"], "C", "Advise someone to V: khuyên ai nên làm gì."),
        ],
      },
    ],
  },
  {
    slug: "practice-test-3",
    chapter: CHAPTER,
    code: "Practice Test 3",
    title: "Đề luyện tập số 3",
    summary: "40 câu tổng hợp danh từ, động từ, tính từ, trạng từ, đại từ, liên từ và giới từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["extend the work hours", "v", "tăng thời gian làm việc"],
          ["fair evaluation", "n", "đánh giá công bằng"],
          ["limited", "adj", "hạn chế, có hạn"],
          ["on time", "prep", "đúng hạn"],
          ["raw material", "n", "nguyên liệu thô"],
          ["supplier", "n", "nhà phân phối, nhà cung cấp"],
        ],
      },
    ],
    exercises: [
      {
        title: "Practice Test 3",
        kind: "test",
        instructions: INSTRUCTIONS,
        questions: [
          q("When you invest your money, you have to choose ------- to invest in high-risk opportunities or low-risk ones.", ["either", "neither", "yet", "nor"], "A", "Either … or."),
          q("Our company ------- receives returned products because of the new machine they purchased recently.", ["occasion", "occasional", "occasionally", "occasions"], "C", "Trạng từ bổ nghĩa cho động từ receive."),
          q("While Kim was waiting for the ------- of the product that she ordered a month ago, she realized she ordered the wrong item.", ["release", "delivery", "transportation", "resource"], "B", "Delivery of the product: việc giao hàng."),
          q("Jason attempted to use some new equipment but he had trouble figuring out even where ------- start button was.", ["it", "its", "them", "they"], "B", "Sau chỗ trống là danh từ start button nên cần tính từ sở hữu tương ứng với equipment → its."),
          q("The company decided to increase sales figures by ------- the price of their products.", ["low", "lower", "lowered", "lowering"], "D", "Sau giới từ là V-ing."),
          q("It is necessary for superiors to give a fair ------- of their workers because it has a huge impact on their future career.", ["evaluate", "evaluates", "evaluated", "evaluation"], "D", "Sau tính từ fair là danh từ."),
          q("Because Jack had served ------- the company's general manager for more than 20 years, there was not one employee who didn't know him.", ["as", "in", "to", "from"], "A", "Serve as + chức danh."),
          q("The factory wasn't able to produce as many products as it was supposed to because the ------- couldn't deliver the raw materials on time.", ["supplies", "supplier", "supplied", "supplying"], "B", "'Nhà cung cấp đã không chuyển nguyên liệu thô đến đúng hạn.'"),
          q("In order to ------- the purchase of its new products, the company spent a great deal on advertising.", ["obligate", "afford", "promote", "participate"], "C", "Promote: thúc đẩy, quảng bá."),
          q("Noticing that the stock value was ------- decreasing, the biggest shareholder sold all of his stocks.", ["continuing", "continually", "continued", "continual"], "B", "Trạng từ continually bổ nghĩa cho động từ decrease."),
          q("With the strong visual effects, the general manager sounded very ------- in his presentation.", ["persuade", "to persuade", "persuasiveness", "persuasive"], "D", "Sau động từ sound là tính từ."),
          q("HIB Bank, ------- shareholders were passionate about getting a new CEO, has been going through some chaotic changes.", ["whatever", "whose", "which", "who"], "B", "Sau chỗ trống là danh từ shareholders nên chọn đại từ quan hệ whose."),
          q("The head of the department has ------- that all employees hand in their vacation plans.", ["distinguished", "requested", "connected", "employed"], "B", "Request that + S + V nguyên thể: yêu cầu ai làm gì."),
          q("Because of the sudden death of the CEO, the company's stock value dropped ------- and didn't recover for several years.", ["extremely", "adversely", "dramatically", "retroactively"], "C", "Drop dramatically: giảm mạnh."),
          q("The president seemed ------- upset.", ["very", "near", "extreme", "so much"], "A", "Trạng từ very bổ nghĩa cho tính từ upset."),
          q("------- some customers claimed that the company's customer service providers were impolite, HISL Corporation totally ignored the claims.", ["Despite", "Whatever", "Although", "Whenever"], "C", "Phía sau chỗ trống là mệnh đề nên chọn although."),
          q("After Rachel had worked for the company for more than 10 years, ------- was finally promoted.", ["her", "hers", "herself", "she"], "D", "Cần đại từ làm chủ ngữ."),
          q("Our most recent model ------- vivid images on its screen.", ["produce", "produced", "product", "produces"], "D", "Động từ chia theo chủ ngữ số ít model → produces."),
          q("------- further information, please don't hesitate to call our customer service.", ["From", "Of", "By", "For"], "D", "For further information: để có thêm thông tin."),
          q("Clients of Bank of America can ------- gain access to their accounts 24 hours a day.", ["easily", "easy", "easing", "ease"], "A", "Trạng từ bổ nghĩa cho động từ gain."),
          q("The president presented the award to the sales manager for the ------- work done by himself.", ["excellent", "interested", "grateful", "absolute"], "A", "'Chủ tịch trao giải cho quản lý bán hàng vì đã làm việc rất xuất sắc.'"),
          q("The ------- of flood victims has just exceeded a thousand.", ["numerical", "numbers", "number", "numerous"], "C", "The number of + N số nhiều + động từ số ít (has)."),
          q("The Wall Street banks collapsed ------- the uncertainty that investors had about the American economy.", ["even though", "because of", "since", "besides"], "B", "Sau chỗ trống là cụm danh từ (the uncertainty + mệnh đề quan hệ) → because of."),
          q("Wiping out the company's data may ------- any leak concerning crucial information about the company.", ["begin", "hurry", "prevent", "enhance"], "C", "'Xóa dữ liệu có thể giúp phòng tránh rò rỉ thông tin quan trọng.'"),
          q("Ms. Hong was forced to resign as CEO ------- since investors were not pleased with her recent performance.", ["quickly", "quicken", "quickened", "quickness"], "A", "Trạng từ bổ nghĩa cho động từ resign."),
          q("We are invited to the meeting ------- the new communications system that the company is about to bring in.", ["at", "with", "on", "over"], "C", "On = about: về (the meeting on …)."),
          q("EMI requires all of its employees ------- their own arrangements for their business trips.", ["making", "make", "to make", "made"], "C", "Require somebody to V."),
          q("Although the marketing department submitted the proposal, it ------- many times since then.", ["is editing", "was editing", "will be editing", "has been edited"], "D", "Dấu hiệu since then → hiện tại hoàn thành; bản đề xuất được chỉnh sửa → bị động."),
          q("Although Jack was ------- that his coworker would be nervous on the first day at work, he was quite confident.", ["concern", "concerns", "concerned", "concerning"], "C", "Sau to be là tính từ (be concerned that: lo lắng rằng)."),
          q("The CEO addressed the future of the company so passionately ------- the conference that he didn't even realize that he was losing his voice.", ["among", "throughout", "while", "toward"], "B", "Throughout: trong suốt."),
          q("Please reserve a seat because the number of seats is -------.", ["guided", "timely", "early", "limited"], "D", "'Số lượng chỗ rất hạn chế.'"),
          q("Job interviewers generally evaluate the applicants' working abilities rather than their -------.", ["personal", "personalities", "personally", "personalize"], "B", "Sau tính từ sở hữu là danh từ."),
          q("The general manager made it clear before the meeting that employees can ask questions ------- after the meeting is over.", ["immediate", "immediately", "immediateness", "immediacy"], "B", "Trạng từ immediately đứng trước trạng ngữ thời gian (after …)."),
          q("The new novel by Steven ------- no later than November 18th according to a reliable source.", ["will be published", "will publish", "are publishing", "publishes"], "A", "Tiểu thuyết được xuất bản → bị động."),
          q("Most workers agree that ------- the number of work hours is not going to increase the company's revenue.", ["reaching", "submitting", "extending", "offering"], "C", "Extend the work hours: tăng thời gian làm việc."),
          q("While Jason found the proposal from another company -------, he turned it down to keep the relationship with his original partner company.", ["attraction", "attractive", "attractively", "attracted"], "B", "Find + O + adj."),
          q("Although the company had a tight budget, they invested more money in the product because they believed it was ------- in the long run.", ["conclusive", "financial", "beneficial", "regulated"], "C", "Beneficial in the long run: có lợi về lâu dài."),
          q("Maverick Manufacturers has maintained the highest safety ------- of any company in its industry.", ["standards", "guides", "documents", "precautions"], "A", "Safety standards: tiêu chuẩn an toàn."),
          q("It's difficult for heads of the company to ------- understand the different characteristics of each employee.", ["full", "fully", "fuller", "fullness"], "B", "Trạng từ bổ nghĩa cho động từ understand."),
          q("The new technology ------- the consumption of natural resources by a tremendous amount.", ["having reduced", "reduce", "reduced", "reducing"], "C", "Chủ ngữ số ít (loại reduce), chủ động → reduced."),
        ],
      },
    ],
  },
  {
    slug: "practice-test-4",
    chapter: CHAPTER,
    code: "Practice Test 4",
    title: "Đề luyện tập số 4",
    summary: "40 câu tổng hợp danh từ, động từ, tính từ, trạng từ, đại từ, liên từ và giới từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["a wide variety of", "n", "nhiều"],
          ["mechanic", "n", "thợ sửa xe"],
          ["reputation", "n", "danh tiếng"],
          ["shift", "n", "ca làm việc"],
          ["under pressure", "n", "chịu áp lực"],
          ["utensil", "n", "đồ dùng, dụng cụ"],
        ],
      },
    ],
    exercises: [
      {
        title: "Practice Test 4",
        kind: "test",
        instructions: INSTRUCTIONS,
        questions: [
          q("Inspired by ------- father's presidential nomination acceptance speech when she was a child, Irene decided to become a politician.", ["herself", "she", "her", "hers"], "C", "Tính từ sở hữu đứng trước danh từ father."),
          q("It is difficult to find a worker who can work evening and weekend -------.", ["orders", "permits", "shifts", "entries"], "C", "Shift: ca làm việc."),
          q("OBI store will be the first local store to move in ------- the much larger Target Shopping Center.", ["between", "among", "near", "to"], "D", "Move in to (into): chuyển vào."),
          q("If your car has to be -------, please call our mechanic and we will provide the service you need immediately.", ["concerned", "repaired", "established", "determined"], "B", "'Nếu xe của bạn cần sửa chữa, hãy gọi thợ của chúng tôi.'"),
          q("The envelope that we are going to send you ------- all the necessary documents that you'll need to figure out.", ["was enclosing", "will be enclosed", "enclosed", "will enclose"], "D", "Động từ ở vị trí vị ngữ, chủ động, chia tương lai theo thì của các động từ khác trong câu."),
          q("Since the company had so many unsold products from last year, they had to sell ------- at a hugely discounted rate.", ["they", "their", "theirs", "them"], "D", "Đại từ tân ngữ thay cho products."),
          q("The Korean economy has been ------- affected by the number of exported goods because Korea is an export-driven country.", ["larger", "large", "largely", "largeness"], "C", "Trạng từ bổ nghĩa cho động từ affect."),
          q("Although the company made a ------- large profit, it was still not enough to pay off their debt.", ["considerable", "considering", "considerably", "consider"], "C", "Trạng từ bổ nghĩa cho tính từ large."),
          q("The ------- is protected by high fences.", ["restrict", "restrictedly", "restriction", "restricted"], "C", "Sau mạo từ the là danh từ."),
          q("Howard was looking ------- to working with his new colleague who has been awarded Employee of the Year.", ["around", "forward", "altogether", "never"], "B", "Look forward to + V-ing."),
          q("The two largest manufacturing corporations in this country have now become the leading ------- in their industry worldwide.", ["produces", "producers", "products", "productive"], "B", "'Hai tập đoàn đã trở thành những nhà sản xuất hàng đầu.'"),
          q("It's crucial for contractors to have good ------- skills because they represent their clients' business.", ["conducting", "cooperating", "negotiating", "commenting"], "C", "Negotiating skills: kỹ năng đàm phán."),
          q("When the two software companies gave a presentation, the partner company had to choose one or -------.", ["other", "the other", "another", "the one"], "B", "Hai công ty: one – the other."),
          q("By donating a ------- amount of money, the chairman of HD Incorporation was able to give a positive impression to the public.", ["substantial", "contented", "approximately", "required"], "A", "Substantial amount of money: một số tiền lớn."),
          q("------- the company paid extra wages for workers' overtime, the employees were still not content.", ["During", "In spite of", "Even though", "Because"], "C", "Sau chỗ trống là mệnh đề nên loại giới từ; nghĩa tương phản → Even though."),
          q("Because of its regular customers' support, the shop ------- the economic depression.", ["withstanding", "to withstand", "is withstood", "has withstood"], "D", "Chủ ngữ the shop (số ít), withstand (chống chọi) chủ động → has withstood."),
          q("He didn't expect his management would lead to an ------- in the company's stock value.", ["to increase", "increase", "increased", "increasing"], "B", "Sau an là danh từ increase."),
          q("I had to notify our partner company in China three days ------- my departure so that they could find me somewhere to stay.", ["in favor of", "owing to", "in case", "prior to"], "D", "Prior to my departure: trước khi khởi hành."),
          q("The provincial government decided ------- a stronger environmental policy to alleviate air pollution.", ["implement", "to implement", "implementing", "implemented"], "B", "Decide to V."),
          q("Dr. Jones will be back in two ------- three hours after finishing his visits.", ["by", "or", "with", "against"], "B", "'Ông Jones sẽ trở về sau hai hoặc ba giờ nữa.'"),
          q("Vander Computer is expecting the conclusion of its contract with Sher Electronics ------- the next three months.", ["within", "for", "by", "to"], "A", "Within + số + thời gian."),
          q("Because their supervisor was on leave, the team is temporarily working by -------.", ["their", "themselves", "them", "they"], "B", "By themselves: tự mình."),
          q("You must submit the ------- version of the proposal to the president.", ["revises", "revised", "revision", "revising"], "B", "Bổ nghĩa cho danh từ version là tính từ mang nghĩa bị động revised."),
          q("Nason Cookware offers a ------- variety of cookware for people looking for modern utensils.", ["widely", "widen", "width", "wide"], "D", "A wide variety of + danh từ số nhiều."),
          q("------- the new advertising strategy, Kemp Computers' quarterly sales proved disappointingly poor.", ["Even though", "However", "Due to", "Despite"], "D", "Sau chỗ trống là cụm danh từ nên loại A, B. Nghĩa 'Mặc dù có chiến lược quảng cáo mới, doanh số vẫn thấp' → Despite."),
          q("Every accountant here has a ------- for precision and diligence.", ["demonstration", "reputation", "presentation", "development"], "B", "Have a reputation for: có tiếng về."),
          q("For the price to be more -------, Bled Hair has implemented a cost-effective manufacturing process.", ["competitively", "competition", "compete", "competitive"], "D", "Sau to be là tính từ."),
          q("Dr. Hartman seemed dedicated to ------- a new medicine for an unidentified disease.", ["developing", "developed", "develop", "developer"], "A", "Be dedicated to V-ing."),
          q("Once the final draft -------, the marketing team will immediately start their relevant strategies.", ["approve", "will approve", "has approved", "has been approved"], "D", "Draft và approve có quan hệ bị động → has been approved."),
          q("Students ------- an overseas exchange program should visit the administration office.", ["regarding", "concerning", "considering", "transforming"], "C", "'Những sinh viên xem xét chương trình trao đổi nên đến phòng quản trị.'"),
          q("Evelyn was granted a bonus because she worked -------.", ["diligent", "diligence", "diligently", "more diligent"], "C", "Sau động từ work là trạng từ."),
          q("Weirdman Computers ------- hosts parties for its employees to foster the relations among them.", ["occasionally", "loudly", "scarcely", "considerably"], "A", "'Weirdman Computers thỉnh thoảng tổ chức tiệc cho nhân viên.'"),
          q("Pharmaceutical companies must ensure that their products are ------- federal health regulations.", ["in compliance", "complies", "compliant with", "comply"], "C", "Be compliant with a regulation: tuân thủ quy định."),
          q("The Nero-403 was highly appreciated by IT specialists as the ------- laptop computer ever.", ["most speedy", "speediest", "more speedy", "speedily"], "B", "Sau the là so sánh cao nhất; speedy → speediest."),
          q("The president of Cahoo Automobiles is under a lot of ------- now that the company is on the verge of bankruptcy.", ["issue", "pressure", "conflict", "effort"], "B", "Under pressure: chịu áp lực."),
          q("The price ------- between the two companies was intense.", ["competing", "competitive", "compete", "competition"], "D", "Chỗ trống làm chủ ngữ nên chọn danh từ."),
          q("Because the oil price has gone up -------, the demand for fuel-efficient cars has been increasing as well.", ["closely", "perfectly", "recently", "highly"], "C", "Trạng từ recently đi với thì hiện tại hoàn thành."),
          q("The company has decided to hold its annual ceremony ------- Shaneil Hall.", ["as", "to", "on", "at"], "D", "At + địa điểm cụ thể."),
          q("Our ------- customers are what have been sustaining our sales.", ["regular", "regularly", "regularity", "regulating"], "A", "Regular customer: khách hàng thường xuyên."),
          q("The entire company had to be ------- because the CEO was sued for inappropriate usage of the company's funds.", ["inspection", "inspected", "inspect", "inspecting"], "B", "'Cả công ty phải bị điều tra' → bị động be inspected."),
        ],
      },
    ],
  },
  {
    slug: "practice-test-5",
    chapter: CHAPTER,
    code: "Practice Test 5",
    title: "Đề luyện tập số 5",
    summary: "40 câu tổng hợp danh từ, động từ, tính từ, trạng từ, đại từ, liên từ và giới từ.",
    blocks: [
      {
        type: "table",
        title: "Extra vocabulary",
        headers: VOCAB_HEADERS,
        rows: [
          ["approachable", "adj", "thân thiện, dễ gần"],
          ["briefly", "adv", "nhanh chóng, ngắn gọn"],
          ["extensively", "adv", "nhiều, rộng khắp"],
          ["reliable", "adj", "đáng tin cậy"],
          ["response to", "n", "phản hồi, trả lời"],
          ["sign the contract", "v", "ký hợp đồng"],
        ],
      },
    ],
    exercises: [
      {
        title: "Practice Test 5",
        kind: "test",
        instructions: INSTRUCTIONS,
        questions: [
          q("The CEO of Buy4less.com is a very approachable person who prefers that his employees call ------- by his first name.", ["he", "him", "his", "himself"], "B", "Sau động từ là đại từ làm tân ngữ him."),
          q("Ms. Junko's sales presentation is supposed to start ------- ten o'clock tomorrow morning.", ["on", "at", "in", "for"], "B", "At + giờ."),
          q("While Sheila is going to retire as vice president, she is still open to the possibility of remaining as a creative -------.", ["consulted", "consultation", "consult", "consultant"], "D", "Chọn danh từ chỉ người (chức vụ của Sheila)."),
          q("I luckily found out about the job opportunity at your office through a close colleague of -------, Ms. Nancy Albright.", ["mine", "me", "myself", "my"], "A", "A + danh từ + of + đại từ sở hữu."),
          q("After discussing the terms of the new health-benefits contract, ------- management and employees were satisfied.", ["both", "also", "either", "too"], "A", "Both … and."),
          q("There is now increased competition among motor-vehicle manufacturers ------- has resulted in better cars at lower prices.", ["those", "what", "that", "where"], "C", "Đại từ quan hệ thay thế cho competition là that."),
          q("Speaking ------- behalf of the vice president, Alan thanks the employees for their contributions to the fund-raising project.", ["at", "on", "by", "for"], "B", "On behalf of: thay mặt cho."),
          q("------- workers always have a better chance at getting a job and also a high salary.", ["Previous", "Included", "Experienced", "Actual"], "C", "'Nhân viên có kinh nghiệm luôn có cơ hội tốt hơn.'"),
          q("As an anthropologist, Mickey has to travel ------- to explore different cultures and traditions.", ["extensive", "extensively", "extension", "extending"], "B", "Trạng từ extensively bổ nghĩa cho động từ travel."),
          q("Jane always wondered ------- she would have been more successful if she had completed graduate school.", ["whether", "or", "even", "both"], "A", "Wonder whether: tự hỏi liệu."),
          q("When John decided ------- to apply for a new job or keep his old one, he kept his old job.", ["neither", "whether", "either", "unless"], "B", "Whether to V … or …"),
          q("When Kimmy realized that ------- agent overcharged her, she hired a lawyer to sue him.", ["her", "hers", "she", "herself"], "A", "Trước danh từ là tính từ sở hữu."),
          q("As a ------- to my proposal, Mike simply threw away the notes I brought to him.", ["respond", "response", "responsive", "responded"], "B", "Sau mạo từ a là danh từ response."),
          q("Although the note said \"Please handle with -------,\" most of the workers didn't follow it.", ["cautious", "cautiously", "caution", "cautiousness"], "C", "Handle with caution: xử lý cẩn thận."),
          q("Workers who have not ------- paid the entrance fee must do it now.", ["only", "earlier", "yet", "rather"], "C", "Trạng từ yet đi với thì hiện tại hoàn thành (phủ định)."),
          q("Protective clothing must be worn prior to ------- the laboratory.", ["stepping", "entering", "processing", "producing"], "B", "'Quần áo bảo hộ phải được mặc trước khi vào phòng thí nghiệm.'"),
          q("Diesel engine cars are ------- in Asian countries due to their high fuel efficiency.", ["prefer", "preferred", "preference", "preferring"], "B", "Xe được ưa chuộng → bị động are preferred."),
          q("Confused by the two very close ------- of the companies, John had trouble finding the place.", ["locate", "locations", "located", "location"], "B", "Two + danh từ số nhiều."),
          q("------- Parker keeps up his good work, he will be up for promotion next month.", ["As long as", "Prior to", "Despite", "In order to"], "A", "Phía sau là mệnh đề nên loại các phương án là giới từ. As long as: miễn là."),
          q("Mr. Jones ------- his own business last January and it is already turning into a profitable one.", ["started", "had started", "would start", "will be started"], "A", "Câu có last January nên chia quá khứ đơn."),
          q("The stores in this area are generally closed ------- 6 p.m.", ["except", "after", "unlike", "with"], "B", "'Các cửa hàng ở khu này thường đóng cửa sau 6 giờ tối.'"),
          q("Considering the size of the company in the ------- year, BHW Corporation has made tremendous progress.", ["precede", "precedes", "preceded", "preceding"], "D", "Tính từ preceding (trước đó) bổ nghĩa cho danh từ year."),
          q("The company registered the copyright for its new product ------- no other companies could create a similar product.", ["nor", "instead of", "so that", "due to"], "C", "Phía sau là mệnh đề nên loại giới từ; so that: để."),
          q("A ------- from BWM explained that the recent recall of its tires would not adversely affect sales.", ["represent", "representation", "represented", "representative"], "D", "Representative: người đại diện."),
          q("Mr. Van also ------- visited with local town leaders to gain their trust.", ["brief", "briefly", "briefer", "briefness"], "B", "Bổ nghĩa cho động từ visited là trạng từ."),
          q("------- the company launched its new products, it was already too late to make an impact on the market.", ["In order for", "By the time", "As much as", "Now"], "B", "Phía sau là mệnh đề; by the time: vào lúc, trước khi."),
          q("Please ------- Mr. Kyle, the new manager of the marketing department.", ["welcome", "welcoming", "to welcome", "will welcome"], "A", "Câu mệnh lệnh dùng động từ nguyên thể."),
          q("Customers cannot receive their products ------- they make the full payment.", ["until", "even", "just", "which"], "A", "Phía sau là mệnh đề; until: cho đến khi."),
          q("NYC Corporation boasts a ------- security software that ensures the protection of its customers' personal information.", ["relied", "reliably", "reliable", "rely"], "C", "Tính từ reliable bổ nghĩa cho danh từ security software."),
          q("HID Corporation is requiring all of its employees to ------- the summer conference.", ["send", "play", "allow", "attend"], "D", "Attend the conference: tham dự hội thảo."),
          q("Ms. Chalfant realized that ------- employees work best when they are provided with a clean working environment.", ["she", "herself", "her", "hers"], "C", "Trước danh từ là tính từ sở hữu."),
          q("Guests were asked to wear tags ------- the ceremony.", ["between", "behind", "upon", "throughout"], "D", "Throughout the ceremony: trong suốt buổi lễ."),
          q("The vice president ------- requested that all employees complete the survey on the work environment.", ["kindly", "kindliest", "kindlier", "kind"], "A", "Trạng từ bổ nghĩa cho động từ request."),
          q("Due to store -------, the cashier could not accept the returned products from one of the store's regular customers.", ["manual", "guide", "agency", "policy"], "D", "Store policy: chính sách cửa hàng."),
          q("Genuine Motors will lower the price ------- response to the intense price competition with its rival company.", ["for", "like", "in", "at"], "C", "In response to: để đáp lại."),
          q("The president of the company announced that workers can ------- a slight increase in their wages.", ["expect", "expecting", "expectation", "expects"], "A", "Sau động từ khuyết thiếu là động từ nguyên thể."),
          q("Lawyers always remind their clients to read every single condition ------- signing a contract.", ["so", "that", "before", "prior"], "C", "Before + V-ing."),
          q("Daily Nutrition is advertising a new product for those ------- lack the necessary vitamins from daily meals.", ["who", "because", "when", "such"], "A", "Those who: những người mà."),
          q("Once all the conditions are discussed, the two clients will sign the -------.", ["negotiation", "contract", "dialogue", "meeting"], "B", "Sign the contract: ký hợp đồng."),
          q("The owner of the company realized that the marketing department accounted for most of the company's -------.", ["expends", "expenses", "expended", "expensive"], "B", "Sau sở hữu cách the company's là danh từ."),
        ],
      },
    ],
  },
];
